# Created by: Dikshie
# $FreeBSD: textproc/py-errorhandler/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	errorhandler
PORTVERSION=	1.1.1
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dikshie@sfc.wide.ad.jp
COMMENT=	A logging framework handler that tracks when messages above a certain level have been logged.

USE_PYTHON=		yes
USE_PYDISTUTILS=	easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
