# Created by: mm@FreeBSD.org
# $FreeBSD: graphics/libwmf-nox11/Makefile 315150 2013-03-24 17:43:23Z rene $

PORTSCOUT=	ignore:1

MASTERDIR=	${.CURDIR}/../libwmf
OPTIONS_EXCLUDE=	X11
OPTIONS_FILE_UNSET=	X11

.include        "${MASTERDIR}/Makefile"
