# Created by: Daniel Harris <dannyboy@subdimension.com>
# $FreeBSD: sysutils/fortunelock/Makefile 333680 2013-11-13 12:50:18Z vanilla $

PORTNAME=	fortunelock
PORTVERSION=	0.1.2
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	dannyboy

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Locks a terminal while showing fortunes

USE_BZIP2=	yes

PLIST_FILES=	bin/fortunelock man/man1/${PORTNAME}.1.gz

.include <bsd.port.mk>
