# Created by: Konstantin Menshikov <kostjnspb@yandex.ru>
# $FreeBSD: sysutils/p5-File-Tee/Makefile 327772 2013-09-20 23:05:58Z bapt $

PORTNAME=	File-Tee
PORTVERSION=	0.07
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN \
		http://kostjn.spb.ru/freebsd/
PKGNAMEPREFIX=	p5-

MAINTAINER=	kostjnspb@yandex.ru
COMMENT=	Replicate data sent to a Perl stream

USES=		perl5
USE_PERL5=	configure

MAN3=	File::Tee.3

NO_STAGE=	yes
.include <bsd.port.mk>
