# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: textproc/rubygem-diffy/Makefile 313022 2013-02-27 02:18:50Z zi $

PORTNAME=	diffy
PORTVERSION=	2.1.3
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Convenient diffing in ruby

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_RAKE=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
