# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: textproc/rubygem-diffy/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	diffy
PORTVERSION=	2.1.4
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Convenient diffing in ruby

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_RAKE=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
