# $FreeBSD: x11-drivers/xf86-video-glint/Makefile 336621 2013-12-16 11:11:09Z zeising $

PORTNAME=	xf86-video-glint
PORTVERSION=	1.2.8
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org glint display driver

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto xf86dgaproto glproto

.include <bsd.port.mk>
