# $FreeBSD: x11-drivers/xf86-video-dummy/Makefile 327049 2013-09-12 10:01:07Z zeising $

PORTNAME=	xf86-video-dummy
PORTVERSION=	0.3.7
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org dummy display driver

XORG_CAT=	driver
USE_XORG=	xf86dgaproto

.include <bsd.port.mk>
