--- crates/arti/src/arti-example-config.toml.orig	2022-09-25 15:06:18 UTC
+++ crates/arti/src/arti-example-config.toml
@@ -86,8 +86,8 @@
 #
 # The state directory is not yet used.
 [storage]
-#cache_dir = "${ARTI_CACHE}"
-#state_dir = "${ARTI_LOCAL_DATA}"
+cache_dir = "/var/db/arti/"
+state_dir = "/var/db/arti/"
 
 # Describe how to enforce permissions on the filesystem when accessing the cache
 # and state directories.  (This does not apply to configuration files) 
