# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-File-chdir/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	File-chdir
PORTVERSION=	0.1008
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	More sensible way to change directories

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		File::chdir.3

NO_STAGE=	yes
.include <bsd.port.mk>
