# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: chinese/p5-Lingua-ZH-Segment/Makefile 328366 2013-09-26 14:35:04Z vanilla $

PORTNAME=	Lingua-ZH-Segment
PORTVERSION=	0.02
CATEGORIES=	chinese perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Lingua
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Chinese Text Segmentation

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
