# Created by: Josh Carroll <josh.carroll@gmail.com>
# $FreeBSD: net-mgmt/wdiag/Makefile 327757 2013-09-20 22:24:43Z bapt $

PORTNAME=	wdiag
PORTVERSION=	0.10.2
CATEGORIES=	net-mgmt
MASTER_SITES=	SF
EXTRACT_SUFX=	.tgz

MAINTAINER=	josh.carroll@gmail.com
COMMENT=	Utility to collect DSL line stats from Westell DSL modems

WRKSRC=		${WRKDIR}/${PORTNAME}/src

NO_STAGE=	yes
.include <bsd.port.mk>
