# Created by: thierry@pompo.net
# $FreeBSD: games/cardpics/Makefile 328226 2013-09-25 00:54:08Z bdrewery $

PORTNAME=		cardpics
PORTVERSION=		0.4
CATEGORIES=		games devel
MASTER_SITES=		${MASTER_SITE_SAVANNAH}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=		thierry@FreeBSD.org
COMMENT=		Free cards for your free card games!

USE_BZIP2=		yes
GNU_CONFIGURE=		yes

.include <bsd.port.mk>
