# $FreeBSD: ports/korean/libreoffice/Makefile,v 1.3 2012/11/17 05:58:47 svnexp Exp $

LO_I18N=	ko
LO_HAS_HELPPACK=	yes
CATEGORIES=	korean editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
