# $FreeBSD: korean/libreoffice/Makefile 306473 2012-10-26 20:24:07Z jkim $

LO_I18N=	ko
LO_HAS_HELPPACK=	yes
CATEGORIES=	korean editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
