# Ports collection makefile for:	jeta
# Date created:			Sat Feb 10, 2007
# Whom:				Beech Rintoul <beech@FreeBSD.org>
#
# $FreeBSD: security/horde3-jeta/Makefile 316464 2013-04-24 18:10:30Z ak $
#

PORTNAME=	jeta
PORTVERSION=	1.0
PORTREVISION=	8
CATEGORIES=	security www

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde wrapper around various Java SSH applets

USE_HORDE=	base pkg-message
USES=		gettext
PORTDOCS=	README CHANGES CREDITS INSTALL RELEASE_NOTES

.include "${.CURDIR}/../../www/horde3-base/bsd.horde.mk"
.include <bsd.port.mk>
