# Created by: Beech Rintoul <beech@FreeBSD.org>
# $FreeBSD: security/horde3-jeta/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	jeta
PORTVERSION=	1.0
PORTREVISION=	8
CATEGORIES=	security www

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde wrapper around various Java SSH applets

USE_HORDE=	base pkg-message
USES=		gettext
PORTDOCS=	README CHANGES CREDITS INSTALL RELEASE_NOTES

NO_STAGE=	yes
.include "${.CURDIR}/../../www/horde3-base/bsd.horde.mk"
.include <bsd.port.mk>
