# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-Devel-DProfPP/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Devel-DProfPP
PORTVERSION=	1.3
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Parse Devel::DProf output

USES=		perl5
USE_PERL5=	configure

MAN3=		Devel::DProfPP.3

NO_STAGE=	yes
.include <bsd.port.mk>
