# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: devel/p5-File-DirSync/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	File-DirSync
PORTVERSION=	1.22
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mhjacks@swbell.net
COMMENT=	Perl5 module for synchronizing two directories rapidly

USES=		perl5
USE_PERL5=	configure

MAN1=		dirsync.1
MAN3=		File::DirSync.3

NO_STAGE=	yes
.include <bsd.port.mk>
