# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: security/p5-Crypt-IDEA/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	Crypt-IDEA
PORTVERSION=	1.10
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 interface to IDEA block cipher

USES=		perl5
USE_PERL5=	configure

MAN3=		Crypt::IDEA.3

NO_STAGE=	yes
.include <bsd.port.mk>
