# Ports collection makefile for:	rubygem-sax-machine
# Date created:		29 May 2010
# Whom:			Eric Freeman <freebsdports@chillibear.com>
#
# $FreeBSD: ports/textproc/rubygem-sax-machine/Makefile,v 1.3 2012/11/17 06:02:20 svnexp Exp $
#

PORTNAME=	sax-machine
PORTVERSION=	0.0.16
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	freebsdports@chillibear.com
COMMENT=	A declarative sax parsing library backed by Nokogiri

RUN_DEPENDS=	rubygem-nokogiri>=0.0.0:${PORTSDIR}/textproc/rubygem-nokogiri

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
