# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: textproc/rubygem-sax-machine/Makefile 335341 2013-11-30 19:59:20Z sunpoet $

PORTNAME=	sax-machine
PORTVERSION=	0.2.1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Declarative sax parsing library backed by Nokogiri

LICENSE=	MIT

RUN_DEPENDS=	rubygem-nokogiri>=1.6.0:${PORTSDIR}/textproc/rubygem-nokogiri

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
