# Created by: Seth Kingsley <sethk@meowfishies.com>
# $FreeBSD: security/p5-Safe-Hole/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	Safe-Hole
PORTVERSION=	0.13
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sethk@meowfishies.com
COMMENT=	Make a hole to the original main compartment in the Safe compartment

USES=		perl5
USE_PERL5=	modbuild

MAN3=		Safe::Hole.3

NO_STAGE=	yes
.include <bsd.port.mk>
