# $FreeBSD: ports/hungarian/libreoffice/Makefile,v 1.3 2012/11/17 05:58:27 svnexp Exp $

LO_I18N=	hu
LO_HAS_HELPPACK=	yes
CATEGORIES=	hungarian editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
