# $FreeBSD: hungarian/libreoffice/Makefile 327735 2013-09-20 18:43:02Z bapt $

LO_I18N=	hu
LO_HAS_HELPPACK=	yes
CATEGORIES=	hungarian editors

NO_STAGE=	yes
.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
