# $FreeBSD: hungarian/libreoffice/Makefile 340722 2014-01-22 17:00:46Z mat $

LO_I18N=	hu
LO_HAS_HELPPACK=	yes
CATEGORIES=	hungarian editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
