# Created by: Igor Vinokurov <igor@zynaps.ru>
# $FreeBSD: net/p5-Net-ext/Makefile 332868 2013-11-05 16:42:55Z vanilla $

PORTNAME=	Net-ext
PORTVERSION=	1.011
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl modules for using sockets

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
