# New ports collection makefile for:	p5-Net-ext
# Date created:				25 March 2000
# Whom:					Igor Vinokurov <igor@zynaps.ru>
#
# $FreeBSD: ports/net/p5-Net-ext/Makefile,v 1.11 2012/11/17 06:00:12 svnexp Exp $
#

PORTNAME=	Net-ext
PORTVERSION=	1.011
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl modules for using sockets

PERL_CONFIGURE=	yes

MAN3=		Net::Gen.3 Net::Inet.3 Net::TCP.3 Net::TCP::Server.3 \
		Net::UDP.3 Net::UNIX.3 Net::UNIX::Server.3

.include <bsd.port.mk>
