# Created by: ijliao
# $FreeBSD: devel/rubygem-mash/Makefile 332039 2013-10-30 02:39:14Z swills $

PORTNAME=	mash
PORTVERSION=	0.1.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Mocking Hash library for Ruby

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
