# Created by: alepulver
# $FreeBSD: deskutils/menumaker/Makefile 327718 2013-09-20 16:21:37Z bapt $

PORTNAME=	menumaker
PORTVERSION=	0.99.7
CATEGORIES=	deskutils
MASTER_SITES=	SF/${PORTNAME}/MenuMaker/${PORTVERSION}

MAINTAINER=	jgh@FreeBSD.org
COMMENT=	Menu generator for X Window Managers and desktop environments

USE_PYTHON=	yes
USES=	gmake
GNU_CONFIGURE=	yes

INFO=		mmaker

NO_STAGE=	yes
.include <bsd.port.mk>
