# Created by: alepulver
# $FreeBSD: deskutils/menumaker/Makefile 331352 2013-10-23 06:31:21Z jgh $

PORTNAME=	menumaker
PORTVERSION=	0.99.7
CATEGORIES=	deskutils
MASTER_SITES=	SF/${PORTNAME}/MenuMaker/${PORTVERSION}

MAINTAINER=	jgh@FreeBSD.org
COMMENT=	Menu generator for X Window Managers and desktop environments

USE_PYTHON=	yes
USES=	gmake
GNU_CONFIGURE=	yes

INFO=		mmaker

.include <bsd.port.mk>
