# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: databases/buzhug/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	buzhug
PORTVERSION=	1.8
CATEGORIES=	databases python
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/${PORTNAME}-${PORTVERSION}

MAINTAINER=	culot@FreeBSD.org
COMMENT=	A pure-Python database engine

USE_ZIP=	yes
USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
