# $FreeBSD: math/hs-data-lens-template/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	data-lens-template
PORTVERSION=	2.1.7
PORTREVISION=	5
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities for Data.Lens

LICENSE=	BSD

USE_CABAL=	data-lens>=2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
