# New ports collection makefile for:	p5-Mail-RFC822-Address
# Date created:		18 May 2003
# Whom:			Simon Barner <barner@in.tum.de>
#
# $FreeBSD: ports/mail/p5-Mail-RFC822-Address/Makefile,v 1.10 2012/11/17 05:59:09 svnexp Exp $
#

PORTNAME=	Mail-RFC822-Address
PORTVERSION=	0.3
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to validate RFC822 conformance of email addresses

PERL_CONFIGURE=	yes

INSTALL_TARGET=	pure_site_install

MAN3=		Mail::RFC822::Address.3

.include <bsd.port.mk>
