# Created by: Ryan Steinmetz <rpsfa@rit.edu>
# $FreeBSD: net/isc-dhcp42-relay/Makefile 316014 2013-04-18 01:25:41Z zi $

COMMENT=	The ISC Dynamic Host Configuration Protocol relay

SUBSYS=		relay
MASTERDIR=	${.CURDIR}/../isc-dhcp42-server

.include "${MASTERDIR}/Makefile"
