# Ports collection makefile for:	isc-dhcp42-relay
# Date created:				29 June 2011
# Whom:					Ryan Steinmetz <rpsfa@rit.edu>
#
# $FreeBSD: ports/net/isc-dhcp42-relay/Makefile,v 1.2 2012/11/17 06:00:03 svnexp Exp $
#

COMMENT=	The ISC Dynamic Host Configuration Protocol relay

SUBSYS=		relay
MASTERDIR=	${.CURDIR}/../isc-dhcp42-server

.include "${MASTERDIR}/Makefile"
