# $FreeBSD: devel/hs-activehs-base/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	activehs-base
PORTVERSION=	0.3.0.2
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Basic definitions for activehs

LICENSE=	BSD

USE_CABAL=	QuickCheck>=2.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
