# New ports collection makefile for:	p5-Text-Outdent
# Date created:		2011-01-13
# Whom:			Kurt Lidl <kurt.lidl@cello.com>
#
# $FreeBSD: ports/devel/p5-Text-Outdent/Makefile,v 1.3 2012/11/17 05:56:34 svnexp Exp $
#

PORTNAME=	Text-Outdent
PORTVERSION=	0.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:LODIN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kurt.lidl@cello.com
COMMENT=	Strip leading whitespace from here-docs

PERL_CONFIGURE=	yes

MAN3=	Text::Outdent.3

.include <bsd.port.mk>
