# $FreeBSD: net/p5-Geo-IPfree/Makefile 327755 2013-09-20 22:10:23Z bapt $

PORTNAME=	Geo-IPfree
PORTVERSION=	1.131650
CATEGORIES=	net perl5 geography
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Look up country from an IP Address

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		Geo::IPfree.3

NO_STAGE=	yes
.include <bsd.port.mk>
