# $FreeBSD: math/R-cran-gtable/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	gtable
PORTVERSION=	0.1.2
PORTREVISION=	5
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Arrange grobs in tables

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
