# Created by: Dryice Liu	<dryice@dryice.name>
# $FreeBSD: head/www/py-paste/Makefile 343585 2014-02-10 05:32:35Z miwi $

PORTNAME=	Paste
PORTVERSION=	1.7.5.1
PORTREVISION=	2
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Tools for using a Web Server Gateway Interface stack

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST= yes

.include <bsd.port.mk>
