# New ports collection makefile for:	rubygem-metaid
# Date created:		28, Dec 2008
# Whom:			Martin Wilke <miwi@FreeBSD.org>
#
# $FreeBSD: ports/devel/rubygem-metaid/Makefile,v 1.4 2012/11/17 05:57:00 svnexp Exp $
#

PORTNAME=	metaid
PORTVERSION=	1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Ruby metaprogramming helpers

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_RAKE=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
