# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: devel/rubygem-metaid/Makefile 340901 2014-01-24 14:46:50Z miwi $

PORTNAME=	metaid
PORTVERSION=	1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Ruby metaprogramming helpers

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_RAKE=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
