# New ports collection makefile for:	p5-Math-CDF
# Date created:		2010-11-13
# Whom:			Gea-Suan Lin <gslin@gslin.org>
#
# $FreeBSD: ports/math/p5-Math-CDF/Makefile,v 1.2 2012/11/17 05:59:25 svnexp Exp $
#

PORTNAME=	Math-CDF
PORTVERSION=	0.1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Generate probabilities and quantiles from several statistical probability functions

PERL_CONFIGURE=	yes

MAN3=		Math::CDF.3

.include <bsd.port.mk>
