# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: math/p5-Math-CDF/Makefile 327032 2013-09-12 05:53:03Z az $

PORTNAME=	Math-CDF
PORTVERSION=	0.1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Generate probabilities and quantiles from several statistical probability functions

USES=		perl5
USE_PERL5=	configure

MAN3=		Math::CDF.3

.include <bsd.port.mk>
