# Created by: jyyou@cs.nctu.edu.tw
# $FreeBSD: databases/hs-mysql/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	mysql
PORTVERSION=	0.1.1.4
PORTREVISION=	4
CATEGORIES=	databases haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Low-level MySQL client library

LICENSE=	BSD

USE_MYSQL=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
