# $FreeBSD: comms/pear-Horde_ActiveSync/Makefile 326775 2013-09-08 22:50:31Z mm $

PORTNAME=	Horde_ActiveSync
PORTVERSION=	2.7.3
CATEGORIES=	comms www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde ActiveSync Server Library

USE_HORDE_RUN=	Horde_Date \
		Horde_Exception \
		Horde_Icalendar \
		Horde_Mime \
		Horde_Support \
		Horde_Util

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
