# Created by: Peter Schuller <peter.schuller@infidyne.com>
# $FreeBSD: devel/py-boto/Makefile 319393 2013-05-29 22:27:57Z rm $

PORTNAME=	boto
PORTVERSION=	2.9.5
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	rm@FreeBSD.org
COMMENT=	Python interface to Amazon Web Services

LICENSE=	MIT

USE_PYTHON=	-2.7
USE_PYDISTUTILS=	easy_install

CONFLICTS=	p5-Net-Amazon-Route53-[0-9]*

.include <bsd.port.mk>
