# New ports collection makefile for:  	xbraitenberg
# Date created:       		28 Mar 2004
# Whom:  			krion
#
# $FreeBSD: ports/emulators/xbraitenberg/Makefile,v 1.9 2012/11/17 05:57:24 svnexp Exp $
#

PORTNAME=	xbraitenberg
PORTVERSION=	0.9
PORTREVISION=	2
CATEGORIES=	emulators
MASTER_SITES=	http://www.lcdf.org/~eddietwo/xbraitenberg/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A Braitenberg vehicle simulator with pseudo-physics

USE_XORG=	x11 ice sm xext
GNU_CONFIGURE=	yes

PLIST_FILES=	bin/xbraitenberg

.include <bsd.port.mk>
