# Created by: krion
# $FreeBSD: emulators/xbraitenberg/Makefile 327721 2013-09-20 16:43:52Z bapt $

PORTNAME=	xbraitenberg
PORTVERSION=	0.9
PORTREVISION=	2
CATEGORIES=	emulators
MASTER_SITES=	http://www.lcdf.org/~eddietwo/xbraitenberg/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A Braitenberg vehicle simulator with pseudo-physics

USE_XORG=	x11 ice sm xext
GNU_CONFIGURE=	yes

PLIST_FILES=	bin/xbraitenberg

NO_STAGE=	yes
.include <bsd.port.mk>
