# Created by: Alexander Koch <fbsd@meersau.de>
# $FreeBSD: www/p5-HTML-Chunks/Makefile 338763 2014-01-05 13:05:56Z az $

PORTNAME=	HTML-Chunks
PORTVERSION=	1.55.1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	fbsd@meersau.de
COMMENT=	A simple nested template engine for HTML, XML and XHTML

RUN_DEPENDS=	p5-IO-stringy>=0:${PORTSDIR}/devel/p5-IO-stringy

USES=		perl5
USE_PERL5=	configure

WRKSRC=		${WRKDIR}/${PORTNAME}

.include <bsd.port.mk>
