# $FreeBSD: textproc/hs-HStringTemplate/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	HStringTemplate
PORTVERSION=	0.7.1
PORTREVISION=	3
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	StringTemplate implementation in Haskell

LICENSE=	BSD

USE_CABAL=	blaze-builder mtl parsec syb text utf8-string void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
