# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: textproc/py-Tempita/Makefile 332200 2013-10-31 04:17:29Z eadler $

PORTNAME=	Tempita
PORTVERSION=	0.5.1
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wenheping@gmail.com
COMMENT=	Small text templating language

USE_PYTHON=		2.5+
USE_PYDISTUTILS=	easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
