# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-Lingua-Conjunction/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Lingua-Conjunction
PORTVERSION=	2.00
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Convert Perl lists into linguistic conjunctions

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
