# $FreeBSD: devel/hs-geniplate/Makefile 327723 2013-09-20 17:04:43Z bapt $

PORTNAME=	geniplate
PORTVERSION=	0.6.0.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use template Haskell to generate Uniplate-like functions

LICENSE=	BSD

USE_CABAL=	mtl

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
