# $FreeBSD: devel/hs-geniplate/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	geniplate
PORTVERSION=	0.6.0.3
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use template Haskell to generate Uniplate-like functions

LICENSE=	BSD

USE_CABAL=	mtl

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
