# Created by: Zach Thompson <hideo@lastamericanempire.com>
# $FreeBSD: devel/p5-Clone-PP/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Clone-PP
PORTVERSION=	1.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Recursively copy Perl datatypes

USES=		perl5
USE_PERL5=	configure

MAN3=	Clone::PP.3

.include <bsd.port.mk>
