# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-Number-Format/Makefile 326939 2013-09-11 05:29:55Z az $

PORTNAME=		Number-Format
PORTVERSION=		1.73
CATEGORIES=		textproc perl5
MASTER_SITES=		CPAN
PKGNAMEPREFIX=		p5-

MAINTAINER=		clsung@FreeBSD.org
COMMENT=		Perl extension for formatting numbers

USES=		perl5
USE_PERL5=	configure

MAN3=			Number::Format.3

.include <bsd.port.mk>
