# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: textproc/es-aspell/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-es-1.11-2
PORTEPOCH=	1
CATEGORIES=	textproc spanish

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Spanish dictionary

DICT=	 	es

NO_STAGE=	yes
.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
