# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: archivers/php55-bz2/Makefile 327699 2013-09-20 13:11:20Z bapt $

CATEGORIES=	archivers

NO_STAGE=	yes
MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-bz2

.include "${MASTERDIR}/Makefile"
