# Created by: will
# $FreeBSD: devel/p5-Mac-FileSpec-Unixish/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Mac-FileSpec-Unixish
PORTVERSION=	1.12
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module with functions to manipulate pathspecs in Unixish style

USES=		perl5
USE_PERL5=	configure

MAN3=		Mac::FileSpec::Unixish.3

.include <bsd.port.mk>
