# Created by: Mathieu Arnold <m@absolight.net>
# $FreeBSD: devel/p5-Set-Crontab/Makefile 332205 2013-10-31 07:36:25Z vanilla $

PORTNAME=	Set-Crontab
PORTVERSION=	1.03
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Set::Crontab - Expand crontab(5)-style integer lists

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
