# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: print/biblio-py/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	biblio-py
PORTVERSION=	0.6.1
CATEGORIES=	print python
MASTER_SITES=	CHEESESHOP \
		http://cabcat2.cnea.gov.ar/staff/fiol/

MAINTAINER=	wen@FreeBSD.org
COMMENT=	A package to manage bibliography written in python

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
