# Created by: Thomas Abthorpe <thomas@goodking.ca>
# $FreeBSD: archivers/p5-Compress-Raw-Bzip2/Makefile 332576 2013-11-03 04:53:24Z sunpoet $

PORTNAME=	Compress-Raw-Bzip2
PORTVERSION=	2.063
CATEGORIES=	archivers perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PMQS
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Low-Level Interface to bzip2 compression library

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Pod>=1:${PORTSDIR}/devel/p5-Test-Pod

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
