# New ports collection makefile for:	wxgtk26-unicode-contrib
# Date created:         		June 27, 2004
# Whom:					fjoe@FreeBSD.ORG
#
# $FreeBSD: ports/x11-toolkits/wxgtk26-unicode-contrib/Makefile,v 1.13 2012/11/17 06:03:40 svnexp Exp $
#

MAINTAINER=	fjoe@FreeBSD.org
COMMENT=	The wxWidgets GUI toolkit contributed libraries (Unicode)

CONFLICTS=	wxgtk2-unicode-contrib-devel-2.5.2*

WXGTK_FLAVOR=	gtk2-unicode-contrib
MASTERDIR=	${.CURDIR}/../wxgtk26

.include "${MASTERDIR}/Makefile"
