# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: math/p5-Math-Random/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Math-Random
PORTVERSION=	0.71
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Random number generators

USES=		perl5
USE_PERL5=	configure

MAN3=		Math::Random.3

.include <bsd.port.mk>
