# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-Time-Out/Makefile 341707 2014-01-29 09:19:35Z az $

PORTNAME=	Time-Out
PORTVERSION=	0.11
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Time
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Easily timeout long running operations

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
