# $FreeBSD: japanese/p5-Lingua-JA-Regular-Unicode/Makefile 318706 2013-05-21 14:24:57Z kuriyama $

PORTNAME=	Lingua-JA-Regular-Unicode
PORTVERSION=	0.12
CATEGORIES=	japanese perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX:=	${PKGNAMEPREFIX}p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to convert Japanese chars

TEST_DEPENDS=	\
	p5-Text-TestBase>0:${PORTSDIR}/textproc/p5-Text-TestBase

PERL_MODBUILD=	yes

MAN3=	Lingua::JA::Regular::Unicode.3

.include <bsd.port.mk>
