# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: devel/hs-StateVar/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	StateVar
PORTVERSION=	1.0.0.0
PORTREVISION=	10
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	State variables for Haskell

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
