# Created by: Max Kochubey <root@hangover.org.ru>
# $FreeBSD: ports/databases/firebird21-client/Makefile,v 1.3 2012/12/18 23:19:31 svnexp Exp $

PORTNAME=	firebird
PKGNAMESUFFIX=	-client

COMMENT=	Firebird-2 database client

MASTERDIR=	${.CURDIR}/../firebird21-server

PLIST=		${PKGDIR}/pkg-plist.client

CLIENT_ONLY=	yes

.include "${MASTERDIR}/Makefile"
