# Created by: Loic Pefferkorn <loic-freebsd@loicp.eu>
# $FreeBSD: textproc/rubygem-heredoc_unindent/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	heredoc_unindent
PORTVERSION=	1.1.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	loic-freebsd@loicp.eu
COMMENT=	Removes common margin from indented strings

LICENSE=	MIT

RUN_DEPENDS=	rubygem-hoe>=2.9.6:${PORTSDIR}/devel/rubygem-hoe

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
