# $FreeBSD: ports/sysutils/cfengine/Makefile,v 1.52 2013/01/08 04:42:05 svnexp Exp $

VERSIONS=		22 32 33 34 -devel
CFENGINE_VERSION?=	34

MASTERDIR=		${.CURDIR}/../cfengine${CFENGINE_VERSION}

.include "${MASTERDIR}/Makefile"
