# $FreeBSD: sysutils/cfengine/Makefile 327772 2013-09-20 23:05:58Z bapt $

VERSIONS=		22 32 33 34 35 -devel
CFENGINE_VERSION?=	35

MASTERDIR=		${.CURDIR}/../cfengine${CFENGINE_VERSION}

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
