# $FreeBSD: devel/p5-List-UtilsBy/Makefile 338867 2014-01-06 12:18:47Z az $

PORTNAME=	List-UtilsBy
PORTVERSION=	0.09
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for higher-order list utility functions

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
