# Created by: Pete Fritchman <petef@databits.net>
# $FreeBSD: devel/p5-Class-Date/Makefile 338870 2014-01-06 12:43:03Z az $

PORTNAME=	Class-Date
PORTVERSION=	1.1.10
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Perl class for easy date and time manipulation

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
