# New ports collection makefile for:	gstreamer-plugins-neon
# Date created:			6 July 2006
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD: ports/www/gstreamer-plugins-neon/Makefile,v 1.13 2012/11/17 06:02:34 svnexp Exp $
#    $MCom: ports/www/gstreamer-plugins-neon/Makefile,v 1.5 2008/03/19 14:05:38 ahze Exp $
#

PORTREVISION=	0
CATEGORIES=	www

COMMENT=	Gstreamer neon plugin

GST_PLUGIN=	neon

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
