# Created by: will
# $FreeBSD: ports/devel/p5-Tie-IxHash/Makefile,v 1.13 2013/02/24 16:44:18 svnexp Exp $

PORTNAME=	Tie-IxHash
PORTVERSION=	1.23
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module implementing ordered in-memory associative arrays

MAKE_JOBS_SAFE=	yes

PERL_CONFIGURE=	yes

MAN3=		Tie::IxHash.3

.include <bsd.port.mk>
