# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: games/p5-Algorithm-Pair-Swiss/Makefile 324175 2013-08-02 21:38:09Z mat $

PORTNAME=	Algorithm-Pair-Swiss
PORTVERSION=	0.14
CATEGORIES=	games perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Generate unique pairings for tournaments

TEST_DEPENDS=	p5-Test-Exception>=0:${PORTSDIR}/devel/p5-Test-Exception

MAN3=	Algorithm::Pair::Swiss.3

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
