# Created by: Kozlov Sergey <kozlov.sergey.404@gmail.com>
# $FreeBSD: www/py-django-tinymce/Makefile 333330 2013-11-09 19:17:57Z wg $

PORTNAME=	django-tinymce
PORTVERSION=	1.5.2
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kozlov.sergey.404@gmail.com
COMMENT=	Django application to use TinyMCE editor

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django>=1.0:${PORTSDIR}/www/py-django

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
