# $FreeBSD: www/hs-recaptcha/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	recaptcha
PORTVERSION=	0.1
PORTREVISION=	5
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Functions for using the reCAPTCHA service in web applications

LICENSE=	BSD

USE_CABAL=	HTTP>=3001.1.4 network>=2.2.0.1 xhtml>=3000.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
