# $FreeBSD: ports/www/hs-recaptcha/Makefile,v 1.6 2013/02/05 22:47:15 svnexp Exp $

PORTNAME=	recaptcha
PORTVERSION=	0.1
PORTREVISION=	4
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Functions for using the reCAPTCHA service in web applications

LICENSE=	BSD

USE_CABAL=	HTTP>=3001.1.4 network>=2.2.0.1 xhtml>=3000.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
