# $FreeBSD: devel/hs-cereal/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	cereal
PORTVERSION=	0.3.5.2
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Binary serialization library for Haskell

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
