# Created by: Dennis Herrmann <adox@mcx2.org>
# $FreeBSD: devel/rubygem-trollop/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	trollop
PORTVERSION=	1.16.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	dhn@FreeBSD.org
COMMENT=	A commandline option parser for Ruby that gets out of your way

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_RAKE=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
