# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: textproc/rubygem-itextomml/Makefile 332051 2013-10-30 02:58:22Z swills $

PORTNAME=	itextomml
PORTVERSION=	1.4.10
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Native Ruby bindings to itex2MML

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
