# New ports collection makefile for:	textproc/rubygem-itextomml
# Date created:				23 Oct, 2011
# Whom:					Wen Heping <wen@FreeBSD.org>
#
# $FreeBSD: ports/textproc/rubygem-itextomml/Makefile,v 1.4 2012/11/17 06:02:20 svnexp Exp $
#

PORTNAME=	itextomml
PORTVERSION=	1.4.10
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Native Ruby bindings to itex2MML

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
