# Created by: Cory R. King <coryking@mozimediacom>
# $FreeBSD: devel/p5-Devel-Timer/Makefile 326706 2013-09-08 08:16:43Z az $

PORTNAME=	Devel-Timer
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	coryking@mozimedia.com
COMMENT=	Track and report execution time for parts of code

USES=		perl5
USE_PERL5=	configure

MAN3=	Devel::Timer.3

.include <bsd.port.mk>
