# Created by: Cory R. King <coryking@mozimediacom>
# $FreeBSD: devel/p5-Devel-Timer/Makefile 323795 2013-07-27 16:06:25Z az $

PORTNAME=	Devel-Timer
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	coryking@mozimedia.com
COMMENT=	Track and report execution time for parts of code

PERL_CONFIGURE=	yes

MAN3=	Devel::Timer.3

.include <bsd.port.mk>
