# Created by: Steven Kreuzer
# $FreeBSD: security/rubygem-ezcrypto/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	ezcrypto
PORTVERSION=	0.7.2
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Wrapper for the poorly documented OpenSSL ruby library

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
