# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: astro/R-cran-maptools/Makefile 324609 2013-08-12 01:25:07Z tota $

PORTNAME=	maptools
DISTVERSION=	0.8-26
CATEGORIES=	astro
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for reading and handling spatial objects

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-cran-sp>=1.0.11:${PORTSDIR}/math/R-cran-sp

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
