# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: ports/astro/R-cran-maptools/Makefile,v 1.18 2013/02/11 21:09:07 svnexp Exp $

PORTNAME=	maptools
DISTVERSION=	0.8-23
CATEGORIES=	astro
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for reading and handling spatial objects

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-cran-sp>=0.9.47:${PORTSDIR}/math/R-cran-sp

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
