# Created by: Cheng-Lung Sung <clsung@dragon2.net>
# $FreeBSD: ports/textproc/p5-Text-Ngrams/Makefile,v 1.15 2012/12/16 15:55:36 svnexp Exp $

PORTNAME=	Text-Ngrams
PORTVERSION=	2.003
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 modules for Flexible Ngram analysis

PERL_CONFIGURE=	yes

MAN1=		ngrams.pl.1
MAN3=		Text::Ngrams.3

.include <bsd.port.mk>
