# Created by: Thomas Gellekum <tg@FreeBSD.org>
# $FreeBSD: games/xdemineur/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xdemineur
PORTVERSION=	2.1.1
PORTREVISION=	1
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_XCONTRIB} \
		http://www.babafou.eu.org/xdemineur/
MASTER_SITE_SUBDIR=	games

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Another minesweeper game for the X Window System

USES=		imake
USE_XORG=	xpm
PLIST_FILES=	bin/xdemineur \
		man/man1/xdemineur.1.gz

.include <bsd.port.mk>
