# Created by: Akinori MUSHA aka knu <knu@idaemons.org>
# $FreeBSD: devel/ruby-flexmock/Makefile 319623 2013-06-02 01:48:59Z swills $

PORTNAME=	flexmock
PORTVERSION=	1.3.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A simple mock object for Ruby

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
