# $FreeBSD: ports/devel/hs-data-default/Makefile,v 1.7 2013/02/05 22:47:09 svnexp Exp $

PORTNAME=	data-default
PORTVERSION=	0.5.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A class for types with a default value

LICENSE=	BSD

USE_CABAL=	dlist

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
