# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: net/php55-soap/Makefile 332107 2013-10-30 13:32:02Z ale $

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-soap

.include "${MASTERDIR}/Makefile"
