# Created by: tiger@whitetigersd.com
# $FreeBSD: devel/p5-Algorithm-LCS/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Algorithm-LCS
PORTVERSION=	1.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JOESUF
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Fast (XS) implementation of the Longest Common Subsequence Algorithm

USES=		perl5
USE_PERL5=	configure

MAN3=		Algorithm::LCS.3

NO_STAGE=	yes
.include <bsd.port.mk>
