# New ports collection makefile for:	Chemistry::Elements
# Date created:				31 Dec 2001
# Whom:					Seamus Venasse <svenasse@polaris.ca>
#
# $FreeBSD: ports/science/p5-Chemistry-Elements/Makefile,v 1.12 2012/11/17 06:00:59 svnexp Exp $
#

PORTNAME=	Chemistry-Elements
PORTVERSION=	1.07
CATEGORIES=	science perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for working with Chemical Elements

PERL_CONFIGURE=	yes

MAN3=	Chemistry::Elements.3

.include <bsd.port.mk>
