# Created by: Jim Riggs <ports@christianserving.org>
# $FreeBSD: net-mgmt/zabbix2-proxy/Makefile 327757 2013-09-20 22:24:43Z bapt $

PORTNAME=	zabbix2
PKGNAMESUFFIX=	-proxy

MASTERDIR=	${.CURDIR}/../zabbix2-server

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
