# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: ports/devel/hs-Stream/Makefile,v 1.16 2013/02/05 22:47:09 svnexp Exp $

PORTNAME=	Stream
PORTVERSION=	0.4.6.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A Haskell library for manipulating infinite lists

LICENSE=	BSD

USE_CABAL=	lazysmallcheck>=0.3 QuickCheck>=2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
