# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: misc/kde4-l10n-wa/Makefile 315373 2013-03-27 11:55:25Z makc $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
CATEGORIES=	misc kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Walloon messages and documentation for KDE SC 4

KDE4_L10N=	wa

.include "${.CURDIR}/../../misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.post.mk>
