# New ports collection makefile for:	gstreamer-plugins-wavpack
# Date created:			5 July 2005
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD: ports/audio/gstreamer-plugins-wavpack/Makefile,v 1.13 2012/11/17 05:54:34 svnexp Exp $
#   $MCom: ports/audio/gstreamer-plugins-wavpack/Makefile,v 1.3 2008/03/19 14:05:33 ahze Exp $
#

PORTREVISION=	0
CATEGORIES=	audio

GST_PLUGIN=	wavpack

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
