# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: x11/kbproto/Makefile 328096 2013-09-24 06:24:17Z bapt $

PORTNAME=	kbproto
PORTVERSION=	1.0.6
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	KB extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
