# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/sysfsutils/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	sysfsutils
PORTVERSION=	2.1.0
CATEGORIES=	devel
MASTER_SITES=	SF/linux-diag/${PORTNAME}/${PORTVERSION}

MAINTAINER=	gslin@gslin.org
COMMENT=	System Utilities Based on Sysfs

GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

MAN1=		systool.1

NO_STAGE=	yes
.include <bsd.port.mk>
