# Created by: rafan@infor.org
# $FreeBSD: science/libsvm-python/Makefile 340722 2014-01-22 17:00:46Z mat $

PKGNAMESUFFIX=	-python

MAINTAINER=	rafan@FreeBSD.org

MASTERDIR=	${.CURDIR}/../../science/libsvm

PLIST=		${.CURDIR}/pkg-plist

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
