# Created by: rafan@infor.org
# $FreeBSD: science/libsvm-python/Makefile 327767 2013-09-20 22:48:30Z bapt $

PKGNAMESUFFIX=	-python

MAINTAINER=	rafan@FreeBSD.org

MASTERDIR=	${.CURDIR}/../../science/libsvm

PLIST=		${.CURDIR}/pkg-plist

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
