# New ports collection makefile for:	p5-File-chmod
# Date created:	   2008-02-18
# Whom:		   Shinsuke Matsui <smatsui@karashi.org>
#
# $FreeBSD: devel/p5-File-chmod/Makefile 326581 2013-09-07 08:23:45Z az $
#

PORTNAME=	File-chmod
PORTVERSION=	0.32
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	smatsui@karashi.org
COMMENT=	File::chmod - Implements symbolic and ls chmod modes

USES=		perl5
USE_PERL5=	configure

MAN3=		File::chmod.3

.include <bsd.port.mk>
