--- cargo-crates/wasmtime-1.0.2/Cargo.toml.orig	2022-11-19 14:17:53 UTC
+++ cargo-crates/wasmtime-1.0.2/Cargo.toml
@@ -146,7 +146,6 @@ default = [
     "cranelift",
     "pooling-allocator",
     "memory-init-cow",
-    "vtune",
 ]
 incremental-cache = ["wasmtime-cranelift?/incremental-cache"]
 jitdump = ["wasmtime-jit/jitdump"]
