--- lapce-proxy/Cargo.toml.orig	2023-02-12 19:26:27 UTC
+++ lapce-proxy/Cargo.toml
@@ -49,7 +49,7 @@ which = "4.2.5"
 which = "4.2.5"
 
 # git
-git2 = { version = "0.16.1", features = ["vendored-openssl"] }
+git2 = { version = "0.16.1", features = [] }
 
 # deleting files
 trash = "2.1.5"
@@ -72,4 +72,4 @@ objc = "0.2"
 [target.'cfg(target_os = "macos")'.dependencies]
 cocoa = "0.24"
 objc = "0.2"
-libc = "0.2"
\ No newline at end of file
+libc = "0.2"
