# New ports collection makefile for:    manck
# Date created:         10 September 1995
# Whom:                 joerg
#
# $FreeBSD: ports/sysutils/manck/Makefile,v 1.18 2012/11/17 06:01:38 svnexp Exp $
#

PORTNAME=	manck
PORTVERSION=	1.2
CATEGORIES=	sysutils
MASTER_SITES=	http://wolfram.schneider.org/src/

MAINTAINER=	wosch@FreeBSD.org
COMMENT=	Manual page consistency checker

MAN1=		manck.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
