# Created by: ache@FreeBSD.org
# $FreeBSD: converters/p5-MIME-Base64/Makefile 327715 2013-09-20 16:05:24Z bapt $

PORTNAME=	MIME-Base64
PORTVERSION=	3.14
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module for Base64 and Quoted-Printable encodings

USES=		perl5
USE_PERL5=	configure

MAN3=		MIME::Base64.3 \
		MIME::QuotedPrint.3

NO_STAGE=	yes
.include <bsd.port.mk>
