# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD: ports/net/py-amqp/Makefile,v 1.4 2013/02/14 15:09:04 svnexp Exp $

PORTNAME=	amqp
PORTVERSION=	1.2.0
CATEGORIES=	net python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Low-level AMQP client for Python (fork of amqplib)

LICENSE=	LGPL21

USE_GITHUB=		yes
USE_PYTHON=		yes
USE_PYDISTUTILS=	easy_install

GH_ACCOUNT=	celery
GH_PROJECT=	py-${PORTNAME}
GH_COMMIT=	10f0ded
GH_TAGNAME=	v${PORTVERSION}

.include <bsd.port.mk>
