# Created by: Mathieu Arnold <m@absolight.net>
# $FreeBSD: textproc/p5-Pod-Escapes/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Pod-Escapes
PORTVERSION=	1.04
CATEGORIES=	textproc devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	For resolving Pod E<...> sequences

USES=		perl5
USE_PERL5=	configure

MAN3=		Pod::Escapes.3

.include <bsd.port.mk>
