# Created by: Raphael Kubo da Costa <kubito@gmail.com>
# $FreeBSD: audio/gstreamer-plugins-gme/Makefile 332416 2013-11-01 22:14:07Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer game-music-emu (libgme) frontend

GST_PLUGIN=	gme

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
