# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: audio/gstreamer-plugins-sidplay/Makefile 332416 2013-11-01 22:14:07Z kwm $
#   $MCom: ports/audio/gstreamer-plugins-sidplay/Makefile,v 1.5 2008/03/19 14:05:31 ahze Exp $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer Commodore SID decoder plugin

GST_PLUGIN=	sidplay

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
