# $FreeBSD: x11/xvinfo/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xvinfo
PORTVERSION=	1.1.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Print out X-Video extension adaptor information

XORG_CAT=	app
USE_XORG=	xv x11

PLIST_FILES=	bin/xvinfo man/man1/xvinfo.1.gz

.include <bsd.port.mk>
