# $FreeBSD: devel/hs-unordered-containers/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	unordered-containers
PORTVERSION=	0.2.3.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient hashing-based container types

LICENSE=	BSD

USE_CABAL=	hashable>=1.0.1.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
