# $FreeBSD: ports/editors/calligra-l10n-nb/Makefile,v 1.42 2013/02/05 12:23:33 svnexp Exp $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
CATEGORIES=	editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Norwegian Bokmaal messages and documentation for Calligra

CALLIGRA_L10N=	nb

.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
