
.if 1
# zrj: not tracked SOVER is violation, might as well auto-plist/find, bump on updates
PLIST_SUB+=	LIBSUFX=2111.0.0
.else
# XXX No time to find out why WRKSRC is not expanded by when the
# shell command is called in _GET_SOVER.

_GET_SOVER=	${GREP} SOVERSION ${WRKDIR}/${GH_PROJECT}-${DISTVERSION}/CMake/AbseilHelpers.cmake \
		| ${CUT} -d\" -f2

PLIST_SUB+=	LIBSUFX=${_GET_SOVER:sh}
.endif
