# Created by: Sergey Matveychuk <sem@FreeBSD.org>
# $FreeBSD: net/p5-Net-Ping/Makefile 338813 2014-01-05 18:05:39Z az $

PORTNAME=	Net-Ping
PORTVERSION=	2.40
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sem@FreeBSD.org
COMMENT=	Perl module to check a remote host for reachability

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
