# Created by: Blaz Zupan <blaz@amis.net>
# $FreeBSD: sysutils/p5-Unix-Syslog/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Unix-Syslog
PORTVERSION=	1.1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 interface to the UNIX syslog(3) calls

USES=		perl5
USE_PERL5=	configure

MAN3=		Unix::Syslog.3

.include <bsd.port.mk>
