# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/p5-Term-Title/Makefile 325898 2013-09-01 18:15:29Z az $

PORTNAME=	Term-Title
PORTVERSION=	0.03
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DAGOLDEN
PKGNAMEPREFIX=	p5-

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Portable API to set the terminal titlebar

USES=		perl5
USE_PERL5=	modbuild

MAN3=	Term::Title.3

.include <bsd.port.mk>
