# Created by: Eirik Oeverby <ltning@anduin.net>
# $FreeBSD: sysutils/jailctl/Makefile 327772 2013-09-20 23:05:58Z bapt $

PORTNAME=	jailctl
PORTVERSION=	0.80
CATEGORIES=	sysutils
MASTER_SITES=	http://anduin.net/jailctl/

MAINTAINER=	ltning-jailctl@anduin.net
COMMENT=	Jail management tool

MAN1=		jailctl.1 \
		jails.conf.1
MANCOMPRESSED=	yes

NO_BUILD=	yes

WRKSRC=		${WRKDIR}/jailctl

NO_STAGE=	yes
.include <bsd.port.mk>
