# $FreeBSD: net/rubygem-rubyntlm/Makefile 332048 2013-10-30 02:54:59Z swills $

PORTNAME=	rubyntlm
PORTVERSION=	0.4.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Message creator and parser for the NTLM authentication.

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes


.include <bsd.port.mk>
