# Created by: Jos Backus <josb@cncdsl.com>
# $FreeBSD: textproc/gpp/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	gpp
PORTVERSION=	2.24
CATEGORIES=	textproc
MASTER_SITES=	http://files.nothingisreal.com/software/gpp/

MAINTAINER=	jos@catnook.com
COMMENT=	The Generic Preprocessor

USE_BZIP2=	yes
GNU_CONFIGURE=	yes

MAN1=		gpp.1

NO_STAGE=	yes
.include <bsd.port.mk>
