# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: science/R-cran-e1071/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	e1071
DISTVERSION=	1.6-1
PORTREVISION=	5
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Misc Functions of the Department of Statistics (e1071), TU Wien

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
