# New ports collection makefile for:   XBlood
# Date created:        27 Jun 1999
# Whom:                Sakai Hiroaki <sakai@miya.ee.kagu.sut.ac.jp>
#
# $FreeBSD: ports/games/xblood/Makefile,v 1.15 2012/11/17 05:57:56 svnexp Exp $
#

PORTNAME=	xblood
PORTVERSION=	2.0
PORTREVISION=	2
CATEGORIES=	games
MASTER_SITES=	http://kozos.jp/myfreesoft/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Makes the root window bloody

MAKE_ENV=	X11BASE=${LOCALBASE}
USE_XORG=	x11
MAN1=		xblood.1
MANCOMPRESSED=	yes
PLIST_FILES=	bin/xblood

.include <bsd.port.mk>
