#!/bin/sh
# $FreeBSD: head/games/sokoban/pkg-deinstall 314610 2013-03-18 23:48:12Z bdrewery $

FILE="/var/games/sokoban"

if [ "$2" = "POST-DEINSTALL" -a -f "$FILE" ]; then
	echo "===>   If you are completely uninstalling sokoban you may also want to remove the scores files: $FILE"
fi
