# Created by: ache
# $FreeBSD: devel/p5-String-CRC32/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	String-CRC32
PORTVERSION=	1.4
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl interface for cyclic redundancy check generation

USES=		perl5
USE_PERL5=	configure

MAN3=		String::CRC32.3

NO_STAGE=	yes
.include <bsd.port.mk>
