# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: devel/R-cran-iterators/Makefile 338168 2013-12-30 20:55:18Z ohauer $

PORTNAME=	iterators
PORTVERSION=	1.0.6
PORTREVISION=	7
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Iterator construct for R

LICENSE=	APACHE20

USES=	cran:auto-plist

.include <bsd.port.mk>
