# New ports collection makefile for:	devel/p5-Perl6-Say
# Date created:				2007/07/28
# Whom:					chinsan
#
# $FreeBSD: ports/devel/p5-Perl6-Say/Makefile,v 1.9 2012/11/17 05:56:26 svnexp Exp $
#

PORTNAME=	Perl6-Say
PORTVERSION=	0.16
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl 6 say (print, but no newline needed) function

PERL_CONFIGURE=	yes

MAN3=		Perl6::Say.3

.include <bsd.port.mk>
