--- config/elasticsearch.yml.orig	2022-11-17 18:55:38 UTC
+++ config/elasticsearch.yml
@@ -31,10 +31,12 @@
 # Path to directory where to store the data (separate multiple locations by comma):
 #
 #path.data: /path/to/data
+path.data: /var/db/elasticsearch
 #
 # Path to log files:
 #
 #path.logs: /path/to/logs
+path.logs: /var/log/elasticsearch
 #
 # ----------------------------------- Memory -----------------------------------
 #
@@ -80,6 +82,9 @@
 # Enable an unauthenticated TCP readiness endpoint on localhost
 #
 #readiness.port: 9399
+
+# ml is not supported on FreeBSD
+xpack.ml.enabled: false
 #
 # ---------------------------------- Various -----------------------------------
 #
