# Created by: Zhang Shu
# $FreeBSD: chinese/jis2gb/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	jis2gb
PORTVERSION=	1.5
CATEGORIES=	chinese
MASTER_SITES=	http://kanji.zinbun.kyoto-u.ac.jp/~yasuoka/ftp/program/
DISTFILES=	jis2gb.tar.Z

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Convert JIS Kanji to GuoBiao Hanzi

WRKSRC=		${WRKDIR}/${PORTNAME}
ALL_TARGET=

#MAN1=		${PORTNAME}.1

.include <bsd.port.mk>
