# lots of clang'isms heare:wq

dfly-patch:
	${CP} ${DFLY_FILESDIR}/bundled_libuv_dfly.patch ${WRKSRC}/deps/patches/
	${REINPLACE_CMD} -e 's@-stdlib=libc\+\+@@g' \
			 -e '/CXXLD /s@CXX)@CXX) -lgcc_s@g' \
		${WRKSRC}/src/Makefile \
		${WRKSRC}/ui/Makefile
	${REINPLACE_CMD} -e "s@\(-lutf8proc\)@${LOCALBASE}/lib/libutf8proc.a@g"	\
			 -e "s@-DJULIA_ENABLE_THREADING@@g"	\
		${WRKSRC}/Make.inc
