# $FreeBSD: www/rubygem-d3_rails/Makefile 331012 2013-10-20 12:49:22Z swills $

PORTNAME=	d3_rails
PORTVERSION=	3.3.6
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	JavaScript framework for data visualization

RUN_DEPENDS=	rubygem-railties>=3.1.0:${PORTSDIR}/www/rubygem-railties

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes

.include <bsd.port.mk>
