# Created by: Anatoliy Dmytriyev
# $FreeBSD: head/devel/p5-Heap/Makefile 341625 2014-01-28 16:46:01Z miwi $

PORTNAME=	Heap
PORTVERSION=	0.80
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tolid@tolid.eu.org
COMMENT=	Perl extensions for keeping data partially sorted

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
