# Created by: Joe Marcus Clarke <marcus@FreeBSD.org>
# $FreeBSD: print/pdflib-perl/Makefile 327765 2013-09-20 22:43:59Z bapt $

PKGNAMESUFFIX=	-perl

MAINTAINER=	ale@FreeBSD.org

MASTERDIR=	${.CURDIR}/../pdflib

OPTIONS_DEFAULT=PERL

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
