# Created by: Joe Marcus Clarke <marcus@FreeBSD.org>
# $FreeBSD: print/pdflib-perl/Makefile 340722 2014-01-22 17:00:46Z mat $

PKGNAMESUFFIX=	-perl

MAINTAINER=	ale@FreeBSD.org

MASTERDIR=	${.CURDIR}/../pdflib

OPTIONS_DEFAULT=PERL

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
