# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: devel/R-cran-chron/Makefile 313562 2013-03-07 04:21:34Z bf $

PORTNAME=	chron
DISTVERSION=	2.3-43
PORTREVISION=	2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R package for creating objects which can handle dates and times

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
