# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: devel/R-cran-chron/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	chron
DISTVERSION=	2.3-43
PORTREVISION=	4
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R package for creating objects which can handle dates and times

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
