# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: x11-themes/kde-icons-sky/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	sky
PORTVERSION=	0.7.3
MASTER_SITES=	http://www.kde-look.org/CONTENT/content-files/
DISTNAME=	3095-${PORTNAME}-${PORTVERSION}dave
EXTRACT_SUFX=	.tgz

COMMENT=	KDE SKY iconset

WRKSRC=		${WRKDIR}/${PORTNAME}

NO_STAGE=	yes
.include "${.CURDIR}/../kde-icons-noia/Makefile.icons"
