# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: textproc/p5-DelimMatch/Makefile 340601 2014-01-21 11:52:07Z mat $

PORTNAME=	DelimMatch
PORTVERSION=	1.05
CATEGORIES=	textproc perl5
MASTER_SITES=	http://nwalsh.com/perl/delimmatch/
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl extension to find regexp delimited strings with proper nesting

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
