# Created by: ijliao
# $FreeBSD: devel/sdlmm/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	sdlmm
PORTVERSION=	0.1.8
PORTREVISION=	6
CATEGORIES=	devel
MASTER_SITES=	SF/${PORTNAME}/SDLmm/${PORTVERSION}
DISTNAME=	SDLmm-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A C++ Wrapper for the SDL (Simple DirectMedia Layer)

USE_AUTOTOOLS=	libtool
USE_SDL=	sdl
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
