# Created by: clsung@dragon2.net
# $FreeBSD: devel/p5-Class-NamedParms/Makefile 315509 2013-03-29 00:44:53Z eadler $

PORTNAME=	Class-NamedParms
PORTVERSION=	1.06
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lightweight named parameter handling system

PERL_CONFIGURE=	yes

MAN3=		Class::NamedParms.3

.include <bsd.port.mk>
