# Created by: clsung@dragon2.net
# $FreeBSD: devel/p5-Class-NamedParms/Makefile 331856 2013-10-28 13:46:25Z vanilla $

PORTNAME=	Class-NamedParms
PORTVERSION=	1.06
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lightweight named parameter handling system

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
