# $FreeBSD: graphics/php53-exif/Makefile 327733 2013-09-20 18:35:44Z bapt $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php53

PKGNAMESUFFIX=	-exif

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
