# New ports collection makefile for:	p5-Chess-PGN-Parse
# Date created: 			23 July 2005
# Whom: 				Aaron Dalton <aaron@daltons.ca>
#
# $FreeBSD: ports/textproc/p5-Chess-PGN-Parse/Makefile,v 1.8 2012/11/17 06:02:04 svnexp Exp $
#

PORTNAME=	Chess-PGN-Parse
PORTVERSION=	0.19
CATEGORIES=	textproc games perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:GMAX
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Reads and parses PGN (Portable Game Notation) Chess files

PERL_CONFIGURE=	yes

MAN3=		Chess::PGN::Parse.3

.include <bsd.port.mk>
