# Created by: smace@FreeBSD.org
# $FreeBSD: net/tcpslice/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	tcpslice
PORTVERSION=	2008.05.19
CATEGORIES=	net
MASTER_SITES=	http://www.tcpdump.org/weekly/

MAINTAINER=	sbz@FreeBSD.org
COMMENT=	A tool for extracting portions of pcap files

MAN1=		tcpslice.1
PLIST_FILES=	sbin/tcpslice

GNU_CONFIGURE=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
