# Created by: janos.mohacsi@bsd.hu
# $FreeBSD: hungarian/jdictionary-eng-hun-expr/Makefile 327735 2013-09-20 18:43:02Z bapt $

PORTNAME=	jdictionary-eng-hun-expr
PORTVERSION=	1.4
PORTREVISION=	4
CATEGORIES=	hungarian textproc
MASTER_SITES=	SF/jdictionary/Plugins%20for%20jDictionary/Smart%20English-Hungarian%20expression
DISTNAME=	SmartEngHunExp-1_4.jar

COMMENT=	JDictionary plugin: English-Hungarian expression dictionary

MASTERDIR=	${.CURDIR}/../../textproc/jdictionary

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile.plugin"
