# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: ports/devel/p5-App-Rad/Makefile,v 1.2 2012/11/17 05:56:04 svnexp Exp $

PORTNAME=	App-Rad
PORTVERSION=	1.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Rapid (and easy!) creation of command line applications

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		App::Rad.3 \
		App::Rad::Exclude.3 \
		App::Rad::Help.3 \
		App::Rad::Include.3 \
		App::Rad::Plugin.3

.include <bsd.port.mk>
