# Created by: will
# $FreeBSD: astro/p5-Geo-METAR/Makefile 331586 2013-10-25 14:04:57Z vanilla $

PORTNAME=	Geo-METAR
PORTVERSION=	1.15
CATEGORIES=	astro geography perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Geo
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module that processes METAR information from NOAA sources

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
