# $FreeBSD: devel/hs-ConfigFile/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	ConfigFile
PORTVERSION=	1.1.1
PORTREVISION=	6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Configuration file reading and writing

LICENSE=	LGPL21

USE_CABAL=	MissingH>=1.0.0 mtl parsec

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
