# $FreeBSD: devel/hs-ConfigFile/Makefile 327723 2013-09-20 17:04:43Z bapt $

PORTNAME=	ConfigFile
PORTVERSION=	1.1.1
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Configuration file reading and writing

LICENSE=	LGPL21

USE_CABAL=	MissingH>=1.0.0 mtl parsec

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
