# New ports collection makefile for:   libsrs2
# Date created:        02 July 2004
# Whom:                snowchyld
#
# $FreeBSD: ports/mail/libsrs2/Makefile,v 1.13 2012/11/17 05:59:04 svnexp Exp $
#

PORTNAME=		libsrs2
PORTVERSION=		1.0.18
PORTREVISION=	1
CATEGORIES=		mail
MASTER_SITES=		http://www.libsrs2.org/%SUBDIR%/
MASTER_SITE_SUBDIR=	srs

MAINTAINER=		ports@FreeBSD.org
COMMENT=		Sender Rewriting Scheme 2 C Implementation

USE_AUTOTOOLS=	libtool
USE_LDCONFIG=	yes
GNU_CONFIGURE=		yes

.include <bsd.port.mk>
