# $FreeBSD: textproc/p5-YAML/Makefile 336871 2013-12-19 07:23:49Z sunpoet $

PORTNAME=	YAML
PORTVERSION=	0.87
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	YAML implementation in Perl

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
