# New ports collection makefile for:	gimp-help
# Date created:		10th April 2010
# Whom:			SimaMoto,RyoTa <liangtai.s4@gmail.com>
#
# $FreeBSD: ports/polish/gimp-help/Makefile,v 1.2 2012/11/17 06:00:44 svnexp Exp $
#

CATEGORIES=	polish graphics

MAINTAINER=	liangtai.s4@gmail.com
COMMENT=	The GIMP User Manual in Polish

MASTERDIR=	${.CURDIR}/../../misc/gimp-help-en

DOCLANG=	pl
AMPLE=	"@comment "

.include "${MASTERDIR}/Makefile"
