# Created by: SimaMoto,RyoTa <liangtai.s4@gmail.com>
# $FreeBSD: polish/gimp-help/Makefile 327761 2013-09-20 22:34:42Z bapt $

CATEGORIES=	polish graphics

MAINTAINER=	liangtai.s4@gmail.com
COMMENT=	The GIMP User Manual in Polish

MASTERDIR=	${.CURDIR}/../../misc/gimp-help-en

DOCLANG=	pl
AMPLE=	"@comment "

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
