# Created by: Joe Marcus Clarke <marcus@FreeBSD.org>
# $FreeBSD: security/pam_helper/Makefile 328226 2013-09-25 00:54:08Z bdrewery $

PORTNAME=	pam_helper
PORTVERSION=	1.0
CATEGORIES=	security sysutils
MASTER_SITES=	http://www.marcuscom.com/pam_helper/

MAINTAINER=	marcus@FreeBSD.org
COMMENT=	Authenticate applications requiring PAM services

USE_BZIP2=	yes

PLIST_FILES=	bin/pam_helper

.include <bsd.port.mk>
