# New ports collection makefile for:	pam_helper
# Date created:				09 August 2008
# Whom:					Joe Marcus Clarke <marcus@FreeBSD.org>
#
# $FreeBSD: ports/security/pam_helper/Makefile,v 1.2 2012/11/17 06:01:14 svnexp Exp $
#

PORTNAME=	pam_helper
PORTVERSION=	1.0
CATEGORIES=	security sysutils
MASTER_SITES=	http://www.marcuscom.com/pam_helper/

MAINTAINER=	marcus@FreeBSD.org
COMMENT=	Authenticate applications requiring PAM services

USE_BZIP2=	yes

PLIST_FILES=	bin/pam_helper

.include <bsd.port.mk>
