# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: textproc/p5-Text-Tags/Makefile 326942 2013-09-11 06:27:41Z az $

PORTNAME=	Text-Tags
PORTVERSION=	0.04
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Parses folksonomy space-separated tags

USES=		perl5
USE_PERL5=	configure

MAN3=		Text::Tags.3 Text::Tags::Parser.3

.include <bsd.port.mk>
