# New ports collection makefile for:	p5-Text-Tags
# Date created:		2006-07-10
# Whom:			Gea-Suan Lin <gslin@gslin.org>
#
# $FreeBSD: ports/textproc/p5-Text-Tags/Makefile,v 1.5 2012/11/17 06:02:10 svnexp Exp $
#

PORTNAME=	Text-Tags
PORTVERSION=	0.04
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Parses folksonomy space-separated tags

PERL_CONFIGURE=	yes

MAN3=		Text::Tags.3 Text::Tags::Parser.3

.include <bsd.port.mk>
