# Created by: Thorsten Greiner <thorsten.greiner@web.de>
# $FreeBSD: textproc/p5-Lingua-Stem-It/Makefile 333056 2013-11-07 03:52:41Z vanilla $

PORTNAME=	Lingua-Stem-It
PORTVERSION=	0.02
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Stemmer for Italian

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
