# New ports collection makefile for:    obliterate
# Date created:         17 Nov 1999
# Whom:                 Wes Peters <wes@FreeBSD.ORG>
#
# $FreeBSD: ports/sysutils/obliterate/Makefile,v 1.14 2012/11/17 06:01:39 svnexp Exp $
#

PORTNAME=	obliterate
PORTVERSION=	0.5
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR= wes


MAINTAINER=	ports@FreeBSD.org
COMMENT=	Securely delete file[s]

.include <bsd.port.mk>
