# New ports collection makefile for:   libxkbfile
# Date Created:			7 May 2004
# Whom:				Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/libxkbfile/Makefile,v 1.13 2012/11/17 06:03:18 svnexp Exp $
#

PORTNAME=	libxkbfile
PORTVERSION=	1.0.7
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XKB file library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 kbproto:both

.include <bsd.port.mk>
