# New ports collection makefile for:    nl-aspell
# Date created:                         2 September 2002
# Whom:                                 Thierry Thomas <thierry@pompo.net>
#
# $FreeBSD: ports/textproc/nl-aspell/Makefile,v 1.9 2012/11/17 06:02:03 svnexp Exp $
#

PORTNAME=	${DICT}-aspell
DISTVERSION=	-nl-0.50-2
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Dutch dictionary

DICT=	 	nl

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
