# Ports collection makefile for:	rubygem-god
# Date created:				23 July 2007
# Whom:					Robert Gogolok <gogo@cs.uni-sb.de>
#
# $FreeBSD: ports/sysutils/rubygem-god/Makefile,v 1.19 2012/11/17 06:01:44 svnexp Exp $

PORTNAME=	god
PORTVERSION=	0.12.1
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	gogo@cs.uni-sb.de
COMMENT=	Monitoring framework written in Ruby

RUN_DEPENDS=	rubygem-hoe>=1.3.0:${PORTSDIR}/devel/rubygem-hoe

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/god

.include <bsd.port.mk>
