# Created by: Lubomir Marinov <lubomir_m@abv.bg>
# $FreeBSD: x11-toolkits/p5-Tk-ResizeButton/Makefile 332594 2013-11-03 08:05:18Z az $

PORTNAME=	Tk-ResizeButton
PORTVERSION=	0.01
PORTREVISION=	4
CATEGORIES=	x11-toolkits perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Resizeable button to be used in a Tk::HList column header

BUILD_DEPENDS=	p5-Tk>=0:${PORTSDIR}/x11-toolkits/p5-Tk
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
