# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: math/p5-Math-Polygon/Makefile 332813 2013-11-05 06:56:18Z vanilla $

PORTNAME=	Math-Polygon
PORTVERSION=	1.02
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Class for Maintaining Polygon Data

BUILD_DEPENDS=	p5-Test-Pod>=0:${PORTSDIR}/devel/p5-Test-Pod
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
