# $FreeBSD: x11/xprop/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	xprop
PORTVERSION=	1.2.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Property displayer for X

XORG_CAT=	app
USE_XORG=	xmuu x11

PLIST_FILES=	bin/xprop

MAN1=		xprop.1

.include <bsd.port.mk>
