# $FreeBSD: x11/xprop/Makefile 324725 2013-08-14 14:39:01Z zeising $

PORTNAME=	xprop
PORTVERSION=	1.2.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Property displayer for X

XORG_CAT=	app
USE_XORG=	xmuu x11

PLIST_FILES=	bin/xprop

MAN1=		xprop.1

.include <bsd.port.mk>
