# $FreeBSD: devel/p5-Test-Mock-Guard/Makefile 338870 2014-01-06 12:43:03Z az $

PORTNAME=	Test-Mock-Guard
PORTVERSION=	0.09
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for simple mock test library using RAII

BUILD_DEPENDS=	p5-Class-Load>=0.06:${PORTSDIR}/devel/p5-Class-Load
RUN_DEPENDS=	p5-Class-Load>=0.06:${PORTSDIR}/devel/p5-Class-Load

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
