# $FreeBSD: ports/russian/libreoffice/Makefile,v 1.3 2012/11/17 06:00:56 svnexp Exp $

LO_I18N=	ru
LO_HAS_HELPPACK=	yes
CATEGORIES=	russian editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
