# Created by: Bill Swingle <unfurl@FreeBSD.org>
# $FreeBSD: www/p5-Compress-LeadingBlankSpaces/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	Compress-LeadingBlankSpaces
PORTVERSION=	0.06
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl class to compress leading blank spaces in web content

USES=		perl5
USE_PERL5=	configure

MAN3=		Compress::LeadingBlankSpaces.3

NO_STAGE=	yes
.include <bsd.port.mk>
