# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: misc/rubygem-mime-types/Makefile 319601 2013-06-01 21:25:48Z swills $

PORTNAME=	mime-types
PORTVERSION=	1.23
CATEGORIES=	misc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby gem which provides a mailcap-like MIME Content-Type lookup

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
