# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: misc/rubygem-mime-types/Makefile 327745 2013-09-20 20:50:57Z bapt $

PORTNAME=	mime-types
PORTVERSION=	1.23
CATEGORIES=	misc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby gem which provides a mailcap-like MIME Content-Type lookup

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
