# $FreeBSD: graphics/hs-dia-base/Makefile 327733 2013-09-20 18:35:44Z bapt $

PORTNAME=	dia-base
PORTVERSION=	0.1.1.2
PORTREVISION=	2
CATEGORIES=	graphics haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	EDSL for teaching Haskell with diagrams - data types

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
