# $FreeBSD: x11-drivers/xf86-video-savage/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	xf86-video-savage
PORTVERSION=	2.3.6
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org savage display driver

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto glproto
MAN4=		savage.4x

.include <bsd.port.mk>
