# Created by: eimar.koort
# $FreeBSD: x11/keyboardcast/Makefile 337411 2013-12-25 12:54:43Z amdmi3 $

PORTNAME=	keyboardcast
PORTVERSION=	0.1.1
PORTREVISION=	2
CATEGORIES=	x11
MASTER_SITES=	GOOGLE_CODE \
		http://desrt.mcmaster.ca/code/keyboardcast/

MAINTAINER=	eimar.koort@gmail.com
COMMENT=	Broadcast keystrokes to multiple X windows for Gnome2

USE_XORG=	xmu x11
USE_GNOME=	libwnck libglade2 gtk20
USES=		pkgconfig
INSTALLS_ICONS=	yes

.include <bsd.port.mk>
