# Created by: will
# $FreeBSD: security/p5-Crypt-UnixCrypt/Makefile 341825 2014-01-30 09:42:48Z az $

PORTNAME=	Crypt-UnixCrypt
PORTVERSION=	1.0
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl module implementing crypt(3) function

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
