# Created by: Sergey Skvortsov <skv@FreeBSD.org>
# $FreeBSD: devel/p5-Class-ISA/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Class-ISA
PORTVERSION=	0.36
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Report the search path for a class's ISA tree

USES=		perl5
USE_PERL5=	configure

MAN3=		Class::ISA.3

NO_STAGE=	yes
.include <bsd.port.mk>
