# New ports collection makefile for:	Class-ISA
# Date created:		17 Dec 2001
# Whom:			Sergey Skvortsov <skv@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Class-ISA/Makefile,v 1.8 2012/11/17 05:56:07 svnexp Exp $
#

PORTNAME=	Class-ISA
PORTVERSION=	0.36
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Report the search path for a class's ISA tree

PERL_CONFIGURE=	yes

MAN3=		Class::ISA.3

.include <bsd.port.mk>
