# Created by: Sergey Skvortsov <skv@FreeBSD.org>
# $FreeBSD: head/devel/p5-Class-ISA/Makefile 331856 2013-10-28 13:46:25Z vanilla $

PORTNAME=	Class-ISA
PORTVERSION=	0.36
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Report the search path for a class's ISA tree

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
