# Created by: Alexander Logvinov <avl@FreeBSD.org>
# $FreeBSD: net/remmina-plugin-telepathy/Makefile 321344 2013-06-20 01:59:25Z fluffy $

PKGNAMESUFFIX=	-telepathy

COMMENT=	Remmina plugin for Telepathy support

LIB_DEPENDS=	telepathy-glib.0:${PORTSDIR}/net-im/telepathy-glib

MASTERDIR=	${.CURDIR}/../remmina-plugins

WITH_TELEP=	yes

.include "${MASTERDIR}/Makefile"
