# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: devel/rubygem-sequel3/Makefile 322972 2013-07-13 21:30:51Z swills $

# legacy for rubygem-larch

PORTNAME=	sequel
PORTVERSION=	3.48.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	The Database Toolkit for Ruby

PORTSCOUT=	limit:^3
NO_LATEST_LINK=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=yes

PLIST_FILES=	bin/sequel

.include <bsd.port.mk>
