post-patch-NJS-on:
	(cd ${WRKSRC_njs} && ${PATCH} ${PATCH_ARGS} < ${DFLY_PATCHDIR}/extra-auto_readline.diff)

pre-patch-MODSECURITY-on:
	-${REINPLACE_CMD} -e 's|\*-\*-freebsd\*|*-*-dragonfly*|' \
		${WRKSRC_MODSECURITY}/configure

pre-patch-HTTP_ZIP-on:
	-${REINPLACE_CMD} -e 's@\(defined(__OpenBSD__)\)@(\1 || defined(__FreeBSD__) || defined(__DragonFly__))@g' \
		${WRKSRC_mod_zip}/ngx_http_zip_endian.h
