# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-Object-Container/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Object-Container
PORTVERSION=	0.14
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Simple object container

RUN_DEPENDS=	p5-Class-Accessor>=0:${PORTSDIR}/devel/p5-Class-Accessor

USES=		perl5
USE_PERL5=	configure

MAN3=		Object::Container.3 \
		Object::Container::ja.3

NO_STAGE=	yes
.include <bsd.port.mk>
