# New ports collection makefile for:	crf++
# Date created:		2006-07-27
# Whom:			Cheng-Lung Sung <clsung@FreeBSD.org>
#
# $FreeBSD: ports/science/crf++/Makefile,v 1.19 2012/11/17 06:00:57 svnexp Exp $
#

PORTNAME=	crf++
PORTVERSION=	0.54
CATEGORIES=	science math
MASTER_SITES=	SF/crfpp/crfpp/${PORTVERSION} \
		${MASTER_SITE_LOCAL}
DISTNAME=	CRF++-${PORTVERSION}

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	Yet Another CRF toolkit

GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes
USE_AUTOTOOLS=	libtool

.include <bsd.port.mk>
