# $FreeBSD: x11/xkill/Makefile 327777 2013-09-20 23:43:19Z bapt $

PORTNAME=	xkill
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Utility for killing a client by its X resource

XORG_CAT=	app
USE_XORG=	x11 xmuu

PLIST_FILES=	bin/xkill

MAN1=		xkill.1

NO_STAGE=	yes
.include <bsd.port.mk>
