# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: www/R-cran-RgoogleMaps/Makefile 315967 2013-04-17 13:20:55Z tota $

PORTNAME=	RgoogleMaps
PORTVERSION=	1.2.0.3
CATEGORIES=	www
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Overlays on Google map tiles in R

RUN_DEPENDS=	R-cran-png>0:${PORTSDIR}/graphics/R-cran-png

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
