# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-Tie-Hash-Sorted/Makefile 332245 2013-10-31 14:31:30Z vanilla $

PORTNAME=	Tie-Hash-Sorted
PORTVERSION=	0.10
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Tie::Hash::Sorted - presents hashes in sorted order

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
