# New ports collection makefile for:    tornado
# Date created:                         1 July 2001
# Whom:                                 minter
#
# $FreeBSD: games/tornado/Makefile 316464 2013-04-24 18:10:30Z ak $
#

PORTNAME=	tornado
PORTVERSION=	1.4
PORTREVISION=	1
CATEGORIES=	games
MASTER_SITES=	http://kiza.kcore.de/media/software/${PORTNAME}/

MAINTAINER=	minter@lunenburg.org
COMMENT=	A curses-based game of weather destruction

MAN6=		tornado.6
MANLANG=	"" de fr it nl no ru

USES=		gettext
USE_GMAKE=	yes

.include <bsd.port.mk>
