# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: converters/R-cran-rjson/Makefile 333659 2013-11-13 08:19:34Z bf $

PORTNAME=	rjson
PORTVERSION=	0.2.13
PORTREVISION=	2
CATEGORIES=	converters
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	JSON for R

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
