# Created by: Autrijus Tang <autrijus@autrijus.org>
# $FreeBSD: www/p5-libapreq2/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	www perl5 devel

MAINTAINER=	skv@FreeBSD.org
COMMENT=	Generic Apache2 Request Library with perl binding

MASTERDIR=	${.CURDIR}/../libapreq2

WITH_MODPERL2=	yes
MAKE_ENV+=	MAKE=${GMAKE} ## MakeMaker blows it without this

.include "${MASTERDIR}/Makefile"
