# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: textproc/p5-Text-ASCIIMathML/Makefile 340594 2014-01-21 10:43:14Z mat $

PORTNAME=	Text-ASCIIMathML
PORTVERSION=	0.81
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	wenheping@gmail.com
COMMENT=	Perl extension for parsing ASCIIMathML text into MathML

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
