# Created by: Jesse
# $FreeBSD: sysutils/pbimaker/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	pbimaker
PORTVERSION=	1.3
CATEGORIES=	sysutils
MASTER_SITES=	SF/makeapbi/makeapbi/

MAINTAINER=	jessefrgsmith@yahoo.ca
COMMENT=	A program to convert ports into PBI modules

LICENSE=	BSD

NO_COFIGURE=	yes

WRKSRC=	${WRKDIR}/PBIMaker

NO_STAGE=	yes
.include <bsd.port.mk>
