# Created by: Akinori MUSHA aka knu <knu@idaemons.org>
# $FreeBSD: textproc/p5-Search-Saryer/Makefile 333056 2013-11-07 03:52:41Z vanilla $

PORTNAME=	Search-Saryer
PORTVERSION=	0.40
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	http://namazu.org/~tsuchiya/perl/
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl interface to the Sary library

LIB_DEPENDS=	libsary.so:${PORTSDIR}/textproc/sary

USES=		perl5 pkgconfig
USE_PERL5=	configure

.include <bsd.port.mk>
