# $FreeBSD: editors/calligra-l10n-sv/Makefile 327720 2013-09-20 16:36:23Z bapt $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
CATEGORIES=	editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Swedish messages and documentation for Calligra

CALLIGRA_L10N=	sv

NO_STAGE=	yes
.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
