# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: net/p5-BBS-UserInfo/Makefile 338850 2014-01-06 09:24:24Z az $

PORTNAME=	BBS-UserInfo
PORTVERSION=	0.01
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:GSLIN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Base class of BBS::UserInfo::XXX

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
