# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD: devel/py-d2to1/Makefile 342116 2014-02-01 11:24:30Z koobs $

PORTNAME=	d2to1
PORTVERSION=	0.2.11
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Distutils2-like setup.cfg files with setuptools setup.py

LICENSE=	BSD3CLAUSE

USE_PYTHON=		yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
