# $FreeBSD: devel/hs-bytestring-show/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	bytestring-show
PORTVERSION=	0.3.5.5
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient conversion of values into readable byte strings

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
