# Created by: vanilla
# $FreeBSD: www/p5-HTML-Strip/Makefile 333099 2013-11-07 13:55:25Z vanilla $

PORTNAME=	HTML-Strip
PORTVERSION=	1.06
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module for strip HTML tag

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
