# New ports collection makefile for:	pecl-stats
# Date created:			2006/07/31
# Whom:				chinsan <chinsan.tw@gmail.com>
#
# $FreeBSD: ports/math/pecl-stats/Makefile,v 1.6 2012/11/17 05:59:28 svnexp Exp $
#

PORTNAME=	stats
PORTVERSION=	1.0.2
CATEGORIES=	math textproc pear
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
EXTRACT_SUFX=	.tgz
DIST_SUBDIR=	PECL

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	A PECL extension which with routines for statistical computation

USE_PHP=	yes
USE_PHPEXT=	yes
DEFAULT_PHP_VER=53
IGNORE_WITH_PHP=5

.include <bsd.port.mk>
