# Created by: wenheping <wenheping@gmail.com>
# $FreeBSD: net/rubygem-oauth/Makefile 321604 2013-06-23 02:02:41Z swills $

PORTNAME=	oauth
PORTVERSION=	0.4.7
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Rubygem for Creating both OAuth Consumers and Service Providers

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=		bin/oauth

.include <bsd.port.mk>
