# New ports collection makefile for:	mergelog
# Date created:				Jun 25, 2002
# Whom:					Anton Berezin <tobez@FreeBSD.org>
#
# $FreeBSD: ports/www/mergelog/Makefile,v 1.6 2012/11/17 06:02:39 svnexp Exp $
#

PORTNAME=	mergelog
PORTVERSION=	4.5
PORTREVISION=	2
CATEGORIES=	www textproc
MASTER_SITES=	SF

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	A tool to merge and sort by date http log files

USE_GMAKE=	yes
GNU_CONFIGURE=	yes

MAN1=	mergelog.1 zmergelog.1

.include <bsd.port.mk>
