# $FreeBSD: devel/hs-base-unicode-symbols/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	base-unicode-symbols
PORTVERSION=	0.2.2.4
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode alternatives for common functions and operators

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
