# Created by: ijliao
# $FreeBSD: devel/ebnf2yacc/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	ebnf2yacc
PORTVERSION=	0.1.1
CATEGORIES=	devel
MASTER_SITES=	SF

MAINTAINER=	ports@FreeBSD.org
COMMENT=	EBNF to YACC

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/ebnf2yacc

.include <bsd.port.mk>
