--- pyproject.toml.orig	2022-10-14 17:21:32 UTC
+++ pyproject.toml
@@ -18,7 +18,7 @@ classifiers = [
 ]
 urls = {Homepage = "https://github.com/ipython/traitlets"}
 requires-python = ">=3.7"
-dynamic = ["description", "version"]
+dynamic = ["version"]
 
 [project.optional-dependencies]
 test = ["pytest", "pre-commit"]
