#!/bin/sh
#
# ex:ts=4:sw=4:noet
#-*- mode: makefile; tab-width: 4; -*-
#
# $FreeBSD: ports/mail/spamd/pkg-deinstall,v 1.2 2012/11/17 05:59:14 svnexp Exp $

if [ "$2" = "DEINSTALL" ]; then
	FILE="/etc/services"
	echo "===>   Removing spamd entries from ${FILE}"
	sed -i '' \
		-e "/^spamd-sync.*8025/d" \
		-e "/^spamd-cfg.*8026/d" \
		-e "/^spamd.*8025/d" \
		${FILE}
fi
