# Created by: Vincent Tantardini <vinc@freebsd-fr.org>
# $FreeBSD: ports/graphics/hsetroot/Makefile,v 1.19 2013/01/24 11:56:09 svnexp Exp $

PORTNAME=	hsetroot
PORTVERSION=	1.0.2
PORTREVISION=	10
CATEGORIES=	graphics
MASTER_SITES=	http://cdn.thegraveyard.org/releases/hsetroot/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Wallpaper manipulation utility for X11

LICENSE=	GPLv2

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_EFL=	imlib2

PLIST_FILES=	bin/hsetroot

.include <bsd.port.mk>
