# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: sysutils/php55-fileinfo/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	sysutils

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-fileinfo

.include "${MASTERDIR}/Makefile"
