# $FreeBSD: net/gstreamer1-plugins-libmms/Makefile 327755 2013-09-20 22:10:23Z bapt $

PORTREVISION=	0
CATEGORIES=	net

COMMENT=	Gstreamer mms:// and mmsh:// plugin

GST_PLUGIN=	libmms
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
