# Ports collection makefile for:  pear-Horde_Date_Parser
# Date created:			  7 July 2011
# Whom:				  Martin Matuska <mm@FreeBSD.org>
#
# $FreeBSD: ports/devel/pear-Horde_Date_Parser/Makefile,v 1.6 2012/12/12 15:19:48 svnexp Exp $

PORTNAME=	Horde_Date_Parser
PORTVERSION=	2.0.1
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Date Parser

USE_HORDE_RUN=	Horde_Date \
		Horde_Support

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
