# New ports collection makefile for:	p5-Convert-UU
# Date created:				October 20th 1996
# Whom:	      				James FitzGibbon <jfitz@FreeBSD.org>
#
# $FreeBSD: ports/converters/p5-Convert-UU/Makefile,v 1.33 2012/11/17 05:55:03 svnexp Exp $
#

PORTNAME=	Convert-UU
PORTVERSION=	0.52.01
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:C/\.(..)$/\1/}

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Perl5 module for uuencode and uudecode

PERL_CONFIGURE=	YES

MAN1=		puuencode.1 puudecode.1
MAN3=		Convert::UU.3

.include <bsd.port.mk>
