# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: databases/R-cran-DBI/Makefile 316623 2013-04-26 16:31:38Z tota $

PORTNAME=	DBI
DISTVERSION=	0.2-6
CATEGORIES=	databases
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	R Database Interface

LICENSE=	LGPL20 LGPL21 LGPL3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
