# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: x11-themes/kde-icons-noia/Makefile 327783 2013-09-20 23:54:03Z bapt $

PORTNAME=	noia
PORTVERSION=	1.00
MASTER_SITES=	${MASTER_SITE_GENTOO}
MASTER_SITE_SUBDIR=	distfiles
DISTNAME=	noia-kde-icons-${PORTVERSION}
EXTRACT_SUFX=	.tgz

COMMENT=	KDE Noia complete iconset

WRKSRC=		"${WRKDIR}/noia_kde_${PORTVERSION:C/\.//}"
PORT_SHAREDIR=	${PORTNAME}

NO_STAGE=	yes
.include "${.CURDIR}/Makefile.icons"
