# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11-toolkits/libXmu/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	libXmu
PORTVERSION=	1.1.1
PORTEPOCH=	1
CATEGORIES=	x11-toolkits

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Miscellaneous Utilities libraries

XORG_CAT=	lib
USE_XORG=	xproto:both x11 xt xext

.include <bsd.port.mk>
