# $FreeBSD: ports/print/rubygem-colortools/Makefile,v 1.13 2012/11/17 06:00:54 svnexp Exp $

PORTNAME=	colortools
PORTVERSION=	1.3.0
CATEGORIES=	print rubygems
MASTER_SITES=	RG
DISTNAME=	color-tools-${PORTVERSION}

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provides colour space definition and manipulation

USE_RUBY=	yes
USE_RUBYGEMS=	yes
GEM_NAME=	${DISTNAME}
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
