# $FreeBSD: print/rubygem-colortools/Makefile 327765 2013-09-20 22:43:59Z bapt $

PORTNAME=	colortools
PORTVERSION=	1.3.0
CATEGORIES=	print rubygems
MASTER_SITES=	RG
DISTNAME=	color-tools-${PORTVERSION}

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provides colour space definition and manipulation

USE_RUBY=	yes
USE_RUBYGEMS=	yes
GEM_NAME=	${DISTNAME}
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
