# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: textproc/p5-Lingua-Treebank/Makefile 333056 2013-11-07 03:52:41Z vanilla $

PORTNAME=	Lingua-Treebank
PORTVERSION=	0.16
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for manipulating the Penn Treebank format

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
