# New ports collection makefile for:	activitymail
# Date created:			11 Nov 2003
# Whom:					Joseph Scott <joseph@randomnetworks.com>
#
# $FreeBSD: devel/activitymail/Makefile 326581 2013-09-07 08:23:45Z az $
#

PORTNAME=	activitymail
PORTVERSION=	1.26
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DWHEELER/activitymail

MAINTAINER=	joseph@randomnetworks.com
COMMENT=	A program for sending email messages for CVS repository commits

USES=		perl5
USE_PERL5=	modbuild

PLIST_FILES=	bin/activitymail
MAN1=		activitymail.1

.include <bsd.port.mk>
