# Created by: Cheng-Lung Sung <clsung@dragon2.net>
# $FreeBSD: devel/p5-Class-XPath/Makefile 331856 2013-10-28 13:46:25Z vanilla $

PORTNAME=	Class-XPath
PORTVERSION=	1.4
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Base class to add xpath matching to object trees

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
