# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: sysutils/gstreamer-plugins-hal/Makefile 327772 2013-09-20 23:05:58Z bapt $
#    $MCom: ports/sysutils/gstreamer-plugins-hal/Makefile,v 1.6 2008/03/19 14:05:38 ahze Exp $

PORTREVISION=	0
CATEGORIES=	sysutils

COMMENT=	Gstreamer hal plugin

GST_PLUGIN=	hal

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
