#!/bin/sh
# $FreeBSD: ports/graphics/jumpgis-postgis/pkg-deinstall,v 1.2 2012/11/17 05:58:11 svnexp Exp $

if [ "$2" != "DEINSTALL" ]; then
    exit
fi

echo Restoring CLASSPATH in ${PKG_PREFIX}/bin/jumpgis

grep -v '^CLASSPATH=$CLASSPATH:$LIB/pg74jdbc3.jar$' ${PKG_PREFIX}/bin/jumpgis > ${PKG_PREFIX}/bin/jumpgis.new
cat ${PKG_PREFIX}/bin/jumpgis.new > ${PKG_PREFIX}/bin/jumpgis
rm ${PKG_PREFIX}/bin/jumpgis.new
