# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-Array-Unique/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Array-Unique
PORTVERSION=	0.08
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Tie-able array that allows only unique values

USES=		perl5
USE_PERL5=	configure

MAN3=		Array::Unique.3

NO_STAGE=	yes
.include <bsd.port.mk>
