# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: security/R-cran-digest/Makefile 338288 2013-12-31 12:52:20Z tota $

PORTNAME=	digest
PORTVERSION=	0.6.4
CATEGORIES=	security
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Create cryptographic hash digests of R objects

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
