# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: ports/security/R-cran-digest/Makefile,v 1.16 2013/02/17 20:51:56 svnexp Exp $

PORTNAME=	digest
PORTVERSION=	0.6.3
CATEGORIES=	security
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Create cryptographic hash digests of R objects

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
