# Ports collection makefile for:	rubygem-prawn-graph
# Date created:				December 16, 2010
# Whom:					Philip M. Gollucci <pgpollucci@p6m7g8.com>
#
# $FreeBSD: ports/print/rubygem-prawn-graph/Makefile,v 1.2 2012/11/17 06:00:54 svnexp Exp $

PORTNAME=	prawn-graph
PORTVERSION=	0.0.4
CATEGORIES=	print rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Draw basic graphs and charts natively in your PDFs

RUN_DEPENDS=	rubygem-prawn>=0:${PORTSDIR}/print/rubygem-prawn

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
