# Created by: Martin Wilke (miwi@FreeBSD.org)
# $FreeBSD: devel/pear-Testing_Selenium/Makefile 333263 2013-11-08 21:41:53Z antoine $

PORTNAME=	Testing_Selenium
PORTVERSION=	0.4.4
CATEGORIES=	devel pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR Binding - Once more unto the breach

BUILD_DEPENDS=	${PEARDIR}/PEAR.php:${PORTSDIR}/devel/pear
RUN_DEPENDS=	${PEARDIR}/PEAR.php:${PORTSDIR}/devel/pear

PEAR_AUTOINSTALL=	yes

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.mk"
.include <bsd.port.post.mk>
