# New ports collection makefile for:	libglade2-reference
# Date created:				09 May 2006
# Whom:					Jean-Yves Lefort <jylefort@FreeBSD.org>
#
# $FreeBSD: ports/devel/libglade2-reference/Makefile,v 1.3 2012/11/17 05:55:54 svnexp Exp $
#

PORTREVISION=	1

REFERENCE_SRC=	${WRKSRC}/doc

.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
