# Created by: Jean-Yves Lefort <jylefort@FreeBSD.org>
# $FreeBSD: devel/libglade2-reference/Makefile 336013 2013-12-09 18:41:16Z antoine $

PORTREVISION=	1

REFERENCE_SRC=	${WRKSRC}/doc

.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
