# Created by: lars.eggert@gmx.net
# $FreeBSD: devel/p5-Algorithm-ChooseSubsets/Makefile 338987 2014-01-07 09:28:30Z az $

PORTNAME=	Algorithm-ChooseSubsets
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lars.eggert@gmx.net
COMMENT=	Perl algorithm to iterate through subsets of a list

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
