# Created by: Dominic Fandrey <kamikaze@bsdforen.de>
# $FreeBSD: games/ioquake3-server/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	ioquake3
PKGNAMESUFFIX=	-server

MAINTAINER=	kamikaze@bsdforen.de
COMMENT=	Ioquake3 dedicated server

UNIQUENAME=	${PORTNAME}${PKGNAMESUFFIX}
MASTERDIR=	${.CURDIR}/../${PORTNAME}

IOQ3=		SERVER GAMELIBS

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
