# Created by: Martin Matuska <martin@matuska.org>
# $FreeBSD: databases/luasql-postgres/Makefile 327717 2013-09-20 16:13:47Z bapt $

PORTNAME=	luasql

LUASQL_DRIVER=	postgres
MASTERDIR=      ${.CURDIR}/../luasql-mysql

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
