# New ports collection makefile for:   luasql-postgres
# Date created:        25 May 2009
# Whom:                Martin Matuska <martin@matuska.org>
#
# $FreeBSD: ports/databases/luasql-postgres/Makefile,v 1.3 2012/11/17 05:55:10 svnexp Exp $
#

PORTNAME=	luasql

LUASQL_DRIVER=	postgres
MASTERDIR=      ${.CURDIR}/../luasql-mysql

.include "${MASTERDIR}/Makefile"
