# Created by: Grzegorz Blach <gblach@FreeBSD.org>
# $FreeBSD: textproc/go-text/Makefile 339441 2014-01-11 17:46:33Z jlaffaye $

PORTNAME=	go-text
PORTVERSION=	20130502
PORTREVISION=	1
CATEGORIES=	textproc
MASTER_SITES=	LOCAL/gblach/

MAINTAINER=	gblach@FreeBSD.org
COMMENT=	Go package for manipulating paragraphs of text

GO_PKGNAME=	github.com/kr/text

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/lang/go/files/bsd.go.mk"
.include <bsd.port.post.mk>
