# Created by: Gabor Kovesdan
# $FreeBSD: security/p5-Digest-MD5-Reverse/Makefile 342011 2014-01-31 15:53:26Z miwi $

PORTNAME=	Digest-MD5-Reverse
PORTVERSION=	1.3
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension that looks for MD5 hashes in several databases

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
