# New ports collection makefile for:	py-repoze.lru
# Date created:				2011-03-21
# Whom:	      				Cheng-Lung Sung <clsung@FreeBSD.org>
#
# $FreeBSD: devel/py-repoze.lru/Makefile 320945 2013-06-14 14:59:38Z miwi $
#

PORTNAME=	repoze.lru
PORTVERSION=	0.6
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	A tiny LRU cache implementation and decorator

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

.include <bsd.port.mk>
