# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: devel/py-repoze.lru/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	repoze.lru
PORTVERSION=	0.6
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	A tiny LRU cache implementation and decorator

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
