# ex:ts=8
# Ports collection makefile for:	p5-Text-Textile
# Date created:			May 4, 2005
# Whom:				Travis Campbell <hcoyote@ghostar.org>
#
# $FreeBSD: ports/textproc/p5-Text-Textile/Makefile,v 1.6 2012/11/17 06:02:10 svnexp Exp $
#

PORTNAME=	Text-Textile
PORTVERSION=	2.12
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	hcoyote@ghostar.org
COMMENT=	A perl-based implementation of the Textile syntax by Dean Allen

PERL_CONFIGURE=	yes

MAN3=	Text::Textile.3

.include <bsd.port.mk>
