# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: www/py-django-pipeline/Makefile 320941 2013-06-14 14:44:51Z miwi $

PORTNAME=	django-pipeline
PORTVERSION=	1.2.24
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	Asset (css/js) packaging library for Django

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django>0<1.5:${PORTSDIR}/www/py-django14

USE_PYTHON=	-2.7
USE_PYDISTUTILS=easy_install

.include <bsd.port.mk>
