# New ports collection makefile for:	libkvkontakte
# Date created:				2012-05-12
# Whom:					Jason E. Hale <bsdkaffee@gmail.com>
#
# $FreeBSD: ports/net/libkvkontakte/Makefile,v 1.4 2012/11/17 06:00:04 svnexp Exp $
#

PORTNAME=	libkvkontakte
PORTVERSION=	${DIGIKAM_VER}
CATEGORIES=	net kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE4 library for accessing vk.com

.include "${.CURDIR}/../../graphics/digikam-kde4/Makefile.common"

LIB_DEPENDS=	qjson:${PORTSDIR}/devel/qjson

.include <bsd.port.mk>
