# $FreeBSD: net/libkvkontakte/Makefile 315762 2013-04-08 17:10:56Z makc $

PORTNAME=	libkvkontakte
PORTVERSION=	${DIGIKAM_VER}
CATEGORIES=	net kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE4 library for accessing vk.com

.include "${.CURDIR}/../../graphics/digikam-kde4/Makefile.common"

LIB_DEPENDS=	qjson:${PORTSDIR}/devel/qjson
USE_LDCONFIG=	yes

.include <bsd.port.mk>
