# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: textproc/p5-Text-Typography/Makefile 317539 2013-05-06 18:30:15Z zi $

PORTNAME=	Text-Typography
PORTVERSION=	0.01
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to markup ASCII text with correct typography for HTML

PERL_CONFIGURE=	yes

MAN3=		Text::Typography.3

.include <bsd.port.mk>
