# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: converters/p5-Text-Unidecode/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	Text-Unidecode
PORTVERSION=	0.04
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Text::Unidecode -- US-ASCII transliterations of Unicode text

USES=		perl5
USE_PERL5=	configure

MAN3=	Text::Unidecode.3

.include <bsd.port.mk>
