# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: print/hs-hscolour/Makefile 315580 2013-03-29 22:43:58Z pgj $

PORTNAME=	hscolour
PORTVERSION=	1.20.3
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	print haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Colourise Haskell code

LICENSE=	GPLv2
FILE_LICENSE=	LICENCE-GPL

CABAL_SETUP=	Setup.hs

EXECUTABLE=	HsColour

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
