# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: audio/gstreamer-plugins-soundtouch/Makefile 327706 2013-09-20 14:36:35Z bapt $
#   $MCom: ports/audio/gstreamer-plugins-soundtouch/Makefile,v 1.3 2008/03/19 14:05:32 ahze Exp $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	GStreamer soundtouch plugin

GST_PLUGIN=	soundtouch

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins
NO_STAGE=	yes

.include "${MASTERDIR}/Makefile"
