# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: audio/gstreamer-plugins-soundtouch/Makefile 340722 2014-01-22 17:00:46Z mat $
#   $MCom: ports/audio/gstreamer-plugins-soundtouch/Makefile,v 1.3 2008/03/19 14:05:32 ahze Exp $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	GStreamer soundtouch plugin

GST_PLUGIN=	soundtouch

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
