# Created by: Gerrit Beine <gerrit.beine@gmx.de>
# $FreeBSD: mail/squirrelmail-calendar_file_backend-plugin/Makefile 327742 2013-09-20 19:59:12Z bapt $

PORTNAME=		calendar_file_backend
PORTVERSION=		1.0
PORTREVISION=	1
DISTNAME=		${PORTNAME}-${PORTVERSION}-2.0
DIST_SUBDIR=		squirrelmail

MAINTAINER=		ports@FreeBSD.org
COMMENT=		File backend for SquirrelMail Calendar plugin

SQUIRREL_PLUGIN_NAME=	${PORTNAME}

NO_STAGE=	yes
.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
