# $FreeBSD: net/dtcpclient/Makefile 332214 2013-10-31 08:02:52Z bapt $

PORTNAME=	dtcpclient
PORTVERSION=	20090812
#PORTREVISION=	0
CATEGORIES=	net ipv6
MASTER_SITES=	http://www.mahoroba.org/~ume/ipv6/ \
		http://home.jp.FreeBSD.org/~ume/ipv6/

MAINTAINER=	ume@FreeBSD.org
COMMENT=	Dynamic Tunnel Configuration Protocol client

LICENSE=	BSD

USES=		uidfix
USE_RC_SUBR=	dtcpclient

.include <bsd.port.mk>
