# New ports collection makefile for:	php53-posix
# Date created:			12 Apr 2012
# Whom:				Florian Smeets <flo@FreeBSD.org>
#
# $FreeBSD: ports/sysutils/php53-posix/Makefile,v 1.4 2012/11/17 06:01:41 svnexp Exp $
#

CATEGORIES=	sysutils

MASTERDIR=	${.CURDIR}/../../lang/php53

PKGNAMESUFFIX=	-posix

.include "${MASTERDIR}/Makefile"
