# Created by: petef@databits.net
# $FreeBSD: textproc/p5-PDF-Create/Makefile 326949 2013-09-11 07:40:59Z az $

PORTNAME=	PDF-Create
PORTVERSION=	1.06
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	A perl script to convert text files to PDF files

USES=		perl5
USE_PERL5=	configure
MAN3=		PDF::Create.3

.include <bsd.port.mk>
