# Created by: petef@databits.net
# $FreeBSD: textproc/p5-PDF-Create/Makefile 333222 2013-11-08 13:35:39Z jadawin $

PORTNAME=	PDF-Create
PORTVERSION=	1.06
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	A perl script to convert text files to PDF files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
