# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@sunpoet.net>
# $FreeBSD: devel/p5-Module-Version/Makefile 328860 2013-09-30 20:16:07Z sunpoet $

PORTNAME=	Module-Version
PORTVERSION=	0.12
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Get module versions

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
