# $FreeBSD: french/libreoffice/Makefile 340722 2014-01-22 17:00:46Z mat $

LO_I18N=	fr
LO_HAS_HELPPACK=	yes
CATEGORIES=	french editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
