# $FreeBSD: editors/libreoffice-hr/Makefile 340722 2014-01-22 17:00:46Z mat $

LO_I18N=	hr
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
