# $FreeBSD: textproc/hs-regex-compat/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	regex-compat
PORTVERSION=	0.95.1
PORTREVISION=	5
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Replaces/Enhances Text.Regex

LICENSE=	BSD

USE_CABAL=	regex-base>=0.93 regex-posix>=0.95.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
