# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: devel/py-jsonschema/Makefile 330869 2013-10-19 14:13:00Z wg $

PORTNAME=	jsonschema
PORTVERSION=	2.2.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	JSON Schema validation for Python

LICENSE=	MIT

USE_PYTHON=	-2.7
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
