# New ports collection makefile for:	Proc::Reliable
# Date created:			31 Dec 2001
# Whom:				Seamus Venasse <svenasse@polaris.ca>
#
# $FreeBSD: ports/devel/p5-Proc-Reliable/Makefile,v 1.7 2012/11/17 05:56:27 svnexp Exp $
#

PORTNAME=	Proc-Reliable
PORTVERSION=	1.16
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Run external processes reliably with many options

PERL_CONFIGURE=	yes

MAN3=		Proc::Reliable.3 Proc::test_intercept.3

.include <bsd.port.mk>
