# Created by: will
# $FreeBSD: security/p5-Authen-Ticket/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Authen-Ticket
PORTVERSION=	0.02
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module providing the framework for implementing a ticketing system

USES=		perl5
USE_PERL5=	configure

MAN3=	Authen::Ticket.3 \
	Authen::Ticket::Client.3 \
	Authen::Ticket::Server.3 \
	Authen::Ticket::Signature.3

.include <bsd.port.mk>
