# Created by: SimaMoto,RyoTa <liangtai.s4@gmail.com>
# $FreeBSD: russian/gimp-help/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	russian graphics

MAINTAINER=	liangtai.s4@gmail.com
COMMENT=	The GIMP User Manual in Russian

MASTERDIR=	${.CURDIR}/../../misc/gimp-help-en

DOCLANG=	ru
AMPLE=	"@comment "

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
