# Created by: Andrew T. Bennett <potatosaladx@gmail.com>
# $FreeBSD: www/mod_xsendfile/Makefile 338168 2013-12-30 20:55:18Z ohauer $

PORTNAME=	mod_xsendfile
PORTVERSION=	0.12
PORTREVISION=	3
CATEGORIES=	www
MASTER_SITES=	https://tn123.org/mod_xsendfile/ \
		http://cloud.github.com/downloads/potatosalad/mod_xsendfile/

MAINTAINER=	potatosaladx@gmail.com
COMMENT=	Apache2 module that processes X-SENDFILE headers

LICENSE=	APACHE20

USE_APACHE=	22+
AP_FAST_BUILD=	yes
AP_GENPLIST=	yes

.include <bsd.port.mk>
