# Created by: Andrew T. Bennett <potatosaladx@gmail.com>
# $FreeBSD: www/mod_xsendfile/Makefile 324744 2013-08-14 22:35:50Z ak $

PORTNAME=	mod_xsendfile
PORTVERSION=	0.12
PORTREVISION=	3
CATEGORIES=	www
MASTER_SITES=	https://tn123.org/mod_xsendfile/ \
		http://cloud.github.com/downloads/potatosalad/mod_xsendfile/

MAINTAINER=	potatosaladx@gmail.com
COMMENT=	An Apache2 module that processes X-SENDFILE headers


USE_APACHE=	22+
AP_FAST_BUILD=	yes
AP_GENPLIST=	yes

.include <bsd.port.mk>
