# Created by: asaddi@philosophysw.com
# $FreeBSD: news/newsfish/Makefile 337679 2013-12-27 10:02:11Z bapt $

PORTNAME=	newsfish
PORTVERSION=	1.2.6
CATEGORIES=	news
MASTER_SITES=	SF

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Batch USENET news reader with filter capabilities

USES=		gmake
GNU_CONFIGURE=	yes

PLIST_FILES=	bin/newsfish \
		man/man1/newsfish.1.gz

.include <bsd.port.mk>
