# New ports collection makefile for:	trapproto
# Date Created:				06 Feb 2006
# Whom:					Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/trapproto/Makefile,v 1.2 2012/11/17 06:03:20 svnexp Exp $
#

PORTNAME=	trapproto
PORTVERSION=	3.4.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	DEC-XTRAP extension headers

XORG_CAT=	proto

USE_XORG=	xt:both

.include <bsd.port.mk>
