# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11/trapproto/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	trapproto
PORTVERSION=	3.4.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	DEC-XTRAP extension headers

XORG_CAT=	proto

USE_XORG=	xt:both

.include <bsd.port.mk>
