# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: lang/hs-brainfuck/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	brainfuck
PORTVERSION=	0.1
PORTREVISION=	9
CATEGORIES=	lang haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Brainfuck interpreter written in Haskell

LICENSE=	GPLv2

USE_CABAL=	mtl

EXECUTABLE=	bf

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
