# Created by: ports@c0decafe.net
# $FreeBSD: security/p5-Data-Password/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	Data-Password
PORTVERSION=	1.08
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Perl extension for assessing password quality

USES=		perl5
USE_PERL5=	configure

MAN3=		Data::Password.3

NO_STAGE=	yes
.include <bsd.port.mk>
