LDFLAGS+= -lz -lutil

WALLPAPERS_RUN_DEPENDS=	${KDE4_PREFIX}/share/wallpapers/Horos/metadata.desktop:${PORTSDIR}/x11-themes/kde4-wallpapers \
			dragonfly-wallpapers>0:${PORTSDIR}/x11-themes/dragonfly-wallpapers
