# Created by: itojun@itojun.org
# $FreeBSD: net-mgmt/choparp/Makefile 327757 2013-09-20 22:24:43Z bapt $

PORTNAME=	choparp
PORTVERSION=	20021107
PORTREVISION=	4
CATEGORIES=	net-mgmt
MASTER_SITES=	SF

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Simple proxy arp daemon

USE_RC_SUBR=	choparp

MANCOMPRESSED=	yes
MAN8=		choparp.8
PLIST_FILES=	sbin/choparp

NO_STAGE=	yes
.include <bsd.port.mk>
