# New ports collection makefile for:	exim-doc-postscript
# Date created:		27 November 2001
# Whom:	      		Johann Visagie <wjv@FreeBSD.org>
#
# $FreeBSD: ports/mail/exim-doc-postscript/Makefile,v 1.2 2012/11/17 05:59:02 svnexp Exp $
#

DOCFORMAT=	postscript
MASTERDIR=	${.CURDIR}/../exim-doc-html

.include "${MASTERDIR}/Makefile"
