# Created by: ijliao
# $FreeBSD: devel/rubygem-builder/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	builder
PORTVERSION=	3.0.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Facilitate programmatic generation of XML markup

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
