# Created by: ijliao
# $FreeBSD: devel/rubygem-builder/Makefile 332034 2013-10-30 02:29:22Z swills $

PORTNAME=	builder
PORTVERSION=	3.0.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Facilitate programmatic generation of XML markup

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
