# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: math/p5-Statistics-Benford/Makefile 341825 2014-01-30 09:42:48Z az $

PORTNAME=	Statistics-Benford
PORTVERSION=	0.08
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Calculate the deviation from Benford's Law

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
