# New ports collection makefile for:	python-couchdb
# Date created:		2011-03-19
# Whom:	Andrei Antoukh <niwi@niwi.be>
#
# $FreeBSD: ports/databases/py-couchdb/Makefile,v 1.2 2012/11/17 05:55:22 svnexp Exp $
#

PORTNAME=	CouchDB
PORTVERSION=	0.8
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	${PORTNAME}-${PORTVERSION}
DIST_SUBDIR=	python

MAINTAINER=	niwi@niwi.be
COMMENT=	Simple Library to Allow Python Applications to Use CouchDB

USE_PYTHON=	2.6+
USE_PYDISTUTILS=	yes
USE_PYTHON_PREFIX=	yes

.include <bsd.port.mk>
