# $FreeBSD: devel/hs-utf8-light/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	utf8-light
PORTVERSION=	0.4.0.1
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
