# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: devel/pear-Horde_Date/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Horde_Date
PORTVERSION=	2.0.7
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Date package

USE_HORDE_RUN=	Horde_Exception \
		Horde_Nls \
		Horde_Translation

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
