# Created by: wenheping@gmail.com
# $FreeBSD: print/rubygem-prawn-layout/Makefile 332048 2013-10-30 02:54:59Z swills $

PORTNAME=	prawn-layout
PORTVERSION=	0.8.4
CATEGORIES=	print rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	An Prawn Extension to Provides Table Support and Other Layout

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
