# Ports collection makefile for:	gem-logging
# Date created:				06 Nov 2009
# Whom:					Ryan Steinmetz (<rpsfa@rit.edu>)
#
# $FreeBSD: ports/devel/rubygem-logging/Makefile,v 1.16 2012/11/17 05:57:00 svnexp Exp $

PORTNAME=	logging
PORTVERSION=	1.7.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Logging library based on Java's log4j

RUN_DEPENDS=	rubygem-little_plugger>=1.1.2:${PORTSDIR}/devel/rubygem-little_plugger

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
