# New ports collection makefile for:	security/p5-Crypt-CAST5
# Date created:				05 May 2010
# Whom:					Anton Berezin <tobez@FreeBSD.org>
#
# $FreeBSD: ports/security/p5-Crypt-CAST5/Makefile,v 1.2 2012/11/17 06:01:10 svnexp Exp $
#

PORTNAME=	Crypt-CAST5
PORTVERSION=	0.05
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Crypt
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	CAST5 block cipher

PERL_CONFIGURE=	yes

MAN3=	Crypt::CAST5.3

.include <bsd.port.mk>
