# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: audio/gstreamer-plugins-faac/Makefile 332416 2013-11-01 22:14:07Z kwm $
#   $MCom: ports/audio/gstreamer-plugins-faac/Makefile,v 1.5 2008/03/19 14:05:28 ahze Exp $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer MPEG-2 and MPEG-4 AAC encoder plugin

GST_PLUGIN=	faac

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
