# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: sysutils/patchelf/Makefile 328192 2013-09-24 20:58:58Z wg $

PORTNAME=	patchelf
PORTVERSION=	0.6
CATEGORIES=	sysutils
MASTER_SITES=	http://hydra.nixos.org/build/1524660/download/3/

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Utility to modify the dynamic linker

USES=		gmake
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
