# $FreeBSD: www/twiki-SubscribePlugin/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	SubscribePlugin
SVNREV=		17653

COMMENT=	Add an easy subscription link to topics

TWDEP=	MailerContrib>=17628

NO_STAGE=	yes
.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
