# $FreeBSD: ports/net/isc-dhcp41-client/Makefile,v 1.3 2012/12/12 18:51:46 svnexp Exp $

COMMENT=	The ISC Dynamic Host Configuration Protocol client

SUBSYS=		client
MASTERDIR=	${.CURDIR}/../isc-dhcp41-server

.include "${MASTERDIR}/Makefile"
