# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: korean/kde4-l10n/Makefile 327739 2013-09-20 19:49:59Z bapt $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
CATEGORIES=	korean kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Korean messages and documentation for KDE SC 4

KDE4_L10N=	ko

NO_STAGE=	yes
.include "${.CURDIR}/../../misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
