# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: x11-themes/kde-icons-lush/Makefile 327783 2013-09-20 23:54:03Z bapt $

PORTNAME=	lush
PORTVERSION=	0.1.0
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	lioux
DISTNAME=	${PORTNAME}-${PORTVERSION}dave

COMMENT=	KDE Lush complete iconset

WRKSRC=		"${WRKDIR}/${PORTNAME}"

NO_STAGE=	yes
.include "${.CURDIR}/../kde-icons-noia/Makefile.icons"
