# New ports collection makefile for:   tcpxtract
# Date created:        3 January 2006
# Whom:                MANTANI Nobutaka <nobutaka@freebsd.org>
#
# $FreeBSD: ports/net/tcpxtract/Makefile,v 1.7 2012/11/17 06:00:23 svnexp Exp $
#

PORTNAME=	tcpxtract
PORTVERSION=	1.0.1
CATEGORIES=	net
MASTER_SITES=	SF

MAINTAINER=	nobutaka@FreeBSD.org
COMMENT=	A tool for extracting files from network traffic

GNU_CONFIGURE=	yes
MAN1=		tcpxtract.1

PLIST_FILES=	bin/tcpxtract etc/tcpxtract.conf

.include <bsd.port.mk>
