# $FreeBSD: devel/hs-asn1-data/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	asn1-data
PORTVERSION=	0.7.1
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	ASN1 data reader and writer in RAW, BER, and DER forms

LICENSE=	BSD

USE_CABAL=	cereal mtl text>=0.11

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
