# Created by: NAKATA, Maho <maho@FreeBSD.org>
# $FreeBSD: math/spooles-mpich/Makefile 340722 2014-01-22 17:00:46Z mat $

MASTERDIR=	${.CURDIR}/../spooles
WITH_MPI=	yes

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
