# $FreeBSD: ukrainian/libreoffice/Makefile 327774 2013-09-20 23:19:33Z bapt $

LO_I18N=	uk
LO_HAS_HELPPACK=	yes
CATEGORIES=	ukrainian editors

NO_STAGE=	yes
.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
