# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: databases/php55-sybase_ct/Makefile 332107 2013-10-30 13:32:02Z ale $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-sybase_ct

.include "${MASTERDIR}/Makefile"
