# Created by: ijliao
# $FreeBSD: security/py-cryptkit/Makefile 337968 2013-12-29 12:08:28Z wg $

PORTNAME=	cryptkit
PORTVERSION=	0.9
CATEGORIES=	security python
MASTER_SITES=	SF/${PORTNAME}/_${PORTNAME}/Complete%20Kit
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Cryptographic Toolkit for Python

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
