# Created by: wosch
# $FreeBSD: mail/movemail/Makefile 327742 2013-09-20 19:59:12Z bapt $

PORTNAME=	movemail
PORTVERSION=	1.0
PORTREVISION=	1
CATEGORIES=	mail
MASTER_SITES=	http://wolfram.schneider.org/src/

MAINTAINER=	wosch@FreeBSD.org
COMMENT=	Move your mail box to another location

MAN1=		movemail.1
MANCOMPRESSED=	maybe
PLIST_FILES=	bin/movemail

NO_STAGE=	yes
.include <bsd.port.mk>
