# New ports collection makefile for:	cdf
# Date created:		2004-10-22
# Whom:			Charlie & <root@lame.novel.ru>
#
# $FreeBSD: ports/sysutils/cdf/Makefile,v 1.8 2012/11/17 06:01:26 svnexp Exp $
#

PORTNAME=	cdf
PORTVERSION=	0.2
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_BERLIOS}
MASTER_SITE_SUBDIR=	bmp-plugins

MAINTAINER=	novel@FreeBSD.org
COMMENT=	A colorized df

PLIST_FILES=	bin/cdf

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
