# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: security/php55-filter/Makefile 327769 2013-09-20 22:55:24Z bapt $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-filter

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
