# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: databases/php55-pdo_mysql/Makefile 321684 2013-06-24 14:32:11Z ale $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-pdo_mysql

.include "${MASTERDIR}/Makefile"
