# New ports collection makefile for:   bottlerocket
# Date created:        15 July 1999
# Whom:                Mike Smith <msmith@freebsd.org>
#
# $FreeBSD: ports/misc/bottlerocket/Makefile,v 1.11 2012/11/17 05:59:33 svnexp Exp $
#

PORTNAME=	bottlerocket
PORTVERSION=	0.04c
PORTREVISION=	1
CATEGORIES=	misc
MASTER_SITES=	SF/futurebsd/futurebsd/${PORTNAME}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Home Automation Software for the X10 FireCracker kit

USE_GMAKE=	yes
GNU_CONFIGURE=	yes
ALL_TARGET=	br
PLIST_FILES=	bin/br

.include <bsd.port.mk>
