# Created by: Mike Smith <msmith@FreeBSD.org>
# $FreeBSD: misc/bottlerocket/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	bottlerocket
PORTVERSION=	0.04c
PORTREVISION=	1
CATEGORIES=	misc
MASTER_SITES=	SF/futurebsd/futurebsd/${PORTNAME}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Home Automation Software for the X10 FireCracker kit

USE_GMAKE=	yes
GNU_CONFIGURE=	yes
ALL_TARGET=	br
PLIST_FILES=	bin/br

NO_STAGE=	yes
.include <bsd.port.mk>
