# Created by: Denis Pokataev <catone@cpan.org>
# $FreeBSD: textproc/p5-String-Escape/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	String-Escape
PORTVERSION=	2010.002
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	catone@cpan.org
COMMENT=	Registry of string functions, including backslash escapes

USES=		perl5
USE_PERL5=	configure

MAN3=	String::Escape.3

NO_STAGE=	yes
.include <bsd.port.mk>
