# Created by: krion
# $FreeBSD: mail/exim-sqlite/Makefile 327742 2013-09-20 19:59:12Z bapt $

PKGNAMESUFFIX=	-sqlite
MASTERDIR=	${.CURDIR}/../exim

WITH_SQLITE=		yes

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
