# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: devel/pear-Horde_Lock/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Horde_Lock
PORTVERSION=	2.1.0
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Resource Locking System

USE_HORDE_RUN=	Horde_Exception \
		Horde_Support

NO_STAGE=	yes
.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
