# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: archivers/rubygem-minitar/Makefile 319618 2013-06-02 01:25:57Z swills $

PORTNAME=	minitar
PORTVERSION=	0.5.4
CATEGORIES=	archivers rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library and command-line utility for tar archives

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/minitar

CONFLICTS=	rubygem-archive-tar-minitar-[0-9]*

.include <bsd.port.mk>
