# Created by: ache
# $FreeBSD: head/net/p5-URI/Makefile 468363 2018-04-26 18:51:07Z sunpoet $

PORTNAME=	URI
PORTVERSION=	1.74
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 interface to Uniform Resource Identifier (URI) references

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Needs>=0:devel/p5-Test-Needs

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
