# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: devel/p5-Iterator-Simple/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Iterator-Simple
PORTVERSION=	0.06
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple iterator and utilities

USES=		perl5
USE_PERL5=	configure

MAN3=		Iterator::Simple.3

NO_STAGE=	yes
.include <bsd.port.mk>
