# Created by: ijliao
# $FreeBSD: textproc/py-jaxml/Makefile 338090 2013-12-30 11:40:41Z wg $

PORTNAME=	jaxml
PORTVERSION=	3.02
PORTREVISION=	1
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP \
		http://www.librelogiciel.com/software/jaxml/tarballs/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Python module to generate XML easily

USE_PYTHON=	yes
USE_PYDISTUTILS=yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
