# Created by: ijliao
# $FreeBSD: textproc/py-jaxml/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	jaxml
PORTVERSION=	3.02
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP \
		http://www.librelogiciel.com/software/jaxml/tarballs/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A Python module to generate XML easily

PLIST_FILES=	lib/${PYTHON_VERSION}/site-packages/${PYEASYINSTALL_EGG}

USE_PYTHON=	yes
USE_PYDISTUTILS=easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
