# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: devel/p5-Religion/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Religion
PORTVERSION=	1.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:KJALB
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl5 module to install die() and warn() handlers

USES=		perl5
USE_PERL5=	configure

MAN3=		Religion.3

NO_STAGE=	yes
.include <bsd.port.mk>
