# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: www/rubygem-domainatrix/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	domainatrix
PORTVERSION=	0.0.11
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for parsing domain names and canonicalizing URLs

RUN_DEPENDS=	rubygem-addressable>=0:${PORTSDIR}/www/rubygem-addressable

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
