@@ -35,6 +35,6 @@
 LIBPCAP_PORTS_DESC=	Build with net/libpcap
 
 LIBPCAP_BASE_CONFIGURE_ON=	--with-libpcap=/usr/lib
-LIBPCAP_PORTS_LIB_DEPENDS=	libpcap.so:net/libpcap
+LIBPCAP_PORTS_LIB_DEPENDS=	libpcap.so.1:net/libpcap
 
 .include <bsd.port.mk>
