# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: german/aspell/Makefile 327732 2013-09-20 18:30:00Z bapt $

PORTNAME=	aspell
DISTVERSION=	6-de-20030222-1
PORTREVISION=	1
CATEGORIES=	german textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell German dictionary

DICT=	 	de

NO_STAGE=	yes
.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
