# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: security/p5-Crypt-Rijndael_PP/Makefile 332949 2013-11-06 07:39:31Z vanilla $

PORTNAME=	Crypt-Rijndael_PP
PORTVERSION=	0.05
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl implementation of Rijndael

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
