# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: textproc/sl-aspell/Makefile 332672 2013-11-04 08:30:37Z bapt $

PORTNAME=	${DICT}-aspell
DISTVERSION=	-sl-0.50-0
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Slovenian dictionary

DICT=	 	sl

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
