# Created by: David Le Brun <david@dyn-ns.net>
# $FreeBSD: sysutils/p5-Filesys-DiskFree/Makefile 332957 2013-11-06 08:54:17Z vanilla $

PORTNAME=	Filesys-DiskFree
PORTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl equivalent of df(2)

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
