# New ports collection makefile for:	sysutils/p5-Filesys-DiskFree
# Date created:				09 December 2003
# Whom:					David Le Brun <david@dyn-ns.net>
#
# $FreeBSD: ports/sysutils/p5-Filesys-DiskFree/Makefile,v 1.6 2012/11/17 06:01:40 svnexp Exp $
#

PORTNAME=	Filesys-DiskFree
PORTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl equivalent of df(2)

PERL_CONFIGURE=	yes

MAN3=		Filesys::DiskFree.3

.include <bsd.port.mk>
