# Created by: Emanuel Haupt <ehaupt@FreeBSD.org>
# $FreeBSD: devel/p5-Package-Generator/Makefile 326810 2013-09-09 14:13:20Z az $

PORTNAME=	Package-Generator
PORTVERSION=	1.105
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	This module lets you quickly and easily construct new packages

USES=		perl5
USE_PERL5=	configure

MAN3=		Package::Reaper.3 Package::Generator.3

.include <bsd.port.mk>
