# Created by: Oleg R. Muhutdinov <mor@WhiteLuna.com>
# $FreeBSD: converters/p5-Convert-Bencode/Makefile 341761 2014-01-29 17:00:41Z az $

PORTNAME=	Convert-Bencode
PORTVERSION=	1.03
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mor@WhiteLuna.com
COMMENT=	Module to encode and decode bencoded strings

BUILD_DEPENDS=	p5-Test-Simple>=0:${PORTSDIR}/devel/p5-Test-Simple

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
