# New ports collection makefile for:	Number-Compare
# Date created:	   19 May 2003
# Whom:		   Sergey Skvortsov <skv@protey.ru>
#
# $FreeBSD: ports/math/p5-Number-Compare/Makefile,v 1.5 2012/11/17 05:59:27 svnexp Exp $
#

PORTNAME=	Number-Compare
PORTVERSION=	0.03
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Numeric comparisons

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		Number::Compare.3

.include <bsd.port.mk>
