# Created by: Ed Schouten <ed@fxq.nl>
# $FreeBSD: devel/mimir/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	mimir
PORTVERSION=	2.15
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.cs.ru.nl/pub/vb/mimir/src/

MAINTAINER=	ed@FreeBSD.org
COMMENT=	Data-structure library used by the Elan Programming Environment

MAN1=		dcg.1

USE_AUTOTOOLS=	libtool
USE_GMAKE=	yes
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
