# Created by: Wen Heping <ruby@FreeBSD.org>
# $FreeBSD: devel/rubygem-treetop/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	treetop
PORTVERSION=	1.4.14
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby-based DSL for text parsing and interpretation

RUN_DEPENDS=	rubygem-polyglot>=0:${PORTSDIR}/devel/rubygem-polyglot

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/tt

NO_STAGE=	yes
.include <bsd.port.mk>
