# Created by: ijliao
# $FreeBSD: textproc/p5-XML-RSS-SimpleGen/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	XML-RSS-SimpleGen
PORTVERSION=	11.11
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	For writing RSS files

USES=		perl5
USE_PERL5=	configure

MAN3=		XML::RSS::SimpleGen.3 \

.include <bsd.port.mk>
