# $FreeBSD: ports/japanese/libreoffice/Makefile,v 1.3 2012/11/17 05:58:36 svnexp Exp $

LO_I18N=	ja
LO_HAS_HELPPACK=	yes
CATEGORIES=	japanese editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
