# $FreeBSD: japanese/libreoffice/Makefile 331614 2013-10-25 17:05:50Z jkim $

LO_I18N=	ja
LO_HAS_HELPPACK=	yes
CATEGORIES=	japanese editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
