# Created by: John Hein <jhein@symmetricom.com>
# $FreeBSD: devel/blame/Makefile 327722 2013-09-20 17:03:26Z bapt $

PORTNAME=	blame
PORTVERSION=	1.3.1
CATEGORIES=	devel
MASTER_SITES=	SF

MAINTAINER=	jhein@symmetricom.com
COMMENT=	Display last modification for each line in an RCS file

USE_CSTD=	gnu89
GNU_CONFIGURE=	yes
MAN1=		blame.1
PLIST_FILES=	bin/blame

NO_STAGE=	yes
.include <bsd.port.mk>
