# New ports collection makefile for:	cdroot
# Date created:				8 August 2002
# Whom:					Brian Dean <bsd@FreeBSD.org>
#
# $FreeBSD: ports/sysutils/cdroot/Makefile,v 1.7 2012/11/17 06:01:26 svnexp Exp $
#

PORTNAME=	cdroot
PORTVERSION=	1.2.5
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	bsd

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Scripts to automate setting up a bootable CD-ROM based FreeBSD system

.include <bsd.port.mk>
