# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: devel/pear-channel-phpunit/Makefile 333263 2013-11-08 21:41:53Z antoine $

PORTNAME=	phpunit
PORTVERSION=	20110327
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.phpunit.de

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
