# $FreeBSD: devel/bugzilla42/Makefile.common 330666 2013-10-17 19:35:22Z ohauer $

DIST_SUBDIR=	${PORTNAME}
PKGNAMESUFFIX=	42

CONFLICTS_INSTALL=	\
		bugzilla4[^2].* \
		bugzilla-4.[^2].*

PORTSCOUT=	limitw:1,even

WWWDIR=		${PREFIX}/www/bugzilla

NO_BUILD=	yes

