# Created by: Gabor Kovesdan
# $FreeBSD: security/p5-Crypt-DES_PP/Makefile 341821 2014-01-30 09:08:26Z az $

PORTNAME=	Crypt-DES_PP
PORTVERSION=	1.00
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension for DES encryption in pure Perl

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
