# Created by: Jin-Shan Tseng <tjs@cdpa.nsysu.edu.tw>
# $FreeBSD: math/p5-Math-Complex/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Math-Complex
PORTVERSION=	1.59
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Complex numbers and associated mathematical functions

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		Math::Complex.3 \
		Math::Trig.3

.include <bsd.port.mk>
