# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: devel/R-cran-memoise/Makefile 319316 2013-05-28 15:15:05Z bf $

PORTNAME=	memoise
PORTVERSION=	0.1
PORTREVISION=	5
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Memoise functions for R

RUN_DEPENDS=	R-cran-digest>=0:${PORTSDIR}/security/R-cran-digest

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
