# Ports collection makefile for:	rubygem-stemmer
# Date created:				2009-12-11
# Whom:					Peter Schuller <peter.schuller@infidyne.com>
#
# $FreeBSD: ports/devel/rubygem-stemmer/Makefile,v 1.5 2012/11/17 05:57:01 svnexp Exp $

PORTNAME=	stemmer
PORTVERSION=	1.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@FreeBSD.org
COMMENT=	An implementation of the Porter word stemming algorithm

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
