# New ports collection makefile for:	p5-File-CounterFile
# Date created:				Jan 28 2000
# Whom:					Wei-chun Chao
#
# $FreeBSD: misc/p5-File-CounterFile/Makefile 324352 2013-08-07 13:20:32Z az $
#

PORTNAME=	File-CounterFile
PORTVERSION=	1.04
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Perl module for persistent counter class

USES=		perl5
USE_PERL5=	configure

MAN3=		File::CounterFile.3

.include <bsd.port.mk>
