# Created by: Wei-chun Chao
# $FreeBSD: misc/p5-File-CounterFile/Makefile 327745 2013-09-20 20:50:57Z bapt $

PORTNAME=	File-CounterFile
PORTVERSION=	1.04
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Perl module for persistent counter class

USES=		perl5
USE_PERL5=	configure

MAN3=		File::CounterFile.3

NO_STAGE=	yes
.include <bsd.port.mk>
