# Created by: asami
# $FreeBSD: net/igmpproxy/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	igmpproxy
PORTVERSION=	0.1
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}/${PORTNAME}/${PORTVERSION}

MAINTAINER=	melifaro@ipfw.ru
COMMENT=	Multicast forwarding IGMP proxy

HOMEPAGE=	http://igmpproxy.sourceforge.net/

USE_RC_SUBR=	igmpproxy
USE_GMAKE=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
