# Created by: Dennis Herrmann <adox@mcx2.org>
# $FreeBSD: devel/rubygem-lockfile/Makefile 333606 2013-11-12 19:44:58Z sunpoet $

PORTNAME=	lockfile
PORTVERSION=	2.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	dhn@FreeBSD.org
COMMENT=	Ruby library for creating NFS safe lockfiles

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_RAKE=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/rlock

.include <bsd.port.mk>
