# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: textproc/pdfoutline/Makefile 325163 2013-08-21 17:42:57Z sunpoet $

PORTNAME=	pdfoutline
PORTREVISION=	0
CATEGORIES=	textproc

COMMENT=	Add outlines to PDF files

MASTERDIR=	${.CURDIR}/../../x11-fonts/fntsample
DESCR=		${.CURDIR}/pkg-descr

PDFOUTLINE=	yes

.include "${MASTERDIR}/Makefile"
