# $FreeBSD: ports/devel/hs-directory-tree/Makefile,v 1.7 2013/02/05 22:47:09 svnexp Exp $

PORTNAME=	directory-tree
PORTVERSION=	0.11.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A simple directory-like tree datatype, with useful IO functions

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
