# Ports collection makefile for:	rubygem-rscm
# Date created:				2006-01-09
# Whom:					Daniel Roethlisberger <daniel@roe.ch>
#
# $FreeBSD: ports/devel/rubygem-rscm/Makefile,v 1.9 2012/11/17 05:57:01 svnexp Exp $

PORTNAME=	rscm
PORTVERSION=	0.5.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby SCM, an SCM-independent API for accessing SCMs

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
