# New ports collection makefile for:	AquaExtreme Sunken (metacity theme)
# Date created:				25 Feb 2005
# Whom:					Alexey Dokuchaev <danfe@FreeBSD.org>
#
# $FreeBSD: ports/x11-themes/metacity-aquaextremesunken-theme/Makefile,v 1.2 2012/11/17 06:03:33 svnexp Exp $
#

TYPE=		metacity
MASTERDIR=	${.CURDIR}/../gtk-aquaextremesunken-theme

.include "${MASTERDIR}/Makefile"
