# New ports collection makefile for:	p5-Data-Table
# Date created:				10 November 2004
# Whom:					Aaron Dalton <aaron@daltons.ca>
#
# $FreeBSD: ports/devel/p5-Data-Table/Makefile,v 1.15 2012/11/17 05:56:11 svnexp Exp $
#

PORTNAME=	Data-Table
PORTVERSION=	1.68
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	dhn@FreeBSD.org
COMMENT=	Data type related to database tables, HTML table displays, etc

PERL_CONFIGURE=	yes

MAN3=	Data::Table.3

.include <bsd.port.mk>
