# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: devel/p5-Data-Table/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Data-Table
PORTVERSION=	1.68
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	dhn@FreeBSD.org
COMMENT=	Data type related to database tables, HTML table displays, etc

USES=		perl5
USE_PERL5=	configure

MAN3=	Data::Table.3

NO_STAGE=	yes
.include <bsd.port.mk>
