# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: lang/p5-Modern-Perl/Makefile 327741 2013-09-20 19:53:09Z bapt $

PORTNAME=	Modern-Perl
PORTVERSION=	1.03
CATEGORIES=	lang perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:CHROMATIC
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Enable all of the features of Modern Perl with one command

USES=		perl5
USE_PERL5=	modbuild

MAN3=		Modern::Perl.3

NO_STAGE=	yes
.include <bsd.port.mk>
