# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: devel/p5-Time-Warp/Makefile 341707 2014-01-29 09:19:35Z az $

PORTNAME=	Time-Warp
PORTVERSION=	0.5
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Control over the flow of time

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
