# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: head/devel/p5-Module-Versions-Report/Makefile 332120 2013-10-30 14:44:54Z vanilla $

PORTNAME=	Module-Versions-Report
PORTVERSION=	1.06
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Report versions of all modules in memory

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
