# Created by: Greg Larkin <glarkin@FreeBSD.org>
# $FreeBSD: devel/rubygem-childprocess/Makefile 340900 2014-01-24 14:46:28Z miwi $

PORTNAME=	childprocess
PORTVERSION=	0.3.9
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	External background process controller

RUN_DEPENDS=	rubygem-ffi>=1.0.11:${PORTSDIR}/devel/rubygem-ffi

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
