# New ports collection makefile for:	pthsem
# Date Created:				6 Dec 2007
# Whom:					Björn König <bkoenig@alpha-tierchen.de>
#
# $FreeBSD: ports/devel/pthsem/Makefile,v 1.3 2012/11/17 05:56:43 svnexp Exp $
#

PORTNAME=	pthsem
PORTVERSION=	2.0.7
CATEGORIES=	devel
MASTER_SITES=	http://www.auto.tuwien.ac.at/~mkoegler/pth/

MAINTAINER=	bkoenig@alpha-tierchen.de
COMMENT=	GNU Portable Threads with semaphores

USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

MAN1=		pthsem-config.1
MAN3=		pthsem.3

MAKE_JOBS_UNSAFE=	yes

.include <bsd.port.mk>
