# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: devel/hs-filemanip/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	filemanip
PORTVERSION=	0.3.6.2
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Expressive file and directory manipulation for Haskell

LICENSE=	BSD

USE_CABAL=	mtl unix-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
