# $FreeBSD: ports/editors/libreoffice-bo/Makefile,v 1.4 2012/11/17 05:57:15 svnexp Exp $

LO_I18N=	bo
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
