# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-CLASS/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	CLASS
PORTVERSION=	1.00
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MSCHWERN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Alias for __PACKAGE__

USES=		perl5
USE_PERL5=	configure

MAN3=		CLASS.3

NO_STAGE=	yes
.include <bsd.port.mk>
