# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: textproc/php55-pspell/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-pspell

.include "${MASTERDIR}/Makefile"
