# Created by: Marijn Meijles <marijn@stack.nl>
# $FreeBSD: mail/sigrot/Makefile 327742 2013-09-20 19:59:12Z bapt $

PORTNAME=	sigrot
PORTVERSION=	1.0
CATEGORIES=	mail
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	system/mail/misc
DISTNAME=	${PORTNAME}_v${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Util to rotate your mail/news signature

MAN1=		sigrot.1
PLIST_FILES=	bin/sigrot

NO_STAGE=	yes
.include <bsd.port.mk>
