# New ports collection makefile for:	sigrot
# Date created:		4 Mar 1998
# Whom:			Marijn Meijles <marijn@stack.nl>
#
# $FreeBSD: ports/mail/sigrot/Makefile,v 1.8 2012/11/17 05:59:14 svnexp Exp $
#

PORTNAME=	sigrot
PORTVERSION=	1.0
CATEGORIES=	mail
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	system/mail/misc
DISTNAME=	${PORTNAME}_v${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Util to rotate your mail/news signature

MAN1=		sigrot.1
PLIST_FILES=	bin/sigrot

.include <bsd.port.mk>
