# Created by: Thorsten Greiner <thorsten.greiner@web.de>
# $FreeBSD: textproc/p5-Lingua-Stem-Snowball-Se/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Lingua-Stem-Snowball-Se
PORTVERSION=	1.2
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ASKSH
PKGNAMEPREFIX=	p5-
DISTNAME=	Snowball-Swedish-${PORTVERSION}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Stemmer for Swedish

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
