# Created by: Hye-Shik Chang <perky@FreeBSD.org>
# $FreeBSD: korean/unfonts-extra/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTVERSION=	1.0.1
PORTREVISION=	1
MASTER_SITES=	http://kldp.net/frs/download.php/1435/

FONTCAT=	extra
FONTLIST=	UnJamoBatang \
		UnJamoDotum \
		UnJamoNovel \
		UnJamoSora \
		UnPen \
		UnPenheulim \
		UnShinmun \
		UnTaza \
		UnYetgul

MASTERDIR=	${.CURDIR}/../unfonts-core

.include "${MASTERDIR}/Makefile"
