# Created by: Martin Otto
# $FreeBSD: textproc/sk-ispell/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	sk-ispell
PORTVERSION=	0.3.2

MAINTAINER=	gamato@users.sf.net

MASTERDIR=	${.CURDIR}/../ispell
ISPELL_SK=	yes
SCRIPTS_ENV=	ISPELL_SK=yes

NO_STAGE=	yes
.include	"${MASTERDIR}/Makefile"
