# New ports collection makefile for:	sysutils/battray
# Date created:				2011-08-30
# Whom:					Martin Tournoij <martin@arp242.net>
#
# $FreeBSD: ports/sysutils/battray/Makefile,v 1.5 2012/11/17 06:01:25 svnexp Exp $
#

PORTNAME=	battray
PORTVERSION=	1.5
CATEGORIES=	sysutils python
MASTER_SITES=	${MASTER_SITE_GOOGLE_CODE}

MAINTAINER=	martin@arp242.net
COMMENT=	Display notebook battery status in tray

LICENSE=	BSD

USE_GNOME=	pygtk2
USE_PYTHON=	yes
USE_PYDISTUTILS=yes

MAN1=		battray.1

.include <bsd.port.mk>
