# $FreeBSD: x11-fonts/font-misc-ethiopic/Makefile 327781 2013-09-20 23:51:14Z bapt $

PORTNAME=	font-misc-ethiopic
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org miscellaneous Ethiopic font

XORG_CAT=	font
INSTALLS_TTF=	yes
FONTDIR=	TTF OTF

NO_STAGE=	yes
.include <bsd.port.mk>
