# Created by: David Chaplin-Loebell <direct@klatha.com>
# $FreeBSD: devel/p5-Tie-CPHash/Makefile 326787 2013-09-09 09:45:12Z az $

PORTNAME=	Tie-CPHash
PORTVERSION=	1.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	direct@klatha.com
COMMENT=	Perl module implementing a case preserving hash table

USES=		perl5
USE_PERL5=	modbuild

MAN3=		Tie::CPHash.3

.include <bsd.port.mk>
