# Created by: David Chaplin-Loebell <direct@klatha.com>
# $FreeBSD: devel/p5-Tie-CPHash/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Tie-CPHash
PORTVERSION=	1.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	direct@klatha.com
COMMENT=	Perl module implementing a case preserving hash table

USES=		perl5
USE_PERL5=	modbuild

MAN3=		Tie::CPHash.3

NO_STAGE=	yes
.include <bsd.port.mk>
