# $FreeBSD: x11/bitmap/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	bitmap
PORTVERSION=	1.0.7
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Bitmap editor and converter utilities for X

XORG_CAT=	app
USE_XORG=	x11 xaw xbitmaps xmu xproto
MAN1=		atobm.1 bitmap.1 bmtoa.1

.include <bsd.port.mk>
