# $FreeBSD: textproc/hs-blaze-markup/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	blaze-markup
PORTVERSION=	0.5.1.5
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Blazingly fast markup combinator library

LICENSE=	BSD

USE_CABAL=	blaze-builder>=0.2 text>=0.10

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
