# Created by: will
# $FreeBSD: security/p5-Crypt-Twofish/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Crypt-Twofish
PORTVERSION=	2.17
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module implementing the Twofish cipher

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
