# Created by: will
# $FreeBSD: ports/security/p5-Crypt-Twofish/Makefile,v 1.18 2012/11/17 06:01:12 svnexp Exp $

PORTNAME=	Crypt-Twofish
PORTVERSION=	2.15
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module implementing the Twofish cipher

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		Crypt::Twofish.3

.include <bsd.port.mk>
