# $FreeBSD: graphics/gstreamer1-plugins-aalib/Makefile 316693 2013-04-27 20:56:38Z kwm $

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	Gstreamer ASCII art plugin

GST_PLUGIN=	aalib
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
