# $FreeBSD: portuguese/webalizer-pt_PT/Makefile 335144 2013-11-29 04:19:56Z dinoex $

CATEGORIES=	portuguese
PKGNAMEPREFIX?=	pt_PT-

MAINTAINER=	ports@FreeBSD.org

MASTERDIR?=	${.CURDIR}/../../www/webalizer
WEBALIZER_LANG=	portuguese

.if exists(${.CURDIR}/Makefile.local)
.include "${.CURDIR}/Makefile.local"
.endif

.include "${MASTERDIR}/Makefile"
