# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: math/py-svgmath/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	svgmath
PORTVERSION=	0.3.3
CATEGORIES=	math python
MASTER_SITES=	SF
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	SVGMath-${PORTVERSION}

MAINTAINER=	wenheping@gmail.com
COMMENT=	MathML to SVG Converter in Python

USE_PYTHON=		yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_PKGNAME=	SVGMath

NO_STAGE=	yes
.include <bsd.port.mk>
