# $FreeBSD: devel/py-collective.monkeypatcher/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	collective.monkeypatcher
PORTVERSION=	1.0.1
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Applying monkey patches on startup using ZCML configuration

LICENSE=	BSD

DIST_SUBDIR=	zope
USE_PYTHON=	yes
USE_PYDISTUTILS=easy_install
USE_ZIP=	yes

NO_STAGE=	yes

.include <bsd.port.mk>
