# Created by: chinsan
# $FreeBSD: math/p5-Statistics-Forecast/Makefile 332813 2013-11-05 06:56:18Z vanilla $

PORTNAME=	Statistics-Forecast
PORTVERSION=	0.3
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Statistics
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Calculates a future value

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
