# Created by: dchapes@zeus.leitch.com
# $FreeBSD: mail/xbuffy/Makefile 327742 2013-09-20 19:59:12Z bapt $

PORTNAME=	xbuffy
PORTVERSION=	3.3.3
PORTREVISION=	4
CATEGORIES=	mail
MASTER_SITES=	http://www.fiction.net/blong/programs/xbuffy/
DISTNAME=	${PORTNAME}-3.3.bl.3

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A replacement for xbiff that handles multiple mail files

USE_XORG=	xext xt xaw
USE_GMAKE=	yes
GNU_CONFIGURE=	yes
MAN1=		xbuffy.1
PLIST_FILES=	bin/xbuffy lib/X11/app-defaults/XBuffy

NO_STAGE=	yes
.include <bsd.port.mk>
