# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: math/R-cran-coda/Makefile 319316 2013-05-28 15:15:05Z bf $

PORTNAME=	coda
DISTVERSION=	0.16-1
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Output analysis and diagnostics for MCMC

USE_R_MOD=		yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
