# New ports collection makefile for:	devel/rubygem-stream
# Date created:				02.08.2005
# Whom:					Ulrich Spoerlein <uspoerlein@gmail.com>
#
# $FreeBSD: ports/devel/rubygem-stream/Makefile,v 1.12 2012/11/17 05:57:01 svnexp Exp $
#

PORTNAME=	stream
PORTVERSION=	0.5
PORTREVISION=	2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Interface for external iterators

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
