# $FreeBSD: x11/editres/Makefile 336621 2013-12-16 11:11:09Z zeising $

PORTNAME=	editres
PORTVERSION=	1.0.6
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Dynamic resource editor for X Toolkit Applications

XORG_CAT=	app
USE_XORG=	x11 xt xmu xaw

.include <bsd.port.mk>
