# Created by: Tsung-Han Yeh <snowfly@yuntech.edu.tw>
# $FreeBSD: net/p5-Net-Flow/Makefile 326384 2013-09-05 11:09:23Z az $

PORTNAME=	Net-Flow
PORTVERSION=	1.000
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	snowfly@yuntech.edu.tw
COMMENT=	Decode and encode NetFlow/IPFIX datagrams

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		Net::Flow.3

.include <bsd.port.mk>
