# New ports collection makefile for:	rubygem-roauth
# Date created:		2010-11-03
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/security/rubygem-roauth/Makefile,v 1.5 2012/11/17 06:01:19 svnexp Exp $
#

PORTNAME=	roauth
PORTVERSION=	0.0.8
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Simple Ruby OAuth library

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
