# $FreeBSD: x11/presentproto/Makefile 336621 2013-12-16 11:11:09Z zeising $

PORTNAME=	presentproto
PORTVERSION=	1.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Present protocol specification

XORG_CAT=	proto

.include <bsd.port.mk>
