# Created by: Cheng-Lung Sung <clsung@dragon2.net>
# $FreeBSD: www/p5-HTTP-Lite/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	HTTP-Lite
PORTVERSION=	2.42
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 modules for Lightweight HTTP implementation

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		HTTP::Lite.3

NO_STAGE=	yes
.include <bsd.port.mk>
