# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: devel/p5-Tree-Simple/Makefile 330132 2013-10-12 15:11:47Z sunpoet $

PORTNAME=	Tree-Simple
PORTVERSION=	1.22
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
EXTRACT_SUFX=	.tgz

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Simple tree object

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Exception>=0.15:${PORTSDIR}/devel/p5-Test-Exception

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
