--- src/common/ittnotify/jitprofiling.c.orig	2021-07-27 16:25:07.194927000 +0200
+++ src/common/ittnotify/jitprofiling.c	2021-07-27 16:25:57.433785000 +0200
@@ -40,7 +40,7 @@
 #if ITT_PLATFORM==ITT_PLATFORM_WIN
 #include <windows.h>
 #endif /* ITT_PLATFORM==ITT_PLATFORM_WIN */
-#if ITT_PLATFORM != ITT_PLATFORM_MAC && ITT_PLATFORM != ITT_PLATFORM_FREEBSD && ITT_PLATFORM != ITT_PLATFORM_OPENBSD
+#if ITT_PLATFORM != ITT_PLATFORM_MAC && ITT_PLATFORM != ITT_PLATFORM_FREEBSD && ITT_PLATFORM != ITT_PLATFORM_OPENBSD && ITT_PLATFORM != ITT_PLATFORM_DRAGONFLY
 #include <malloc.h>
 #endif
 #include <stdlib.h>
