# Created by: Sofian Brabez <sbz@FreeBSD.org>
# $FreeBSD: x11-toolkits/py-SquareMap/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	SquareMap
PORTVERSION=	1.0.2
PORTREVISION=	1
CATEGORIES=	x11-toolkits python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sbz@FreeBSD.org
COMMENT=	Hierarchic visualization control for wxPython

LICENSE=	BSD

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}wxPython>0:${PORTSDIR}/x11-toolkits/py-wxPython28

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
