# Created by: Sofian Brabez <sbz@FreeBSD.org>
# $FreeBSD: x11-toolkits/py-SquareMap/Makefile 320754 2013-06-13 11:13:57Z sbz $

PORTNAME=	SquareMap
PORTVERSION=	1.0.1
CATEGORIES=	x11-toolkits python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sbz@FreeBSD.org
COMMENT=	Hierarchic visualization control for wxPython

LICENSE=	BSD

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}wxPython>0:${PORTSDIR}/x11-toolkits/py-wxPython28

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

.include <bsd.port.mk>
