# New ports collection makefile for:	gstreamer-plugins-esd
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD: ports/audio/gstreamer-plugins-esound/Makefile,v 1.11 2012/11/17 05:54:34 svnexp Exp $
#   $MCom: ports/audio/gstreamer-plugins-esound/Makefile,v 1.5 2008/03/19 14:05:28 ahze Exp $
#

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer enlightenment sound library plugin

GST_PLUGIN=	esound

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
