
.if ${PORTVERSION} == 2.3
USES:=	${USES:Nssl}
BUILD_DEPENDS+=	libressl-static>0:security/libressl-static
CFLAGS+=	-I${LOCALBASE}/libressl-static/include
LDFLAGS+=	-L${LOCALBASE}/libressl-static/lib
CONFIGURE_ENV:=	${CONFIGURE_ENV:NOPENSSL*} \
		SSLEAY="${LOCALBASE}/libressl-static/bin" \
		OPENSSLINC=${LOCALBASE}/libressl-static/include \
		OPENSSLLIB=${LOCALBASE}/libressl-static/lib
.endif
