# vim: tabstop=8 softtabstop=0 noexpandtab
# Ports collection makefile for:	libRmath
# Date created:		14 May 2004
# Whom:			Eric van Gyzen <vangyzen@stat.duke.edu>
#
# $FreeBSD: ports/math/libRmath/Makefile,v 1.25 2012/11/17 05:59:22 svnexp Exp $
#

PORTNAME=	libRmath

COMMENT=	The standalone math library from R

DESCR=	${.CURDIR}/pkg-descr
LIBRMATH_SLAVEPORT=	yes
MASTERDIR=	${.CURDIR}/../R
PLIST=	${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
