# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: graphics/gstreamer-plugins-aalib/Makefile 327733 2013-09-20 18:35:44Z bapt $
#   $MCom: ports/graphics/gstreamer-plugins-aalib/Makefile,v 1.5 2008/03/19 14:05:33 ahze Exp $

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	Gstreamer ASCII art plugin

GST_PLUGIN=	aalib

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
