# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: graphics/gstreamer-plugins-aalib/Makefile 340722 2014-01-22 17:00:46Z mat $
#   $MCom: ports/graphics/gstreamer-plugins-aalib/Makefile,v 1.5 2008/03/19 14:05:33 ahze Exp $

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	Gstreamer ASCII art plugin

GST_PLUGIN=	aalib

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
