# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: textproc/p5-XML-DOM-Lite/Makefile 333056 2013-11-07 03:52:41Z vanilla $

PORTNAME=	XML-DOM-Lite
PORTVERSION=	0.15
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lite Pure Perl XML DOM Parser Kit

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
