# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: textproc/p5-XML-DOM-Lite/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	XML-DOM-Lite
PORTVERSION=	0.15
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lite Pure Perl XML DOM Parser Kit

USES=		perl5
USE_PERL5=	configure

MAN3=		XML::DOM::Lite.3 XML::DOM::Lite::Document.3 \
		XML::DOM::Lite::NodeList.3 XML::DOM::Lite::Parser.3 \
		XML::DOM::Lite::XPath.3 XML::DOM::Lite::XSLT.3

NO_STAGE=	yes
.include <bsd.port.mk>
