# New ports collection makefile for:	p5-XML-DOM-Lite
# Date created:		2006-08-20
# Whom:			Gea-Suan Lin <gslin@gslin.org>
#
# $FreeBSD: ports/textproc/p5-XML-DOM-Lite/Makefile,v 1.7 2012/11/17 06:02:11 svnexp Exp $
#

PORTNAME=	XML-DOM-Lite
PORTVERSION=	0.15
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lite Pure Perl XML DOM Parser Kit

PERL_CONFIGURE=	yes

MAN3=		XML::DOM::Lite.3 XML::DOM::Lite::Document.3 \
		XML::DOM::Lite::NodeList.3 XML::DOM::Lite::Parser.3 \
		XML::DOM::Lite::XPath.3 XML::DOM::Lite::XSLT.3

.include <bsd.port.mk>
