# $FreeBSD: devel/hs-bloomfilter/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	bloomfilter
PORTVERSION=	1.2.6.10
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Pure and impure Bloom Filter implementations

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
