# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: www/rubygem-webrobots/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	webrobots
PORTVERSION=	0.1.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Write robots.txt compliant web robots in Ruby

LICENSE=	BSD

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
