# $FreeBSD: devel/hs-hashtables/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	hashtables
PORTVERSION=	1.1.0.2
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Mutable hash tables in the ST monad

LICENSE=	BSD

USE_CABAL=	hashable>=1.1 primitive vector>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
