# $FreeBSD: devel/hs-hashtables/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	hashtables
PORTVERSION=	1.1.0.2
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Mutable hash tables in the ST monad

LICENSE=	BSD

USE_CABAL=	hashable>=1.1 primitive vector>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
