# Created by: Koichiro IWAO <meta+ports@vmeta.jp>
# $FreeBSD: net/remmina-plugin-gnome/Makefile 339795 2014-01-15 17:28:00Z fluffy $

PKGNAMESUFFIX=	-gnome

COMMENT=	Remmina plugin for GNOME Keyring

LIB_DEPENDS=	libgnome-keyring.so:${PORTSDIR}/security/libgnome-keyring

MASTERDIR=	${.CURDIR}/../remmina-plugins

.include "${MASTERDIR}/Makefile"
