# Created by: tobez
# $FreeBSD: math/p5-Math-BigInt/Makefile 327746 2013-09-20 20:55:04Z bapt $

PORTNAME=	Math-BigInt
PORTVERSION=	1.997
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PJACKLAM
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Math::BigInt - Arbitrary size integer math package

USES=		perl5
USE_PERL5=	configure

MAN3=		Math::BigFloat.3 \
		Math::BigInt.3 \
		Math::BigInt::Calc.3 \
		Math::BigInt::CalcEmu.3

NO_STAGE=	yes
.include <bsd.port.mk>
