# $FreeBSD: devel/hs-syb/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	syb
PORTVERSION=	0.4.0
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Scrap Your Boilerplate

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
