# $FreeBSD: ports/print/ghostscript9/files/Makefile.dmprt,v 1.2 2012/11/17 06:00:50 svnexp Exp $

post-install-dmprt:
	${INSTALL_PROGRAM} ${WRKSRC}/${EPAG_NAME}/ert ${PREFIX}/bin
	cd ${FILESDIR} && \
		${INSTALL_DATA} lqx70ch.upp lqx70cl.upp lqx70cm.upp \
		${DATADIR}/${PORTVERSION}/lib

post-install: post-install-dmprt
