# Created by: Philip M. Gollucci <pgollucci@p6m7g8.com>
# $FreeBSD: devel/rubygem-rr/Makefile 319684 2013-06-02 16:39:26Z swills $

PORTNAME=	rr
PORTVERSION=	1.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	RR is a double framework with lots of double techniques and terse syntax

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
