# Created by: wen@FreeBSD.org
# $FreeBSD: security/pecl-pam/Makefile 340835 2014-01-23 16:00:14Z miwi $

PORTNAME=	pam
PORTVERSION=	1.0.3
CATEGORIES=	security pear
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
EXTRACT_SUFX=	.tgz

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PECL classes for PAM integration

USE_PHP=	yes
USE_PHPIZE=	yes
USE_PHPEXT=	yes

.include <bsd.port.mk>
