# $FreeBSD: www/hs-shakespeare-text/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	shakespeare-text
PORTVERSION=	1.0.0.5
PORTREVISION=	3
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Interpolation with quasi-quotation: put variables strings

LICENSE=	MIT

USE_CABAL=	shakespeare>=1.0 text>=0.7

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
