# New ports collection makefile for:	Module-Find
# Date created:	   26 Sep 2005
# Whom:		   Lars Balker Rasmussen <lbr@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Module-Find/Makefile,v 1.10 2012/11/17 05:56:21 svnexp Exp $
#

PORTNAME=	Module-Find
PORTVERSION=	0.11
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lets you find and use modules in categories

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		Module::Find.3

.include <bsd.port.mk>
