# Created by: Mykola Marzhan <delgod@portaone.com>
# $FreeBSD: devel/p5-Sys-Sendfile-FreeBSD/Makefile 326802 2013-09-09 11:01:46Z az $

PORTNAME=	Sys-Sendfile-FreeBSD
PORTVERSION=	0.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	delgod@portaone.com
COMMENT=	Wrapper for the FreeBSD sendfile(2) function

USES=		perl5
USE_PERL5=	configure

MAN3=		Sys::Sendfile::FreeBSD.3

.include <bsd.port.mk>
