# Created by: renchap@cocoa-x.com
# $FreeBSD: devel/rubygem-systemu/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	systemu
PORTVERSION=	2.5.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	A portable replacement for popen4

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
