# Created by: clsung
# $FreeBSD: www/p5-HTML-TagParser/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	HTML-TagParser
PORTVERSION=	0.20
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Yet another HTML tag parser by pure Perl implementation

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
