# New ports collection makefile for:	p5-HTML-TagParser
# Date Created:				8 Jul 2006
# Whom:					clsung
#
# $FreeBSD: ports/www/p5-HTML-TagParser/Makefile,v 1.6 2012/11/17 06:02:50 svnexp Exp $
#

PORTNAME=	HTML-TagParser
PORTVERSION=	0.20
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Yet another HTML tag parser by pure Perl implementation

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		HTML::TagParser.3

.include <bsd.port.mk>
