# Created by: Brad Hendrickse <bradh@uunet.co.za>
# $FreeBSD: net-mgmt/p5-Net-IPv4Addr/Makefile 332836 2013-11-05 12:02:05Z vanilla $

PORTNAME=	Net-IPv4Addr
PORTVERSION=	0.10
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl extension for manipulating IPv4 addresses

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
