# New ports collection makefile for:    sv-aspell
# Date created:                         7 September 2002
# Whom:                                 Thierry Thomas <thierry@pompo.net>
#
# $FreeBSD: ports/textproc/sv-aspell/Makefile,v 1.8 2012/11/17 06:02:22 svnexp Exp $
#

PORTNAME=	${DICT}-aspell
DISTVERSION=	-sv-0.51-0
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Swedish dictionary

DICT=	 	sv

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
