# $FreeBSD: sysutils/rubygem-fssm/Makefile 332050 2013-10-30 02:57:17Z swills $

PORTNAME=	fssm
PORTVERSION=	0.2.10
CATEGORIES=	sysutils ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provides a state tracking and event firing utility

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
