# Created by: joerg
# $FreeBSD: games/xonix/Makefile 327730 2013-09-20 17:36:33Z bapt $

PORTNAME=	xonix
PORTVERSION=	1.4
PORTREVISION=	3
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.interface-business.de/pub/outgoing/

MAINTAINER=	joerg@FreeBSD.org
COMMENT=	Try to win land without colliding with `flyers' and `eaters'

USES=		imake
USE_XORG=	xaw
MAN1=		xonix.1

NO_STAGE=	yes
.include <bsd.port.mk>
