# New ports collection makefile for:	TiMidity++
# Date created:		27 Feb 1999
# Whom:			Yoichi Asai <yatt@msc.biglobe.ne.jp>
#
# $FreeBSD: ports/audio/timidity++-gtk/Makefile,v 1.9 2012/11/17 05:54:45 svnexp Exp $
#

PKGNAMESUFFIX=	-gtk

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Gtk interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++

PLIST_FILES=	bin/gtkmidi ${TIMID_LIBDIR}/interface_g.so

.include "${MASTERDIR}/Makefile"
