# New ports collection makefile for:	php5-bz2
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/archivers/php5-bz2/Makefile,v 1.2 2012/11/17 05:54:22 svnexp Exp $
#

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-bz2

.include "${MASTERDIR}/Makefile"
