# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: devel/gstreamer-plugins-gio/Makefile 340722 2014-01-22 17:00:46Z mat $
#   $MCom: ports/devel/gstreamer-plugins-gio/Makefile,v 1.1 2008/03/21 04:14:18 ahze Exp $

PORTREVISION=	0
CATEGORIES=	devel

COMMENT=	Gstreamer gio (Glib I/O) plugin

GST_PLUGIN=	gio

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
