# LLDB needs to be ported to dragonfly
OPTIONS_DEFAULT:=	${OPTIONS_DEFAULT:NLLDB:NOPENMP}
OPTIONS_DEFAULT_x86_64:= ${OPTIONS_DEFAULT_x86_64:NCOMPILER_RT:NOPENMP}

dfly-patch:
	${REINPLACE_CMD} -e 's|gcc50|gcc80|g' -e 's|5.0"|8.0"|' \
		${WRKSRC}/tools/clang/lib/Driver/ToolChains/DragonFly.cpp \
		${WRKSRC}/tools/clang/lib/Frontend/InitHeaderSearch.cpp
