# Created by: Emanuel Haupt <ehaupt@FreeBSD.org>
# $FreeBSD: devel/p5-Uniq/Makefile 331567 2013-10-25 11:20:05Z ehaupt $

PORTNAME=	Uniq
PORTVERSION=	0.01
CATEGORIES=	devel
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:SYAMAL
PKGNAMEPREFIX=	p5-

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Perl extension for managing a uniq list of values

USES=		perl5
USE_PERL5=	configure

WRKSRC=		${WRKDIR}/${PORTNAME}

.include <bsd.port.mk>
