# Created by: milki <milki@rescomp.berkeley.edu>
# $FreeBSD: devel/p5-Test-NoTabs/Makefile 340549 2014-01-21 05:12:40Z milki $

PORTNAME=	Test-NoTabs
PORTVERSION=	1.3
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:BOBTFISH
PKGNAMEPREFIX=	p5-

MAINTAINER=	milki@FreeBSD.org
COMMENT=	Check the presence of tabs in your project

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
