# Created by: Guy P.
# $FreeBSD: www/p5-CGI-Response/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	CGI-Response
PORTVERSION=	0.03
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module allowing response construction for CGI applications

USES=		perl5
USE_PERL5=	configure

MAN3=		CGI::Response.3

NO_STAGE=	yes
.include <bsd.port.mk>
