# $FreeBSD: www/twiki-EmptyPlugin/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	EmptyPlugin
SVNREV=		16417

COMMENT=	Empty plugin template

NO_STAGE=	yes
.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
