PORTNAME=	slowaes
PORTVERSION=    0.1a1
CATEGORIES=	devel python
MASTER_SITES=	http://pypi.python.org/packages/source/s/${PORTNAME}/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	${PORTNAME}-${PORTVERSION}

MAINTAINER=	kyuupichan@gmail.com
COMMENT=	Implementation of AES in pure Python

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install	

.include <bsd.port.mk>
