# Created by: chinsan
# $FreeBSD: textproc/p5-Number-Spell/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Number-Spell
PORTVERSION=	0.04
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for spelling out numbers

USES=		perl5
USE_PERL5=	configure

MAN3=		Number::Spell.3

.include <bsd.port.mk>
