# Created by: chinsan
# $FreeBSD: textproc/p5-Number-Spell/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Number-Spell
PORTVERSION=	0.04
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for spelling out numbers

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
