# Created by: Yi-Hsuan Hsin <mhsin@mhsin.org>
# $FreeBSD: math/p5-Math-Base36/Makefile 341825 2014-01-30 09:42:48Z az $

PORTNAME=	Math-Base36
PORTVERSION=	0.10
PORTEPOCH=	2
CATEGORIES=	math converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mhsin@mhsin.org
COMMENT=	Encoding and decoding of base36 strings

BUILD_DEPENDS=	p5-ExtUtils-MakeMaker>=6.59:${PORTSDIR}/devel/p5-ExtUtils-MakeMaker

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
