# New ports collection makefile for:	py-biolccc
# Date created:		2010-10-24
# Whom:			Max Brazhnikov <makc@FreeBSD.org>
#
# $FreeBSD: ports/science/py-biolccc/Makefile,v 1.4 2012/11/17 06:00:59 svnexp Exp $
#

PORTNAME=	BioLCCC
PORTVERSION=	1.4.0
CATEGORIES=	science python
MASTER_SITES=	CHEESESHOP/source/p/${PYDISTUTILS_PKGNAME}/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	${PYDISTUTILS_PKGNAME}-${PORTVERSION}

MAINTAINER=	makc@FreeBSD.org
COMMENT=	Python bindings for BioLCCC

USE_PYTHON=	2.6+
USE_PYDISTUTILS=	yes
PYDISTUTILS_PKGNAME=	pyBioLCCC

.include <bsd.port.mk>
