# Created by: Heiner <h.eichmann@gmx.de>
# $FreeBSD: multimedia/emovix/Makefile 324181 2013-08-03 08:45:51Z az $

PORTNAME=	emovix
PORTVERSION=	0.9.0
CATEGORIES=	multimedia
MASTER_SITES=	SF/movix/eMoviX/0.9

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Mini Linux distro to create bootable video CDs

GNU_CONFIGURE=	yes
USES=		perl5
USE_GMAKE=	yes

.include <bsd.port.mk>
