# $FreeBSD: editors/libreoffice-ca_XV/Makefile 331614 2013-10-25 17:05:50Z jkim $

LO_I18N=	ca_XV
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
