# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-Getopt-Attribute/Makefile 338870 2014-01-06 12:43:03Z az $

PORTNAME=	Getopt-Attribute
PORTVERSION=	2.101700
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Attribute wrapper for Getopt::Long

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
