# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: converters/igbinary/Makefile 339238 2014-01-09 14:10:39Z bapt $

PORTNAME=	igbinary
PORTVERSION=	1.1.1
CATEGORIES=	converters
MASTER_SITES=	http://opensource.dynamoid.com/	\
		http://files.gslin.org/~gslin/Software/

MAINTAINER=	gslin@gslin.org
COMMENT=	Replacement for the standard PHP serializer

USE_PHP=	session
USE_PHP_BUILD=	yes
USE_PHPIZE=	yes
USE_PHPEXT=	yes

.include <bsd.port.mk>
