# Created by: Vladimir Chukharev
# $FreeBSD: head/devel/py-robotframework/Makefile 343450 2014-02-09 10:41:00Z rm $

PORTNAME=	robotframework
PORTVERSION=	2.8.4
CATEGORIES=	devel www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	Vladimir.Chukharev@gmail.com
COMMENT=	Generic test automation framework

LICENSE=	APACHE20

USE_PYTHON=		2
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
