# Created by: Vladimir Chukharev
# $FreeBSD: devel/py-robotframework/Makefile 313096 2013-02-28 15:37:55Z culot $

PORTNAME=	robotframework
PORTVERSION=	2.7.7
CATEGORIES=	devel www python
MASTER_SITES=	GOOGLE_CODE
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	Vladimir.Chukharev@gmail.com
COMMENT=	Generic test automation framework

LICENSE=	AL2

USE_PYTHON=	-2.7
USE_PYDISTUTILS=yes

.include <bsd.port.mk>
