# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: ports/misc/kde4-l10n-sl/Makefile,v 1.71 2013/02/04 01:04:22 svnexp Exp $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
CATEGORIES=	misc kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Slovenian messages and documentation for KDE4

KDE4_L10N=	sl

.include "${.CURDIR}/../../misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.post.mk>
