# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-B-Hooks-OP-Check/Makefile 325134 2013-08-21 14:08:06Z sunpoet $

PORTNAME=	B-Hooks-OP-Check
PORTVERSION=	0.19
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Wrap OP check callbacks

BUILD_DEPENDS=	p5-ExtUtils-Depends>=0.302:${PORTSDIR}/devel/p5-ExtUtils-Depends

USE_PERL5=	configure
USES=		perl5

MAN3=		B::Hooks::OP::Check.3

.include <bsd.port.mk>
