# $FreeBSD: security/p5-Digest-MurmurHash/Makefile 341825 2014-01-30 09:42:48Z az $

PORTNAME=	Digest-MurmurHash
PORTVERSION=	0.11
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for XS interface to the MurmurHash algorithm

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
