# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-AtExit/Makefile 315509 2013-03-29 00:44:53Z eadler $

PORTNAME=	AtExit
PORTVERSION=	2.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	AtExit - Perform exit processing for a program or object

PERL_CONFIGURE=	yes

MAN3=		AtExit.3

.include <bsd.port.mk>
