# New ports collection makefile for:	AtExit
# Date created:	   28 August 2002
# Whom:		   Sergey Skvortsov <skv@protey.ru>
#
# $FreeBSD: ports/devel/p5-AtExit/Makefile,v 1.7 2012/11/17 05:56:05 svnexp Exp $
#

PORTNAME=	AtExit
PORTVERSION=	2.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	AtExit - Perform exit processing for a program or object

PERL_CONFIGURE=	yes

MAN3=		AtExit.3

.include <bsd.port.mk>
