# Created by: Thinker K.F. Li <thinker@branda.to>
# $FreeBSD: devel/pythk/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	pythk
PORTVERSION=	0.2.0
CATEGORIES=	devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A collection of Python functions

LICENSE=	BSD

USE_PYTHON=	2
USE_PYDISTUTILS=yes

NO_STAGE=	yes
.include <bsd.port.mk>
