# Created by: Alex Keda <admin@lissyara.su>
# $FreeBSD: databases/php52-interbase/Makefile 328900 2013-09-30 23:42:21Z acm $

PORTREVISION=	1
CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-interbase

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
