# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: devel/p5-Hook-LexWrap/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Hook-LexWrap
PORTVERSION=	0.24
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lexically scoped subroutine wrappers for Perl

USES=		perl5
USE_PERL5=	configure

MAN3=		Hook::LexWrap.3

NO_STAGE=	yes
.include <bsd.port.mk>
