# Created by: Jean-Yves Lefort <jylefort@FreeBSD.org>
# $FreeBSD: databases/libgda4-reference/Makefile 314630 2013-03-19 10:26:51Z kwm $

PORTREVISION=	0

REFERENCE_SRC=	${WRKSRC}/doc/C

.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
