# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: ports/graphics/R-cran-pixmap/Makefile,v 1.6 2013/01/04 18:45:34 svnexp Exp $

PORTNAME=	pixmap
DISTVERSION=	0.4-11
PORTREVISION=	4
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Bitmap Images ("Pixel Maps")

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
