# $FreeBSD: security/hs-entropy/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	entropy
PORTVERSION=	0.2.1
PORTREVISION=	7
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Platform-independent entropy source

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
