--- engine/sl08/sl08.py.intermediate	2020-11-29 19:57:15.000000000 +0000
+++ engine/sl08/sl08.py
@@ -357,6 +357,7 @@ print("""#ifndef BTANKS_SL08_SLOTSANDSIG
 /* DO NOT MODIFY THIS FILE: IT'S AUTOGENERATED */ 
 
 #include <list>
+#include <cstddef>
 
 #ifndef NULL
 #define NULL            ((void*) 0)
