# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: www/xpi-clearfields/Makefile 341198 2014-01-26 15:07:21Z miwi $

PORTNAME=	clearfields
PORTVERSION=	4.0.3
DISTVERSIONSUFFIX=	-fx
CATEGORIES=	www

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Toolbar buttons that clear input fields

XPI_DISTNAME=	clear_fields
XPI_ID=		clearfields@alex.alexander.googlepages.com
XPI_NUM=	2408

.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
