# Created by: Kimo <kimor79@yahoo.com>
# $FreeBSD: ports/databases/rubygem-mysql2/Makefile,v 1.1 2013/01/23 02:47:35 svnexp Exp $

PORTNAME=	mysql2
PORTVERSION=	0.3.11
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple, fast MySQL library for Ruby, binding to libmysql

USE_MYSQL=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
