# Created by: asami
# $FreeBSD: x11-wm/piewm/Makefile 327786 2013-09-21 00:01:16Z bapt $

PORTNAME=	piewm
PORTVERSION=	1.04
PORTREVISION=	4
CATEGORIES=	x11-wm
MASTER_SITES=	http://www.crynwr.com/piewm/

MAINTAINER=	david@catwhisker.org
COMMENT=	tvtwm with pie (circular) menus

USES=		imake
DISABLE_SIZE=	yes
USE_XORG=	xbitmaps xpm xmu
MAN1=		piewm.1

CFLAGS+=	-Wno-return-type

NO_STAGE=	yes
.include <bsd.port.mk>
