# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11/libXxf86vm/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	libXxf86vm
PORTVERSION=	1.1.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Vidmode Extension

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	xproto x11 xextproto xext xf86vidmodeproto:both

.include <bsd.port.mk>
