# New ports collection makefile for:	php5-pdo_dblib
# Date created:			7 Feb 2007
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/databases/php5-pdo_dblib/Makefile,v 1.2 2012/11/17 05:55:19 svnexp Exp $
#

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-pdo_dblib

.include "${MASTERDIR}/Makefile"
