# New ports collection makefile for:	php5-pdo_dblib
# Date created:			7 Feb 2007
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: databases/php5-pdo_dblib/Makefile 300896 2012-07-14 13:54:48Z beat $
#

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-pdo_dblib

.include "${MASTERDIR}/Makefile"
