# Created by: Sulev-Madis Silber <madis555@hot.ee>
# $FreeBSD: devel/p5-Time-Stopwatch/Makefile 341710 2014-01-29 10:33:57Z az $

PORTNAME=	Time-Stopwatch
PORTVERSION=	1.00
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	madis555@hot.ee
COMMENT=	Use tied scalars as timers

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
