LibreSSL SSL_OP_NO_TLSv1_3 workaround.

--- cmake/ssl.cmake.intermediate	2020-08-16 09:07:00.000000000 +0000
+++ cmake/ssl.cmake
@@ -189,7 +189,7 @@ MACRO (MYSQL_CHECK_SSL)
         OPENSSL_FIX_VERSION "${OPENSSL_VERSION_NUMBER}"
         )
     ENDIF()
-    IF("${OPENSSL_MAJOR_VERSION}.${OPENSSL_MINOR_VERSION}.${OPENSSL_FIX_VERSION}" VERSION_GREATER "1.1.0")
+    IF("${OPENSSL_MAJOR_VERSION}.${OPENSSL_MINOR_VERSION}.${OPENSSL_FIX_VERSION}" VERSION_GREATER "1.1.0" AND NOT ${OPENSSL_MAJOR_VERSION} EQUAL "2" )
        ADD_DEFINITIONS(-DHAVE_TLSv13)
     ENDIF()
     IF(OPENSSL_INCLUDE_DIR AND
