# New ports collection makefile for:	p5-Time-HiRes
# Date created:			13 June 1999
# Whom:				Stephen J. Roznowski <sjr@home.net>
#
# $FreeBSD: ports/devel/p5-Time-HiRes/Makefile,v 1.53 2012/11/17 05:56:35 svnexp Exp $
#

PORTNAME=	Time-HiRes
PORTVERSION=	1.9725
PORTEPOCH=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	A perl5 module implementing High resolution time, sleep, and alarm

TEST_DEPENDS=	p5-Test-Simple>=0.82:${PORTSDIR}/devel/p5-Test-Simple

PERL_CONFIGURE=	yes

MAN3=		Time::HiRes.3

.include <bsd.port.mk>
