# Created by: James Bailie <jimmy@mammothcheese.ca>
# $FreeBSD: devel/pty/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	pty
PORTVERSION=	1.2
CATEGORIES=	devel
MASTER_SITES=	http://www.mammothcheese.ca/

MAINTAINER=	jimmy@mammothcheese.ca
COMMENT=	Helps debug programs which fiddle with their tty settings

MAN1=	pty.1
MANCOMPRESSED=	yes

PLIST_FILES=	bin/pty

NO_STAGE=	yes
.include <bsd.port.mk>
