# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: devel/googlemock/Makefile 333053 2013-11-07 02:51:51Z clsung $

PORTNAME=	googlemock
PORTVERSION=	1.5.0
CATEGORIES=	devel
MASTER_SITES=	GOOGLE_CODE
DISTNAME=	gmock-${PORTVERSION}

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	A library for writing and using C++ mock classes

BUILD_DEPENDS=	googletest>=1.5.0:${PORTSDIR}/devel/googletest

GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
