# Created by: Alexander Logvinov <ports@logvinov,com>
# $FreeBSD: databases/rubygem-jdbc-mysql/Makefile 340899 2014-01-24 14:45:58Z miwi $

PORTNAME=	jdbc-mysql
PORTVERSION=	5.1.25
CATEGORIES=	databases rubygems java
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	MySQL JDBC driver for JRuby

RUN_DEPENDS=	jruby:${PORTSDIR}/lang/jruby

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
