# Ports collection makefile for:	rubygem-fastthread
# Date created:				28 February 2007
# Whom:					Alexander Logvinov <ports@logvinov.com>
#
# $FreeBSD: ports/devel/rubygem-fastthread/Makefile,v 1.12 2012/11/17 05:56:59 svnexp Exp $

PORTNAME=	fastthread
PORTVERSION=	1.0.7
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Optimized replacement for thread.rb primitives

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
