# Created by: Alexander Logvinov <ports@logvinov.com>
# $FreeBSD: devel/rubygem-fastthread/Makefile 332036 2013-10-30 02:32:53Z swills $

PORTNAME=	fastthread
PORTVERSION=	1.0.7
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Optimized replacement for thread.rb primitives

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
