# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-railsless-deploy/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	railsless-deploy
PORTVERSION=	1.1.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Replacement for the rails deploy strategy which ships with Capistrano

RUN_DEPENDS=	rubygem-capistrano>=1.0.0:${PORTSDIR}/sysutils/rubygem-capistrano

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
