# Created by: Maxim Sobolev <sobomax@FreeBSD.org>
# $FreeBSD: net/linphone/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTREVISION=	4
CATEGORIES=	net gnome

LINPHONE_GUI=	yes

MASTERDIR=	${.CURDIR}/../../net/linphone-base

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
