# New ports collection makefile for:	p5-Net-IP-Minimal
# Date created:		2012-02-28
# Whom:			Steve Wills <swills@FreeBSD.org>
#
# $FreeBSD: ports/net/p5-Net-IP-Minimal/Makefile,v 1.4 2012/11/29 15:49:49 svnexp Exp $
#

PORTNAME=	Net-IP-Minimal
PORTVERSION=	0.06
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Minimal functions from Net::IP

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=	Net::IP::Minimal.3

.include <bsd.port.mk>
