# New ports collection makefile for:	py-django-storages
# Date created:		2011-02-26
# Whom:			Li-Wen Hsu <lwhsu@FreeBSD.org>
#
# $FreeBSD: ports/www/py-django-storages/Makefile,v 1.4 2012/11/17 06:02:59 svnexp Exp $
#

PORTNAME=	django-storages
PORTVERSION=	1.1.4
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Generic storages for Django

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

.include <bsd.port.mk>
