# Created by: Lars Balker Rasmussen <lbr@FreeBSD.org>
# $FreeBSD: devel/p5-Algorithm-C3/Makefile 331766 2013-10-27 12:17:59Z vanilla $

PORTNAME=	Algorithm-C3
PORTVERSION=	0.08
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Module for merging hierarchies using the C3 algorithm

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
