# $FreeBSD: x11-drivers/xf86-video-fbdev/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xf86-video-fbdev
PORTVERSION=	0.4.4
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org fbdev display driver

XORG_CAT=	driver

.include <bsd.port.mk>
