# Created by: Emil J.V. Björsell (Jev)
# $FreeBSD: graphics/barcode/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	barcode
PORTVERSION=	0.98
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	barcode

MAINTAINER=	jev@ecad.org
COMMENT=	A barcode generation library along with a command line frontend

BUILD_DEPENDS=	gawk:${PORTSDIR}/lang/gawk

MAN1=		barcode.1
MAN3=		barcode.3
GNU_CONFIGURE=	yes
INFO=		barcode

NO_STAGE=	yes
.include <bsd.port.mk>
