# Ports collection makefile for:  pear-Horde_Pdf
# Date created:			  7 July 2011
# Whom:				  Martin Matuska <mm@FreeBSD.org>
#
# $FreeBSD: ports/textproc/pear-Horde_Pdf/Makefile,v 1.8 2013/02/12 17:39:03 svnexp Exp $
#

PORTNAME=	Horde_Pdf
PORTVERSION=	2.0.3
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde PDF library

USE_HORDE_RUN=	Horde_Exception

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
