# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: ftp/p5-File-Fetch/Makefile 329086 2013-10-02 17:50:44Z sunpoet $

PORTNAME=	File-Fetch
PORTVERSION=	0.44
CATEGORIES=	ftp www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Generic file fetching mechanism

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
