# Created by: obraun@FreeBSD.org
# $FreeBSD: devel/hs-cpphs/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	cpphs
PORTVERSION=	1.16
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Liberalised re-implementation of cpp, the C pre-processor

LICENSE=	LGPL21

EXECUTABLE=	cpphs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
