# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/p5-Sub-Prototype/Makefile 332205 2013-10-31 07:36:25Z vanilla $

PORTNAME=	Sub-Prototype
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Set a subs prototype

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
