# Created by: Frank Mayhar <frank@exit.com>
# $FreeBSD: head/devel/p5-Locale-Maketext/Makefile 332046 2013-10-30 02:52:46Z vanilla $

PORTNAME=	Locale-Maketext
PORTVERSION=	1.23
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:TODDR
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Framework for software localization and inheritance-based lexicons

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Pod>=1.14:${PORTSDIR}/devel/p5-Test-Pod

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
