# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: devel/p5-Decision-ACL/Makefile 331933 2013-10-29 07:56:01Z vanilla $

PORTNAME=	Decision-ACL
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Manage and Build Access Control Lists

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
