# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: x11-themes/metacity-milk-theme/Makefile 340722 2014-01-22 17:00:46Z mat $

TYPE=		metacity
MASTERDIR=	${.CURDIR}/../gtk-milk-theme

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
