# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: devel/R-cran-gsubfn/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	gsubfn
DISTVERSION=	0.6-5
PORTREVISION=	4
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R package used for string matching, substitution and parsing

LICENSE=        GPLv2

RUN_DEPENDS=    R-cran-proto>=0.3.9.2_6:${PORTSDIR}/devel/R-cran-proto

USES=	cran:auto-plist

.include <bsd.port.mk>
