# Created by: Gabor Kovesdan
# $FreeBSD: security/p5-Crypt-Shark/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	Crypt-Shark
PORTVERSION=	1.0.1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension for Shark block cipher

USES=		perl5
USE_PERL5=	configure

MAN3=		Crypt::Shark.3

NO_STAGE=	yes
.include <bsd.port.mk>
