# New ports collection Makefile for:	p5-Crypt-Shark
# Date created:				20 Dec 2006
# Whom:	      				Gabor Kovesdan
# $FreeBSD: ports/security/p5-Crypt-Shark/Makefile,v 1.8 2012/11/17 06:01:11 svnexp Exp $

PORTNAME=	Crypt-Shark
PORTVERSION=	1.0.1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension for Shark block cipher

PERL_CONFIGURE=	yes

MAN3=		Crypt::Shark.3

.include <bsd.port.mk>
