# Created by: will
# $FreeBSD: devel/p5-Ioctl/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Ioctl
PORTVERSION=	0.81
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Ioctl/JPRIT
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module that provides a way to get the value of C ioctl constants

USES=		perl5
USE_PERL5=	configure

NO_STAGE=	yes
.include <bsd.port.mk>
