# $FreeBSD: devel/hs-errors/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	errors
PORTVERSION=	1.4.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simplified error-handling

LICENSE=	BSD

USE_CABAL=	either>=3.1 safe>=0.3.3 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
