# New ports collection makefile for:	rubygem-deprecated
# Date created:		23 Aug, 2009
# Whom:			Wen Heping<wenheping@gmail.com>
#
# $FreeBSD: ports/devel/rubygem-deprecated/Makefile,v 1.6 2013/01/23 21:05:46 svnexp Exp $
#

PORTNAME=	deprecated
PORTVERSION=	3.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A library intended to aid developers working with deprecated code

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
