# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: devel/rubygem-deprecated/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	deprecated
PORTVERSION=	3.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A library intended to aid developers working with deprecated code

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
