# Created by: William Grzybowski <william88@gmail.com>
# $FreeBSD: devel/py-dogpile.core/Makefile 332023 2013-10-29 23:56:26Z wg $

PORTNAME=	dogpile.core
PORTVERSION=	0.4.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Component of a larger caching solution

LICENSE=	BSD

USE_PYTHON=	yes
USE_PYDISTUTILS=easy_install
PYDISTUTILS_AUTOPLIST=	yes
NO_STAGE=	yes

.include <bsd.port.mk>
