# New ports collection makefile for:	php5-mbstring
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/converters/php5-mbstring/Makefile,v 1.2 2012/11/17 05:55:04 svnexp Exp $
#

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-mbstring

.include "${MASTERDIR}/Makefile"
