# Created by: William Grzybowski <william88@gmail.com>
# $FreeBSD: devel/py-mccabe/Makefile 318257 2013-05-15 19:33:14Z wg $

PORTNAME=	mccabe
PORTVERSION=	0.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Ned\'s script to check McCabe complexity

USE_PYTHON=	-2.7 # It actually python3 ready, but still needs some work
USE_PYDISTUTILS=	easy_install

.include <bsd.port.mk>
