# $FreeBSD: arabic/libreoffice/Makefile 327685 2013-09-20 11:04:48Z bapt $

LO_I18N=	ar
CATEGORIES=	arabic editors

NO_STAGE=	yes
.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"
.include <bsd.port.mk>
