# $FreeBSD: ports/arabic/libreoffice/Makefile,v 1.4 2012/12/23 07:08:39 svnexp Exp $

LO_I18N=	ar
CATEGORIES=	arabic editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"
.include <bsd.port.mk>
