# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: devel/php55-pcntl/Makefile 321684 2013-06-24 14:32:11Z ale $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-pcntl

.include "${MASTERDIR}/Makefile"
