# Created by: ijliao
# $FreeBSD: editors/hexcurse/Makefile 337727 2013-12-27 13:08:28Z jadawin $

PORTNAME=	hexcurse
PORTVERSION=	1.55
CATEGORIES=	editors
MASTER_SITES=	DEBIAN
DISTFILES=	${PORTNAME}_${PORTVERSION}.orig

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	A versatile ncurses-based hex editor

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/hexcurse man/man1/hexcurse.1.gz

.include <bsd.port.mk>
