# Created by: ijliao
# $FreeBSD: editors/hexcurse/Makefile 327720 2013-09-20 16:36:23Z bapt $

PORTNAME=	hexcurse
PORTVERSION=	1.55
CATEGORIES=	editors
MASTER_SITES=	DEBIAN
DISTFILES=	${PORTNAME}_${PORTVERSION}.orig

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	A versatile ncurses-based hex editor

GNU_CONFIGURE=	yes

MAN1=		hexcurse.1
PLIST_FILES=	bin/hexcurse

NO_STAGE=	yes
.include <bsd.port.mk>
