# Created by: chinsan
# $FreeBSD: games/p5-Acme-GuessNumber/Makefile 332736 2013-11-04 14:49:24Z vanilla $

PORTNAME=	Acme-GuessNumber
PORTVERSION=	0.04
CATEGORIES=	games perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Locale/IMACAT
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Automatic number guessing game robot

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
