# Created by: tobez
# $FreeBSD: devel/p5-Object-Realize-Later/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Object-Realize-Later
PORTVERSION=	0.18
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Object
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Delayed creation of objects

USES=		perl5
USE_PERL5=	configure

MAN3=		Object::Realize::Later.3

.include <bsd.port.mk>
