# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11-fonts/xf86bigfontproto/Makefile 328096 2013-09-24 06:24:17Z bapt $

PORTNAME=	xf86bigfontproto
PORTVERSION=	1.2.0
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XFree86-Bigfont extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
