# Created by: Maxim Sobolev <sobomax@FreeBSD.org>
# $FreeBSD: editors/led/Makefile 313307 2013-03-02 23:41:11Z eadler $

PORTNAME=	led
PORTVERSION=	2.0
CATEGORIES=	editors
MASTER_SITES=	SF/${PORTNAME}-editor/${PORTNAME}/${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A tiny text editor, with a number of useful programming features

LICENSE=	BSD

GNU_CONFIGURE=	yes
USE_PERL5=	yes
MAKE_JOBS_UNSAFE=	yes

.include <bsd.port.mk>
