# New ports collection makefile for:	p5-Xymon-Client
# Date created:		2012-05-07
# Whom:			Gea-Suan Lin <gslin@gslin.org>
#
# $FreeBSD: ports/net-mgmt/p5-Xymon-Client/Makefile,v 1.2 2012/11/17 06:00:36 svnexp Exp $
#

PORTNAME=	Xymon-Client
PORTVERSION=	0.08
CATEGORIES=	net-mgmt
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Interface to xymon/hobbit client

PERL_CONFIGURE=	yes

MAN3=		Xymon::Client.3

.include <bsd.port.mk>
