# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: net-mgmt/p5-Xymon-Client/Makefile 327757 2013-09-20 22:24:43Z bapt $

PORTNAME=	Xymon-Client
PORTVERSION=	0.08
CATEGORIES=	net-mgmt
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Interface to xymon/hobbit client

USES=		perl5
USE_PERL5=	configure

MAN3=		Xymon::Client.3

NO_STAGE=	yes
.include <bsd.port.mk>
