# Created by: Boris Samorodov <bsam@FreeBSD.org>
# $FreeBSD: german/eric4/Makefile 329493 2013-10-05 18:30:05Z bsam $

CATEGORIES=	german devel python

I18N_LANG=	de

.include "${.CURDIR}/../../devel/eric4/Makefile.inc"
