# $FreeBSD: devel/hs-enumerator/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	enumerator
PORTVERSION=	0.4.19
PORTREVISION=	6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Reliable, high-performance processing with left-fold enumerators

LICENSE=	MIT

USE_CABAL=	text>=0.7 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
