# Created by: Shin-ya MURAKAMI <murashin@gfd-dennou.org>
# $FreeBSD: devel/rubygem-method_source/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	method_source
PORTVERSION=	0.8.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Tool to retrieve the sourcecode for a method

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
