# Created by: Timur I. Bakeyev <bat@cpan.org>
# $FreeBSD: net-mgmt/p5-Net-IP-Match-Regexp/Makefile 326244 2013-09-04 03:24:02Z az $

PORTNAME=	Net-IP-Match-Regexp
PORTVERSION=	1.01
PORTREVISION=	1
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	5u623l20@gmail.com
COMMENT=	Efficiently match IP addresses against IP ranges via regexp

USES=		perl5
USE_PERL5=	configure

MAN3=		Net::IP::Match::Regexp.3

.include <bsd.port.mk>
