@@ -74,10 +74,6 @@
 # remove pre-generated messages catalogs
 	${FIND} ${WRKSRC}/po -name "*.gmo" -delete
 
-post-patch:
-	${REINPLACE_CMD} -e \
-		'/<command>/s|pdftotext|${LOCALBASE}/libexec/xpdf/pdftotext|' \
-		${WRKSRC}/Tokenize/filters/external-filters.xml
 
 pre-configure:
 	${REINPLACE_CMD} -e 's|/usr/share|${LOCALBASE}/share|'	\
