# $FreeBSD: ports/devel/R-cran-gbm/Makefile,v 1.2 2012/11/17 05:55:32 svnexp Exp $

PORTNAME=	gbm
DISTVERSION=	1.6-3.2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Extensions to AdaBoost algorithm

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
