# Created by: kline
# $FreeBSD: print/enscript-letterdj/Makefile 340722 2014-01-22 17:00:46Z mat $

CONFLICTS=	enscript-a4-* enscript-letter-*

PAPERSIZE=	letterdj
PS=		Letterdj

MASTERDIR=	${.CURDIR}/../enscript-letter

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
