# $FreeBSD: misc/rubygem-dotenv/Makefile 332045 2013-10-30 02:50:05Z swills $

PORTNAME=	dotenv
PORTVERSION=	0.9.0
CATEGORIES=	misc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Loads environment variables from `.env`

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES+=	bin/dotenv


.include <bsd.port.mk>
