# Created by: Pawel Worach
# $FreeBSD: x11-fonts/font-arabic-misc/Makefile 327781 2013-09-20 23:51:14Z bapt $

PORTNAME=	font-arabic-misc
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org miscellaneous Arabic fonts

XORG_CAT=	font

NO_STAGE=	yes
.include <bsd.port.mk>
