# Created by:  Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: ports/devel/hs-MonadCatchIO-mtl/Makefile,v 1.14 2013/02/05 22:47:09 svnexp Exp $

PORTNAME=	MonadCatchIO-mtl
PORTVERSION=	0.3.0.5
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad-transformer version of the Control.Exception module

LICENSE=	BSD

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
