# $FreeBSD: comms/rubygem-ruby-termios/Makefile 327714 2013-09-20 16:03:29Z bapt $

PORTNAME=	ruby-termios
PORTVERSION=	0.9.6
CATEGORIES=	comms rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A Ruby interface to termios

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
