
.if !defined(DPORTS_BUILDER)
MANUAL_PACKAGE_BUILD= intended for cross testing only
.endif

# contains freebsd binaries (not used)
.if defined(DEVELOPER)
.MAKEFLAGS+=	DFLY_ALLOW_FOREIGN_BINARIES=yes
DFLY_ALLOW_FOREIGN_BINARIES=yes
.endif
