# Created by: Jean-Yves Lefort <jylefort@FreeBSD.org>
# $FreeBSD: x11-toolkits/vte-reference/Makefile 327785 2013-09-20 23:57:47Z bapt $

PORTREVISION=	1

REFERENCE_SRC=	${WRKSRC}/doc/reference

NO_STAGE=	yes
.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
