# Created by: Ying-Chieh Liao <ijliao@csie.nctu.edu.tw>
# $FreeBSD: head/www/p5-WWW-Scraper-ISBN-Driver/Makefile 332617 2013-11-03 15:16:25Z az $

PORTNAME=	WWW-Scraper-ISBN-Driver
PORTVERSION=	0.20
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Driver class for WWW::Scraper::ISBN module

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
