# Created by: Timur I. Bakeyev <bat@cpan.org>
# $FreeBSD: devel/p5-boolean/Makefile 318076 2013-05-13 12:57:18Z culot $

PORTNAME=		boolean
PORTVERSION=		0.30
CATEGORIES=		devel perl5
MASTER_SITES=		CPAN
MASTER_SITE_SUBDIR=	CPAN:INGY
PKGNAMEPREFIX=		p5-

MAINTAINER=		5u623l20@gmail.com
COMMENT=		Boolean support for Perl

LICENSE=		ART10 GPLv1
LICENSE_COMB=		dual

PERL_CONFIGURE=		yes

MAN3=			boolean.3

.include <bsd.port.mk>
