# $FreeBSD: ports/x11-toolkits/gnustep-cairo/Makefile,v 1.5 2012/11/17 06:03:34 svnexp Exp $

CATEGORIES=	x11-toolkits

MAINTAINER=	dinoex@FreeBSD.org

WITH_GNUSTEP_CAIRO=	yes
MASTERDIR=	${.CURDIR}/../gnustep-back

.if exists(${.CURDIR}/Makefile.local)
.include "${.CURDIR}/Makefile.local"
.endif

.include "${MASTERDIR}/Makefile"
