# Created by: Jose Jachuf <jjachuf@gmail.com>
# $FreeBSD: databases/py-firebirdsql/Makefile 316414 2013-04-24 09:09:19Z culot $

PORTNAME=	firebirdsql
PORTVERSION=	0.7.3
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jjachuf@gmail.com
COMMENT=	Python DBAPI module for FirebirdSQL

LICENSE=	BSD

# Python3 ready
USE_PYTHON=		yes
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
