# Created by: Jose Jachuf <jjachuf@gmail.com>
# $FreeBSD: databases/py-firebirdsql/Makefile 315592 2013-03-30 04:37:26Z acm $

PORTNAME=	firebirdsql
PORTVERSION=	0.7.2
PORTREVISION=	1
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jjachuf@gmail.com
COMMENT=	Python DBAPI module for FirebirdSQL

LICENSE=	BSD

# Python3 ready
USE_PYTHON=		yes
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
