# $FreeBSD: devel/magit/Makefile 315598 2013-03-30 05:13:30Z ashish $

PORTNAME=	magit
PORTVERSION=	1.2.0
PORTREVISION=	1
CATEGORIES=	devel elisp
MASTER_SITES=	${MASTER_SITE_LOCAL} \
		http://cloud.github.com/downloads/magit/magit/
MASTER_SITE_SUBDIR=	kuriyama

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Interface to Git for Emacs

USE_EMACS=	YES
USE_GMAKE=	YES
INFO=		magit

.include <bsd.port.mk>
