# $FreeBSD: multimedia/gstreamer1-plugins-assrender/Makefile 316693 2013-04-27 20:56:38Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer ASS/SSA text renderer plugin

GST_PLUGIN=	assrender
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
