# $FreeBSD: textproc/hs-polyparse/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	polyparse
PORTVERSION=	1.9
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Variety of alternative parser combinator libraries

LICENSE=	LGPL21

USE_CABAL=	text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
