# New ports collection makefile for:	xrefresh
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xrefresh/Makefile,v 1.4 2012/11/17 06:03:22 svnexp Exp $
#

PORTNAME=	xrefresh
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Refresh all or part of an X screen

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xrefresh

MAN1=		xrefresh.1

.include <bsd.port.mk>
