# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: ports/misc/kde4-l10n-nb/Makefile,v 1.73 2013/02/04 01:04:22 svnexp Exp $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
CATEGORIES=	misc kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Norwegian Bokmaal messages and documentation for KDE4

KDE4_L10N=	nb

MANLANG=	${KDE4_L10N}
.include <${.CURDIR}/Makefile.man>

.include "${.CURDIR}/../../misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.post.mk>
