# Created by: Alex Keda <admin@lissyara.su>
# $FreeBSD: archivers/php52-zip/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	archivers

NO_STAGE=	yes
MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-zip

.include "${MASTERDIR}/Makefile"
