# Created by: Alex Keda <admin@lissyara.su>
# $FreeBSD: misc/php52-calendar/Makefile 327745 2013-09-20 20:50:57Z bapt $

CATEGORIES=	misc

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-calendar

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
