# Created by: ijliao
# $FreeBSD: devel/rubygem-fastercsv/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	fastercsv
PORTVERSION=	1.5.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A complete replacement to the CSV standard library

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
