# $FreeBSD: audio/gstreamer-plugins-opus/Makefile 327706 2013-09-20 14:36:35Z bapt $

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	Gstreamer Opus audio encoder/decoder plugin

GST_PLUGIN=	opus

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins
NO_STAGE=	yes

.include "${MASTERDIR}/Makefile"
