# Created by: Jerry Eriksson <jerry@freebsd.se>
# $FreeBSD: audio/rexima/Makefile 327706 2013-09-20 14:36:35Z bapt $

PORTNAME=	rexima
PORTVERSION=	1.4
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	apps/sound/mixers

MAINTAINER=	jerry@freebsd.se
COMMENT=	A ncurses-based console mixer

MAN1=		rexima.1
PLIST_FILES=	bin/rexima
NO_STAGE=	yes

.include <bsd.port.mk>
