# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: head/x11/printproto/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	printproto
PORTVERSION=	1.0.5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Print extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
