# New ports collection makefile for:	printproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/printproto/Makefile,v 1.4 2012/11/17 06:03:19 svnexp Exp $
#

PORTNAME=	printproto
PORTVERSION=	1.0.5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Print extension headers

XORG_CAT=	proto

MAN7=	Xprint.7

.include <bsd.port.mk>
