# New ports collection makefile for:	py-fpconst
# Date created:				7 Oct 2003
# Whom:					Rui Lopes <rui@ruilopes.com>
#
# $FreeBSD: ports/math/py-fpconst/Makefile,v 1.9 2012/11/17 05:59:29 svnexp Exp $

PORTNAME=		fpconst
PORTVERSION=		0.7.2
CATEGORIES=		math python
MASTER_SITES=		${MASTER_SITE_CHEESESHOP}
MASTER_SITE_SUBDIR=	source/f/fpconst
PKGNAMEPREFIX=		${PYTHON_PKGNAMEPREFIX}

MAINTAINER=		ports@FreeBSD.org
COMMENT=		Utilities for handling IEEE 754 floating point special values

USE_PYTHON=		yes
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
