# $FreeBSD: math/hs-contravariant/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	contravariant
PORTVERSION=	0.4
PORTREVISION=	3
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 contravariant functors

LICENSE=	BSD

USE_CABAL=	tagged>=0.4.4 transformers>=0.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
