# Created by: ijliao
# $FreeBSD: textproc/p5-Text-Greeking/Makefile 333056 2013-11-07 03:52:41Z vanilla $

PORTNAME=	Text-Greeking
PORTVERSION=	0.12
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Generate meaningless text that creates the illusion of the document

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
