# Created by: Wei-chun Chao
# $FreeBSD: head/mail/p5-Mail-Sendmail/Makefile 332803 2013-11-05 02:54:53Z vanilla $

PORTNAME=	Mail-Sendmail
PORTVERSION=	0.79
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module implementing a simple, platform-independent mailer

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
