# Created by: Alex Keda <admin@lissyara.su>
# $FreeBSD: ftp/php52-ftp/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	ftp

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-ftp

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
