# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: math/p5-Statistics-LTU/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	Statistics-LTU
PORTVERSION=	2.8
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl implementation of Linear Threshold Units

USES=		perl5
USE_PERL5=	configure

MAN3=		Statistics::LTU.3

.include <bsd.port.mk>
