# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: math/p5-Statistics-LTU/Makefile 341825 2014-01-30 09:42:48Z az $

PORTNAME=	Statistics-LTU
PORTVERSION=	2.8
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl implementation of Linear Threshold Units

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
