# Created by: Yi-Jheng Lin <yzlin@cs.nctu.edu.tw>
# $FreeBSD: devel/p5-IO-BufferedSelect/Makefile 324918 2013-08-18 14:25:16Z az $

PORTNAME=	IO-BufferedSelect
PORTVERSION=	1.0
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Line-buffered select interface

USES=		perl5
USE_PERL5=	configure

MAN3=		IO::BufferedSelect.3

WRKSRC=		${WRKDIR}/${PORTNAME}

.include <bsd.port.mk>
