# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-Lingua-EN-Numbers/Makefile 334741 2013-11-24 16:16:46Z sunpoet $

PORTNAME=	Lingua-EN-Numbers
PORTVERSION=	1.05
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Converts numeric values into their English string equivalents

LICENSE=	GPLv2

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
