# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-Lingua-EN-Numbers/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	Lingua-EN-Numbers
PORTVERSION=	1.04
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Converts numeric values into their English string equivalents

USES=		perl5
USE_PERL5=	configure

MAN3=		Lingua::EN::Numbers.3

NO_STAGE=	yes
.include <bsd.port.mk>
