# Created by: Pawel Worach
# $FreeBSD: x11-fonts/font-adobe-utopia-type1/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	font-adobe-utopia-type1
PORTVERSION=	1.0.4
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Adobe Utopia Type1 font

XORG_CAT=	font

.include <bsd.port.mk>
