# $FreeBSD: devel/hs-HUnit/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	HUnit
PORTVERSION=	1.2.5.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unit testing framework for Haskell

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
