# Ports collection makefile for:	py-openid
# Date created:				Dec 19, 2006
# Whom:					Cheng-Lung Sung <clsung@FreeBSD.org>
#
# $FreeBSD: ports/security/py-openid/Makefile,v 1.8 2012/11/17 06:01:16 svnexp Exp $
#

PORTNAME=	openid
PORTVERSION=	2.2.5
CATEGORIES=	security python
MASTER_SITES=	LOCAL/clsung
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	openid-python-openid-2.2.5-0-gb666238

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	Python OpenID version

WRKSRC=		${WRKDIR}/openid-python-openid-b666238
USE_PYTHON=	yes
USE_PYDISTUTILS=yes
PYDISTUTILS_PKGNAME=	python-openid

.include <bsd.port.mk>
