dfly-patch:
	(cd ${WRKSRC} && ${GREP} -rl "'freebsd'" * | ${XARGS} \
		${REINPLACE_CMD} -e "s|'freebsd'|'dragonfly'|")
	(cd ${WRKSRC} && ${GREP} -rl '"freebsd"' * | ${XARGS} \
		${REINPLACE_CMD} -e 's|"freebsd"|"dragonfly"|')
