# Created by: ports@c0decafe.net <ports@c0decafe.net>
# $FreeBSD: devel/rubygem-notify/Makefile 340902 2014-01-24 14:47:11Z miwi $

PORTNAME=	notify
PORTVERSION=	0.5.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	meta+ports@vmeta.jp
COMMENT=	Desktop notify for many platform

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/notify

.include <bsd.port.mk>
