# $FreeBSD: www/hs-yesod-routes/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	yesod-routes
PORTVERSION=	1.2.0
PORTREVISION=	1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient routing for Yesod

LICENSE=	MIT

USE_CABAL=	path-pieces>=0.1 text>=0.5 vector>=0.8

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
