--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -1,7 +1,6 @@
 [build-system]
 requires = [
     "hatchling>=1.8.0",
-    "hatch-semver",
 ]
 build-backend = "hatchling.build"
 
