# New ports collection makefile for:	php52-gd
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/graphics/php52-gd/Makefile,v 1.2 2012/11/17 05:58:18 svnexp Exp $
#

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-gd

.include "${MASTERDIR}/Makefile"
