# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: math/p5-Math-Random-MT/Makefile 332813 2013-11-05 06:56:18Z vanilla $

PORTNAME=	Math-Random-MT
PORTVERSION=	1.16
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	The Mersenne Twister PRNG

LICENSE=	BSD

TEST_DEPENDS=	p5-Test-Number-Delta>=0:${PORTSDIR}/devel/p5-Test-Number-Delta

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
