# Created by: Alex Keda <admin@lissyara.su>
# $FreeBSD: net/php52-xmlrpc/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-xmlrpc

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
