# $FreeBSD: www/p5-HTTP-Parser-XS/Makefile 338771 2014-01-05 13:37:37Z az $

PORTNAME=	HTTP-Parser-XS
PORTVERSION=	0.16
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension of fast, primitive HTTP request parser

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
