# New ports collection makefile for:	php5-dom
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/textproc/php5-dom/Makefile,v 1.2 2012/11/17 06:02:16 svnexp Exp $
#

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-dom

.include "${MASTERDIR}/Makefile"
