# Created by: janos.mohacsi@bsd.hu
# $FreeBSD: devel/p5-FileHandle-Fmode/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	FileHandle-Fmode
PORTVERSION=	0.11
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jmohacsi@bsd.hu
COMMENT=	Module to determine if a filehandle is opened for reading, writing

MAN3=		FileHandle::Fmode.3

USES=		perl5
USE_PERL5=	configure

NO_STAGE=	yes
.include <bsd.port.mk>
