# New ports collection makefile for:	p5-Locale-Maketext-Fuzzy
# Date created:				Mon April 14th, 2003
# Whom:					Erwin Lansing <erwin@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Locale-Maketext-Fuzzy/Makefile,v 1.8 2012/11/17 05:56:20 svnexp Exp $
#

PORTNAME=	Locale-Maketext-Fuzzy
PORTVERSION=	0.11
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Locale::Maketext::Fuzzy - Maketext from already interpolated strings

PERL_CONFIGURE=	yes

MAN3=		Locale::Maketext::Fuzzy.3

.include <bsd.port.mk>
