# Created by: Sergei Vyshenski <svysh@pn.sinp.msu.ru>
# $FreeBSD: devel/p5-Proc-SafeExec/Makefile 321085 2013-06-17 05:38:19Z az $

PORTNAME=	Proc-SafeExec
PORTVERSION=	1.5
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	svysh.fbsd@gmail.com
COMMENT=	Convenient utility for executing external commands in various ways

LICENSE=	BSD GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		Proc::SafeExec.3 \
		Proc::SafeExec::Queue.3

.include <bsd.port.mk>
