# New ports collection makefile for:    kde4-l10n-ca
# Date created:                         29 July 2008
# Whom:                                 Martin Wilke <miwi@FreeBSD.org>
#
# $FreeBSD: ports/misc/kde4-l10n-ca_valencia/Makefile,v 1.6 2012/11/17 05:59:39 svnexp Exp $
#

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
CATEGORIES=	misc kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Valencian (southern Catalan) messages and documentation for KDE4

KDE4_L10N=	ca@valencia

.include "${.CURDIR}/../../misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
