# $FreeBSD: security/rubygem-net-ssh-gateway/Makefile 338310 2013-12-31 14:30:32Z sunpoet $

PORTNAME=	net-ssh-gateway
PORTVERSION=	1.2.0
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Establish Net::SSH connections through firewalls

LICENSE=	MIT

RUN_DEPENDS=	rubygem-net-ssh>=2.6.5:${PORTSDIR}/security/rubygem-net-ssh

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
