# New ports collection makefile for:	Scope-Upper
# Date created:	   12 мая 2009
# Whom:		   Sergey Skvortsov <skv@protey.ru>
#
# $FreeBSD: ports/devel/p5-Scope-Upper/Makefile,v 1.13 2012/11/17 05:56:28 svnexp Exp $
#

PORTNAME=	Scope-Upper
PORTVERSION=	0.21
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Act on upper scopes

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		Scope::Upper.3

.include <bsd.port.mk>
