# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-Scope-Upper/Makefile 332205 2013-10-31 07:36:25Z vanilla $

PORTNAME=	Scope-Upper
PORTVERSION=	0.24
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:VPIT
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Act on upper scopes

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
