# $FreeBSD: www/p5-CGI-Enurl/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	CGI-Enurl
PORTVERSION=	1.07
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	crees@FreeBSD.org
COMMENT=	Perl module for URL-encoding strings and hashes

RUN_DEPENDS=	p5-CGI.pm>=0:${PORTSDIR}/www/p5-CGI.pm

USES=		perl5
USE_PERL5=	configure

MAN3=		CGI::Enurl.3

NO_STAGE=	yes
.include <bsd.port.mk>
