# New ports collection makefile for:	de-geonext
# Date created:		24 July 2003
# Whom:			Andreas Fehlner (fehlner@gmx.de)
#
# $FreeBSD: ports/german/geonext/Makefile,v 1.7 2012/11/17 05:57:59 svnexp Exp $
#

PORTREVISION=	1
CATEGORIES=	german

MAINTAINER=	fehlner@gmx.de
COMMENT=	Interactive (dynamic) elementary Geometry Software

WITH_LANG=	de
MASTERDIR=	${.CURDIR}/../../math/geonext

.include "${MASTERDIR}/Makefile"
