# Created by: MANTANI Nobutaka <nobutaka@FreeBSD.org>
# $FreeBSD: editors/flim-emacs21/Makefile 327720 2013-09-20 16:36:23Z bapt $

MAINTAINER=	nobutaka@FreeBSD.org
COMMENT=	FLIM, message representation or encoding elisp library for emacs21

# This is a slave port.
PORTCLASS=	slave

MASTERDIR=	${.CURDIR}/../../editors/flim

# emacs port setup
USE_EMACS=	yes
EMACS_PORT_NAME=	emacs21

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
