# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-Test-HasVersion/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Test-HasVersion
PORTVERSION=	0.01.2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-0.012

MAINTAINER=	gslin@gslin.org
COMMENT=	Check Perl modules have version numbers

USES=		perl5
USE_PERL5=	configure

MAN3=		Test::HasVersion.3

NO_STAGE=	yes
.include <bsd.port.mk>
