# Created by: Gabor Kovesdan
# $FreeBSD: security/p5-Crypt-Caesar/Makefile 341825 2014-01-30 09:42:48Z az $

PORTNAME=	Crypt-Caesar
PORTVERSION=	0.01
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl extension for decrypting rot-N strings

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
