# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: misc/p5-Array-RefElem/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Array-RefElem
PORTVERSION=	1.00
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Set up array elements as aliases

USES=		perl5
USE_PERL5=	configure

MAN3=	Array::RefElem.3

.include <bsd.port.mk>
