# Created by: Fernan Aguero <fernan@iib.unsam.edu.ar>
# $FreeBSD: devel/p5-Data-Stag/Makefile 328773 2013-09-30 08:04:05Z culot $

PORTNAME=	Data-Stag
PORTVERSION=	0.14
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Structured Tags datastructures

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

RUN_DEPENDS=	p5-IO-String>=0:${PORTSDIR}/devel/p5-IO-String
BUILD_DEPENDS:=	${RUN_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
