# $FreeBSD: multimedia/gstreamer1-plugins-vpx/Makefile 316693 2013-04-27 20:56:38Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer vp8 codec plugin

GST_PLUGIN=	vpx
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
