# New ports collection makefile for:	TiMidity++
# Date created:		27 Feb 1999
# Whom:			Yoichi Asai <yatt@msc.biglobe.ne.jp>
#
# $FreeBSD: ports/japanese/timidity++-slang/Makefile,v 1.15 2012/11/17 05:58:40 svnexp Exp $
#

PKGNAMESUFFIX=	-slang

CATEGORIES=	japanese

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Slang interface for TiMidity++ with Japanese support

MAKE_JOBS_SAFE=  yes

MASTERDIR=	${.CURDIR}/../../audio/timidity++

JAPANESE=	yes

PLIST_FILES=	${TIMID_LIBDIR}/interface_s.so

.include "${MASTERDIR}/Makefile"
