# Created by: Yoichi Asai <yatt@msc.biglobe.ne.jp>
# $FreeBSD: japanese/timidity++-slang/Makefile 327737 2013-09-20 18:47:54Z bapt $

PKGNAMESUFFIX=	-slang

CATEGORIES=	japanese

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Slang interface for TiMidity++ with Japanese support


MASTERDIR=	${.CURDIR}/../../audio/timidity++

JAPANESE=	yes

PLIST_FILES=	${TIMID_LIBDIR}/interface_s.so

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
