# Created by: Will Andrews <will@FreeBSD.org>
# $FreeBSD: head/devel/p5-LockFile-Simple/Makefile 332046 2013-10-30 02:52:46Z vanilla $

PORTNAME=	LockFile-Simple
PORTVERSION=	0.2.8
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}0${PORTVERSION:E}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module implementing simple file locking

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
