# Created by: Jyun-Yan You <jyyou@cs.nctu.edu.tw>
# $FreeBSD: textproc/rubygem-ezamar/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	ezamar
PORTVERSION=	2009.06
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	jyyou@cs.nctu.edu.tw
COMMENT=	A lightweight and simple templating engine for Ruby

USE_RUBY=	yes

USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
