# New ports collection makefile for:	Devel-LeakTrace
# Date created:	   19 January 2004
# Whom:		   Sergey Skvortsov <skv@protey.ru>
#
# $FreeBSD: ports/devel/p5-Devel-LeakTrace/Makefile,v 1.9 2012/11/17 05:56:13 svnexp Exp $
#

PORTNAME=	Devel-LeakTrace
PORTVERSION=	0.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Indicate where leaked variables are coming from

PERL_MODBUILD=	yes
USE_GNOME=	glib12

MAN3=		Devel::LeakTrace.3

.include <bsd.port.mk>
