# Created by: Li-Wen Hsu <lwhsu@FreeBSD.org>
# $FreeBSD: databases/py-pymysql/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	pymysql
PORTVERSION=	0.6.1
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
DISTNAME=	PyMySQL-${PORTVERSION}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Pure Python MySQL Driver

LICENSE=	MIT

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes
PYDISTUTILS_PKGNAME=	PyMySQL

.include <bsd.port.mk>
