# Created by: Li-Wen Hsu <lwhsu@FreeBSD.org>
# $FreeBSD: databases/py-pymysql/Makefile 334228 2013-11-18 17:02:06Z lwhsu $

PORTNAME=	pymysql
PORTVERSION=	0.5
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
DISTNAME=	PyMySQL-${PORTVERSION}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Pure Python MySQL Driver

LICENSE=	MIT

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes
PYDISTUTILS_PKGNAME=	PyMySQL

.include <bsd.port.mk>
