CFLAGS+=	-I${OPENSSLINC}

CXXFLAGS +=	-DWITHOUT_PULSE

# gcc8 not enough and I don't think we should be adapting code to gcc8, we should
# really upgrade our base's gcc
USE_GCC_VERSION=       9

# bad MF
BUILD_DEPENDS:=	${BUILD_DEPENDS:Npulseaudio*}

dfly-patch:
	${REINPLACE_CMD} -e '/pkg_check_modules(PULSE/d' \
			 -e '/PULSE_INCLUDE_DIRS/d' \
		${WRKSRC}/Telegram/cmake/lib_tgvoip.cmake
