CFLAGS+=	-I${OPENSSLINC}
CXXFLAGS +=	-DWITHOUT_PULSE

# Required for jemalloc
USES+=  gmake

# used by our build
USES+= ninja

# bad MF
BUILD_DEPENDS:=	${BUILD_DEPENDS:Npulseaudio*} autoconf>0:devel/autoconf

dfly-patch:
	${REINPLACE_CMD} -e '/pkg_check_modules(PULSE/d' \
			 -e '/PULSE_INCLUDE_DIRS/d' \
		${WRKSRC}/Telegram/cmake/lib_tgvoip.cmake
