# $FreeBSD: www/twiki-TablePlugin/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	TablePlugin
SVNREV=		17558

COMMENT=	Extra control of table display

NO_STAGE=	yes
.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
