# New ports collection makefile for:	p5-Net-Ifconfig-Wrapper
# Date created:		2012-03-07
# Whom:			Steve Wills <swills@FreeBSD.org>
#
# $FreeBSD: ports/net/p5-Net-Ifconfig-Wrapper/Makefile,v 1.2 2012/11/17 06:00:11 svnexp Exp $
#

PORTNAME=	Net-Ifconfig-Wrapper
PORTVERSION=	0.11
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module provides a unified way to configure network interfaces

MAN3=	Net::Ifconfig::Wrapper.3

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
