# New ports collection makefile for:	String-Random
# Date created:				Mon Jan  1 11:19:27 2001
# Whom:					will
#
# $FreeBSD: ports/devel/p5-String-Random/Makefile,v 1.13 2012/11/17 05:56:30 svnexp Exp $
#

PORTNAME=	String-Random
PORTVERSION=	0.22
PORTEPOCH=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl interface to generate "random" strings

PERL_MODBUILD=	yes

MAN3=		String::Random.3

PORTSCOUT=	limit:^0\.(\d\.){,2}

.include <bsd.port.mk>
