# Created by: Thinker K.F. Li <thinker@branda.to>
# $FreeBSD: devel/py-mez_xml/Makefile 337699 2013-12-27 10:35:36Z wg $

PORTNAME=	mez_xml
PORTVERSION=	0.4
CATEGORIES=	devel www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Simple template engine for Python

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
