# $FreeBSD: ports/devel/automake-wrapper/Makefile,v 1.3 2012/11/17 05:55:34 svnexp Exp $

PORTNAME=	automake-wrapper

COMMENT=	Wrapper script for GNU automake

MASTERDIR=	${.CURDIR}/../../devel/autoconf-wrapper
PKGDIR=		${.CURDIR}

TOOL=		AUTOMAKE
WRAPPED_TOOLS=	aclocal automake

.include "${MASTERDIR}/Makefile"
