# $FreeBSD: devel/automake-wrapper/Makefile 328226 2013-09-25 00:54:08Z bdrewery $

PORTNAME=	automake-wrapper

COMMENT=	Wrapper script for GNU automake

MASTERDIR=	${.CURDIR}/../../devel/autoconf-wrapper
PKGDIR=		${.CURDIR}

TOOL=		AUTOMAKE
WRAPPED_TOOLS=	aclocal automake

.include "${MASTERDIR}/Makefile"
