# $FreeBSD: devel/hs-edit-distance/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	edit-distance
PORTVERSION=	0.2.1.2
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Levenshtein and restricted Damerau-Levenshtein edit distances

LICENSE=	BSD

USE_CABAL=	random>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
