# Created by: Zhihao Yuan <lichray@gmail.com>
# $FreeBSD: graphics/py-png/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	png
PORTVERSION=	0.0.13
CATEGORIES=	graphics python
MASTER_SITES=	GOOGLE_CODE
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	py${PORTNAME}-${PORTVERSION}

MAINTAINER=	lichray@gmail.com
COMMENT=	Python PNG encoder/decoder

PROJECTHOST=	pypng

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install
PYDISTUTILS_PKGNAME=	pypng

NO_STAGE=	yes
.include <bsd.port.mk>
