# New ports collection makefile for:    kn-aspell
# Date created:                         05 May 2011
# Whom:                                 Thierry Thomas <thierry@pompo.net>
#
# $FreeBSD: ports/textproc/kn-aspell/Makefile,v 1.3 2012/11/17 06:02:00 svnexp Exp $
#

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-kn-0.01-1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Kannada dictionary

LICENSE=	GPLv3

DICT=	 	kn

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
