# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: textproc/kn-aspell/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-kn-0.01-1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Kannada dictionary

LICENSE=	GPLv3

DICT=	 	kn

NO_STAGE=	yes
.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
