# $FreeBSD: devel/hs-syb-with-class/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	syb-with-class
PORTVERSION=	0.6.1.4
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Scrap Your Boilerplate With Class

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
