# $FreeBSD: devel/hs-syb-with-class/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	syb-with-class
PORTVERSION=	0.6.1.4
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Scrap Your Boilerplate With Class

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
