# Created by: Ashish Shukla <wahjava@gmail.com>
# $FreeBSD: www/xpi-pencil/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	pencil
DISTVERSION=	2.0-3
DISTVERSIONSUFFIX=	-fx
CATEGORIES=	www
MASTER_SITES=	GOOGLE_CODE
PROJECTHOST=	evoluspencil

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Firefox addon to do GUI prototyping and simple sketching

XPI_DISTNAME=	Pencil
XPI_ID=		pencil@evolus.vn

NO_STAGE=	yes
.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
