# Created by:	KOMATSU Shinichiro <koma2@jiro.c.u-tokyo.ac.jp>
# $FreeBSD: ports/japanese/skk-jisyo-cdb/Makefile,v 1.10 2012/12/09 18:13:48 svnexp Exp $

MAINTAINER=	meta+ports@vmeta.jp
COMMENT=	CDB jisyo (dictionary) files for the SKK Japanese-input software

WITH_SKKJISYO_CDB=	yes

MASTERDIR=	${.CURDIR}/../skk-jisyo

DESCR=		${.CURDIR}/pkg-descr

.include "${MASTERDIR}/Makefile"
