# $FreeBSD: math/hs-distributive/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	distributive
PORTVERSION=	0.3.1
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 distributive functors -- Dual to Traversable

LICENSE=	BSD

USE_CABAL=	transformers>=0.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
