
USES+=	ncurses

OPTIONS_DEFAULT:=	${OPTIONS_DEFAULT:NQUOTAS:NADS:NAVAHI:NGSSAPI_BUILTIN:NFRUIT:NLDAP} GSSAPI_MIT ZEROCONF_NONE

.if defined(DEVELOPER)
dfly-build:
	${RM} -v ${LOCALBASE}/lib/python3.7/site-packages/__pycache__/tevent.cpython-37.pyc
.endif
