# Created by: Stefan Pauly <stefan@fh-mainz.de>
# $FreeBSD: textproc/p5-XML-DOMHandler/Makefile 326942 2013-09-11 06:27:41Z az $

PORTNAME=	XML-DOMHandler
PORTVERSION=	1.0
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	stefan@fh-mainz.de
COMMENT=	A call-back interface to DOM

USES=		perl5
USE_PERL5=	configure

MAN3=		XML::DOMHandler.3

.include <bsd.port.mk>
