# Created by: Lars Balker Rasmussen <lbr@FreeBSD.org>
# $FreeBSD: textproc/p5-Text-SimpleTable/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Text-SimpleTable
PORTVERSION=	2.03
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple Eyecandy ASCII Tables

USES=		perl5
USE_PERL5=	configure

MAN3=		Text::SimpleTable.3

.include <bsd.port.mk>
