# Created by: Lars Balker Rasmussen <lbr@FreeBSD.org>
# $FreeBSD: textproc/p5-Text-SimpleTable/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	Text-SimpleTable
PORTVERSION=	2.03
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple Eyecandy ASCII Tables

USES=		perl5
USE_PERL5=	configure

MAN3=		Text::SimpleTable.3

NO_STAGE=	yes
.include <bsd.port.mk>
