# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: x11-themes/kde-icons-icosx/Makefile 327783 2013-09-20 23:54:03Z bapt $

PORTNAME=	IcOsX
PORTVERSION=	0.7
MASTER_SITES=	http://physics.ramapo.edu/downloads/ \
		http://easylinuxguide.com/downloads/kde-iconthemes/

COMMENT=	KDE IcOsX iconset

WRKSRC=		${WRKDIR}/${PORTNAME}
PORT_SHAREDIR?=	"${PORTNAME}-${PORTVERSION}"

NO_STAGE=	yes
.include "${.CURDIR}/../kde-icons-noia/Makefile.icons"
