# Created by: Archie Cobbs
# $FreeBSD: net/suckblow/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	suckblow
PORTVERSION=	1.1
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	archie

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Two companion utilities for transferring data over a TCP socket

CONFLICTS=	suck-4.* suck-cnews-4.*
MAN1=		suck.1
MLINKS=		suck.1 blow.1
MANCOMPRESSED=	maybe

NO_STAGE=	yes
.include <bsd.port.mk>
