# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: www/rubygem-hpricot/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	hpricot
PORTVERSION=	0.8.6
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A Fast, Enjoyable HTML Parser for Ruby

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
