# Created by: Hsin-Han You <hhyou@cs.nctu.edu.tw>
# $FreeBSD: archivers/rubygem-rubyzip2/Makefile 338711 2014-01-05 00:26:40Z bapt $

PORTNAME=	rubyzip2
PORTVERSION=	2.0.2
CATEGORIES=	archivers rubygems
MASTER_SITES=	RG

MAINTAINER=	hhyou@cs.nctu.edu.tw
COMMENT=	Ruby compatible Zip library

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
