# New ports collection makefile for:   linkcheck
# Date created:                 17 Feb 2004
# Whom:				ismail@enderunix.org
#
# $FreeBSD: ports/www/linkcheck/Makefile,v 1.2 2012/11/17 06:02:38 svnexp Exp $
#

PORTNAME=	linkcheck
PORTVERSION=	1.4
CATEGORIES=	www
MASTER_SITES=	http://www.inter7.com/linkcheck/

MAINTAINER=	ismail@EnderUNIX.org
COMMENT=	Checks a web site for bad links

MAN1=		linkcheck.1
PLIST_FILES=	bin/linkcheck

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
