# $FreeBSD: x11/xsm/Makefile 327777 2013-09-20 23:43:19Z bapt $

PORTNAME=	xsm
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Session Manager

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xsm.1

NO_STAGE=	yes
.include <bsd.port.mk>
