# New ports collection makefile for:	stardict-OxfordCollocation
# Date created:		2010-02-28
# Whom:			Max Brazhnikov <makc@FreeBSD.org>
#
# $FreeBSD: ports/textproc/stardict-OxfordCollocation/Makefile,v 1.3 2012/11/17 06:02:22 svnexp Exp $
#

PORTNAME=	stardict-OxfordCollocation
PORTVERSION=	2.4.2
CATEGORIES=	textproc
MASTER_SITES=	http://yeelou.com/huzheng/stardict-dic/dict.org/
DISTNAME=	stardict-oxford_collocations-${PORTVERSION}

MAINTAINER=	makc@FreeBSD.org
COMMENT=	Oxford English Collocation Dictionary

.include "${.CURDIR}/../../russian/stardict-mueller7/files/Makefile.common"
.include <bsd.port.mk>
