# Created by: Dominic Fandrey
# $FreeBSD: head/games/openarena-server/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	openarena
PKGNAMESUFFIX=	-server

MAINTAINER=	kamikaze@bsdforen.de
COMMENT=	OpenArena dedicated server

UNIQUENAME=	${PORTNAME}${PKGNAMESUFFIX}
MASTERDIR=	${.CURDIR}/../${PORTNAME}

IOQ3=		SERVER

.include "${MASTERDIR}/Makefile"
