# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: www/rubygem-rack-protection/Makefile 321764 2013-06-25 20:09:38Z swills $

PORTNAME=	rack-protection
PORTVERSION=	1.5.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Collection of Rack middleware to protect against opportunistic attack

RUN_DEPENDS=	rubygem-rack>=0:${PORTSDIR}/www/rubygem-rack

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
