# Created by: David Yeske <dyeske@gmail.com>
# $FreeBSD: audio/xmms-faad/Makefile 313559 2013-03-07 03:25:10Z bdrewery $

PKGNAMEPREFIX=	xmms-

MAINTAINER=	c.petrik.sosa@gmail.com
COMMENT=	XMMS plugin for faad

MASTERDIR=	${.CURDIR}

.include "${MASTERDIR}/Makefile.inc"
