# Created by: Brooks Davis <brooks@FreeBSD.org
# $FreeBSD: ports/sysutils/py-nagiosplugin/Makefile,v 1.5 2013/02/09 15:59:45 svnexp Exp $

PORTNAME=	nagiosplugin
PORTVERSION=	0.4.5
CATEGORIES=	sysutils python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Class library for writing Nagios (Icinga) plugins

LICENSE=	ZPL21

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

.include <bsd.port.mk>
