# New ports collection makefile for:    xkeycaps
# Date created:         12 February 1995
# Whom:                 jmz
#
# $FreeBSD: ports/x11/xkeycaps/Makefile,v 1.23 2012/11/17 06:03:21 svnexp Exp $
#

PORTNAME=	xkeycaps
PORTVERSION=	2.46
PORTREVISION=	3
CATEGORIES=	x11
MASTER_SITES=	http://www.jwz.org/xkeycaps/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Graphically display and edit the keyboard mapping

USE_IMAKE=	yes
USE_XORG=	xbitmaps xaw
MAN1=		xkeycaps.1
PLIST_FILES=	bin/xkeycaps

.include <bsd.port.mk>
