# Created by: jmz
# $FreeBSD: x11/xkeycaps/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xkeycaps
PORTVERSION=	2.46
PORTREVISION=	3
CATEGORIES=	x11
MASTER_SITES=	http://www.jwz.org/xkeycaps/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Graphically display and edit the keyboard mapping

USES=		imake
USE_XORG=	xbitmaps xaw
PLIST_FILES=	bin/xkeycaps \
		man/man1/xkeycaps.1.gz

.include <bsd.port.mk>
