# Created by: Alex Kapranoff <alex@kapranoff.ru>
# $FreeBSD: devel/p5-Test-LectroTest/Makefile 321710 2013-06-24 19:48:24Z lippe $

PORTNAME=	Test-LectroTest
PORTVERSION=	0.5001
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lippe@FreeBSD.org
COMMENT=	Easy, automatic, specification-based tests

PERL_CONFIGURE=	yes

MAN3=		Test::LectroTest.3 \
		Test::LectroTest::Compat.3 \
		Test::LectroTest::FailureRecorder.3 \
		Test::LectroTest::Generator.3 \
		Test::LectroTest::Property.3 \
		Test::LectroTest::RegressionTesting.3 \
		Test::LectroTest::TestRunner.3 \
		Test::LectroTest::Tutorial.3

.include <bsd.port.mk>
