# $FreeBSD: devel/geany-plugins-l10n/Makefile 327723 2013-09-20 17:04:43Z bapt $

PORTNAME=	geany-plugins-l10n
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	makc@FreeBSD.org
COMMENT=	Localization messages for Geany plugins

USES=		pathfix

NO_STAGE=	yes
.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
