# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11/xf86miscproto/Makefile 328096 2013-09-24 06:24:17Z bapt $

PORTNAME=	xf86miscproto
PORTVERSION=	0.9.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XFree86-Misc extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
