# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: devel/py-setuptools_hg/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	setuptools_hg
PORTVERSION=	0.4
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Setuptools plugin for hg

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

PLIST_FILES=	%%PYTHON_SITELIBDIR%%/%%PYEASYINSTALL_EGG%%

NO_STAGE=	yes
.include <bsd.port.mk>
