# New ports collection makefile for:	avant-window-navigator-gnome
# Date created:		20 May 2009
# Whom:			Dmitry Marakasov <amdmi3@FreeBSD.org>
#
# $FreeBSD: ports/x11/avant-window-navigator-gnome/Makefile,v 1.4 2012/11/17 06:03:14 svnexp Exp $
#

PORTREVISION=	7
AWN_DESKTOP=    gnome
MASTERDIR=      ${.CURDIR}/../avant-window-navigator

.include <${MASTERDIR}/Makefile>
