# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: x11/avant-window-navigator-gnome/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTREVISION=	7
AWN_DESKTOP=	gnome
MASTERDIR=	${.CURDIR}/../avant-window-navigator

.include <${MASTERDIR}/Makefile>
