# New ports collection makefile for:	appres
# Date Created:				15 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/appres/Makefile,v 1.4 2012/11/17 06:03:14 svnexp Exp $
#

PORTNAME=	appres
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Program to list application's resources

XORG_CAT=	app
USE_XORG=	x11 xt

MAN1=		appres.1
PLIST_FILES=	bin/appres

.include <bsd.port.mk>
