# $FreeBSD: ftp/php53-curl/Makefile 327729 2013-09-20 17:23:18Z bapt $

CATEGORIES=	ftp
PORTREVISION=	1

MASTERDIR=	${.CURDIR}/../../lang/php53

PKGNAMESUFFIX=	-curl

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
