# New ports collection makefile for:	php53-curl
# Date created:			12 Apr 2012
# Whom:				Florian Smeets <flo@FreeBSD.org>
#
# $FreeBSD: ftp/php53-curl/Makefile 322783 2013-07-11 16:26:26Z sunpoet $
#

CATEGORIES=	ftp
PORTREVISION=	1

MASTERDIR=	${.CURDIR}/../../lang/php53

PKGNAMESUFFIX=	-curl

.include "${MASTERDIR}/Makefile"
