USES+=	alias

# no pulse
LIB_DEPENDS:=	${LIB_DEPENDS:Nlibpulse*}

PLIST= ${WRKDIR}/pulseless-plist

# gut it out
dfly-patch:
	${REINPLACE_CMD} -e 's@FreeBSD@DragonFly@g' \
		${WRKSRC}/libobs/CMakeLists.txt \
		${WRKSRC}/plugins/CMakeLists.txt
	${CAT} ${.CURDIR}/pkg-plist | ${SED} -e '/linux-pulseaudio/d' -e '/pulseaudio-wrapper/d' > ${PLIST}
