# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-PHP-Serialization/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	PHP-Serialization
PORTVERSION=	0.34
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	PHP
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Converting the output of PHP serialize() into the Perl

USES=		perl5
USE_PERL5=	configure

MAN3=		PHP::Serialization.3

NO_STAGE=	yes
.include <bsd.port.mk>
