# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: math/R-cran-inline/Makefile 333659 2013-11-13 08:19:34Z bf $

PORTNAME=	inline
PORTVERSION=	0.3.12
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Inline C, C++, Fortran function calls from R

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
