# Created by: Kurt Lidl <kurt.lidl@cello.com>
# $FreeBSD: devel/p5-Test-Mini-Unit/Makefile 338866 2014-01-06 12:05:42Z az $

PORTNAME=	Test-Mini-Unit
PORTVERSION=	v1.0.3
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PVANDE
PKGNAMEPREFIX=	p5-

MAINTAINER=	kurt.lidl@cello.com
COMMENT=	Declarative syntactic sugar for Test::Mini

BUILD_DEPENDS=	p5-Devel-Declare>=0.6.0:${PORTSDIR}/devel/p5-Devel-Declare \
		p5-Test-Mini>=v1.1.3:${PORTSDIR}/devel/p5-Test-Mini

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
