# New ports collection makefile for:	p5-HTML-GenerateUtil
# Date Created:		2010-11-18
# Whom:			Kurt Lidl (kurt.lidl@cello.com)
#
# $FreeBSD: ports/www/p5-HTML-GenerateUtil/Makefile,v 1.3 2012/11/17 06:02:49 svnexp Exp $
#

PORTNAME=	HTML-GenerateUtil
PORTVERSION=	1.11
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module for generating HTML on the fly

PERL_CONFIGURE=	yes

MAN3=		HTML::GenerateUtil.3

.include <bsd.port.mk>
