# Created by: Kurt Lidl (kurt.lidl@cello.com)
# $FreeBSD: www/p5-HTML-GenerateUtil/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	HTML-GenerateUtil
PORTVERSION=	1.11
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module for generating HTML on the fly

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
