# Created by: Kurt Lidl (kurt.lidl@cello.com)
# $FreeBSD: www/p5-HTML-GenerateUtil/Makefile 333099 2013-11-07 13:55:25Z vanilla $

PORTNAME=	HTML-GenerateUtil
PORTVERSION=	1.11
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module for generating HTML on the fly

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
