# Created by: Gvozdikov Veniamin <g.veniamin@googlemail.com>
# $FreeBSD: devel/libpo6/Makefile 314640 2013-03-19 13:04:30Z eadler $

PORTNAME=	libpo6
PORTVERSION=	0.2.3
CATEGORIES=	devel
MASTER_SITES=	http://hyperdex.org/src/

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	POSIX wrappers for C++

LICENSE=	BSD

GNU_CONFIGURE=	yes
USES=	pathfix

.include <bsd.port.mk>
