# $FreeBSD: www/rubygem-acts-as-taggable-on/Makefile 340905 2014-01-24 14:55:44Z miwi $

PORTNAME=	acts-as-taggable-on
PORTVERSION=	2.4.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Tag a single model on several contexts

RUN_DEPENDS=	rubygem-rails>=3.0:${PORTSDIR}/www/rubygem-rails

USE_RUBY=	YES
USE_RUBYGEMS=	YES
RUBYGEM_AUTOPLIST=	YES

.include <bsd.port.mk>
