# New ports collection makefile for:	php5-phar
# Date created:			25 Nov 2011
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/archivers/php5-phar/Makefile,v 1.4 2012/11/17 05:54:22 svnexp Exp $
#

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-phar

.include "${MASTERDIR}/Makefile"
