# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: archivers/php5-phar/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-phar

.include "${MASTERDIR}/Makefile"
