# $FreeBSD: www/rubygem-journey/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	journey
PORTVERSION=	1.0.4
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	It routes requests.

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
