# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: sysutils/php5-posix/Makefile 332107 2013-10-30 13:32:02Z ale $

CATEGORIES=	sysutils

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-posix

.include "${MASTERDIR}/Makefile"
