# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: sysutils/php5-posix/Makefile 327772 2013-09-20 23:05:58Z bapt $

CATEGORIES=	sysutils

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-posix

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
