# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: head/math/fftw3-float/Makefile 431709 2017-01-16 23:10:15Z jhale $

COMMENT=	Fast Discrete Fourier Transform (Single Precision C Routines)

FFTW3_FLAVOR=	float
MASTERDIR=	${.CURDIR}/../../math/fftw3

.include "${MASTERDIR}/Makefile"
