# New ports collection makefile for:	fftw3-float
# Date created:		2004-09-01
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD: ports/math/fftw3-float/Makefile,v 1.11 2012/11/17 05:59:20 svnexp Exp $
#    $MCom: ports-experimental/math/fftw3-float/Makefile,v 1.1 2006/03/28 00:08:57 ahze Exp $

COMMENT=	Fast Discrete Fourier Transform (Single Precision C Routines)

FFTW3_FLAVOR=	float
MASTERDIR=	${.CURDIR}/../../math/fftw3

.include "${MASTERDIR}/Makefile"
