# Ports collection makefile for:	rubygem-loofah
# Date created:				29 May 2010
# Whom:					Eric Freeman <freebsdports@chillibear.com>
#
# $FreeBSD: ports/textproc/rubygem-loofah/Makefile,v 1.6 2012/11/17 06:02:20 svnexp Exp $
#

PORTNAME=	loofah
PORTVERSION=	1.2.1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	freebsdports@chillibear.com
COMMENT=	 Library for manipulating HTML/XML documents and fragments

RUN_DEPENDS=	rubygem-nokogiri>=1.4.4:${PORTSDIR}/textproc/rubygem-nokogiri

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
