# $FreeBSD: graphics/gstreamer1-plugins-opencv/Makefile 327733 2013-09-20 18:35:44Z bapt $

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	Gstreamer opencv real time computer vision plugin

GST_PLUGIN=	opencv
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
