# Created by: Martin Matuska <martin@matuska.org>
# $FreeBSD: databases/luasql-sqlite3/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	luasql

LUASQL_DRIVER=	sqlite3

MASTERDIR=      ${.CURDIR}/../luasql-mysql

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
