# Created by: Jacob Atzen <jatzen@gmail.com>
# $FreeBSD: devel/rubygem-daemon_controller/Makefile 336454 2013-12-14 15:46:25Z osa $

PORTNAME=	daemon_controller
PORTVERSION=	1.1.8
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMEPREFIX=	rubygem-

MAINTAINER=	osa@FreeBSD.org
COMMENT=	A library for implementing daemon management capabilities

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
