# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: misc/p5-Array-PrintCols/Makefile 324054 2013-07-31 14:36:21Z az $

PORTNAME=	Array-PrintCols
PORTVERSION=	2.5
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to print arrays of elements in sorted columns

USES=		perl5
USE_PERL5=	configure

MAN3=		Array::PrintCols.3

.include <bsd.port.mk>
