# Created by: Palle Girgensohn <girgen@pingpong.net>
# $FreeBSD: databases/postgresql92-docs/Makefile 340722 2014-01-22 17:00:46Z mat $

WANT_PGSQL_VER=92
COMPONENT=	-docs

NO_STAGE=	yes
.include "${.CURDIR}/../postgresql91-docs/Makefile"
