# New ports collection makefile for:	Class-StrongSingleton
# Date created:	   22 February 2008
# Whom:		   Sergey Skvortsov <skv@protey.ru>
#
# $FreeBSD: ports/devel/p5-Class-StrongSingleton/Makefile,v 1.4 2012/11/17 05:56:08 svnexp Exp $
#

PORTNAME=	Class-StrongSingleton
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	A stronger and more secure Singleton base class

PERL_CONFIGURE=	yes

MAN3=		Class::StrongSingleton.3

.include <bsd.port.mk>
