# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-Class-StrongSingleton/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Class-StrongSingleton
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Stronger and more secure Singleton base class

USES=		perl5
USE_PERL5=	configure

MAN3=		Class::StrongSingleton.3

.include <bsd.port.mk>
