# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: textproc/uz-aspell/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-uz-0.6-0
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Uzbek dictionary

DICT=	 	uz

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
