# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: ports/textproc/hs-stringsearch/Makefile,v 1.18 2013/02/05 22:47:14 svnexp Exp $

PORTNAME=	stringsearch
PORTVERSION=	0.3.6.4
PORTREVISION=	1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast searching, splitting and replacing of ByteStrings

LICENSE=	BSD
FILE_LICENSE=	LICENCE

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
