# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: textproc/hs-stringsearch/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	stringsearch
PORTVERSION=	0.3.6.4
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast searching, splitting and replacing of ByteStrings

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
