# Created by: Alex Keda <admin@lissyara.su>
# $FreeBSD: security/php52-mcrypt/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-mcrypt

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
