# New ports collection makefile for:	php52-mcrypt
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/security/php52-mcrypt/Makefile,v 1.2 2012/11/17 06:01:15 svnexp Exp $
#

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-mcrypt

.include "${MASTERDIR}/Makefile"
