# $FreeBSD: x11/liboldX/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	liboldX
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Old X library

XORG_CAT=	lib
USE_XORG=	x11
USE_AUTOTOOLS=	libtool

.include <bsd.port.mk>
