# Created by: Greg Larkin <glarkin@FreeBSD.org>
# $FreeBSD: devel/p5-Data-HashArray/Makefile 341711 2014-01-29 10:57:06Z az $

PORTNAME=	Data-HashArray
PORTVERSION=	1.0
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Array class of hashes with properties via overloading and AUTOLOAD

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
