# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD: finance/R-cran-timeSeries/Makefile 335044 2013-11-27 18:56:43Z dbn $

PORTNAME=	timeSeries
PORTVERSION=	3010.97
PORTREVISION=	3
CATEGORIES=	finance
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	Financial Time Series Objects

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-cran-timeDate>=2150.95:${PORTSDIR}/finance/R-cran-timeDate

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
