# New ports collection makefile for:	php52-pspell
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/textproc/php52-pspell/Makefile,v 1.2 2012/11/17 06:02:16 svnexp Exp $
#

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-pspell

.include "${MASTERDIR}/Makefile"
