# ex:ts=8
# Ports collection makefile for:	Regexp::Bind
# Date created:			Jun 5, 2006
# Whom:				ijliao
#
# $FreeBSD: ports/devel/p5-Regexp-Bind/Makefile,v 1.5 2012/11/17 05:56:27 svnexp Exp $
#

PORTNAME=	Regexp-Bind
PORTVERSION=	0.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Bind variables to captured buffers

PERL_CONFIGURE=	yes

MAN3=	Regexp::Bind.3

.include <bsd.port.mk>
