# ex:ts=8
# Ports collection makefile for:	Regexp::Bind
# Created by: ijliao
# $FreeBSD: devel/p5-Regexp-Bind/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Regexp-Bind
PORTVERSION=	0.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Bind variables to captured buffers

USES=		perl5
USE_PERL5=	configure

MAN3=	Regexp::Bind.3

.include <bsd.port.mk>
