# Created by: ijliao
# $FreeBSD: devel/p5-Regexp-Bind/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Regexp-Bind
PORTVERSION=	0.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Bind variables to captured buffers

USES=		perl5
USE_PERL5=	configure

MAN3=	Regexp::Bind.3

NO_STAGE=	yes
.include <bsd.port.mk>
