--- Makefile.orig	2013-03-23 23:26:22.195031000 +0000
+++ Makefile
@@ -6,7 +6,7 @@
 #
 
 PORTNAME=	net
-PORTVERSION=	3.5.1
+PORTVERSION=	3.6.3
 CATEGORIES=	www
 MASTER_SITES=	http://download.camlcity.org/download/
 PKGNAMEPREFIX=	ocaml-
@@ -16,7 +16,7 @@ MAINTAINER=	jaapb@kerguelen.org
 COMMENT=	OCaml modules for Internet applications
 
 BUILD_DEPENDS=	${SA_DIR}/pcre/pcre.a:${PORTSDIR}/devel/ocaml-pcre
-RUN_DEPENDS:=	${BUILD_DEPENDS}
+RUN_DEPENDS=	${BUILD_DEPENDS}
 
 CONFLICTS=	ocaml-equeue-2* ocaml-netclient-0*
 
@@ -43,6 +43,7 @@ PORTEXAMPLES=	*
 OCAML_PKGDIRS=	netsys netshm equeue shell netstring rpc-generator \
 		rpc pop smtp netclient netcgi2 netgssapi netplex \
 		netcgi2-plex netcamlbox netmulticore rpc-auth-local
+OCAML_PKGDIRS+= netstring-pcre
 OCAML_LDLIBS=	${OCAML_PKGDIRS:S/^/${OCAML_SITELIBDIR}\//}
 
 OPTIONS=	SSL "Enable SSL support" ON \
@@ -53,7 +54,7 @@ OPTIONS=	SSL "Enable SSL support" ON \
 		ZIP "Enable compression support" OFF \
 		SCRAM "Enable SCRAM support" OFF
 
-CONFIGURE_ARGS+=	-disable-gtk
+CONFIGURE_ARGS+=	-disable-gtk -enable-pcre
 
 .include <bsd.port.options.mk>
 
