# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/databases/p5-Cache-Memcached-Fast/Makefile 341626 2014-01-28 16:46:12Z miwi $

PORTNAME=	Cache-Memcached-Fast
PORTVERSION=	0.21
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Fast Perl client for memcached, a distributed memory cache daemon

USES=		perl5
USE_PERL5=	configure
MAKE_JOBS_UNSAFE=	yes

.include <bsd.port.mk>
