# Created by: Leo Kim <leo@florida.sarang.net>
# $FreeBSD: audio/p5-MP3-Info/Makefile 326958 2013-09-11 09:54:08Z az $

PORTNAME=	MP3-Info
PORTVERSION=	1.24
CATEGORIES=	audio perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Manipulate / fetch info from MP3 audio files

USES=		perl5
USE_PERL5=	configure

MAN3=		MP3::Info.3

.include <bsd.port.mk>
