# New ports collection makefile for:	devel/p5-Lingua-JA-Fold
# Date created:				07 November 2007
# Whom:					Lars Thegler <lth@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Lingua-JA-Fold/Makefile,v 1.4 2012/11/17 05:56:20 svnexp Exp $
#

PORTNAME=	Lingua-JA-Fold
PORTVERSION=	0.08
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Lingua
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lingua::JA::Fold - fold a Japanese text

PERL_CONFIGURE=	yes

MAN3=	Lingua::JA::Fold.3

.include <bsd.port.mk>
