# $FreeBSD: x11-fonts/xlsfonts/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xlsfonts
PORTVERSION=	1.0.4
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Server font list displayer for X

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xlsfonts man/man1/xlsfonts.1.gz

.include <bsd.port.mk>
