# Ports collection makefile for:  pear-Horde_Argv
# Date created:			  6 July 2011
# Whom:				  Martin Matuska <mm@FreeBSD.org>
#
# $FreeBSD: ports/devel/pear-Horde_Argv/Makefile,v 1.6 2012/12/12 15:19:47 svnexp Exp $

PORTNAME=	Horde_Argv
PORTVERSION=	2.0.2
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde command-line argument parsing package

USE_HORDE_RUN=	Horde_Exception Horde_Translation

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
