# Created by: Pawel Worach
# $FreeBSD: x11-fonts/font-bitstream-type1/Makefile 336621 2013-12-16 11:11:09Z zeising $

PORTNAME=	font-bitstream-type1
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Bitstream Vera Type1 font

XORG_CAT=	font

.include <bsd.port.mk>
