# New ports collection makefile for:    fr-aspell
# Date created:                         15 January 2002
# Whom:                                 Thierry Thomas <thierry@pompo.net>
#
# $FreeBSD: ports/french/aspell/Makefile,v 1.8 2012/11/17 05:57:28 svnexp Exp $
#

PORTNAME=	aspell
DISTVERSION=	-fr-0.50-3
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	french textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell French dictionaries

DICT=	 	fr

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
