# $FreeBSD: databases/php53-dba/Makefile 327717 2013-09-20 16:13:47Z bapt $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php53

PKGNAMESUFFIX=	-dba

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
