# $FreeBSD: devel/pear-Horde_View/Makefile 333263 2013-11-08 21:41:53Z antoine $

PORTNAME=	Horde_View
PORTVERSION=	2.0.3
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde View API

USE_HORDE_RUN=	Horde_Exception \
		Horde_Support \
		Horde_Util

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
