# $FreeBSD: textproc/rubygem-rttool/Makefile 320427 2013-06-10 01:21:22Z swills $

PORTNAME=	rttool
PORTVERSION=	1.0.3.0
CATEGORIES=	textproc ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	RT into HTML and plain text converter

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/rdrt2 bin/rt2

.include <bsd.port.mk>
