# New ports collection makefile for:	gtksourceview-reference
# Date created:				09 May 2006
# Whom:					Jean-Yves Lefort <jylefort@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/gtksourceview2-reference/Makefile,v 1.2 2012/11/17 06:03:35 svnexp Exp $
#   $MCom: ports/x11-toolkits/gtksourceview2-reference/Makefile,v 1.1 2007/06/25 20:59:01 mezz Exp $
#

PORTREVISION=	0

.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
