# $FreeBSD: graphics/gstreamer1-plugins-cairo/Makefile 327733 2013-09-20 18:35:44Z bapt $

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	Gstreamer vector graphics plugin

GST_PLUGIN=	cairo
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
