# Created by: Brian Skrab <brian@quynh-and-brian.org>
# $FreeBSD: devel/p5-Class-Hook/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=		Class-Hook
PORTVERSION=		0.03
CATEGORIES=		devel perl5
MASTER_SITES=		CPAN
PKGNAMEPREFIX=		p5-

MAINTAINER=		perl@FreeBSD.org
COMMENT=		Add hooks on methods from other classes

USES=		perl5
USE_PERL5=	configure

MAN3=			Class::Hook.3

.include <bsd.port.mk>
