# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-Env-Path/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Env-Path
PORTVERSION=	0.19
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Advanced operations on path variables

USES=		perl5
USE_PERL5=	configure

MAN1=		envpath.1
MAN3=		Env::Path.3

NO_STAGE=	yes
.include <bsd.port.mk>
