# Created by: Cy Schubert <Cy.Schubert@uumail.gov.bc.ca>
# $FreeBSD: x11/xcut/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xcut
PORTVERSION=	0.2
PORTREVISION=	3
CATEGORIES=	x11
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}-src/${PORTVERSION} \
		http://acsys.anu.edu.au/~tpot/%SUBDIR%/


MAINTAINER=	cy@FreeBSD.org
COMMENT=	Manipulate X cut buffers from the commandline

USES=		imake
USE_XORG=	x11
PLIST_FILES=	bin/xcut man/man1/xcut.1.gz

.include <bsd.port.mk>
