# Created by: jmz
# $FreeBSD: comms/viewfax/Makefile 321975 2013-06-28 18:37:20Z bapt $

PORTNAME=	viewfax
PORTVERSION=	2.6
PORTREVISION=	1
CATEGORIES=	comms
MASTER_SITES=	ftp://ftp.ping.de/pub/unix/ \
		ftp://ftp.leo.org/historic/comp/os/unix/networking/mgetty/

MAINTAINER=	dhn@FreeBSD.org
COMMENT=	Display files containing g3 and/or g4 coded fax pages

USES=		imake
USE_XORG=	x11 xext

PLIST_FILES=	bin/viewfax lib/viewfax.tif

MAN1=		viewfax.1

.include <bsd.port.mk>
