# Created by: mig
# $FreeBSD: head/devel/p5-Config-Simple/Makefile 331856 2013-10-28 13:46:25Z vanilla $

PORTNAME=	Config-Simple
PORTVERSION=	4.59
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN/Config/SHERZODR
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Simple configuration file class

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
