# $FreeBSD: x11-wm/twm/Makefile 327786 2013-09-21 00:01:16Z bapt $

PORTNAME=	twm
PORTVERSION=	1.0.8
CATEGORIES=	x11-wm

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Tab Window Manager for the X Window System

XORG_CAT=	app
USE_XORG=	x11 xext xt xmu

MAN1=		twm.1

NO_STAGE=	yes
.include <bsd.port.mk>
