# $FreeBSD: vietnamese/kde4-l10n/Makefile 322618 2013-07-10 06:33:41Z bapt $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
CATEGORIES=	vietnamese kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Vietnamese messages and documentation for KDE SC 4

KDE4_L10N=	vi

.include "${.CURDIR}/../../misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
