# $FreeBSD: vietnamese/kde4-l10n/Makefile 327775 2013-09-20 23:20:31Z bapt $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
CATEGORIES=	vietnamese kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Vietnamese messages and documentation for KDE SC 4

KDE4_L10N=	vi

NO_STAGE=	yes
.include "${.CURDIR}/../../misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
