# New ports collection makefile for:	Devel-Pointer
# Date created:	   19 January 2004
# Whom:		   Sergey Skvortsov <skv@protey.ru>
#
# $FreeBSD: ports/devel/p5-Devel-Pointer/Makefile,v 1.6 2012/11/17 05:56:14 svnexp Exp $
#

PORTNAME=	Devel-Pointer
PORTVERSION=	1.00
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Fiddle around with pointers

PERL_CONFIGURE=	yes

MAN3=		Devel::Pointer.3

.include <bsd.port.mk>
