# $FreeBSD: devel/hs-parallel/Makefile 327723 2013-09-20 17:04:43Z bapt $

PORTNAME=	parallel
PORTVERSION=	3.2.0.3
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parallel programming library

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
