# $FreeBSD: databases/php53-mssql/Makefile 327717 2013-09-20 16:13:47Z bapt $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php53

PKGNAMESUFFIX=	-mssql

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
