# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: dns/p5-Net-Domain-TLD/Makefile 341765 2014-01-29 17:46:33Z az $

PORTNAME=	Net-Domain-TLD
PORTVERSION=	1.70
CATEGORIES=	dns perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Look up and validate TLDs

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
