# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: security/php55-mcrypt/Makefile 321684 2013-06-24 14:32:11Z ale $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-mcrypt

.include "${MASTERDIR}/Makefile"
