# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: math/R-cran-deldir/Makefile 319316 2013-05-28 15:15:05Z bf $

PORTNAME=	deldir
DISTVERSION=	0.0-22
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Delaunay Triangulation and Dirichlet (Voronoi) Tessellation

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
