# Created by: Bill Brinzer <bill.brinzer@gmail.com>
# $FreeBSD: devel/p5-Capture-Tiny/Makefile 316517 2013-04-25 14:07:35Z culot $

PORTNAME=	Capture-Tiny
PORTVERSION=	0.22
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DAGOLDEN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bill.brinzer@gmail.com
COMMENT=	Capture STDOUT and STDERR from Perl, XS, or external programs

LICENSE=	AL2

PERL_CONFIGURE=	yes

MAN3=		Capture::Tiny.3

.include <bsd.port.mk>
