# Created by: Bill Brinzer <bill.brinzer@gmail.com>
# $FreeBSD: devel/p5-Capture-Tiny/Makefile 338168 2013-12-30 20:55:18Z ohauer $

PORTNAME=	Capture-Tiny
PORTVERSION=	0.23
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DAGOLDEN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bill.brinzer@gmail.com
COMMENT=	Capture STDOUT and STDERR from Perl, XS, or external programs

LICENSE=	APACHE20

TEST_DEPENDS=	p5-Inline>=0:${PORTSDIR}/devel/p5-Inline

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
