# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-ExtUtils-Depends/Makefile 326644 2013-09-07 15:51:29Z az $

PORTNAME=	ExtUtils-Depends
PORTVERSION=	0.304
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:FLORA
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Easily build XS extensions that depend on XS extensions

USES=		perl5
USE_PERL5=	configure

MAN3=		ExtUtils::Depends.3

.include <bsd.port.mk>
