# New ports collection makefile for:	Stream
# Date created:				21 May 2006
# Whom:					Aaron Dalton <aaron@FreeBSD.org>
#
# $FreeBSD: devel/p5-Stream/Makefile 324171 2013-08-02 18:21:05Z az $
#

PORTNAME=	Stream
PORTVERSION=	1.00
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Generic stream classes for Perl

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
