# $FreeBSD: devel/hs-tagged/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	tagged
PORTVERSION=	0.6
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 phantom types to avoid unsafely passing dummy arguments

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
