# New ports collection makefile for:	php5-shmop
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/devel/php5-shmop/Makefile,v 1.2 2012/11/17 05:56:41 svnexp Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-shmop

.include "${MASTERDIR}/Makefile"
