# ex:ts=8
# Ports collection makefile for:	silvercity
# Date created:			Dec 29, 2003
# Whom:				ijliao
#
# $FreeBSD: ports/textproc/silvercity/Makefile,v 1.9 2012/11/17 06:02:21 svnexp Exp $
#

PORTNAME=	silvercity
PORTVERSION=	0.9.7
CATEGORIES=	textproc
MASTER_SITES=	SF/${PORTNAME}/Python%20SilverCity%20Bindings/${PORTVERSION}
DISTNAME=	SilverCity-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A lexing package for over 20 programming and markup languages

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_PKGNAME=	SilverCity
USE_DOS2UNIX=	yes

.include <bsd.port.mk>
