# Created by: Kojedzinszky Richard <krichy@tvnetwork.hu>
# $FreeBSD: devel/libjson++/Makefile 324744 2013-08-14 22:35:50Z ak $

PORTNAME=	libjson++
PORTVERSION=	0.4.0
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.cflinux.hu/pub/

MAINTAINER=	krichy@tvnetwork.hu
COMMENT=	Small C++ library to handle JSON serialized data

USES=		cmake
USE_LDCONFIG=	yes

.include <bsd.port.mk>
