# Created by: Kojedzinszky Richard <krichy@tvnetwork.hu>
# $FreeBSD: devel/libjson++/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	libjson++
PORTVERSION=	0.4.0
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.cflinux.hu/pub/

MAINTAINER=	krichy@tvnetwork.hu
COMMENT=	Small C++ library to handle JSON serialized data

USES=		cmake
USE_LDCONFIG=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
