# Created by: Nobutaka Mantani <nobutaka@FreeBSD.org>
# $FreeBSD: devel/p5-Parse-Win32Registry/Makefile 326868 2013-09-10 06:44:11Z az $

PORTNAME=	Parse-Win32Registry
PORTVERSION=	1.0
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	nobutaka@FreeBSD.org
COMMENT=	A Perl extension for parsing Win32Registry

LICENSE_COMB=	dual
LICENSE=	ART10 GPLv1

USES=		perl5
USE_PERL5=	configure

MAN3=	Parse::Win32Registry.3

.include <bsd.port.mk>
