# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: www/hs-url/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	url
PORTVERSION=	2.1.3
PORTREVISION=	4
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library for working with URLs

LICENSE=	BSD

USE_CABAL=	utf8-string>=0.3.4

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
