# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: ports/games/p5-Games-Dice/Makefile,v 1.6 2012/11/29 17:35:48 svnexp Exp $

PORTNAME=	Games-Dice
PORTVERSION=	0.03
CATEGORIES=	games perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module to simulate die rolls

MAN3=		Games::Dice.3

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
