# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: devel/p5-Test-TinyMocker/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Test-TinyMocker
PORTVERSION=	0.03
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Very simple tool to mock external modules

USES=		perl5
USE_PERL5=	configure

MAN3=		Test::TinyMocker.3

.include <bsd.port.mk>
