# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: devel/rubygem-drydock/Makefile 331721 2013-10-26 17:01:45Z sunpoet $

PORTNAME=	drydock
PORTVERSION=	0.6.9
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Build seaworthy command-line apps with a powerful Ruby DSL

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
