# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: devel/p5-Test-TableDriven/Makefile 325163 2013-08-21 17:42:57Z sunpoet $

PORTNAME=	Test-TableDriven
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Write tests, not scripts that run them

USE_PERL5=	configure
USES=		perl5

MAN3=		Test::TableDriven.3

.include <bsd.port.mk>
