# Created by: Zane C, Bowers <vvelox@vvelox.net>
# $FreeBSD: net/p5-ZConf-Bookmarks/Makefile 338849 2014-01-06 09:14:19Z az $

PORTNAME=	ZConf-Bookmarks
PORTVERSION=	0.2.4
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:VVELOX
PKGNAMEPREFIX=	p5-

MAINTAINER=	vvelox@vvelox.net
COMMENT=	System for bookmarking URIs using ZConf

RUN_DEPENDS=	p5-ZConf>=0:${PORTSDIR}/net/p5-ZConf

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
