# $FreeBSD: devel/hs-abstract-par/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	abstract-par
PORTVERSION=	0.3.1
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type classes generalizing the functionality of the 'monad-par' library

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
