#!/bin/sh

# $FreeBSD: vietnamese/vntex/pkg-deinstall 300897 2012-07-14 14:29:18Z beat $

if [ "$2" != "DEINSTALL" ]; then
  exit 0
fi

PATH=/bin:/usr/sbin:${PKG_PREFIX}/bin

texconfig rehash

exit 0
