--- pyproject.toml.orig	2025-03-15 15:08:08 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@ requires = [
 [build-system]
 requires = [
-    "setuptools>=67.4",
+    "setuptools>=61",
     "wheel"
 ]
 build-backend = "setuptools.build_meta"
