# Created by: <mbowie@buzmo.com>
# $FreeBSD: finance/php-tclink/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	tclink
PORTVERSION=	3.4.4
CATEGORIES=	finance
MASTER_SITES=	http://www.trustcommerce.com/downloads/
PKGNAMEPREFIX=	php-
DISTNAME=	${PORTNAME}-${PORTVERSION}-php

MAINTAINER=	mbowie@buzmo.com
COMMENT=	A PHP extension for TrustCommerce credit card processing

USE_PHP=	yes
USE_PHPEXT=	yes
USE_OPENSSL=	yes
DEFAULT_PHP_VER=53

NO_STAGE=	yes
.include <bsd.port.mk>
