# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: misc/p5-Locale-SubCountry/Makefile 327745 2013-09-20 20:50:57Z bapt $

PORTNAME=	Locale-SubCountry
PORTVERSION=	1.62
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Convert state, province, county etc. names to/from code

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

MAN3=	Locale::SubCountry.3 \
	Locale::SubCountry::Data.3

NO_STAGE=	yes
.include <bsd.port.mk>
