# Created by: Akinori MUSHA aka knu <knu@idaemons.org>
# $FreeBSD: security/rubygem-hmac/Makefile 332049 2013-10-30 02:56:33Z swills $

PORTNAME=	hmac
PORTVERSION=	0.4.0
CATEGORIES=	security ruby
MASTER_SITES=	RG
DISTNAME=	ruby-${PORTNAME}-${PORTVERSION}

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A Ruby library which implements the HMAC algorithm

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
GEM_NAME=	${DISTNAME}

.include <bsd.port.mk>
