# New ports collection makefile for:	ruby-hmac
# Date created:		20 February 2002
# Whom:			Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/security/rubygem-hmac/Makefile,v 1.2 2012/11/17 06:01:19 svnexp Exp $
#

PORTNAME=	hmac
PORTVERSION=	0.4.0
CATEGORIES=	security ruby
MASTER_SITES=	RG
DISTNAME=	ruby-${PORTNAME}-${PORTVERSION}

MAINTAINER=	ruby@freebsd.org
COMMENT=	A Ruby library which implements the HMAC algorithm

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
GEM_NAME=	${DISTNAME}

.include <bsd.port.mk>
