# New ports collection makefile for:	ocaml-nox11
# Date created:		2004-02-03
# Whom:			Eugene Ossintsev
#
# $FreeBSD: ports/lang/ocaml-nox11/Makefile,v 1.6 2012/11/17 05:58:53 svnexp Exp $
#

PORTNAME=	ocaml-nox11
CATEGORIES=	lang

MAINTAINER=	michael.grunewald@laposte.net
COMMENT=	Objective Caml compiler and programming environment (no X11)

MASTERDIR=	${.CURDIR}/../ocaml

CONFLICTS=	metaocaml-[0-9]* ocaml-[0-9]* ocaml-notk-[0-9]*

WITHOUT_X11=	yes

.include "${MASTERDIR}/Makefile"
