# $FreeBSD: devel/hs-murmur-hash/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	murmur-hash
PORTVERSION=	0.1.0.6
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	MurmurHash2 implementation for Haskell

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
