# $FreeBSD: audio/gstreamer1-plugins-jack/Makefile 332416 2013-11-01 22:14:07Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer low-latency audio server plugin

GST_PLUGIN=	jack
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
