# $FreeBSD: audio/gstreamer1-plugins-jack/Makefile 316693 2013-04-27 20:56:38Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer low-latency audio server plugin

GST_PLUGIN=	jack
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
