# $FreeBSD: ports/devel/hs-transformers-base/Makefile,v 1.6 2013/02/05 22:47:09 svnexp Exp $

PORTNAME=	transformers-base
PORTVERSION=	0.4.1
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lift computations from the bottom of a transformer stack

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
