# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: net-mgmt/p5-Net-IP-Match-XS/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	Net-IP-Match-XS
PORTVERSION=	0.03
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Efficiently match IP addresses against IP ranges

USES=		perl5
USE_PERL5=	configure

MAN3=	Net::IP::Match::XS.3

.include <bsd.port.mk>
