# New ports collection makefile for:	xf86-video-rendition
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-rendition/Makefile,v 1.14 2012/11/17 06:03:25 svnexp Exp $
#

PORTNAME=	xf86-video-rendition
PORTVERSION=	4.2.4
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org rendition display driver

XORG_CAT=	driver
USE_XORG=	xextproto videoproto
MAN4=		rendition.4x

.include <bsd.port.mk>
