# $FreeBSD: multimedia/gstreamer1-plugins-mpeg2dec/Makefile 316693 2013-04-27 20:56:38Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer mpeg decode plugin

GST_PLUGIN=	mpeg2dec
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
