# Created by: Oliver Eikemeier <eikemeier@fillmore-labs.com>
# $FreeBSD: mail/exim-doc-info/Makefile 327742 2013-09-20 19:59:12Z bapt $

DOCFORMAT=	info
DISTDOCFORMAT=	texinfo
MASTERDIR=	${.CURDIR}/../exim-doc-html

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
