# Created by: Maxim Sobolev <sobomax@FreeBSD.org>
# $FreeBSD: finance/p5-Business-OCV/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Business-OCV
PORTVERSION=	0.1
CATEGORIES=	finance perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:BENL
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Interface to the Ingenico OCV Server

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
