# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/xf86dgaproto/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xf86dgaproto
PORTVERSION=	2.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XFree86-DGA extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
