# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: net/rubygem-dropbox-sdk/Makefile 331721 2013-10-26 17:01:45Z sunpoet $

PORTNAME=	dropbox-sdk
PORTVERSION=	1.6.2
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Library of the Dropbox API web endpoints

LICENSE=	MIT

RUN_DEPENDS=	rubygem-json>=0:${PORTSDIR}/devel/rubygem-json

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
