# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: misc/php55-calendar/Makefile 321684 2013-06-24 14:32:11Z ale $

CATEGORIES=	misc

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-calendar

.include "${MASTERDIR}/Makefile"
