# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/p5-CPAN-Perl-Releases/Makefile 334481 2013-11-21 13:01:51Z culot $

PORTNAME=	CPAN-Perl-Releases
PORTVERSION=	1.48
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Map Perl releases to the location of the tarballs

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
