# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: ports/devel/p5-CPAN-Perl-Releases/Makefile,v 1.17 2012/11/27 14:33:05 svnexp Exp $

PORTNAME=	CPAN-Perl-Releases
PORTVERSION=	0.90
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for mapping Perl releases to the location of the tarballs

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		CPAN::Perl::Releases.3

.include <bsd.port.mk>
