# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/p5-CPAN-Perl-Releases/Makefile 321723 2013-06-25 06:42:05Z culot $

PORTNAME=	CPAN-Perl-Releases
PORTVERSION=	1.24
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Map Perl releases to the location of the tarballs

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		CPAN::Perl::Releases.3

.include <bsd.port.mk>
