Obtained from:	https://github.com/python-poetry/cleo/commit/57c6b9ee79164c099aed385413566ac3f3d2af4e

--- pyproject.toml.orig	2022-11-22 23:29:56 UTC
+++ pyproject.toml
@@ -33,7 +33,7 @@ classifiers = [
 [tool.poetry.dependencies]
 python = "^3.7"
 crashtest = "^0.4.1"
-rapidfuzz = "^2.2.0"
+rapidfuzz = "^3.0.0"
 
 [tool.poetry.group.dev.dependencies]
 pytest = "^7.1.2"
