# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: databases/php5-mysql/Makefile 332107 2013-10-30 13:32:02Z ale $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-mysql

.include "${MASTERDIR}/Makefile"
