# New ports collection makefile for:	php5-zlib
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/archivers/php5-zlib/Makefile,v 1.4 2012/11/17 05:54:23 svnexp Exp $
#

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-zlib

.include "${MASTERDIR}/Makefile"
