# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: math/p5-Statistics-ChiSquare/Makefile 341829 2014-01-30 10:27:43Z az $

PORTNAME=	Statistics-ChiSquare
PORTVERSION=	0.6
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	How random is your data?

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
