# Created by: chinsan <chinsan.tw@gmail.com>
# $FreeBSD: textproc/p5-Text-Emoticon-GoogleTalk/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Text-Emoticon-GoogleTalk
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Emoticon filter of GoogleTalk

BUILD_DEPENDS=	p5-Text-Emoticon>=0:${PORTSDIR}/textproc/p5-Text-Emoticon
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
