# Created by: Nick Sayer <nsayer@FreeBSD.org>
# $FreeBSD: comms/p5-Device-SerialPort/Makefile 315509 2013-03-29 00:44:53Z eadler $

PORTNAME=	Device-SerialPort
PORTVERSION=	1.040000
CATEGORIES=	comms perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:C/0+$//}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module for simple serial port control

PERL_CONFIGURE=	yes

MAN1=		modemtest.1
MAN3=		Device::SerialPort.3

.include <bsd.port.mk>
