# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: ftp/php55-curl/Makefile 327729 2013-09-20 17:23:18Z bapt $

CATEGORIES=	ftp

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-curl

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
