# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: ftp/php55-curl/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	ftp

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-curl

.include "${MASTERDIR}/Makefile"
