# ex:ts=8
# Ports collection makefile for:	taggable
# Date created:			Apr 22, 2007
# Whom:				ijliao
#
# $FreeBSD: ports/www/rubygem-taggable/Makefile,v 1.7 2012/11/17 06:03:05 svnexp Exp $
#

PORTNAME=	taggable
PORTVERSION=	2.0.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG
DISTNAME=	acts_as_taggable-${PORTVERSION}

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Add tagging capabilities to your ActiveRecord objects

GEM_NAME=	${DISTNAME}

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
