# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: databases/php5-pgsql/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-pgsql

.include "${MASTERDIR}/Makefile"
