# Created by: niels <niels@FreeBSD.org>
# $FreeBSD: www/rubygem-robots/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	robots
PORTVERSION=	0.10.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Simple library to parse robots.txt files

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
