# Created by: tobez@FreeBSD.org
# $FreeBSD: devel/p5-IO-NestedCapture/Makefile 332028 2013-10-30 01:38:24Z vanilla $

PORTNAME=	IO-NestedCapture
PORTVERSION=	1.03
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for performing nested STD\* handle captures

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
