--- binder/environment.yml.orig	2022-11-04 20:45:25 UTC
+++ binder/environment.yml
@@ -31,12 +31,12 @@ dependencies:
 - pyqt <5.16
 - pyqtwebengine <5.16
 - python-lsp-black >=1.2.0
-- python-lsp-server >=1.6.0,<1.7.0
+- python-lsp-server >0
 - pyxdg >=0.26
 - pyzmq >=22.1.0
-- qdarkstyle >=3.0.2,<3.1.0
+- qdarkstyle >=3.0.2
 - qstylizer >=0.2.2
-- qtawesome >=1.2.1
+- qtawesome >0
 - qtconsole >=5.4.0,<5.5.0
 - qtpy >=2.1.0
 - rtree >=0.9.7
