--- binder/environment.yml.orig	2023-08-29 21:53:14 UTC
+++ binder/environment.yml
@@ -31,7 +31,7 @@ - python-lsp-black >=1.2.0,<3.0.0
 - pyqt <5.16
 - pyqtwebengine <5.16
 - python-lsp-black >=1.2.0,<3.0.0
-- python-lsp-server >=1.7.4,<1.8.0
+- python-lsp-server >=1.7.4
 - pyxdg >=0.26
 - pyzmq >=22.1.0
 - qdarkstyle >=3.0.2,<3.2.0
