# Created by: Kozlov Sergey <kozlov.sergey.404@gmail.com>
# $FreeBSD: textproc/py-pdfminer/Makefile 340284 2014-01-19 13:39:33Z mva $

PORTNAME=	pdfminer
PORTVERSION=	20131113
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kozlov.sergey.404@gmail.com
COMMENT=	PDF parser and analyzer

LICENSE=	MIT

USE_PYTHON=	2
USE_PYDISTUTILS=yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
