# Created by: chinsan
# $FreeBSD: devel/p5-Array-Group/Makefile 331780 2013-10-27 15:12:16Z vanilla $

PORTNAME=	Array-Group
PORTVERSION=	3.0
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:TBONE
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Convert an array into array of arrayrefs of uniform size N

USE_ZIP=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
