# Created by: chinsan
# $FreeBSD: devel/p5-Array-Group/Makefile 325048 2013-08-20 13:41:04Z mat $

PORTNAME=	Array-Group
PORTVERSION=	3.0
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:TBONE
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Convert an array into array of arrayrefs of uniform size N

USE_ZIP=	yes

MAN3=		Array::Group.3

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
