# New ports collection Makefile for:	p5-File-Remove
# Date created:				16th March 2001
# Whom: 				Justin Stanford <jus@security.za.net>
#
# $FreeBSD: ports/devel/p5-File-Remove/Makefile,v 1.25 2012/11/17 05:56:16 svnexp Exp $
#

PORTNAME=	File-Remove
PORTVERSION=	1.52
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ADAMK
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to easily removes files and directories

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		File::Remove.3

.include <bsd.port.mk>
