# New ports collection makefile for:	bmp-crossfade
# Date created:		1 January 2006
# Whom:			Andrew Pantyukhin <infofarmer@FreeBSD.org>
#
# $FreeBSD: ports/audio/bmp-crossfade/Makefile,v 1.4 2012/11/21 00:56:57 svnexp Exp $
#

APP=		bmp
LIB_DEPENDS=	beep.2:${PORTSDIR}/multimedia/beep-media-player

MASTERDIR=	${.CURDIR}/../xmms-crossfade

PORTSCOUT=	limit:^0\.3\.12

.include "${MASTERDIR}/Makefile"
