# $FreeBSD: devel/geany-plugin-geniuspaste/Makefile 327723 2013-09-20 17:04:43Z bapt $

PORTNAME=	geany-plugin-geniuspaste
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	makc@FreeBSD.org
COMMENT=	Geany plugin: ${${GEANY_PLUGIN}_DESC}

LIB_DEPENDS=	soup-2.4:${PORTSDIR}/devel/libsoup

NO_STAGE=	yes
.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
