# Created by: Sergey Skvortsov <skv@FreeBSD.org>
# $FreeBSD: textproc/p5-Pod-Constants/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	Pod-Constants
PORTVERSION=	0.16
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:SAMV
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Include constants from POD

USES=		perl5
USE_PERL5=	configure

MAN3=		Pod::Constants.3

NO_STAGE=	yes
.include <bsd.port.mk>
