# $FreeBSD: devel/hs-gio/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	gio
PORTVERSION=	0.12.4
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Binding to the GIO

LICENSE=	LGPL21

USES=		pkgconfig
USE_CABAL=	glib>=0.12.0 mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
