dfly-patch:
	${REINPLACE_CMD} -e 's/[[:<:]]isinf[[:>:]]/std::isinf/g'	\
			 -e 's/[[:<:]]isnan[[:>:]]/std::isnan/g'	\
		${WRKSRC}/src/libs/learning/policy.cpp			\
		${WRKSRC}/src/drivers/olethros/driver.cpp		\
		${WRKSRC}/src/drivers/olethros/geometry.cpp
