# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: ports/devel/pear-channel-ezc/Makefile,v 1.1 2012/12/03 13:26:07 svnexp Exp $

PORTNAME=	ezc
PORTVERSION=	20060124
CATEGORIES=	devel www pear

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	components.ez.no

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
