# Created by: UMENO Takashi
# $FreeBSD: x11-clocks/gtubeclock/Makefile 326137 2013-09-03 12:13:23Z bapt $

PORTNAME=	gtubeclock
PORTVERSION=	0.9.1
PORTREVISION=	11
CATEGORIES=	x11-clocks
MASTER_SITES=	http://www.bonnyswan.com/gtubeclock/downloads/

MAINTAINER=	umeno@rr.iij4u.or.jp
COMMENT=	A nixie tube clock for GNOME

USES=		pkgconfig
USE_XORG=	x11
GNU_CONFIGURE=	yes
USE_GNOME=	gnomeprefix gnomehack gtk20 libgnomeui

.include <bsd.port.mk>
