# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: science/R-cran-snow/Makefile 333659 2013-11-13 08:19:34Z bf $

PORTNAME=	snow
DISTVERSION=	0.3-13
PORTREVISION=	2
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Support for simple parallel computing in R

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
