# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: science/R-cran-snow/Makefile 329229 2013-10-03 21:03:28Z tota $

PORTNAME=	snow
DISTVERSION=	0.3-13
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Support for simple parallel computing in R

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
