# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: astro/p5-Astro/Makefile 315509 2013-03-29 00:44:53Z eadler $

PORTNAME=	Astro
PORTVERSION=	0.75
CATEGORIES=	astro perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Collection of useful astronomical routines in Perl

PERL_CONFIGURE=	yes

MAN3=	Astro::Time.3 \
	Astro::Misc.3 \
	Astro::Coord.3

.include <bsd.port.mk>
