# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: devel/p5-Devel-Gladiator/Makefile 319878 2013-06-04 16:55:36Z miwi $

PORTNAME=	Devel-Gladiator
PORTVERSION=	0.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Perl 5 module to walk Perls arena

PERL_CONFIGURE=	yes

MAN3=		Devel::Gladiator.3

.include <bsd.port.mk>
