# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: devel/p5-Devel-Gladiator/Makefile 338884 2014-01-06 14:40:31Z az $

PORTNAME=	Devel-Gladiator
PORTVERSION=	0.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Perl 5 module to walk Perls arena

USES=		perl5
USE_PERL5=	configure


.include <bsd.port.mk>
