# New ports collection makefile for: xlrd
# Date created:		2009-08-19
# Whom:			Dikshie
#
# $FreeBSD: ports/textproc/py-xlrd/Makefile,v 1.6 2012/11/17 06:02:18 svnexp Exp $
#

PORTNAME=	xlrd
PORTVERSION=	0.7.1
PORTREVISION=	2
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dikshie@sfc.wide.ad.jp
COMMENT=	Reading data and formatting information from Excel files

USE_PYTHON=	2.5-2.7
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
