# $FreeBSD: net/hs-sendfile/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	sendfile
PORTVERSION=	0.7.9
PORTREVISION=	3
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Portable sendfile library

LICENSE=	BSD

USE_CABAL=	network>=2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
