# $FreeBSD: net/hs-sendfile/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	sendfile
PORTVERSION=	0.7.9
PORTREVISION=	1
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Portable sendfile library

LICENSE=	BSD

USE_CABAL=	network>=2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
