# New ports collection makefile for:   xproxymanagementprotocol
# Date Created:			Jun 21 2006
# Whom:				Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xproxymanagementprotocol/Makefile,v 1.3 2012/11/17 06:03:22 svnexp Exp $
#

PORTNAME=	xproxymanagementprotocol
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Proxy Management Protocol headers

XORG_CAT=	proto

.include <bsd.port.mk>
