# $FreeBSD: x11/xproxymanagementprotocol/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xproxymanagementprotocol
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Proxy Management Protocol headers

XORG_CAT=	proto

.include <bsd.port.mk>
