# $FreeBSD: audio/gstreamer1-plugins-vorbis/Makefile 332416 2013-11-01 22:14:07Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer vorbis encoder/decoder plugin

GST_PLUGIN=	vorbis
DIST=		base

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
