# New ports collection makefile for:	p5-Tie-Cache
# Date created:				March 30th 2001
# Whom:	      				Alex Kapranoff <kapr@crosswinds.net>
#
# $FreeBSD: ports/devel/p5-Tie-Cache/Makefile,v 1.10 2012/11/17 05:56:35 svnexp Exp $
#

PORTNAME=	Tie-Cache
PORTVERSION=	0.19
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:CHAMAS
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	LRU Cache in Memory through a tie interface

INSTALL_TARGET=	pure_install
PERL_CONFIGURE=	yes

MAN3=		Tie::Cache.3

.include <bsd.port.mk>
