# Created by: Jesse McConnell <jesse@gallup.com>
# $FreeBSD: head/devel/p5-Log-Agent/Makefile 332046 2013-10-30 02:52:46Z vanilla $

PORTNAME=	Log-Agent
PORTVERSION=	1.000
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Set of Perl modules that allows you to enhance logging capabilities

LICENSE=	ART20

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
