# Created by: Peter van Heusden <pvh@egenetics.com>
# $FreeBSD: lang/p5-Error/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Error
PORTVERSION=	0.17020
CATEGORIES=	lang perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to provide Error/exception support for perl: Error

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		Error.3 Error::Simple.3

.include <bsd.port.mk>
