# Created by: Rouslan Iskhakov <rouslan@rshell.net>
# $FreeBSD: devel/p5-IPC-Signal/Makefile 326784 2013-09-09 08:21:32Z az $

PORTNAME=	IPC-Signal
PORTVERSION=	1.00
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	rouslan@rshell.net
COMMENT=	IPC::Signal - Utility functions dealing with signals

USES=		perl5
USE_PERL5=	configure

MAN3=		IPC::Signal.3

.include <bsd.port.mk>
