# Created by: Dmitry Sivachenko <dima@Chg.RU>
# $FreeBSD: www/p5-HTML-Summary/Makefile 338763 2014-01-05 13:05:56Z az $

PORTNAME=	HTML-Summary
PORTVERSION=	0.017
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Produces summaries from the textual content of web pages

BUILD_DEPENDS=	p5-HTML-Tree>=0:${PORTSDIR}/www/p5-HTML-Tree

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
