# Created by: Stefan Bethke <stb@lassitu.de>
# $FreeBSD: mail/squirrelmail-login_auth-plugin/Makefile 321853 2013-06-27 06:48:43Z bapt $

PORTNAME=		login_auth
PORTVERSION=		3.0
MASTER_SITES=		http://www.squirrelmail.org/plugins/ \
			http://www.transit.hanse.de/mirror/www.squirrelmail.org/plugins/
DISTNAME=		${PORTNAME}-${PORTVERSION}-1.4.0
DIST_SUBDIR=		squirrelmail

MAINTAINER=		stb@lassitu.de
COMMENT=		Automatically log in user based on HTTP authentication

SQUIRREL_PLUGIN_NAME=	${PORTNAME}

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
