# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: devel/pecl-uri_template/Makefile 332883 2013-11-05 17:58:34Z antoine $

PORTNAME=	uri_template
PORTVERSION=	1.0
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
EXTRACT_SUFX=	.tgz
DIST_SUBDIR=	PECL

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	URI Template(RFC6570) library for PHP

LICENSE=	PHP301

USE_PHP=	yes
USE_PHPEXT=	yes

.include <bsd.port.mk>
