# $FreeBSD: net/hs-network/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	network
PORTVERSION=	2.4.1.2
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Low-level networking interface

LICENSE=	BSD

USE_CABAL=	parsec>=3.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
