# Created by: Patrick Li <pat@databits.net>
# $FreeBSD: security/knocker/Makefile 315566 2013-03-29 19:33:41Z cs $
#

PORTNAME=	knocker
PORTVERSION=	0.7.1
CATEGORIES=	security net
MASTER_SITES=	SF

MAINTAINER=	sbz@FreeBSD.org
COMMENT=	Simple and easy to use TCP only port scanner (Console version)

GNU_CONFIGURE=	yes

MAN1=		${PORTNAME}.1
PLIST_FILES=	bin/knocker

.include <bsd.port.mk>
