# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: misc/p5-File-Sort/Makefile 327745 2013-09-20 20:50:57Z bapt $

PORTNAME=		File-Sort
PORTVERSION=		1.01
CATEGORIES=		misc perl5
MASTER_SITES=		CPAN
PKGNAMEPREFIX=		p5-

MAINTAINER=		ports@FreeBSD.org
COMMENT=	Sort a file or merge sort multiple files

USES=			perl5
USE_PERL5=		configure

MAN3=			File::Sort.3

NO_STAGE=	yes
.include <bsd.port.mk>
