# Created by: petef
# $FreeBSD: net-im/p5-Net-AIM/Makefile 327756 2013-09-20 22:13:34Z bapt $

PORTNAME=	Net-AIM
PORTVERSION=	1.22
CATEGORIES=	net-im perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl extension for the AOL Instant Messenger TOC protocol

USES=		perl5
USE_PERL5=	configure

MAN3=	Net::AIM.3 Net::AIM::Connection.3 Net::AIM::Event.3

NO_STAGE=	yes
.include <bsd.port.mk>
