# New ports collection makefile for:	py-pydicom
# Date created:		2009-01-13
# Whom:			Wen Heping <wenheping@gmail.com>
#
# $FreeBSD: ports/science/py-pydicom/Makefile,v 1.4 2012/11/17 06:00:59 svnexp Exp $
#

PORTNAME=	pydicom
PORTVERSION=	0.9.4.1
CATEGORIES=	science python
MASTER_SITES=	${MASTER_SITE_GOOGLE_CODE}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	${PORTNAME}-0.9.4-1

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Read, modify, and write DICOM files with Python code

USE_DOS2UNIX=	yes
USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install
PYDISTUTILS_PKGVERSION=	0.9.4_1

.include <bsd.port.mk>
