# $FreeBSD: math/hs-semigroups/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	semigroups
PORTVERSION=	0.9.1
PORTREVISION=	2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 semigroups

LICENSE=	BSD

USE_CABAL=	nats>=0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
