# Created by: wmoran
# $FreeBSD: sysutils/jailme/Makefile 327772 2013-09-20 23:05:58Z bapt $

PORTNAME=	jailme
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	http://people.collaborativefusion.com/~wmoran/code/jailme/

MAINTAINER=	wmoran@collaborativefusion.com
COMMENT=	A setuid version of jexec to allow normal users access to jails

PLIST_FILES=	sbin/jailme

USE_BZIP2=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
