# $FreeBSD: net/libnids-libnet11/Makefile 318350 2013-05-17 02:00:55Z wxs $

PKGNAMESUFFIX=	-libnet11

COMMENT=	Network monitoring library with TCP/IP reassembly using libnet11

MASTERDIR=	${.CURDIR}/../libnids

DESCR=		${.CURDIR}/pkg-descr

WITH_LIBNET11=	yes

CONFLICTS?=	libnids-[0-9]*

DISTINFO_FILE=	${MASTERDIR}/distinfo

.include "${MASTERDIR}/Makefile"
