# Created by: SimaMoto,RyoTa <liangtai.s4@gmail.com>
# $FreeBSD: misc/gimp-help-nl/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	misc graphics

MAINTAINER=	liangtai.s4@gmail.com
COMMENT=	The GIMP User Manual in Dutch

MASTERDIR=	${.CURDIR}/../gimp-help-en

DOCLANG=	nl
AMPLE=	"@comment "

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
