# New ports collection makefile for:    ku-aspell
# Date created:                         12 February 2007
# Whom:                                 Thierry Thomas <thierry@pompo.net>
#
# $FreeBSD: ports/textproc/ku-aspell/Makefile,v 1.6 2012/11/17 06:02:00 svnexp Exp $
#

PORTNAME=	${DICT}-aspell
DISTVERSION=	5-ku-0.20-1
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Kurdi dictionary

DICT=	 	ku

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
