# New ports collection makefile for:	py-rope
# Date created:				2011-05-11
# Whom:					Jose Jachuf <jjachuf@gmail.com>
#
# $FreeBSD: ports/devel/py-rope/Makefile,v 1.3 2012/11/17 05:56:50 svnexp Exp $
#

PORTNAME=	rope
PORTVERSION=	0.9.4
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jjachuf@gmail.com
COMMENT=	Rope is a python refactoring library

USE_PYTHON=		yes
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
