# $FreeBSD: ports/devel/hs-file-embed/Makefile,v 1.5 2013/02/05 22:47:09 svnexp Exp $

PORTNAME=	file-embed
PORTVERSION=	0.0.4.7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use Template Haskell to embed file contents directly

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
