# $FreeBSD: x11-drivers/xf86-video-voodoo/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	xf86-video-voodoo
PORTVERSION=	1.2.5
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org voodoo display driver

XORG_CAT=	driver
USE_XORG=	xf86dgaproto
MAN4=		voodoo.4x

.include <bsd.port.mk>
