# New ports collection makefile for:	XML::RegExp
# Date created:		7 Dec 2001
# Whom:			Sergey Skvortsov <skv@protey.ru>
#
# $FreeBSD: ports/textproc/p5-XML-RegExp/Makefile,v 1.8 2012/11/17 06:02:13 svnexp Exp $
#

PORTNAME=	XML-RegExp
PORTVERSION=	0.04
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Regular expressions for XML tokens

PERL_CONFIGURE=	yes

MAN3=		XML::RegExp.3

.include <bsd.port.mk>
