# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: textproc/p5-XML-RegExp/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	XML-RegExp
PORTVERSION=	0.04
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Regular expressions for XML tokens

USES=		perl5
USE_PERL5=	configure

MAN3=		XML::RegExp.3

.include <bsd.port.mk>
