# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-File-HStore/Makefile 330981 2013-10-20 05:49:26Z eadler $

PORTNAME=	File-HStore
PORTVERSION=	0.10
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Store files on a filesystem using a simple hash-based storage

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
