# ex:ts=8
# New ports collection makefile for:	ample
# Date created:			March 21, 2002
# Whom:				patrick
#
# $FreeBSD: ports/audio/ample/Makefile,v 1.11 2012/11/17 05:54:28 svnexp Exp $
#

PORTNAME=	ample
PORTVERSION=	0.5.7
CATEGORIES=	audio
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}-devel/${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Allows you to listen to your own MP3's away from home

GNU_CONFIGURE=	yes

MAN1=		ample.1
MAN5=		ample.conf.5 ample.html.5
PLIST_FILES=	bin/ample

.include <bsd.port.mk>
