# ex:ts=8
# Ports collection makefile for:	libyaml
# Date created:			Aug 31, 2006
# Whom:				ijliao
#
# $FreeBSD: ports/textproc/libyaml/Makefile,v 1.12 2012/11/17 06:02:02 svnexp Exp $
#

PORTNAME=	libyaml
PORTVERSION=	0.1.4
PORTREVISION=	2
CATEGORIES=	textproc
MASTER_SITES=	http://pyyaml.org/download/libyaml/
DISTNAME=	yaml-${PORTVERSION}
DIST_SUBDIR=	repacked

MAINTAINER=	jpaetzel@FreeBSD.org
COMMENT=	A YAML 1.1 parser and emitter written in C

GNU_CONFIGURE=	yes
USE_GNOME=	gnomehack
USE_LDCONFIG=	yes

.include <bsd.port.mk>
