# New ports collection makefile for:	py-YABT
# Date created:		2008-09-20
# Whom:			Wen Heping <wenheping@gmail.com>
#
# $FreeBSD: ports/misc/py-YABT/Makefile,v 1.4 2012/11/17 05:59:44 svnexp Exp $
#

PORTNAME=	YABT
PORTVERSION=	2.0.2
CATEGORIES=	misc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A General Purpose Braille Translation System

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

.include <bsd.port.mk>
