# Created by: Zach Thompson <hideo@lastamericanempire.com>
# $FreeBSD: devel/p5-POE-Component-Child/Makefile 332203 2013-10-31 06:20:32Z vanilla $

PORTNAME=	POE-Component-Child
PORTVERSION=	1.39
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	POE child management

BUILD_DEPENDS=	p5-POE>=0:${PORTSDIR}/devel/p5-POE
RUN_DEPENDS=	p5-POE>=0:${PORTSDIR}/devel/p5-POE

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
