# Created by: Andrei V. Shetuhin <reki@reki.ru>
# $FreeBSD: converters/p5-String-SetUTF8/Makefile 326870 2013-09-10 07:12:35Z az $

PORTNAME=	String-SetUTF8
PORTVERSION=	1.00
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	reki@reki.ru
COMMENT=	Perl module to manipulate internal UTF-8 flag on strings

USES=		perl5
USE_PERL5=	configure

MAN3=		String::SetUTF8.3

.include <bsd.port.mk>
