# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: textproc/p5-Text-Lorem/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Text-Lorem
PORTVERSION=	0.3
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Generate random Latin looking text

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
