# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-docile/Makefile 333526 2013-11-11 17:26:22Z sunpoet $

PORTNAME=	docile
PORTVERSION=	1.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Docile turns any Ruby object into a DSL

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
