# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: devel/rubygem-mutter/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	mutter
PORTVERSION=	0.5.3
#PORTREVISION=	0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	This Ruby gem is a tiny command-line interface library

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
