# $FreeBSD: security/hs-crypto-api/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	crypto-api
PORTVERSION=	0.12.1
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic interface for cryptographic operations

LICENSE=	BSD

USE_CABAL=	cereal>=0.2 entropy tagged>=0.1 transformers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
