# New ports collection makefile for:	qdbm-plus
# Date created:		September 25th, 2006
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD: ports/databases/qdbm-plus/Makefile,v 1.8 2012/11/17 05:55:23 svnexp Exp $
#

PORTREVISION=	0
PKGNAMESUFFIX=	-plus

COMMENT=	C++ API for QDBM

SLAVEPORT=	plus

MASTERDIR=	${.CURDIR}/../../databases/qdbm
WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}/plus
PLIST=		${.CURDIR}/pkg-plist
DESCR=		${.CURDIR}/pkg-descr
PATCHDIR=	${.CURDIR}/files

.include "${MASTERDIR}/Makefile"
