# Created by: fjoe@FreeBSD.org
# $FreeBSD: x11-toolkits/wxgtk26-unicode/Makefile 327785 2013-09-20 23:57:47Z bapt $

MAINTAINER=	fjoe@FreeBSD.org
COMMENT=	The wxWidgets GUI toolkit (Unicode)

WXGTK_FLAVOR=	gtk2-unicode
MASTERDIR=	${.CURDIR}/../wxgtk26

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
