# Created by: Gabor Kovesdan
# $FreeBSD: security/p5-Crypt-GOST/Makefile 326998 2013-09-11 17:56:03Z az $

PORTNAME=	Crypt-GOST
PORTVERSION=	1.00
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension for GOST Encryption Algorithm

USES=		perl5
USE_PERL5=	configure

MAN3=		Crypt::GOST.3

.include <bsd.port.mk>
