# Created by: Chris D. Faulhaber <jedgar@fxp.org>
# $FreeBSD: games/speyes/Makefile 327730 2013-09-20 17:36:33Z bapt $

PORTNAME=	speyes
PORTVERSION=	1.2.0
PORTREVISION=	1
CATEGORIES=	games
MASTER_SITES=	http://okb-1.org/speyes/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	WindowMaker dockapp/xeyes clone using SouthPark characters

PLIST_FILES=	bin/speyes
USES=		imake
USE_XORG=	xpm xmu

NO_STAGE=	yes
.include <bsd.port.mk>
