# New ports collection makefile for:	speyes
# Date created:				03 November 1999
# Whom:					Chris D. Faulhaber <jedgar@fxp.org>
#
# $FreeBSD: ports/games/speyes/Makefile,v 1.13 2012/11/17 05:57:53 svnexp Exp $
#

PORTNAME=	speyes
PORTVERSION=	1.2.0
PORTREVISION=	1
CATEGORIES=	games
MASTER_SITES=	http://okb-1.org/speyes/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	WindowMaker dockapp/xeyes clone using SouthPark characters

PLIST_FILES=	bin/speyes
USE_IMAKE=	yes
USE_XORG=	xpm xmu

.include <bsd.port.mk>
