# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: textproc/p5-CSS-Minifier/Makefile 316559 2013-04-26 03:05:31Z sunpoet $

PORTNAME=	CSS-Minifier
PORTVERSION=	0.01
CATEGORIES=	textproc www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Perl extension for minifying CSS

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		CSS::Minifier.3

.include <bsd.port.mk>
