# $FreeBSD: devel/rubygem-thor/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	thor
PORTVERSION=	0.18.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A scripting framework that replaces rake, sake, and rubigen

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/thor

NO_STAGE=	yes
.include <bsd.port.mk>
