# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: graphics/gstreamer-plugins-cairo/Makefile 327733 2013-09-20 18:35:44Z bapt $
#   $MCom: ports/graphics/gstreamer-plugins-cairo/Makefile,v 1.6 2008/03/19 14:05:34 ahze Exp $

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	Gstreamer vector graphics plugin

GST_PLUGIN=	cairo

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
