# Created by: Ju Pengfei <jupengfei@gmail.com>
# $FreeBSD: devel/hs-bsd-sysctl/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	bsd-sysctl
PORTVERSION=	1.0.7
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Access to the BSD sysctl(3) interface

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
