# Created by: Muhammad Moinur Rahman <5u623l20@gmail.com>
# $FreeBSD: devel/pear-Structure_LinkedList/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Structures_LinkedList
PORTVERSION=	0.2.2
CATEGORIES=	devel pear

MAINTAINER=	5u623l20@gmail.com
COMMENT=	Implements singly and doubly-linked lists

PEAR_AUTOINSTALL=	yes

NO_STAGE=	yes
.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.mk"
.include <bsd.port.post.mk>
