# Ports collection makefile for:	pear-Structures_LinkedList
# Date created:				26 April 2012
# Whom:					Muhammad Moinur Rahman <5u623l20@gmail.com>
#
# $FreeBSD: ports/devel/pear-Structure_LinkedList/Makefile,v 1.2 2012/11/17 05:56:40 svnexp Exp $
#

PORTNAME=	Structures_LinkedList
PORTVERSION=	0.2.2
CATEGORIES=	devel pear

MAINTAINER=	5u623l20@gmail.com
COMMENT=	Implements singly and doubly-linked lists

PEAR_AUTOINSTALL=	yes

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.mk"
.include <bsd.port.post.mk>
