# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: multimedia/gstreamer-plugins-vp8/Makefile 327747 2013-09-20 20:57:48Z bapt $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer vp8 codec plugin

GST_PLUGIN=	vp8

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
