# Created by: Mark Felder <feld@FreeBSD.org>
# $FreeBSD: devel/py-pyechonest/Makefile 341541 2014-01-28 12:44:35Z feld $

PORTNAME=	pyechonest
PORTVERSION=	7.1.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP

MAINTAINER=	feld@FreeBSD.org
COMMENT=	Python interface to The Echo Nest APIs

LICENSE=	MIT

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

PLIST_FILES=	%%PYTHON_SITELIBDIR%%/%%PYEASYINSTALL_EGG%%

.include <bsd.port.mk>
