# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-Proc-Wait3/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	Proc-Wait3
PORTVERSION=	0.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Proc
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl extension for wait3 system call

USES=		perl5
USE_PERL5=	configure

MAN3=	Proc::Wait3.3

.include <bsd.port.mk>
