# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: databases/php55-interbase/Makefile 328904 2013-09-30 23:44:01Z acm $

PORTREVISION=	1
CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-interbase

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
