# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: databases/php55-interbase/Makefile 332107 2013-10-30 13:32:02Z ale $

PORTREVISION=	1
CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-interbase

.include "${MASTERDIR}/Makefile"
