# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: textproc/p5-Text-Balanced/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	Text-Balanced
PORTVERSION=	2.02
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Extract delimited text sequences from strings

USES=		perl5
USE_PERL5=	configure

MAN3=		Text::Balanced.3

NO_STAGE=	yes
.include <bsd.port.mk>
