# New ports collection makefile for:	drupal6-seo_checklist
# Date created:				2 May 2009
# Whom:					Nick Hilliard <nick@foobar.org>
#
# $FreeBSD: ports/www/drupal6-seo_checklist/Makefile,v 1.6 2012/11/17 06:02:31 svnexp Exp $
#

PORTNAME=	seo_checklist
DISTVERSION=	6.x-2.0
PORTREVISION=	1
CATEGORIES=	www

MAINTAINER=	nick@foobar.org
COMMENT=	Drupal module to provide checklist of actions for SEO

USE_DRUPAL=	yes
DRUPAL6_MODULE=	yes
MODULE_FILES=	seochecklist.info seochecklist.install seochecklist.module
DOC_FILES=	LICENSE.txt README.txt

.include <bsd.port.mk>
