# $FreeBSD: x11-fonts/font-bitstream-speedo/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	font-bitstream-speedo
PORTVERSION=	1.0.2
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Bitstream Vera Speedo font

XORG_CAT=	font

.include <bsd.port.mk>
