BUILD_DEPENDS+= ${LOCALBASE}/bin/update-mime-database:${PORTSDIR}/misc/shared-mime-info
LIB_DEPENDS+=	raptor2.0:${PORTSDIR}/textproc/raptor2 \
		xml2.5:${PORTSDIR}/textproc/libxml2 \
		yajl.2:${PORTSDIR}/devel/yajl
