# Created by: Anatoliy Dmytriyev
# $FreeBSD: russian/p5-cyrillic/Makefile 327766 2013-09-20 22:46:16Z bapt $

PORTNAME=	cyrillic
PORTVERSION=	2.09
CATEGORIES=	russian converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tolid@plab.ku.dk
COMMENT=	Library for fast and easy Cyrillic text manipulation

USES=		perl5
USE_PERL5=	configure

MAN3=	cyrillic.3

NO_STAGE=	yes
.include <bsd.port.mk>
