# $FreeBSD: audio/kid3-qt4/Makefile 333590 2013-11-12 16:50:12Z makc $

PKGNAMESUFFIX=	-qt4

COMMENT=	Qt 4 based MP3/Ogg/FLAC tag editor

MASTERDIR=	${.CURDIR}/../kid3-kde4
.include "${MASTERDIR}/Makefile"
