# Created by: gahr
# $FreeBSD: x11-themes/e16-themes/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	e16-themes
PORTVERSION=	1.0.1
CATEGORIES=	x11-themes enlightenment
MASTER_SITES=	SF/enlightenment/${PORTNAME}/${PORTVERSION}

MAINTAINER=	gahr@FreeBSD.org
COMMENT=	A set of themes for the e16 window manager

DATADIR=	${PREFIX}/share/e16
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
