# $FreeBSD: multimedia/gstreamer1-plugins-dv/Makefile 332416 2013-11-01 22:14:07Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia
PKGNAMESUFFIX=	1-plugins-dv

COMMENT=	Gstreamer dv plugin

GST_PLUGIN=	libdv
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
