# Created by: Yen-Ming Lee <leeym@FreeBSD.org>
# $FreeBSD: devel/p5-IPC-Shareable/Makefile 326702 2013-09-08 05:43:26Z az $

PORTNAME=	IPC-Shareable
PORTVERSION=	0.61
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	leeym@FreeBSD.org
COMMENT=	Share Perl variables between processes

USES=		perl5
USE_PERL5=	configure

MAN3=		IPC::Shareable.3 IPC::Shareable::SharedMem.3

.include <bsd.port.mk>
