# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: devel/php5-sysvmsg/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-sysvmsg

.include "${MASTERDIR}/Makefile"
