# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: science/R-cran-Epi/Makefile 319316 2013-05-28 15:15:05Z bf $

PORTNAME=	Epi
PORTVERSION=	1.1.49
PORTREVISION=	1
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Package for statistical analysis in epidemiology

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
