# Created by: Yoichi Asai <yatt@msc.biglobe.ne.jp>
# $FreeBSD: audio/timidity++-tcltk/Makefile 340722 2014-01-22 17:00:46Z mat $

PKGNAMESUFFIX=	-tcltk

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tcl/Tk interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++
NO_STAGE=	yes

.include "${MASTERDIR}/Makefile"
