# New ports collection makefile for:	TiMidity++
# Date created:		27 Feb 1999
# Whom:			Yoichi Asai <yatt@msc.biglobe.ne.jp>
#
# $FreeBSD: ports/audio/timidity++-tcltk/Makefile,v 1.8 2012/11/17 05:54:46 svnexp Exp $
#

PKGNAMESUFFIX=	-tcltk

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tcl/Tk interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++

.include "${MASTERDIR}/Makefile"
