# Created by: Li-Wen Hsu <lwhsu@lwhsu.org>
# $FreeBSD: www/py-flup/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	flup
PORTVERSION=	1.0.2
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	http://www.saddi.com/software/flup/dist/ \
		CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Random assortment of WSGI servers, middleware

USE_PYTHON=	2.5+
USE_PYDISTUTILS=	easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
