# New ports collection makefile for:	py-flup
# Date created:		2006-12-16
# Whom:			Li-Wen Hsu <lwhsu@lwhsu.org>
#
# $FreeBSD: ports/www/py-flup/Makefile,v 1.10 2012/11/17 06:03:00 svnexp Exp $
#

PORTNAME=	flup
PORTVERSION=	1.0.2
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	http://www.saddi.com/software/flup/dist/ \
		CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Random assortment of WSGI servers, middleware

USE_PYTHON=	2.5+
USE_PYDISTUTILS=	easy_install

.include <bsd.port.mk>
