# Ports collection makefile for:  pear-Horde_Text_Diff
# Date created:			  7 July 2011
# Whom:				  Martin Matuska <mm@FreeBSD.org>
#
# $FreeBSD: ports/textproc/pear-Horde_Text_Diff/Makefile,v 1.5 2012/12/12 15:19:53 svnexp Exp $

PORTNAME=	Horde_Text_Diff
PORTVERSION=	2.0.1
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde engine for performing and rendering text diffs

USE_HORDE_RUN=	Horde_Exception \
		Horde_Util

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
