# Created by: Alexander Logvinov <avl@FreeBSD.org>
# $FreeBSD: devel/rubygem-jruby-jars/Makefile 321832 2013-06-27 02:02:16Z swills $

PORTNAME=	jruby-jars
PORTVERSION=	1.7.4
CATEGORIES=	devel rubygems java
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	JAR files from the JRuby distribution

USE_JAVA=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
