--- pyproject.toml.orig	2025-03-04 17:10:32 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=68.2.0"]
+requires = ["setuptools>=61"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -32,7 +32,7 @@ dependencies = [
 dependencies = [
     "aiohttp >= 3.9.2, < 4.0.0",
     "aioitertools >= 0.5.1, < 1.0.0",
-    "botocore >= 1.37.0, < 1.37.2", # NOTE: When updating, always keep `project.optional-dependencies` aligned
+    "botocore >= 1.37.0", # NOTE: When updating, always keep `project.optional-dependencies` aligned
     "python-dateutil >= 2.1, < 3.0.0",
     "jmespath >= 0.7.1, < 2.0.0",
     "multidict >= 6.0.0, < 7.0.0",
@@ -41,10 +41,10 @@ awscli = [
 
 [project.optional-dependencies]
 awscli = [
-    "awscli >= 1.38.0, < 1.38.2",
+    "awscli >= 1.29.81",
 ]
 boto3 = [
-    "boto3 >= 1.37.0, < 1.37.2",
+    "boto3 >= 1.37.0",
 ]
 
 [project.urls]
