# uses -jN (all cores) during stage
# zrj: disable because of things it does (ld.gold binutils 2.27)
#CONFIGURE_ARGS+= --without-cluster-support # etc but thats plist changes, so..
MAKE_ENV+= LDVER=ld.bfd  # needed only for mail/libmapi (that we dont have)

dfly-patch:
	${REINPLACE_CMD} -e "s|'md'|'md-disable'|" \
		-e "s|'sys/md5.h'|'sys/md5-disable.h'|" \
		${WRKDIR}/${DISTNAME}/lib/crypto/wscript_configure
