# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-Class-Interfaces/Makefile 315509 2013-03-29 00:44:53Z eadler $

PORTNAME=	Class-Interfaces
PORTVERSION=	0.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Module for defining interface classes inline

PERL_CONFIGURE=	yes

MAN3=		Class::Interfaces.3

.include <bsd.port.mk>
