# Created by: clsung
# $FreeBSD: devel/p5-Algorithm-MinMax/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Algorithm-MinMax
PORTVERSION=	0.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl modules to find the minimum and maximum of an array

USES=		perl5
USE_PERL5=	configure

MAN3=		Algorithm::MinMax.3

NO_STAGE=	yes
.include <bsd.port.mk>
