# $FreeBSD: mail/hs-mime-types/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	mime-types
PORTVERSION=	0.1.0.3
PORTREVISION=	2
CATEGORIES=	mail haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Basic mime-type handling types and functions

LICENSE=	MIT

USE_CABAL=	text

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
