# Created by: Anes Mukhametov <anes@anes.su>
# $FreeBSD: devel/p5-Lingua-Translit/Makefile 333869 2013-11-15 14:24:29Z mat $

PORTNAME=	Lingua-Translit
PORTVERSION=	0.19
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	anes@anes.su
COMMENT=	Transliterates text between writing systems

LICENSE=	GPLv2 ART20
LICENSE_COMB=	dual

USES=	perl5
USE_PERL5=	configure

.include <bsd.port.mk>
