# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: devel/pear-channel-phpdoc/Makefile 318652 2013-05-21 07:38:08Z miwi $

PORTNAME=	phpdoc
PORTVERSION=	20120214
CATEGORIES=	devel www pear

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.phpdoc.org

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
