# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: x11-toolkits/py-wxPython26-common/Makefile 327785 2013-09-20 23:57:47Z bapt $

PORTREVISION=	6

WITH_COMMON_ONLY=	yes

MASTERDIR=	${.CURDIR}/../py-wxPython26
PYDISTUTILS_NOEGGINFO=	yes

PLIST=	${.CURDIR}/pkg-plist

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
