# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: x11-toolkits/py-wxPython26-common/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTREVISION=	7

WITH_COMMON_ONLY=	yes

MASTERDIR=	${.CURDIR}/../py-wxPython26
PYDISTUTILS_NOEGGINFO=	yes

PLIST=	${.CURDIR}/pkg-plist

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
