# Created by: Mathieu Arnold <m@absolight.net>
# $FreeBSD: textproc/p5-Text-Reform/Makefile 333056 2013-11-07 03:52:41Z vanilla $

PORTNAME=	Text-Reform
PORTVERSION=	1.20
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Text
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Manual text wrapping and reformatting

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
