# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: math/R-cran-nnls/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	nnls
PORTVERSION=	1.4
PORTREVISION=	5
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R implementation of an algorithm for non-negative least squares

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
