# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: math/R-cran-nnls/Makefile 335044 2013-11-27 18:56:43Z dbn $

PORTNAME=	nnls
PORTVERSION=	1.4
PORTREVISION=	5
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R implementation of an algorithm for non-negative least squares

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
