# New ports collection makefile for:    py-roman
# Date created:				Oct 28, 2011
# Whom:					Wen Heping <wen@FreeBSD.org>
#
# $FreeBSD: ports/math/py-roman/Makefile,v 1.2 2012/11/17 05:59:29 svnexp Exp $
#

PORTNAME=	roman
PORTVERSION=	1.4.0
CATEGORIES=	math python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Integer to Roman numerals converter

PLIST_FILES=	%%PYTHON_SITELIBDIR%%/%%PYEASYINSTALL_EGG%%

USE_PYTHON=	2.6+
USE_PYDISTUTILS=easy_install

.include <bsd.port.mk>
