# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-UDCode/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	UDCode
PORTVERSION=	1.03
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MJD
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Does a set of code words form a uniquely decodable code?

USES=		perl5
USE_PERL5=	configure

MAN3=	UDCode.3

.include <bsd.port.mk>
