# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: audio/gstreamer-plugins-pulse/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	GStreamer plugin for pulseaudio

GST_PLUGIN=	pulse

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
