# Created by: Denis N. Peplin <info@volginfo.ru>
# $FreeBSD: sysutils/utcount/Makefile 327772 2013-09-20 23:05:58Z bapt $

PORTNAME=	utcount
PORTVERSION=	0.1
CATEGORIES=	sysutils net
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/${PORTNAME}-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Users Traffic Count

NO_STAGE=	yes
.include <bsd.port.mk>
