# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: math/p5-Statistics-Regression/Makefile 327032 2013-09-12 05:53:03Z az $

PORTNAME=	Statistics-Regression
PORTVERSION=	0.53
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Perl module to perform weighted linear regression

USES=		perl5
USE_PERL5=	configure

MAN3=		Statistics::Regression.3

.include <bsd.port.mk>
