# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/p5-Symbol-Util/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Symbol-Util
PORTVERSION=	0.0203
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Additional utils for Perl symbols manipulation

USES=		perl5
USE_PERL5=	configure

MAN3=		Symbol::Util.3

.include <bsd.port.mk>
