# Created by: Eugene Grosbein <ports@grosbein.net>
# $FreeBSD: devel/py-application/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	application
PORTVERSION=	1.2.9
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-${PORTNAME}-${PORTVERSION}

MAINTAINER=	ports@grosbein.net
COMMENT=	Basic building blocks for python applications

USE_PYTHON=	yes
USE_PYDISTUTILS=yes
PYDISTUTILS_PKGNAME=python_${PORTNAME}

NO_STAGE=	yes
.include <bsd.port.mk>
