# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: devel/hs-dlist/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	dlist
PORTVERSION=	0.5
PORTREVISION=	11
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	List-like type supporting O(1) append for Haskell

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
