# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: devel/hs-dlist/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	dlist
PORTVERSION=	0.5
PORTREVISION=	9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	List-like type supporting O(1) append for Haskell

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
