# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: devel/hs-dlist/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	dlist
PORTVERSION=	0.5
PORTREVISION=	10
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	List-like type supporting O(1) append for Haskell

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
