# Created by: Peter Schuller <peter.schuller@infidyne.com>
# $FreeBSD: devel/py-greenlet/Makefile 313920 2013-03-11 17:26:07Z sunpoet $

PORTNAME=	greenlet
PORTVERSION=	0.4.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
EXTRACT_SUFX=	.zip

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Light-weight microthreads for Python

LICENSE=	MIT

ONLY_FOR_ARCHS=	amd64 i386
USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
