# Created by: thierry@pompo.net
# $FreeBSD: cad/astk-client/Makefile 320674 2013-06-12 10:31:12Z miwi $

PORTNAME=	astk

COMMENT=	Graphical interface for Code_Aster (client side)

MASTERDIR=	${.CURDIR}/../astk-serveur

CLIENT_SEUL=	oui

.include "${MASTERDIR}/Makefile"
