# New ports collection makefile for:	de-MT
# Date created:			Fri, 2 Oct 2009 07:56:20 GMT
# Whom:				takefu
#
# $FreeBSD: ports/german/MT/Makefile,v 1.6 2012/11/17 05:57:59 svnexp Exp $
#

CATEGORIES=	german www
DISTNAME=	MTOS-${PORTVERSION}-${PKGNAMEPREFIX:S,-,,}
PKGNAMEPREFIX=	de-

COMMENT=	German localization of the MovableType publishing system

MASTERDIR=	${.CURDIR}/../../www/MT
CONFLICTS=	MT-[2-5].* fr-MT-[2-5].* ja-MT-[2-5].* ru-MT-[2-5].*

.include "${MASTERDIR}/Makefile"
