# $FreeBSD: ports/x11/xpr/Makefile,v 1.4 2013/02/04 05:01:49 svnexp Exp $

PORTNAME=	xpr
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Utility for printing an X window dump

XORG_CAT=	app
USE_XORG=	xmuu x11

PLIST_FILES=	bin/xdpr bin/xpr

MAN1=		xdpr.1 xpr.1

.include <bsd.port.mk>
