# New ports collection makefile for:	py-venusian
# Date created:				2011-03-21
# Whom:	      				Cheng-Lung Sung <clsung@FreeBSD.org>
#
# $FreeBSD: ports/devel/py-venusian/Makefile,v 1.6 2012/11/17 05:56:51 svnexp Exp $
#

PORTNAME=	venusian
PORTVERSION=	1.0a6
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	A Python library for deferring decorator actions

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

.include <bsd.port.mk>
