# New ports collection makefile for:    fy-aspell
# Date created:                         12 June 2007
# Whom:                                 Thierry Thomas <thierry@pompo.net>
#
# $FreeBSD: ports/textproc/fy-aspell/Makefile,v 1.7 2012/11/17 06:01:56 svnexp Exp $
#

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-fy-0.12-0
PORTREVISION=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Frisian (Frysk) dictionary

DICT=	 	fy

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
