# $FreeBSD: x11-drivers/xf86-input-mouse/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xf86-input-mouse
PORTVERSION=	1.9.0
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org mouse input driver

XORG_CAT=	driver
USES=		pathfix

.include <bsd.port.mk>
