# Created by: Tsung-Han Yeh <snowfly@yuntech.edu.tw>
# $FreeBSD: www/p5-CGI-FCKeditor/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	CGI-FCKeditor
PORTVERSION=	0.02
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	snowfly@yuntech.edu.tw
COMMENT=	This's FCKeditor Controller for Perl OOP

USES=		perl5
USE_PERL5=	configure

MAN3=		CGI::FCKeditor.3

NO_STAGE=	yes
.include <bsd.port.mk>
