# Created by: vanilla@
# $FreeBSD: ports/devel/jansson/Makefile,v 1.14 2012/12/19 16:07:04 svnexp Exp $

PORTNAME=	jansson
PORTVERSION=	2.4
CATEGORIES=	devel
MASTER_SITES=	http://www.digip.org/jansson/releases/

MAINTAINER=	vanilla@FreeBSD.org
COMMENT=	A C library for encoding, decoding, and manipulating JSON data

USE_BZIP2=	yes
USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes
USE_GNOME=	gnomehack pkgconfig

.include <bsd.port.mk>
