# $FreeBSD: head/www/p5-Mozilla-CA/Makefile 466307 2018-04-03 09:50:24Z sunpoet $

PORTNAME=	Mozilla-CA
PORTVERSION=	20180117
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for Mozilla CA cert bundle in PEM format

LICENSE=	MPL20

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
