# Created by: pst
# $FreeBSD: www/weblint/Makefile 318131 2013-05-13 20:58:05Z dinoex $

PORTNAME=	weblint
PORTVERSION=	1.020
CATEGORIES=	www
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:NEILB

MAINTAINER=	ports@FreeBSD.org
COMMENT=	HTML validator and sanity checker

MAN1=		weblint.1

.include <bsd.port.mk>
