# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: devel/p5-Errno/Makefile 341629 2014-01-28 16:46:49Z miwi $

PORTNAME=	Errno
PORTVERSION=	1.10
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org
COMMENT=	A perl5 module providing access to System errno constants

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
