# New ports collection makefile for:	p5-LWP-MediaTypes
# Date created:				2011-04-15
# Whom:					Frederic Culot <culot@FreeBSD.org>
#
# $FreeBSD: ports/www/p5-LWP-MediaTypes/Makefile,v 1.4 2012/11/17 06:02:51 svnexp Exp $
#

PORTNAME=	LWP-MediaTypes
PORTVERSION=	6.02
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Guess media type for a file or a URL

CONFLICTS=	p5-libwww-5*

PERL_CONFIGURE=	yes

MAN3=		LWP::MediaTypes.3

.include <bsd.port.mk>
