# Created by: Frederic Culot <culot@FreeBSD.org>
# $FreeBSD: head/www/p5-LWP-MediaTypes/Makefile 449893 2017-09-15 08:58:46Z mat $

PORTNAME=	LWP-MediaTypes
PORTVERSION=	6.02
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Guess media type for a file or a URL

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
