# New ports collection makefile for:	fftw-float
# Date created:		2004-09-02
# Whom:			Michael Johnson <ahze@ahze.net>
#
# $FreeBSD: ports/math/fftw-float/Makefile,v 1.5 2012/11/17 05:59:20 svnexp Exp $
#

PORTREVISION=	2

COMMENT=	Fast C routines (Single Percision)

FFTW_FLAVOR=	float
MASTERDIR=	${.CURDIR}/../../math/fftw

.include "${MASTERDIR}/Makefile"
