# Created by: Michael Johnson <ahze@ahze.net>
# $FreeBSD: math/fftw-float/Makefile 327746 2013-09-20 20:55:04Z bapt $

PORTREVISION=	2

COMMENT=	Fast C routines (Single Percision)

FFTW_FLAVOR=	float
MASTERDIR=	${.CURDIR}/../../math/fftw

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
