# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-Lingua-EN-Squeeze/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Lingua-EN-Squeeze
PORTVERSION=	2006.0704
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Shorten text to minimum syllables by using hash table

USES=		perl5
USE_PERL5=	configure

MAN3=	Lingua::EN::Squeeze.3

.include <bsd.port.mk>
