# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-Lingua-EN-Squeeze/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Lingua-EN-Squeeze
PORTVERSION=	2006.0704
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Shorten text to minimum syllables by using hash table

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
