# Created by: Alexander V. Ribchansky <triosoft@triosoft.com.ua>
# $FreeBSD: www/xpi-imglikeopera/Makefile 341207 2014-01-26 15:10:29Z miwi $

PORTNAME=	imglikeopera
PORTVERSION=	0.6.20
CATEGORIES=	www
MASTER_SITES=	MOZDEV

MAINTAINER=	triosoft@triosoft.com.ua
COMMENT=	Load only the images that you want in Firefox

XPI_ID=		imglikeopera@imfo.ru

.include "${.CURDIR}/../../www/xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
