# New ports collection makefile for:	libgnomedb-reference
# Date created:				09 May 2006
# Whom:					Jean-Yves Lefort <jylefort@FreeBSD.org>
#
# $FreeBSD: ports/databases/libgnomedb-reference/Makefile,v 1.3 2012/11/17 05:55:10 svnexp Exp $
#

PORTREVISION=	1

REFERENCE_SRC=	${WRKSRC}/doc/C

.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
