# $FreeBSD: devel/py-Products.ExternalEditor/Makefile 340992 2014-01-25 07:19:34Z rm $

PORTNAME=	Products.ExternalEditor
PORTVERSION=	1.1.0
PORTREVISION=	1
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Zope external editor

LICENSE=	ZPL21

USE_PYTHON=		yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes
USE_ZIP=		yes

.include <bsd.port.mk>
