# New ports collection makefile for:	R-cran-Formula
# Date created:		2012-01-04
# Whom:			TAKATSU Tomonari <tota@FreeBSD.org>
#
# $FreeBSD: ports/math/R-cran-Formula/Makefile,v 1.5 2012/11/17 05:59:18 svnexp Exp $
#

PORTNAME=	Formula
DISTVERSION=	1.1-0
PORTREVISION=	3
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Extended Model Formulas

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
