# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-Devel-Messenger/Makefile 331933 2013-10-29 07:56:01Z vanilla $

PORTNAME=	Devel-Messenger
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Let Your Code Talk to You

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
