# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-Devel-Messenger/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Devel-Messenger
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Let Your Code Talk to You

USES=		perl5
USE_PERL5=	configure

MAN3=		Devel::Messenger.3

.include <bsd.port.mk>
