# Created by: gurkan@phys.ethz.ch
# $FreeBSD: games/lapispuzzle/Makefile 327730 2013-09-20 17:36:33Z bapt $

PORTNAME=	lapispuzzle
PORTVERSION=	1.2
CATEGORIES=	games gnustep
MASTER_SITES=	${MASTER_SITE_SAVANNAH}
MASTER_SITE_SUBDIR=	gap
DISTNAME=	LapisPuzzle-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tetris-like game for GNUstep

LICENSE=	GPLv2

USE_GNUSTEP=	yes
USE_GNUSTEP_BACK=	yes
USE_GNUSTEP_BUILD=	yes
USE_GNUSTEP_INSTALL=	yes

WRKSRC=		${WRKDIR}/LapisPuzzle-${PORTVERSION}

NO_STAGE=	yes
.include <bsd.port.mk>
