# New ports collection makefile for:    jpeg2ps (a4)
# Date created:         30 December 2000
# Whom:                 Lars Koeller <Lars.Koeller@Uni-Bielefeld.de>
#
# $FreeBSD: ports/graphics/jpeg2ps-a4/Makefile,v 1.2 2012/11/17 05:58:10 svnexp Exp $
#

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../jpeg2ps-letter

.include "${MASTERDIR}/Makefile"
