# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: textproc/p5-Sort-ArbBiLex/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Sort-ArbBiLex
PORTVERSION=	4.01
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to make sort functions for arbitrary sort orders

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
