# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-Proc-Queue/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	Proc-Queue
PORTVERSION=	1.23
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Proc::Queue - limit the number of child processes running

USES=		perl5
USE_PERL5=	configure

MAN3=	Proc::Queue.3

.include <bsd.port.mk>
