# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-Proc-Queue/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Proc-Queue
PORTVERSION=	1.23
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Proc::Queue - limit the number of child processes running

USES=		perl5
USE_PERL5=	configure

MAN3=	Proc::Queue.3

NO_STAGE=	yes
.include <bsd.port.mk>
