# Created by: Thomas Gellekum <tg@FreeBSD.org>
# $FreeBSD: audio/libcdaudio/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	libcdaudio
PORTVERSION=	0.99.12p2
PORTREVISION=	2
CATEGORIES=	audio
MASTER_SITES=	SF

MAINTAINER=	novel@FreeBSD.org
COMMENT=	A library for playing audio CDs

USE_AUTOTOOLS=	libtool
USES=		pathfix pkgconfig
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
