# Created by: Jan-Peter Koopmann <j.koopmann@seceidos.de>
# $FreeBSD: converters/p5-Convert-BinHex/Makefile 325256 2013-08-23 08:39:12Z jadawin $

PORTNAME=	Convert-BinHex
PORTVERSION=	1.120
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to extract data from Macintosh BinHex files

USES=		perl5
USE_PERL5=	configure

MAN3=		Convert::BinHex.3

.include <bsd.port.mk>
