# New ports collection makefile for:	xmess
# Date created:				Tue Aug 17 00:21:10 MET DST 1999
# Whom:					nox@jelal.kn-bremen.de
#
# $FreeBSD: ports/emulators/xmess/Makefile,v 1.48 2012/11/17 05:57:24 svnexp Exp $
#

PORTNAME=	xmess
PORTREVISION=	3

MAINTAINER=	ports@FreeBSD.org
COMMENT=	X11 emulator for game consoles

MASTERDIR=	${.CURDIR}/../xmame
DESCR=		${.CURDIR}/pkg-descr

MAMEMESS=	mess

.include "${MASTERDIR}/Makefile"
