# New ports collection makefile for:	xmms-scrobbler
# Date created:							2004-12-06
# Whom:									arved
#
# $FreeBSD: ports/audio/xmms-scrobbler/Makefile,v 1.13 2012/11/17 05:54:49 svnexp Exp $

PORTNAME=	xmms-scrobbler
PORTREVISION=	6

MAINTAINER=	novel@FreeBSD.org
COMMENT=	XMMS plugin for Audioscrobbler.com

CONFLICTS=	scrobbler-*

MASTERDIR=	${.CURDIR}/../scrobbler

WITH_XMMS=	yes

.include "${MASTERDIR}/Makefile"
