# New ports collection makefile for:	nxml for emacs
# Date created:		26 Oct 2003
# Whom:			Fritz Heinrichmeyer
#
# $FreeBSD: ports/editors/nxml-emacs21/Makefile,v 1.9 2012/11/17 05:57:17 svnexp Exp $
#

MAINTAINER=		hrs@FreeBSD.org
MASTERDIR=		${.CURDIR}/../nxml

EMACS_PORT_NAME=	emacs21

.include "${MASTERDIR}/Makefile"
