# $FreeBSD: textproc/hs-hxt-charproperties/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	hxt-charproperties
PORTVERSION=	9.1.1
PORTREVISION=	5
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Character properties and classes for XML and Unicode

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
