# Created by: Leo Kim <leo@florida.sarang.net>
# $FreeBSD: devel/p5-B-Graph/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	B-Graph
PORTVERSION=	0.51
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl Compiler backend to diagram OP trees

USES=		perl5
USE_PERL5=	configure
MAN3=		B::Graph.3

NO_STAGE=	yes
.include <bsd.port.mk>
