# New ports collection makefile for:	php52-pdo_sqlite
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/databases/php52-pdo_sqlite/Makefile,v 1.2 2012/11/17 05:55:19 svnexp Exp $
#

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-pdo_sqlite

.include "${MASTERDIR}/Makefile"
