# Created by: Timur I. Bakeyev <bat@cpan.org>
# $FreeBSD: devel/p5-File-ExtAttr/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=		File-ExtAttr
PORTVERSION=		1.09
CATEGORIES=		devel perl5
MASTER_SITES=		CPAN
PKGNAMEPREFIX=		p5-

MAINTAINER=		5u623l20@gmail.com
COMMENT=		Access to extended attributes of the files

USES=		perl5
USE_PERL5=	configure

MAN3=			File::ExtAttr.3 File::ExtAttr::Tie.3

NO_STAGE=	yes
.include <bsd.port.mk>
