# Created by: Timur I. Bakeyev <bat@cpan.org>
# $FreeBSD: devel/p5-File-ExtAttr/Makefile 338872 2014-01-06 12:55:03Z az $

PORTNAME=	File-ExtAttr
PORTVERSION=	1.09
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	5u623l20@gmail.com
COMMENT=	Access to extended attributes of the files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
