# $FreeBSD: x11/libXprintAppUtil/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	libXprintAppUtil
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The XprintAppUtil library

XORG_CAT=	lib
USE_XORG=	printproto x11 xau xp xprintutil xproto:both
USE_AUTOTOOLS=	libtool
.include <bsd.port.mk>
