# $FreeBSD: security/p5-Crypt-URandom/Makefile 318711 2013-05-21 14:57:43Z kuriyama $

PORTNAME=	Crypt-URandom
PORTVERSION=	0.34
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to provide non blocking randomness

PERL_CONFIGURE=	yes

MAN3=	Crypt::URandom.3

.include <bsd.port.mk>
