# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/converters/php5-iconv/Makefile 343435 2014-02-09 08:39:00Z ale $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-iconv

.include "${MASTERDIR}/Makefile"
