# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: textproc/p5-Text-Bind/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	Text-Bind
PORTVERSION=	0.04
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Bind Perl structures to text files

USES=		perl5
USE_PERL5=	configure

MAN3=		Text::Bind.3

NO_STAGE=	yes
.include <bsd.port.mk>
