# New ports collection makefile for:	courier-authlib-pgsql
# Date created:				02 Apr 2005
# Whom:					Yarema <yds@CoolRat.org>
#
# $FreeBSD: ports/databases/courier-authlib-pgsql/Makefile,v 1.19 2012/11/17 05:55:06 svnexp Exp $
#

PKGNAMESUFFIX=	-pgsql

COMMENT=	PostgreSQL support for the Courier authentication library
CATEGORIES=	databases mail

MASTERDIR=	${.CURDIR}/../../security/courier-authlib

.include "${MASTERDIR}/Makefile"
