# Created by: Scott Sanders <scott@jssjr.com>
# $FreeBSD: www/rubygem-url_escape/Makefile 332058 2013-10-30 03:05:18Z swills $

PORTNAME=	url_escape
PORTVERSION=	2009.06.24
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast replacement for CGI.escape and Rack::Utils.escape

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
