# Created by: Kurt Lidl <kurt.lidl@cello.com>
# $FreeBSD: textproc/p5-JavaScript-Minifier/Makefile 340787 2014-01-23 03:28:04Z sunpoet $

PORTNAME=	JavaScript-Minifier
PORTVERSION=	1.08
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ZOFFIX
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	JavaScript whitespace/comment eliminator

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
