# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: www/py-apachelog/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	apachelog
PORTVERSION=	1.1
CATEGORIES=	www python
MASTER_SITES=	${MASTER_SITE_GOOGLE_CODE} \
		http://freebsd.unixfreunde.de/sources/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Python access log parser.

USE_PYTHON=	yes
USE_PYDISTUTILS=yes

NO_STAGE=	yes
.include <bsd.port.mk>
