# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: www/py-apachelog/Makefile 341745 2014-01-29 15:04:46Z miwi $

PORTNAME=	apachelog
PORTVERSION=	1.1
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	${MASTER_SITE_GOOGLE_CODE} \
		http://freebsd.unixfreunde.de/sources/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Python access log parser.

USE_PYTHON=	yes
USE_PYDISTUTILS=yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
