# Created by: Carlo Strub
# $FreeBSD: ports/devel/py-fastimport/Makefile,v 1.1 2012/11/19 21:29:48 svnexp Exp $
#

PORTNAME=	fastimport
PORTVERSION=	0.9.2
CATEGORIES=	devel
MASTER_SITES=	https://launchpadlibrarian.net/99879696/ \
		http://www.c-s.li/ports/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Fastimport parser in Python

LICENSE=	GPLv2

WRKSRC=		${WRKDIR}/python-${PORTNAME}-${PORTVERSION}
USE_PYTHON=	2.5+
USE_PYDISTUTILS=	yes
PYDISTUTILS_PKGNAME=	fastimport

.include <bsd.port.mk>
