# $FreeBSD: print/rubygem-prawn-svg/Makefile 332048 2013-10-30 02:54:59Z swills $

PORTNAME=	prawn-svg
PORTVERSION=	0.12.0.4
CATEGORIES=	print rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	SVG renderer for Prawn PDF library

RUN_DEPENDS=	rubygem-prawn>=0.8.4:${PORTSDIR}/print/rubygem-prawn

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
