# New ports collection makefile for:	ANSIColor
# Date created:				1 December 1999
# Whom:	      				Denis Shaposhnikov <dsh@vlink.ru>
#
# $FreeBSD: ports/devel/p5-Term-ANSIColor/Makefile,v 1.20 2012/11/17 05:56:31 svnexp Exp $
#

PORTNAME=	Term-ANSIColor
PORTVERSION=	3.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	dsh@vlink.ru
COMMENT=	Color screen output using ANSI escape sequences

PERL_CONFIGURE=	yes

MAN3=		Term::ANSIColor.3

.include <bsd.port.mk>
