# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: devel/pear-Horde_Serialize/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Horde_Serialize
PORTVERSION=	2.0.2
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Data Encapulation API

USE_HORDE_RUN=	Horde_Exception \
		Horde_Util

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
