# $FreeBSD: archivers/pear-Horde_Compress_Fast/Makefile 327699 2013-09-20 13:11:20Z bapt $

PORTNAME=	Horde_Compress_Fast
PORTVERSION=	1.0.2
CATEGORIES=	archivers www pear
PKGNAMEPREFIX=	pear-

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Fast Compression Library

NO_STAGE=	yes
USE_HORDE_RUN=	Horde_Exception

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
