# Created by: Sulev-Madis Silber <madis555@hot.ee>
# $FreeBSD: devel/p5-Number-Bytes-Human/Makefile 338987 2014-01-07 09:28:30Z az $

PORTNAME=	Number-Bytes-Human
PORTVERSION=	0.07
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	madis555@hot.ee
COMMENT=	Convert byte count to human readable format

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
