# $FreeBSD: x11/gstreamer1-plugins-x/Makefile 332416 2013-11-01 22:14:07Z kwm $

PORTREVISION=	0
CATEGORIES=	x11

COMMENT=	Gstreamer X and Xvideo output plugins

GST_PLUGIN=	x
DIST=		base

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
