# Created by: ijliao
# $FreeBSD: head/devel/p5-File-Copy-Recursive/Makefile 331943 2013-10-29 12:52:07Z vanilla $

PORTNAME=	File-Copy-Recursive
PORTVERSION=	0.38
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for recursively copying files and directories

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
