# Ports collection makefile for:  pear-Horde_Imsp
# Date created:			  7 July 2011
# Whom:				  Martin Matuska <mm@FreeBSD.org>
#
# $FreeBSD: ports/databases/pear-Horde_Imsp/Makefile,v 1.8 2012/12/12 15:19:46 svnexp Exp $

PORTNAME=	Horde_Imsp
PORTVERSION=	2.0.1
CATEGORIES=	databases www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde IMSP API

USE_HORDE_RUN=	Horde_Translation

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
