# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: multimedia/gstreamer-plugins-annodex/Makefile 332416 2013-11-01 22:14:07Z kwm $
#    $MCom: ports/multimedia/gstreamer-plugins-annodex/Makefile,v 1.1 2006/07/06 19:48:44 ahze Exp $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer annodex CMML plugin

GST_PLUGIN=	annodex

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
