# Created by: Satoshi Asami <asami@FreeBSD.org>
# $FreeBSD: print/pkfonts240/Makefile 327765 2013-09-20 22:43:59Z bapt $

RESOLUTION=	240
MASTERDIR=	${.CURDIR}/../pkfonts300

NO_STAGE=	yes
.include	"${MASTERDIR}/Makefile"
