# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: databases/py-pg8000/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	pg8000
PORTVERSION=	1.09
CATEGORIES=	databases python
MASTER_SITES=	GOOGLE_CODE
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	A Pure-Python Interface to the PostgreSQL Database

USE_PYTHON=	2
USE_PYDISTUTILS=easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
