# New ports collection makefile for: icmpmonitor
# Date created:		31 Jul 2001
# Whom:			nbm
#
# $FreeBSD: net-mgmt/icmpmonitor/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	icmpmonitor
PORTVERSION=	1.2
CATEGORIES=	net-mgmt
MASTER_SITES=	SF

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A multiple host icmp monitoring tool

GNU_CONFIGURE=	YES

MAN1=		icmpmonitor.1
PLIST_FILES=	sbin/icmpmonitor

.include <bsd.port.mk>
