# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-Lingua-Ident/Makefile 328854 2013-09-30 19:41:57Z sunpoet $

PORTNAME=	Lingua-Ident
PORTVERSION=	1.7
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MPIOTR
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Statistical language identification

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
