# Created by: Julien Laffaye <kimelto@gmail.com>
# $FreeBSD: x11/sselp/Makefile 339245 2014-01-09 14:48:54Z vanilla $

PORTNAME=	sselp
PORTVERSION=	0.2
CATEGORIES=	x11
MASTER_SITES=	http://dl.suckless.org/tools/ \
		http://laffaye.free.fr/distfiles/

MAINTAINER=	jlaffaye@FreeBSD.org
COMMENT=	Simple SELection Printer for X11

USE_XORG=	x11

PLIST_FILES=	bin/sselp

.include <bsd.port.mk>
