# Created by: clsung@dragon2.net
# $FreeBSD: devel/p5-Algorithm-NaiveBayes/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Algorithm-NaiveBayes
PORTVERSION=	0.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl class performing Bayesian prediction of categories

USES=		perl5
USE_PERL5=	modbuild

MAN3=		Algorithm::NaiveBayes.3

.include <bsd.port.mk>
