# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: math/p5-Math-Evol/Makefile 327746 2013-09-20 20:55:04Z bapt $

PORTNAME=	Math-Evol
PORTVERSION=	1.12
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module implements the evolution search strategy

USES=		perl5
USE_PERL5=	configure

MAN1=	ps_evol.1
MAN3=	Math::Evol.3

NO_STAGE=	yes
.include <bsd.port.mk>
