# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: net-mgmt/php55-snmp/Makefile 321684 2013-06-24 14:32:11Z ale $

CATEGORIES=	net-mgmt

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-snmp

.include "${MASTERDIR}/Makefile"
