# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: net-mgmt/php55-snmp/Makefile 332107 2013-10-30 13:32:02Z ale $

CATEGORIES=	net-mgmt

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-snmp

.include "${MASTERDIR}/Makefile"
