# Created by: ijliao
# $FreeBSD: devel/p5-Sort-Maker/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Sort-Maker
DISTVERSION=	0.06
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple way to make efficient sort subs

USES=		perl5
USE_PERL5=	configure

MAN3=	Sort::Maker.3

NO_STAGE=	yes
.include <bsd.port.mk>
