# Created by: TERAMOTO Masahiro <markun@onohara.to>
# $FreeBSD: irc/p5-IRC-Utils/Makefile 341420 2014-01-27 16:20:00Z miwi $

PORTNAME=	IRC-Utils
PORTVERSION=	0.12
CATEGORIES=	irc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:HINRIK
PKGNAMEPREFIX=	p5-

MAINTAINER=	markun@onohara.to
COMMENT=	Common utilities for IRC-related tasks

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
