# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: ports/devel/p5-Devel-Hide/Makefile,v 1.1 2013/02/11 11:33:26 svnexp Exp $

PORTNAME=	Devel-Hide
PORTVERSION=	0.0009
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Forces the unavailability of specified Perl modules (for testing)

PERL_CONFIGURE=	yes

MAN3=	Devel::Hide.3

.include <bsd.port.mk>
