# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-Devel-Hide/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	Devel-Hide
PORTVERSION=	0.0009
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Forces the unavailability of specified Perl modules (for testing)

USES=		perl5
USE_PERL5=	configure

MAN3=	Devel::Hide.3

.include <bsd.port.mk>
