# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-String-Scanf/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=		String-Scanf
PORTVERSION=		2.1
CATEGORIES=		textproc perl5
MASTER_SITES=		CPAN
PKGNAMEPREFIX=		p5-

MAINTAINER=		perl@FreeBSD.org
COMMENT=		Emulates the sscanf() of the C stdio library

USES=		perl5
USE_PERL5=	configure

MAN3=			String::Scanf.3

NO_STAGE=	yes
.include <bsd.port.mk>
