# Created by: Murray Nesbitt <freebsd@nesbitt.ca>
# $FreeBSD: misc/loop/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	loop
PORTVERSION=	1.0
CATEGORIES=	misc
MASTER_SITES=	http://www.nesbitt.ca/downloads/loop/

MAINTAINER=	freebsd@nesbitt.ca
COMMENT=	Prints to stdout a series of numbers from `start' to `end'

MAN1=		loop.1
MANCOMPRESSED=	yes
PLIST_FILES=	bin/loop

NO_STAGE=	yes
.include <bsd.port.mk>
