# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11/xineramaproto/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	xineramaproto
PORTVERSION=	1.2.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Xinerama extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
