--- pyproject.toml.orig	2023-03-30 16:54:02 UTC
+++ pyproject.toml
@@ -1,7 +1,7 @@
 [build-system]
 requires = [
     "setuptools >= 42",
-    "setuptools_scm[toml]>=3.4,<6",
+    "setuptools_scm[toml]>=3.4",
     "wheel"
 ]
-build-backend = "setuptools.build_meta"
\ No newline at end of file
+build-backend = "setuptools.build_meta"
