# $FreeBSD: x11/xlsclients/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	xlsclients
PORTVERSION=	1.1.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	List client applications running on a display

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	x11 xmuu

PLIST_FILES=	bin/xlsclients

MAN1=		xlsclients.1

.include <bsd.port.mk>
