# $FreeBSD: x11/xlsclients/Makefile 326806 2013-09-09 12:18:27Z zeising $

PORTNAME=	xlsclients
PORTVERSION=	1.1.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	List client applications running on a display

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	x11 xmuu

PLIST_FILES=	bin/xlsclients

MAN1=		xlsclients.1

.include <bsd.port.mk>
