# New ports collection makefile for:	rubygem-rspec-mocks
# Date created:		2011-06-12
# Whom:			Steve Wills <swills@FreeBSD.org>
#
# $FreeBSD: ports/devel/rubygem-rspec-mocks/Makefile,v 1.6 2012/11/17 05:57:01 svnexp Exp $
#

PORTNAME=	rspec-mocks
PORTVERSION=	2.11.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Rspec-mocks provides a test-double framework for rspec

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
