# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-rspec-mocks/Makefile 335527 2013-12-02 18:36:10Z sunpoet $

PORTNAME=	rspec-mocks
PORTVERSION=	2.14.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Rspec-mocks provides a test-double framework for rspec

LICENSE=	MIT

USE_RUBY=	yes
#USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
