# New ports collection makefile for:	p5-IO-Tee
# Date created:		Sun Jan 18 07:27:41 CST 2004
# Whom:					dcf@aracnet.com
#
# $FreeBSD: devel/p5-IO-Tee/Makefile 324171 2013-08-02 18:21:05Z az $
#

PORTNAME=	IO-Tee
PORTVERSION=	0.64
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Multiplex output to multiple output handles

USES=		perl5
USE_PERL5=	configure

MAN3=		IO::Tee.3

.include <bsd.port.mk>
