# Created by: dcf@aracnet.com
# $FreeBSD: devel/p5-IO-Tee/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	IO-Tee
PORTVERSION=	0.64
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Multiplex output to multiple output handles

USES=		perl5
USE_PERL5=	configure

MAN3=		IO::Tee.3

NO_STAGE=	yes
.include <bsd.port.mk>
