# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: textproc/rubygem-ya2yaml/Makefile 332053 2013-10-30 03:00:33Z swills $

PORTNAME=	ya2yaml
PORTVERSION=	0.31
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Yet another YAML converter, includes complete UTF8 support

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_RAKE=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
