# New ports collection makefile for:	base64
# Date created:				29 Oct 2000
# Whom:					will
#
# $FreeBSD: ports/converters/base64/Makefile,v 1.14 2012/11/17 05:55:02 svnexp Exp $
#

PORTNAME=	base64
PORTVERSION=	1.5
PORTREVISION=	1
CATEGORIES=	converters
MASTER_SITES=	http://www.fourmilab.ch/webtools/base64/ \
		http://dl.droso.net/FreeBSD/distfiles/

MAINTAINER=	nikola.lecic@anthesphoria.net
COMMENT=	Utility to encode and decode base64 files

GNU_CONFIGURE=	yes
ALL_TARGET=	prog
MAN1=		base64.1
PLIST_FILES=	bin/base64

.include <bsd.port.mk>
