# $FreeBSD: devel/p5-App-FatPacker/Makefile 333063 2013-11-07 05:37:32Z kuriyama $

PORTNAME=	App-FatPacker
PORTVERSION=	0.009018
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to pack your dependencies onto your script file

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
