# Created by: Alex Kapranoff <kapr@crosswinds.net>
# $FreeBSD: www/p5-HTML-Clean/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	HTML-Clean
PORTVERSION=	0.8
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Cleans up HTML code for web browsers, not humans

USES=		perl5
USE_PERL5=	configure

MAN1=		htmlclean.1
MAN3=		HTML::Clean.3

NO_STAGE=	yes
.include <bsd.port.mk>
