# Created by: peter
# $FreeBSD: sysutils/paicc/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	paicc
PORTVERSION=	1.4
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	utils/shell

MAINTAINER=	peter@FreeBSD.org
COMMENT=	Paint Changed Characters

MAKE_ENV=	BIN=${PREFIX}/bin MAN=${PREFIX}/man DATA=${PREFIX}/libdata
MAN1=		paicc.1

NO_STAGE=	yes
.include <bsd.port.mk>
