# New ports collection makefile for:	py-anonfunc
# Date created:		3 January 2004
# Whom:			Hye-Shik Chang
#
# $FreeBSD: ports/devel/py-anonfunc/Makefile,v 1.5 2012/11/17 05:56:45 svnexp Exp $

PORTNAME=	anonfunc
PORTVERSION=	1.0
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_LOCAL} \
		http://people.freebsd.org/~perky/distfiles/
MASTER_SITE_SUBDIR=	perky
PKGNAMEPREFIX=  ${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Python module that provides easy anonymous function

USE_PYTHON=	yes
USE_PYDISTUTILS=yes

.include <bsd.port.mk>
