# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: x11-themes/kde-icons-lime-rade8/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	lime-rade8
PORTVERSION=	1.01
MASTER_SITES=	SF/graphitekde/OldFiles
DISTNAME=	Lime-Rade8-${PORTVERSION}

COMMENT=	KDE Mac OS X like iconset, most from rad-e8 design

USE_BZIP2=	yes
WRKSRC=		${WRKDIR}/${DISTNAME:C|-${PORTVERSION}$||}

NO_STAGE=	yes
.include "${.CURDIR}/../kde-icons-noia/Makefile.icons"
