
LDFLAGS+=     -L${LOCALBASE}/lib -ltinfo -lncurses

# includes <threads.h> w/o good reason
BUILD_DEPENDS+= libstdthreads>0:misc/libstdthreads

dfly-patch:
	${REINPLACE_CMD} -e 's@freebsd@dragonfly@g' \
		${WRKSRC}/src/pipewire/meson.build \
		${WRKSRC}/meson.build
