# Created by: rpsfa@rit.edu
# $FreeBSD: dns/rubygem-net-dns/Makefile 319713 2013-06-02 18:56:18Z swills $

PORTNAME=	net-dns
PORTVERSION=	0.8.0
CATEGORIES=	dns rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A pure Ruby DNS library

RUN_DEPENDS=	rubygem-rcov>=0:${PORTSDIR}/devel/rubygem-rcov

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
