# Ports collection makefile for:	rubygem-net-dns
# Date created:				2011-06-16
# Whom:					rpsfa@rit.edu
#
# $FreeBSD: ports/dns/rubygem-net-dns/Makefile,v 1.5 2012/11/17 05:57:11 svnexp Exp $

PORTNAME=	net-dns
PORTVERSION=	0.7.1
CATEGORIES=	dns rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A pure Ruby DNS library

RUN_DEPENDS=	rubygem-rcov>=0:${PORTSDIR}/devel/rubygem-rcov

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
