# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: databases/php5-pdo_firebird/Makefile 328899 2013-09-30 23:41:54Z acm $

PORTREVISION=	1
CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-pdo_firebird

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
