# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: databases/php5-pdo_firebird/Makefile 320229 2013-06-07 23:49:53Z flo $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-pdo_firebird

.include "${MASTERDIR}/Makefile"
