# Created by: TAKAHASHI Kaoru <kaoru@kaisei.org>
# $FreeBSD: textproc/p5-String-CamelCase/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	String-CamelCase
PORTVERSION=	0.02
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	String
PKGNAMEPREFIX=	p5-

MAINTAINER=	kaoru@kaisei.org
COMMENT=	Perl module for camelcase, de-camelcase

USES=		perl5
USE_PERL5=	configure

MAN3=		String::CamelCase.3

NO_STAGE=	yes
.include <bsd.port.mk>
