# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: textproc/py-zope.i18nmessageid/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	zope.i18nmessageid
PORTVERSION=	3.6.1
CATEGORIES=	textproc www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Message Identifiers for internationalization

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install
PYEASYINSTALL_ARCHDEP=yes

NO_STAGE=	yes

.include <bsd.port.mk>
