# $FreeBSD: devel/rubygem-rake-compiler/Makefile 332040 2013-10-30 02:40:36Z swills $

PORTNAME=	rake-compiler
PORTVERSION=	0.8.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Build and package Ruby extensions (C, Java) using Rake

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/rake-compiler

.include <bsd.port.mk>
