# $FreeBSD: devel/hs-utf8-string/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	utf8-string
PORTVERSION=	0.3.7
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Support for reading/writing UTF-8 strings for Haskell programs

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
