# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: devel/pear-Horde_Stream_Wrapper/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Horde_Stream_Wrapper
PORTVERSION=	2.0.1
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Stream wrappers

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
