# Created by: Tsung-Han Yeh <snowfly@yuntech.edu.tw>
# $FreeBSD: net/p5-Net-sFlow/Makefile 338799 2014-01-05 16:55:04Z az $

PORTNAME=	Net-sFlow
PORTVERSION=	0.11
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	snowfly@yuntech.edu.tw
COMMENT=	Decode sFlow datagrams

LICENSE=	ART10

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
