# Created by: Tsung-Han Yeh <snowfly@yuntech.edu.tw>
# $FreeBSD: net/p5-Net-sFlow/Makefile 327755 2013-09-20 22:10:23Z bapt $

PORTNAME=	Net-sFlow
PORTVERSION=	0.11
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	snowfly@yuntech.edu.tw
COMMENT=	Decode sFlow datagrams

LICENSE=	ART10

USES=		perl5
USE_PERL5=	configure

MAN3=		Net::sFlow.3

NO_STAGE=	yes
.include <bsd.port.mk>
