# Ports collection makefile for:  pear-Horde_Stream
# Date created:			  12 December 2012
# Whom:				  Martin Matuska <mm@FreeBSD.org>
#
# $FreeBSD: ports/devel/pear-Horde_Stream/Makefile,v 1.1 2012/12/12 14:53:34 svnexp Exp $

PORTNAME=	Horde_Stream
PORTVERSION=	1.2.0
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde stream handler

USE_HORDE_RUN=	Horde_Exception

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
