# Created by: Yarema <yds@CoolRat.org>
# $FreeBSD: databases/courier-authlib-userdb/Makefile 327717 2013-09-20 16:13:47Z bapt $

PKGNAMESUFFIX=	-userdb

COMMENT=	Userdb support for the Courier authentication library
CATEGORIES=	databases mail

MASTERDIR=	${.CURDIR}/../../security/courier-authlib

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
