# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: devel/pear-channel-pdepend/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	pdepend
PORTVERSION=	20100520
CATEGORIES=	devel www pear

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.pdepend.org

NO_STAGE=	yes
.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
