# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: science/R-cran-bayesm/Makefile 335044 2013-11-27 18:56:43Z dbn $

PORTNAME=	bayesm
PORTVERSION=	2.2.4
PORTREVISION=	13
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${PORTVERSION:C/\./-/g:C/-/\./1}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Bayesian Inference for Marketing/Micro-econometrics

USE_R_MOD=		yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
