# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: science/R-cran-bayesm/Makefile 313562 2013-03-07 04:21:34Z bf $

PORTNAME=	bayesm
PORTVERSION=	2.2.4
PORTREVISION=	10
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${PORTVERSION:C/\./-/g:C/-/\./1}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Bayesian Inference for Marketing/Micro-econometrics

USE_R_MOD=		yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
