# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11-wm/xcompmgr/Makefile 327786 2013-09-21 00:01:16Z bapt $

PORTNAME=	xcompmgr
PORTVERSION=	1.1.6
CATEGORIES=	x11-wm

MAINTAINER=	x11@FreeBSD.org
COMMENT=	A sample X compositing manager

XORG_CAT=	app
USE_XORG=	x11 xcomposite xfixes xdamage xrender

PLIST_FILES=	bin/${PORTNAME}

MAN1=		xcompmgr.1

NO_STAGE=	yes
.include <bsd.port.mk>
