# Created by: Marcin Cieslak <saper@saper.info>
# $FreeBSD: deskutils/x026/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	x026
PORTVERSION=	1.2
CATEGORIES=	deskutils
MASTER_SITES=	SF/x3270/${PORTNAME}/${PORTVERSION}
EXTRACT_SUFX=	.tgz

MAINTAINER=	saper@saper.info
COMMENT=	IBM 026 Keypunch Emulator for the X Window System

USES=		imake
USE_XORG=	xaw7 xpm xt

PLIST_FILES=	bin/${PORTNAME}
MAN1=		${PORTNAME}.1

NO_STAGE=	yes
.include <bsd.port.mk>
