# Created by: andrew@scoop.co.nz
# $FreeBSD: print/p5-Net-Printer/Makefile 327765 2013-09-20 22:43:59Z bapt $

PORTNAME=	Net-Printer
PORTVERSION=	1.12
CATEGORIES=	print perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	5u623l20@gmail.com
COMMENT=	Perl extension for direct-to-lpd printing

LICENSE=	BSD

USES=		perl5
USE_PERL5=	configure

MAN3=		Net::Printer.3

NO_STAGE=	yes
.include <bsd.port.mk>
