# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: textproc/py-pss/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	pss
PORTVERSION=	1.38
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	Tool for grepping through source code

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_PKGNAME=	pss

NO_STAGE=	yes
.include <bsd.port.mk>
