# $FreeBSD: devel/pear-Horde_Queue/Makefile 317884 2013-05-11 15:16:00Z mm $

PORTNAME=	Horde_Queue
PORTVERSION=	1.0.0
CATEGORIES=	devel www pear
PKGNAMEPREFIX=	pear-

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Queue

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
