# $FreeBSD: devel/pear-Horde_Queue/Makefile 333263 2013-11-08 21:41:53Z antoine $

PORTNAME=	Horde_Queue
PORTVERSION=	1.1.1
CATEGORIES=	devel www pear
PKGNAMEPREFIX=	pear-

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Queue

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
