# Created by: Rick Elrod <codeblock@eighthbit.net>
# $FreeBSD: graphics/rubygem-imagesize/Makefile 332044 2013-10-30 02:48:42Z swills $

PORTNAME=	imagesize
PORTVERSION=	0.1.1
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	RubyGem for finding the size of an image

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
