# $FreeBSD: devel/rubygem-gitlab_meta/Makefile 332037 2013-10-30 02:34:55Z swills $

PORTNAME=	gitlab_meta
PORTVERSION=	6.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	GitLab meta gem

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes


.include <bsd.port.mk>
