# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: mail/hs-mime/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	mime
PORTVERSION=	0.3.4
PORTREVISION=	3
CATEGORIES=	mail haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Working with MIME types

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
