# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: mail/hs-mime/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	mime
PORTVERSION=	0.3.4
PORTREVISION=	4
CATEGORIES=	mail haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Working with MIME types

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
