# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: mail/hs-mime/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	mime
PORTVERSION=	0.3.4
PORTREVISION=	2
CATEGORIES=	mail haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Working with MIME types

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
