# Created by: Johann Visagie <johann@egenetics.com>
# $FreeBSD: devel/p5-File-Temp/Makefile 326734 2013-09-08 14:47:37Z az $

PORTNAME=	File-Temp
PORTVERSION=	0.23.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	leeym@FreeBSD.org
COMMENT=	Perl5 module to generate temporary files or directories safely

USES=		perl5
USE_PERL5=	configure

MAN3=		File::Temp.3

.include <bsd.port.mk>
