#!/bin/sh
#
# $FreeBSD: ports/games/formido/pkg-install,v 1.2 2012/11/17 05:57:38 svnexp Exp $

HISCOREDIR="/var/games/formido"

[ "$2" != "POST-INSTALL" -o -e "$HISCOREDIR" ] && exit 0 

echo "Creating hiscore directory..."
mkdir -p "$HISCOREDIR"

chgrp games "$HISCOREDIR"
chmod g+w "$HISCOREDIR"
