# Created by: will
# $FreeBSD: devel/p5-File-Cache/Makefile 331943 2013-10-29 12:52:07Z vanilla $

PORTNAME=	File-Cache
PORTVERSION=	0.16
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module implementing a persistent object store

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
