# Created by: will
# $FreeBSD: devel/p5-File-Cache/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	File-Cache
PORTVERSION=	0.16
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module implementing a persistent object store

USES=		perl5
USE_PERL5=	configure

MAN3=		File::Cache.3

NO_STAGE=	yes
.include <bsd.port.mk>
