# Created by: Miguel Mendez <flynn@energyhq.homeip.net>
# $FreeBSD: archivers/xpk/Makefile 328226 2013-09-25 00:54:08Z bdrewery $

PORTNAME=	xpk
PORTVERSION=	0.1.4
PORTREVISION=	1
CATEGORIES=	archivers
MASTER_SITES=	http://vesuri.jormas.com/xpk/ \
		http://www.energyhq.es.eu.org/files/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	The eXternal PacKer (XPK) library system

USE_AUTOTOOLS=	libtool
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
