# Created by: jnlin@csie.nctu.edu.tw
# $FreeBSD: devel/p5-Tie-ShareLite/Makefile 341710 2014-01-29 10:33:57Z az $

PORTNAME=	Tie-ShareLite
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jnlin@csie.nctu.edu.tw
COMMENT=	Tied hash interface to IPC::ShareLite

RUN_DEPENDS=	p5-IPC-ShareLite>=0:${PORTSDIR}/devel/p5-IPC-ShareLite

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
