# $FreeBSD: devel/p5-FindBin-libs/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	FindBin-libs
PORTVERSION=	1.8000
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:LEMBARK
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:C/000$//}

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to locate and use lib directories

USES=		perl5
USE_PERL5=	modbuild

MAN3=		FindBin::libs.3

NO_STAGE=	yes
.include <bsd.port.mk>
