# New ports collection makefile for:	p5-HTML-TableContentParser
# Date created:		2010-11-22
# Whom:			Steven Kreuzer <skreuzer@FreeBSD.org>
#
# $FreeBSD: ports/www/p5-HTML-TableContentParser/Makefile,v 1.3 2012/11/17 06:02:50 svnexp Exp $
#

PORTNAME=	HTML-TableContentParser
PORTVERSION=	0.13
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Do interesting things with the contents of tables

RUN_DEPENDS=	p5-HTML-Parser>=3.68:${PORTSDIR}/www/p5-HTML-Parser

PERL_CONFIGURE=	yes

MAN3=		HTML::TableContentParser.3

.include <bsd.port.mk>
