# New ports collection makefile for:	topless
# Date created:				Jun 11 2005
# Whom:					koma2@lovepeers.org
#
# $FreeBSD: ports/sysutils/topless/Makefile,v 1.7 2012/11/17 06:01:48 svnexp Exp $
#

PORTNAME=	topless
PORTVERSION=	1.52
CATEGORIES=	sysutils
MASTER_SITES=	http://people.freebsd.org/~daichi/src/

MAINTAINER=	koma2@lovepeers.org
COMMENT=	Display command output on the whole screen like "top"

USE_PERL5_BUILD=yes

MAN1=		topless.1
PLIST_FILES=	bin/topless

.include <bsd.port.mk>
