# New ports collection makefile for:	devel/p5-Data-Hierarchy
# Date created:				Mar 15 2004
# Whom:					Autrijus Tang <autrijus@autrijus.org>
#
# $FreeBSD: ports/devel/p5-Data-Hierarchy/Makefile,v 1.14 2012/11/17 05:56:10 svnexp Exp $
#

PORTNAME=	Data-Hierarchy
PORTVERSION=	0.34
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	rafan@FreeBSD.org
COMMENT=	Handle data in a hierarchical structure

TEST_DEPENDS=	p5-Test-Exception>=0:${PORTSDIR}/devel/p5-Test-Exception

PERL_CONFIGURE=	yes

MAN3=		Data::Hierarchy.3

.include <bsd.port.mk>
