# Created by: dbader@eece.unm.edu
# $FreeBSD: print/bibview/Makefile 342327 2014-02-02 16:05:24Z miwi $

PORTNAME=	bibview
PORTVERSION=	2.2
PORTREVISION=	2
CATEGORIES=	print databases
MASTER_SITES=	${MASTER_SITE_TEX_CTAN}
MASTER_SITE_SUBDIR= biblio/bibtex/utils/bibview-2.0

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Graphical interface for manipulating BibTeX bibliography databases


USES=		imake
USE_XORG=	ice sm x11 xaw xext xmu xt
WRKSRC=		${WRKDIR}/bibview-${PORTVERSION}

.include <bsd.port.mk>
