# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/py-zope.event/Makefile 404782 2015-12-29 20:02:47Z sunpoet $

PORTNAME=	zope.event
PORTVERSION=	4.1.0
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Very basic event publishing system

LICENSE=	ZPL21
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
