# $FreeBSD: math/hs-semigroupoids/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	semigroupoids
PORTVERSION=	3.0.2
PORTREVISION=	4
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 semigroupoids: Category sans id

LICENSE=	BSD

USE_CABAL=	comonad>=3.0 contravariant>=0.2.0.1 semigroups>=0.8.3.1 \
		transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
