# Ports collection makefile for:	rubygem-state_machine
# Date created:				27 April 2011
# Whom:					Eric Freeman <freebsdports@chillibear.com>
#
# $FreeBSD: ports/devel/rubygem-state_machine/Makefile,v 1.2 2012/11/17 05:57:01 svnexp Exp $
#

PORTNAME=	state_machine
PORTVERSION=	0.10.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	freebsdports@chillibear.com
COMMENT=	Support for creating state machines for attributes on any Ruby class

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
