# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD: devel/py-xmltodict/Makefile 330239 2013-10-13 16:59:18Z olivierd $

PORTNAME=	xmltodict
PORTVERSION=	0.8.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	xmj@chaot.net
COMMENT=	XML parser that returns python dictionaries

LICENSE=	MIT

USE_PYTHON=		yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes
PYTHON_PY3K_PLIST_HACK=	yes

.include <bsd.port.mk>
