# $FreeBSD: www/pear-Horde_Css_Parser/Makefile 332016 2013-10-29 21:46:58Z mm $

PORTNAME=	Horde_Css_Parser
PORTVERSION=	1.0.3
CATEGORIES=	www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde CSS Parser

NO_STAGE=	yes
.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
