# Created by: Mons Anderson <mons@cpan.org>
# $FreeBSD: devel/p5-common-sense/Makefile 339224 2014-01-09 13:14:30Z az $

PORTNAME=	common-sense
PORTVERSION=	3.6
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MLEHMANN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mons@cpan.org
COMMENT=	Perl common defaults with lower memory usage

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
