#!/bin/sh
#
# $FreeBSD: ports/security/pks/pkg-install,v 1.3 2012/11/17 06:01:16 svnexp Exp $

PKGNAME=$1
STAGE=$2

case ${STAGE} in
PRE-INSTALL)
	;;
POST-INSTALL)
	DBDIR=/var/pks/db
	MAILDIR=/var/pks/incoming

	mkdir -p ${DBDIR} ${MAILDIR}
	;;
*)
	echo "Unexpected argument: ${STAGE}"
	exit 1
	;;
esac
exit 0
