# Created by: Pawel Worach
# $FreeBSD: x11-fonts/font-adobe-75dpi/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	font-adobe-75dpi
PORTVERSION=	1.0.3
PORTREVISION=	1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Adobe 75dpi font

XORG_CAT=	font
USE_XORG=	fontutil

.include <bsd.port.mk>
