# Created by: TAKAHASHI Kaoru <kaoru@kaisei.org>
# $FreeBSD: devel/p5-Class-Accessor-Lite/Makefile 326823 2013-09-09 17:31:07Z az $

PORTNAME=	Class-Accessor-Lite
PORTVERSION=	0.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kaoru@kaisei.org
COMMENT=	Minimalistic variant of p5-Class-Accessor

USES=		perl5
USE_PERL5=	configure

MAN3=		Class::Accessor::Lite.3

.include <bsd.port.mk>
