
dfly-patch:
	${REINPLACE_CMD} -e 's@-lprocstat@@g' \
		${WRKSRC}/src/usr.sbin/httpd/Makefile
	-${REINPLACE_CMD} -e 's/TAILQ_FOREACH_SAFE/TAILQ_FOREACH_MUTABLE/g' \
		${WRKSRC}/src/usr.sbin/httpd/server.c \
		${WRKSRC}/src/usr.sbin/httpd/logger.c \
		${WRKSRC}/src/usr.sbin/httpd/parse.y
IGNORE=   unmaintained, please request fixing to users mailing list
