# New ports collection makefile for:	Crypt-TripleDES
# Date created:				Wed Jan  3 16:20:30 2001
# Whom:					will
#
# $FreeBSD: ports/security/p5-Crypt-TripleDES/Makefile,v 1.11 2012/11/17 06:01:12 svnexp Exp $
#

PORTNAME=	Crypt-TripleDES
PORTVERSION=	0.24
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl module implementing the Triple-DES cipher

PERL_CONFIGURE=	yes

MAN3=		Crypt::TripleDES.3

.include <bsd.port.mk>
