# Created by: Rui Lopes (rgl ruilopes com)
# $FreeBSD: devel/rubygem-tzinfo/Makefile 335529 2013-12-02 18:36:18Z sunpoet $

PORTNAME=	tzinfo
PORTVERSION=	0.3.38
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Daylight-savings aware timezone support for Ruby

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
