# Ports collection makefile for:  pear-Horde_Routes
# Date created:			  7 July 2011
# Whom:				  Martin Matuska <mm@FreeBSD.org>
#
# $FreeBSD: ports/www/pear-Horde_Routes/Makefile,v 1.8 2013/01/10 10:41:49 svnexp Exp $

PORTNAME=	Horde_Routes
PORTVERSION=	2.0.2
CATEGORIES=	www pear
MASTER_SITES=	http://pear.horde.org/get/

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Routes URL mapping system

USE_HORDE_RUN=	Horde_Exception \
		Horde_Util

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
