# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-blockenspiel/Makefile 313313 2013-03-03 01:27:25Z swills $

PORTNAME=	blockenspiel
PORTVERSION=	0.4.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library designed to make it easy to implement DSL blocks in Ruby

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
