# Created by: clsung@dragon2.net
# $FreeBSD: devel/p5-Algorithm-Networksort/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Algorithm-Networksort
PORTVERSION=	1.30
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module that will create sorting networks

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		Algorithm::Networksort.3

.include <bsd.port.mk>
