# Created by: James Bailie <jimmy@mammothcheese.ca>
# $FreeBSD: www/drood/Makefile 329806 2013-10-08 16:12:18Z tabthorpe $

PORTNAME=	drood
PORTVERSION=	3.8
CATEGORIES=	www
MASTER_SITES=	http://www.mammothcheese.ca/

MAINTAINER=	jimmy@mammothcheese.ca
COMMENT=	Lightweight kqueue-based http/1.1 server

MAN8=		drood.8

MANCOMPRESSED=	yes

NO_STAGE=	yes

.include <bsd.port.mk>
