# Created by: Andrea Sozzi <as@g-cows.org>
# $FreeBSD: www/g-cows/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	g-cows
PORTVERSION=	1.12
CATEGORIES=	www
MASTER_SITES=	http://www.g-cows.org/download/1.12/

MAINTAINER=	as@g-cows.org
COMMENT=	Scripting language for creation of web sites

GNU_CONFIGURE=	YES

PLIST_FILES=	bin/cows \
		bin/cows-mkgen

.include <bsd.port.mk>
