# Created by: Maxim Sobolev <sobomax@FreeBSD.org>
# $FreeBSD: devel/p5-Class-Generate/Makefile 331856 2013-10-28 13:46:25Z vanilla $

PORTNAME=	Class-Generate
PORTVERSION=	1.11
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to simplify creating class hierarchies

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
