# New ports collection makefile for:	Class:Generate
# Date created:				24 October 2002
# Whom:					Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Class-Generate/Makefile,v 1.13 2012/11/17 05:56:07 svnexp Exp $
#

PORTNAME=	Class-Generate
PORTVERSION=	1.11
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	A Perl5 module to simplify creating class hierarchies

PERL_CONFIGURE=	yes

MAN3=		Class::Generate.3

.include <bsd.port.mk>
