# Created by: Maxim Sobolev <sobomax@FreeBSD.org>
# $FreeBSD: devel/p5-Class-Generate/Makefile 315509 2013-03-29 00:44:53Z eadler $

PORTNAME=	Class-Generate
PORTVERSION=	1.11
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to simplify creating class hierarchies

PERL_CONFIGURE=	yes

MAN3=		Class::Generate.3

.include <bsd.port.mk>
