# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: devel/py-tgMochiKit/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	tgMochiKit
PORTVERSION=	1.4.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	MochiKit packaged as TurboGears widgets

USE_PYTHON=		yes
USE_PYDISTUTILS=	easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
