# $FreeBSD: x11/x11perf/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	x11perf
PORTVERSION=	1.5.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X11 server performance test program

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	x11 xmuu xrender xft xext

MAN1=		Xmark.1 \
		x11perf.1 \
		x11perfcomp.1

.include <bsd.port.mk>
