# Created by: Wen Heping<wen@FreeBSD.org>
# $FreeBSD: devel/p5-System-Command/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	System-Command
PORTVERSION=	1.103
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Object for running system commands

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		System::Command.3

.include <bsd.port.mk>
