# New ports collection makefile for:	xkbcomp
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xkbcomp/Makefile,v 1.5 2012/11/17 06:03:21 svnexp Exp $
#

PORTNAME=	xkbcomp
PORTVERSION=	1.2.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Compile XKB keyboard description

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	x11 xkbfile

PLIST_FILES=	bin/xkbcomp

MAN1=		xkbcomp.1

.include <bsd.port.mk>
