#!/bin/sh
#
# $FreeBSD: databases/pgpool-II-22/files/pgpool_remote_start 300896 2012-07-14 13:54:48Z beat $

DEST=pgsql@$1

logger="logger -t pgpool -p local0.info"

/bin/sh <<EOF | ${logger} 2>&1

ssh $DEST '/usr/local/etc/rc.d/postgresql start'

EOF
