# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: devel/pear-Horde_Timezone/Makefile 332016 2013-10-29 21:46:58Z mm $

PORTNAME=	Horde_Timezone
PORTVERSION=	1.0.4
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde timezone library

USE_HORDE_RUN=	Horde_Date \
		Horde_Icalendar \
		Horde_Vfs

NO_STAGE=	yes
.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
