# $FreeBSD: net/rubygem-omniauth-twitter/Makefile 332047 2013-10-30 02:53:47Z swills $

PORTNAME=	omniauth-twitter
PORTVERSION=	1.0.1
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	OmniAuth strategy for Twitter

RUN_DEPENDS=	rubygem-multi_json>=1.3:${PORTSDIR}/devel/rubygem-multi_json \
		rubygem-omniauth-oauth>=1.0:${PORTSDIR}/net/rubygem-omniauth-oauth

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes


.include <bsd.port.mk>
