# New ports collection makefile for:    arm-rtems-binutils
# Date created:         12 April 2001
# Whom:                 James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/arm-rtems-binutils/Makefile,v 1.8 2012/11/17 05:55:33 svnexp Exp $
#

MAINTAINER=	ports@FreeBSD.org

TGTARCH=	arm
TGTABI=		rtems
WITH_RTEMS_PATCHES=	yes

MASTERDIR=	${.CURDIR}/../cross-binutils
.include "${MASTERDIR}/Makefile"
