# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-rspec-core/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	rspec-core
PORTVERSION=	2.14.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	RSpec Core provides the structure for writing executable examples

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/autospec bin/rspec

NO_STAGE=	yes
.include <bsd.port.mk>
