# Created by: glen.j.barber@gmail.com
# $FreeBSD: security/clamd-stream-client/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	clamd-stream-client
DISTVERSION=	1.3
CATEGORIES=	security
MASTER_SITES=	SF/clamd-stream-cl/${PORTNAME}/${DISTVERSION}

MAINTAINER=	gjb@FreeBSD.org
COMMENT=	Standalone clamav client

HAS_CONFIGURE=	yes
PLIST_FILES=	bin/clamd-stream-client

NO_STAGE=	yes
.include <bsd.port.mk>
