# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-Lingua-EN-Infinitive/Makefile 333056 2013-11-07 03:52:41Z vanilla $

PORTNAME=	Lingua-EN-Infinitive
PORTVERSION=	1.11
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
EXTRACT_SUFX=	.tgz

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Determine the infinitive form of a conjugated word

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
