# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-Lingua-EN-Infinitive/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Lingua-EN-Infinitive
PORTVERSION=	1.11
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
EXTRACT_SUFX=	.tgz

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Determine the infinitive form of a conjugated word

USES=		perl5
USE_PERL5=	configure

MAN3=		Lingua::EN::Infinitive.3

.include <bsd.port.mk>
