# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: devel/py-six/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	six
PORTVERSION=	1.5.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Python 2 and 3 compatibility utilities

LICENSE=	MIT

USE_PYTHON=		yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
