# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-atomic/Makefile 338168 2013-12-30 20:55:18Z ohauer $

PORTNAME=	atomic
PORTVERSION=	1.1.14
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Atomic reference implementation

LICENSE=	APACHE20

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
