# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-atomic/Makefile 331400 2013-10-23 18:01:14Z swills $

PORTNAME=	atomic
PORTVERSION=	1.1.14
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Atomic reference implementation

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes

.include <bsd.port.mk>
