# Created by: chinsan <chinsan.tw@gmail.com>
# $FreeBSD: ports/www/xpi-web_developer/Makefile,v 1.13 2013/02/03 21:04:30 svnexp Exp $

PORTNAME=	web_developer
PORTVERSION=	1.2.2
DISTVERSIONSUFFIX=	-fx+sm
CATEGORIES=	www

MAINTAINER=	geckoFreeBSD.org
COMMENT=	An extension to add various web developer tools

XPI_NUM=	60
XPI_ID=		{c45c406e-ab73-11d8-be73-000a95be3b12}

.include "../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
