# Created by: Stephen Montgomery-Smith <stephen@math.missouri.edu>
# $FreeBSD: math/octave-forge-zenity/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	octave-forge-zenity
PORTVERSION=	0.5.7
PORTREVISION=	8
CATEGORIES=	math

MAINTAINER=	stephen@FreeBSD.org
COMMENT=	Octave-forge package ${OCTAVE_PKGNAME}

LICENSE=	GPLv2

GNU_CONFIGURE=	yes

RUN_DEPENDS+=	zenity:${PORTSDIR}/x11/zenity

.include "${.CURDIR}/../../Mk/bsd.octave.mk"
.include <bsd.port.mk>
