# Created by: Daniel Roethlisberger <daniel@roe.ch>
# $FreeBSD: textproc/rubygem-rdiscount/Makefile 321657 2013-06-23 21:26:52Z swills $

PORTNAME=	rdiscount
PORTVERSION=	2.1.6
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A fast Markdown converter for ruby based on discount

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/rdiscount

.include <bsd.port.mk>
