# $FreeBSD: ports/devel/p5-B-Size2/Makefile,v 1.1 2013/01/17 23:46:07 svnexp Exp $

PORTNAME=	B-Size2
PORTVERSION=	2.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to measure size of Perl OPs and SVs

PERL_CONFIGURE=	yes

MAN3=	B::Size2.3 \
	B::Size2::Terse.3

.include <bsd.port.mk>
