
# bauer/../tpl/sparse_tpl.h:60:11: error: binding reference of type 'koord&' to 'const koord' discards qualifiers
#    return size;
CXXFLAGS= -Wno-c++11-narrowing
BUILD_DEPENDS+= clang60:devel/llvm60
MAKE_ARGS+= CC=clang60 CXX=clang++60
