# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: net/rubygem-amq-protocol/Makefile 322470 2013-07-08 01:50:31Z clsung $

PORTNAME=	amq-protocol
PORTVERSION=	1.6.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	An AMQP serialization library for Ruby

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
