# New ports collection makefile for:	atk-reference
# Date created:				09 May 2006
# Whom:					Jean-Yves Lefort <jylefort@FreeBSD.org>
#
# $FreeBSD: ports/accessibility/atk-reference/Makefile,v 1.3 2012/11/17 05:54:19 svnexp Exp $
#

PORTREVISION=	0

REFERENCE_SRC=	${WRKSRC}/docs

.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
