dflypri_args1= enable_basic_printing=true enable_print_preview=true use_dbus=true use_udev=false
# not needed here: use_system_yasm only if bundled jpeg_turbo and use_system_libusb no longer available
#dflypri_args2= use_system_yasm=true #use_system_libusb=true

# zrj: first remove some crud then create config and patch
dfly-patch:
	${REINPLACE_CMD} -e '/"cxxrt"/d' \
		${WRKSRC}/src/3rdparty/chromium/third_party/blink/renderer/platform/BUILD.gn
	${REINPLACE_CMD} -e '/-fgnu-inline-asm/d' \
		${WRKSRC}/src/3rdparty/chromium/sandbox/linux/BUILD.gn
	${RM} -rf ${WRKSRC}/src/3rdparty/chromium/third_party/tcmalloc
#	${CP} ${WRKSRC}/src/core/config/freebsd.pri ${WRKSRC}/src/core/config/dragonfly.pri
# missing remove for files/patch-src_3rdparty_chromium_build_linux_unbundle_libwebp.gn
	${REINPLACE_CMD} -e '/use_system_libwebp/d' ${WRKSRC}/src/core/config/linux.pri
	${ECHO} 'include(linux.pri)' > ${WRKSRC}/src/core/config/dragonfly.pri
	${ECHO} "gn_args += ${dflypri_args1}" >> ${WRKSRC}/src/core/config/dragonfly.pri
#	${ECHO} "gn_args += ${dflypri_args2}" >> ${WRKSRC}/src/core/config/dragonfly.pri
	${REINPLACE_CMD} -e 's@freebsd.pri@dragonfly.pri@g' \
		${WRKSRC}/mkspecs/features/functions.prf
	${CP} ${WRKSRC}/src/3rdparty/chromium/base/process/process_handle_freebsd.cc \
		${WRKSRC}/src/3rdparty/chromium/base/process/process_handle_dragonfly.cc
	${CP} ${WRKSRC}/src/3rdparty/chromium/base/process/process_iterator_freebsd.cc \
		${WRKSRC}/src/3rdparty/chromium/base/process/process_iterator_dragonfly.cc
	${CP} ${WRKSRC}/src/3rdparty/chromium/base/process/process_metrics_freebsd.cc \
		${WRKSRC}/src/3rdparty/chromium/base/process/process_metrics_dragonfly.cc
	${CP} ${WRKSRC}/src/3rdparty/chromium/base/system/sys_info_freebsd.cc \
		${WRKSRC}/src/3rdparty/chromium/base/system/sys_info_dragonfly.cc
