# Created by: Pawel Pekala <c0rn@o2.pl>
# $FreeBSD: mail/claws-mail-attach_warner/Makefile 317877 2013-05-11 14:10:28Z pawel $

PORTNAME=	attach_warner
PORTREVISION=	0

COMMENT=	Not attached file warning plugin for Claws Mail

CLAWS_PLUGINS_BUILD=	attachwarner

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
