# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: databases/p5-DR-Tarantool/Makefile 341764 2014-01-29 17:31:52Z az $

PORTNAME=	DR-Tarantool
PORTVERSION=	0.37
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:UNERA
PKGNAMEPREFIX=	p5-

MAINTAINER=	vg@FreeBSD.org
COMMENT=	Perl driver for Tarantool

LICENSE=	ART10

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
