# New ports collection makefile for:	twiki-TinyMCEPlugin
# Date created:		17 April 2008
#
# $FreeBSD: ports/www/twiki-TinyMCEPlugin/Makefile,v 1.3 2012/11/17 06:03:09 svnexp Exp $
#

PORTNAME=	TinyMCEPlugin
SVNREV=		17303

COMMENT=	TinyMCE WYSIWYG editor integration

TWDEP=		BehaviourContrib>=15357 WysiwygPlugin>=16650

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
