# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: devel/py-flexmock/Makefile 321438 2013-06-21 03:34:36Z clsung $

PORTNAME=	flexmock
PORTVERSION=	0.9.7
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	Flexmock is a mock/stub/spy library for Python

USE_PYTHON=	2.5+
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
