# New ports collection makefile for:	flexmock
# Date created:				4 Nov 2011
# Whom:					Cheng-Lung Sung <clsung@FreeBSD.org>
#
# $FreeBSD: ports/devel/py-flexmock/Makefile,v 1.5 2012/11/17 05:56:46 svnexp Exp $
#

PORTNAME=	flexmock
PORTVERSION=	0.9.6
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	Flexmock is a mock/stub/spy library for Python

USE_PYTHON=	2.5+
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
