# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: graphics/gstreamer-plugins-opencv/Makefile 335601 2013-12-04 02:51:00Z jhale $

PORTREVISION=	1
CATEGORIES=	graphics

COMMENT=	Gstreamer opencv real time computer vision plugin

GST_PLUGIN=	opencv

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
