# Created by: clsung
# $FreeBSD: textproc/p5-Text-Affixes/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Text-Affixes
PORTVERSION=	0.07
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for prefixes and suffixes analisys of text

USES=		perl5
USE_PERL5=	configure

MAN3=		Text::Affixes.3

.include <bsd.port.mk>
