# New ports collection makefile for:	R-cran-AMORE
# Date created:				March 07, 2011
# Whom:					Wen Heping <wenheping@gmail.com>
#
# $FreeBSD: ports/science/R-cran-AMORE/Makefile,v 1.11 2012/11/17 06:00:56 svnexp Exp $
#

PORTNAME=	AMORE
PORTVERSION=	0.2.12
PORTREVISION=	8
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${PORTVERSION:C/\./-/g:C/-/\./1}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	A MORE flexible neural network package

USE_R_MOD=  		yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
