# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: ports/science/R-cran-AMORE/Makefile,v 1.12 2013/01/04 18:45:37 svnexp Exp $

PORTNAME=	AMORE
PORTVERSION=	0.2.12
PORTREVISION=	9
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${PORTVERSION:C/\./-/g:C/-/\./1}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	A MORE flexible neural network package

USE_R_MOD=  		yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
