# Created by: Andrew Maltsev <am@amsoft.ru>
# $FreeBSD: www/ruboard/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	ruboard
PORTVERSION=	1.2.2
CATEGORIES=	www russian
MASTER_SITES=	http://amsoft.ru/pub/ruboard/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A web based discussion board

USES=		perl5

NO_STAGE=	yes
.include <bsd.port.mk>
