# Ports collection makefile for:	daemons
# Date created:				20 May 2006
# Whom:					Rui Lopes (<rgl ruilopes com>)
#
# $FreeBSD: ports/devel/rubygem-daemons/Makefile,v 1.26 2012/11/17 05:56:58 svnexp Exp $

PORTNAME=	daemons
PORTVERSION=	1.1.9
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A toolkit to convert your script to a controllable daemon

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
