# $FreeBSD: audio/gstreamer1-plugins-opus/Makefile 316693 2013-04-27 20:56:38Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer Opus audio encoder/decoder plugin

GST_PLUGIN=	opus
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
