# Created by: Anish Mistry (<amistry@am-productions.biz>)
# $FreeBSD: devel/pear-Validate_Finance/Makefile 333263 2013-11-08 21:41:53Z antoine $

PORTNAME=	Validate_Finance
PORTVERSION=	0.5.6
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR Finance Validation class

BUILD_DEPENDS=	pear-Validate>=0.5.0:${PORTSDIR}/devel/pear-Validate
RUN_DEPENDS=	pear-Validate>=0.5.0:${PORTSDIR}/devel/pear-Validate

PEAR_AUTOINSTALL=	yes

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.mk"
.include <bsd.port.post.mk>
