# Created by: Rong-En Fan <rafan@FreeBSD.org>
# $FreeBSD: devel/p5-App-Control/Makefile 341711 2014-01-29 10:57:06Z az $

PORTNAME=	App-Control
PORTVERSION=	1.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	rafan@FreeBSD.org
COMMENT=	An apachectl style control of another script or executable

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
