# New ports collection makefile for:	p5-File-Tempdir
# Date created:		2007-01-02
# Whom:	      		loader <loader@freebsdmall.com>
#
# $FreeBSD: ports/devel/p5-File-Tempdir/Makefile,v 1.4 2012/11/17 05:56:16 svnexp Exp $
#

PORTNAME=	File-Tempdir
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	loader@freebsdmall.com
COMMENT=	Perl5 module to provide an object interface for File::Temp

PERL_CONFIGURE=	yes

MAN3=		File::Tempdir.3

.include <bsd.port.mk>
