# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-coffee-script-source/Makefile 338241 2013-12-31 06:58:37Z sunpoet $

PORTNAME=	coffee-script-source
PORTVERSION=	1.6.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	CoffeeScript is a little language that compiles into JavaScript

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
