# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-coffee-script-source/Makefile 332035 2013-10-30 02:31:04Z swills $

PORTNAME=	coffee-script-source
PORTVERSION=	1.6.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	CoffeeScript is a little language that compiles into JavaScript

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
