# New ports collection makefile for:    jdictionary-eng-ger
# Date created:         		20.12.2004
# Whom:                 		hq@FreeBSD.org
#
# $FreeBSD: ports/german/jdictionary-eng-ger/Makefile,v 1.5 2012/11/17 05:57:59 svnexp Exp $
#

PORTNAME=	jdictionary-eng-ger
PORTVERSION=	1.4
PORTREVISION=	2
CATEGORIES=	german textproc
MASTER_SITES=	SF/jdictionary/Plugins%20for%20jDictionary/Smart%20English-German
DISTNAME=	SmartEngGer-1_4.jar

COMMENT=	JDictionary plugin: English-German dictionary

MASTERDIR=	${.CURDIR}/../../textproc/jdictionary

.include "${MASTERDIR}/Makefile.plugin"
