# $FreeBSD: ports/portuguese/libreoffice-pt_BR/Makefile,v 1.3 2012/11/17 06:00:47 svnexp Exp $

LO_I18N=	pt_BR
LO_HAS_HELPPACK=	yes
CATEGORIES=	portuguese editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
