# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: security/pear-Horde_Perms/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Horde_Perms
PORTVERSION=	2.1.2
CATEGORIES=	security www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Permissions System

USE_HORDE_RUN=	Horde_Db \
		Horde_Exception \
		Horde_Group \
		Horde_Util \
		Horde_Translation

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
