# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: ports/math/R-cran-bdsmatrix/Makefile,v 1.6 2013/01/04 18:45:35 svnexp Exp $

PORTNAME=	bdsmatrix
PORTVERSION=	1.3
PORTREVISION=	4
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Routines for Block Diagonal Symmetric matrices

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
