--- cmake/modules/DetectMachine.cmake.intermediate	2019-10-29 10:11:54.000000000 +0000
+++ cmake/modules/DetectMachine.cmake
@@ -4,7 +4,7 @@ ELSEIF(APPLE)
 	SET(LMMS_BUILD_APPLE 1)
 ELSEIF(${CMAKE_SYSTEM_NAME} MATCHES "OpenBSD")
 	SET(LMMS_BUILD_OPENBSD 1)
-ELSEIF(${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")
+ELSEIF(${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD|DragonFly")
 	SET(LMMS_BUILD_FREEBSD 1)
 ELSEIF(HAIKU)
 	SET(LMMS_BUILD_HAIKU 1)
