# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: print/rubygem-afm/Makefile 327765 2013-09-20 22:43:59Z bapt $

PORTNAME=	afm
PORTVERSION=	0.2.0
CATEGORIES=	print rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Read AFM files and use the data conveniently

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
