# New ports collection makefile for:	tracker-gnome
# Date created:		2008-03-30
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD: ports/sysutils/tracker-gnome/Makefile,v 1.10 2012/11/17 06:01:48 svnexp Exp $
#    $MCom: ports/sysutils/tracker-gnome/Makefile,v 1.4 2009/08/08 18:46:42 ahze Exp $

PORTREVISION=	3

COMMENT=	Tracker GNOME applet, search tool, and preference programs

TRACKER_SLAVE=	gnome
PLIST=		${.CURDIR}/pkg-plist
MASTERDIR=	${.CURDIR}/../../sysutils/tracker-client

.include "${MASTERDIR}/Makefile"
