# New ports collection makefile for:	p5-Module-Reload-Selective
# Date created:		25 April 2005
# Whom:	      		simond@irrelevant.org
#
# $FreeBSD: ports/devel/p5-Module-Reload-Sel/Makefile,v 1.3 2012/11/17 05:56:22 svnexp Exp $
#

PORTNAME=	Module-Reload-Sel
PORTVERSION=	1.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	simond@irrelevant.org
COMMENT=	Reload perl library files when updated on disk

PERL_CONFIGURE=	yes

MAN3=		Module::Reload::Selective.3

.include <bsd.port.mk>
