# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: sysutils/p5-Shell-Command/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Shell-Command
PORTVERSION=	0.06
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Cross-platform functions emulating common shell commands

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
