# New ports collection makefile for:	Perl-OSType
# Date created:	   03 Mar 2011
# Whom:		   Sergey Skvortsov <skv@protey.ru>
#
# $FreeBSD: ports/devel/p5-Perl-OSType/Makefile,v 1.2 2012/11/17 05:56:26 svnexp Exp $
#

PORTNAME=	Perl-OSType
PORTVERSION=	1.002
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Map Perl operating system names to generic types

PERL_CONFIGURE=	YES

MAN3=		Perl::OSType.3

.include <bsd.port.mk>
