CONFIGURE_ARGS:= fixed-dragonfly

dfly-patch:
	${CP} ${WRKSRC}/config.fixed-freebsd ${WRKSRC}/config.fixed-dragonfly
	${REINPLACE_CMD} -e 's/(INCLUDES)/& -I\/usr\/local\/include /' ${WRKSRC}/config.fixed-dragonfly
	${REINPLACE_CMD} -e "s@LIBRARY_LINK_OPTS)@& -L${LOCALBASE}/lib -lcrypto@g" \
		${WRKSRC}/liveMedia/Makefile.tail

