# Created by: Akinori MUSHA aka knu <knu@idaemons.org>
# $FreeBSD: devel/p5-String-Ediff/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	String-Ediff
PORTVERSION=	0.09
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to produce common sub-string indices for two strings

USES=		perl5
USE_PERL5=	configure

MAN3=		String::Ediff.3

NO_STAGE=	yes
.include <bsd.port.mk>
