# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: devel/R-cran-RUnit/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	RUnit
PORTVERSION=	0.4.26
PORTREVISION=	3
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R functions implementing a Unit Testing framework

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
