# $FreeBSD: russian/stardict-bars/Makefile 327766 2013-09-20 22:46:16Z bapt $

PORTNAME=	stardict-bars
PORTVERSION=	2.4.2
CATEGORIES=	russian
MASTER_SITES=	http://yeelou.com/huzheng/stardict-dic/ru/
DISTNAME=	stardict-en-ru-bars-${PORTVERSION}

MAINTAINER=	makc@FreeBSD.org
COMMENT=	New Comprehensive English-Russian dictionary

NO_STAGE=	yes
.include "${.CURDIR}/../stardict-mueller7/files/Makefile.common"
.include <bsd.port.mk>
