# Created by: Yar Tikhiy <yar@comp.chem.msu.su>
# $FreeBSD: audio/p5-CDDB/Makefile 332336 2013-11-01 02:28:24Z vanilla $

PORTNAME=	CDDB
PORTVERSION=	1.222
CATEGORIES=	audio perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	High-level interface to the Compact Disc Database

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
