# Created by: Emanuel Haupt <ehaupt@FreeBSD.org>
# $FreeBSD: converters/drg2sbg/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	drg2sbg
PORTVERSION=	2.2
CATEGORIES=	converters audio
MASTER_SITES=	GOOGLE_CODE

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Convert propiatary .drg file format into SBaGen format

LICENSE=	GPLv2

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/drg2sbg bin/drgbuilder man/man1/drg2sbg.1.gz \
		man/man1/drgbuilder.1.gz

.include <bsd.port.mk>
