# Created by: Ilia Chipitsine <ilia@cgu.chel.su>
# $FreeBSD: head/devel/p5-String-Approx/Makefile 332205 2013-10-31 07:36:25Z vanilla $

PORTNAME=	String-Approx
PORTVERSION=	3.27
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for approximate matching (fuzzy matching)

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
