# Ports collection makefile for: bash-static
# Date created:			 22 Jan 2009
# Whom:				 Emanuel Haupt <ehaupt@FreeBSD.org>
#
# $FreeBSD: ports/shells/bash-static/Makefile,v 1.2 2012/11/17 06:01:23 svnexp Exp $
#

MASTERDIR=	${.CURDIR}/../../shells/bash

WITH_STATIC_BASH=	yes

.include "${MASTERDIR}/Makefile"
