# Created by:  Emanuel Haupt <ehaupt@FreeBSD.org>
# $FreeBSD: shells/bash-static/Makefile 317405 2013-05-05 08:39:30Z bapt $

MASTERDIR=	${.CURDIR}/../../shells/bash

OPTIONS_SLAVE=	STATIC

.include "${MASTERDIR}/Makefile"
