# New ports collection makefile for:    hil-aspell
# Date created:                         02 June 2005
# Whom:                                 Thierry Thomas <thierry@pompo.net>
#
# $FreeBSD: ports/textproc/hil-aspell/Makefile,v 1.7 2012/11/17 06:01:57 svnexp Exp $
#

PORTNAME=	${DICT}-aspell
DISTVERSION=	5-hil-0.11-0
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Hiligaynon dictionary

DICT=	 	hil

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
