# Created by: Dryice Liu <dryice@FreeBSD.org>
# $FreeBSD: www/py-beaker/Makefile 323086 2013-07-16 05:02:29Z wen $

PORTNAME=	beaker
PORTVERSION=	1.6.4
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Beaker-${PORTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	A Session and Caching library with WSGI Middleware

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install
PYDISTUTILS_PKGNAME=	Beaker

.include <bsd.port.mk>
