# New ports collection makefile for:	kde4-l10n
# Date created:		2009-01-25
# Whom:			Max Brazhnikov <makc@FreeBSD.org>
#
# $FreeBSD: ports/hebrew/kde4-l10n/Makefile,v 1.68 2012/11/17 05:58:27 svnexp Exp $
#

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
CATEGORIES?=	hebrew kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Hebrew messages and documentation for KDE4

KDE4_L10N=	he

.include "${.CURDIR}/../../misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
