# $FreeBSD: hebrew/kde4-l10n/Makefile 327734 2013-09-20 18:41:52Z bapt $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
CATEGORIES=	hebrew kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Hebrew messages and documentation for KDE SC 4

KDE4_L10N=	he

NO_STAGE=	yes
.include "${.CURDIR}/../../misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
