# Created by: Dirk Froemberg <dirk@FreeBSD.org>
# $FreeBSD: german/php_doc/Makefile 327732 2013-09-20 18:30:00Z bapt $

CATEGORIES=	german lang
PKGNAMEPREFIX=
PHP_LANG=	de
MASTERDIR=	${.CURDIR}/../../lang/php_doc

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
