# Created by: Klaus T. Aehlig <aehlig@linta.de>
# $FreeBSD: devel/py-wsgitools/Makefile 314550 2013-03-18 10:23:47Z culot $

PORTNAME=	wsgitools
PORTVERSION=	0.2.4
CATEGORIES=	devel
MASTER_SITES=	http://subdivi.de/~helmut/darcs/${PORTNAME}/dist/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	aehlig@linta.de
COMMENT=	Useful middlewares and filters for wsgi as well as scgi servers

LICENSE=	GPLv2                    # or higher

USE_PYTHON=	2.5-2.7
USE_PYDISTUTILS=yes

.include <bsd.port.mk>
