# Ports collection Makefile for:	MarkupSafe
# Date created:				Sep 08, 2010
# Whom:					wen@FreeBSD.org
#
# $FreeBSD: ports/textproc/py-MarkupSafe/Makefile,v 1.4 2012/11/17 06:02:17 svnexp Exp $
#

PORTNAME=		MarkupSafe
PORTVERSION=		0.15
CATEGORIES=		textproc python
MASTER_SITES=		CHEESESHOP
PKGNAMEPREFIX=		${PYTHON_PKGNAMEPREFIX}

MAINTAINER=		wen@FreeBSD.org
COMMENT=		Implements a XML/HTML/XHTML Markup safe string for Python

LICENSE=		BSD

USE_PYTHON=		yes
USE_PYDISTUTILS=	easy_install
PYEASYINSTALL_ARCHDEP=	no

.include <bsd.port.mk>
