# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: www/rubygem-http-cookie/Makefile 332054 2013-10-30 03:01:19Z swills $

PORTNAME=	http-cookie
PORTVERSION=	1.0.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby library to handle HTTP Cookies

RUN_DEPENDS=	rubygem-domain_name>=0.5.1:${PORTSDIR}/net/rubygem-domain_name

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
