# $FreeBSD: ports/textproc/nunnimcax/files/Makefile,v 1.2 2012/11/17 06:02:03 svnexp Exp $

LIB = 	NunniMCAX
SRCS=	NunniCXMLParser.c NunniCXMLParserFSM.c NunniHashtable.c NunniStack.c
INCS=	NunniMCAX.h

SHLIB_MAJOR=	%%SHLIB_MAJOR%%

LIBDIR=		${PREFIX}/lib
INCLUDEDIR=	${PREFIX}/include

.include <bsd.lib.mk>
