# $FreeBSD: textproc/nunnimcax/files/Makefile 300897 2012-07-14 14:29:18Z beat $

LIB = 	NunniMCAX
SRCS=	NunniCXMLParser.c NunniCXMLParserFSM.c NunniHashtable.c NunniStack.c
INCS=	NunniMCAX.h

SHLIB_MAJOR=	%%SHLIB_MAJOR%%

LIBDIR=		${PREFIX}/lib
INCLUDEDIR=	${PREFIX}/include

.include <bsd.lib.mk>
