# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: ports/math/R-cran-sm/Makefile,v 1.23 2013/01/04 18:45:35 svnexp Exp $

PORTNAME=	sm
DISTVERSION=	2.2-4.1
PORTREVISION=	9
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Smoothing methods for nonparametric regression and density estimation

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
