# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: math/R-cran-sm/Makefile 319316 2013-05-28 15:15:05Z bf $

PORTNAME=	sm
DISTVERSION=	2.2-4.1
PORTREVISION=	11
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Smoothing methods for nonparametric regression and density estimation

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
