# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: math/R-cran-sm/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	sm
DISTVERSION=	2.2-5.3
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Smoothing methods for nonparametric regression and density estimation

USES=	cran:auto-plist

.include <bsd.port.mk>
