# New ports collection makefile for:	rubygem-capistrano-ext
# Date created:		2011-08-24
# Whom:			Steve Wills <swills@FreeBSD.org>
#
# $FreeBSD: ports/sysutils/rubygem-capistrano-ext/Makefile,v 1.3 2012/11/17 06:01:44 svnexp Exp $
#

PORTNAME=	capistrano-ext
PORTVERSION=	1.2.1
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Useful task libraries and methods for Capistrano

RUN_DEPENDS=	rubygem-capistrano>=1.0.0:${PORTSDIR}/sysutils/rubygem-capistrano

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
