# New ports collection makefile for:	jumpgate
# Date created:				20 March 2001
# Whom:	      				Yen-Ming Lee <leeym@FreeBSD.org>
#
# $FreeBSD: ports/net/jumpgate/Makefile,v 1.8 2012/11/17 06:00:03 svnexp Exp $
#

PORTNAME=	jumpgate
PORTVERSION=	0.7
CATEGORIES=	net
MASTER_SITES=	http://jumpgate.sourceforge.net/

MAINTAINER=	leeym@FreeBSD.org
COMMENT=	TCP connection forwarder

GNU_CONFIGURE=	yes

MAN8=		jumpgate.8
PLIST_FILES=	sbin/jumpgate

.include <bsd.port.mk>
