# Created by: Yen-Ming Lee <leeym@FreeBSD.org>
# $FreeBSD: net/jumpgate/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	jumpgate
PORTVERSION=	0.7
CATEGORIES=	net
MASTER_SITES=	http://jumpgate.sourceforge.net/

MAINTAINER=	leeym@FreeBSD.org
COMMENT=	TCP connection forwarder

GNU_CONFIGURE=	yes

MAN8=		jumpgate.8
PLIST_FILES=	sbin/jumpgate

NO_STAGE=	yes
.include <bsd.port.mk>
