# Created by: Greg Larkin <glarkin@FreeBSD.org>
# $FreeBSD: textproc/p5-File-Inplace/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	File-Inplace
PORTVERSION=	0.20
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	glarkin@FreeBSD.org
COMMENT=	Perl module for in-place editing of files

USES=		perl5
USE_PERL5=	configure

MAN3=		File::Inplace.3

NO_STAGE=	yes
.include <bsd.port.mk>
