
USES:=	${USES:Nncurses*} ncurses

dfly-patch:
	${REINPLACE_CMD} -e 's@<curses.h>@<ncurses.h>@g' \
		${WRKSRC}/edlis.c \
		${WRKSRC}/main.c \
		${WRKSRC}/term.h \
		${WRKSRC}/library/virtty.lsp
	${REINPLACE_CMD} -e 's@FreeBSD@DragonFly@g' \
		${WRKSRC}/function.c
