# Ports collection makefile for:  pear-mailparse
# Date created:			  09 January 2003
# Whom:				  Thierry Thomas (<thierry@pompo.net>)
#
# $FreeBSD: ports/mail/pecl-mailparse/Makefile,v 1.21 2012/11/17 05:59:10 svnexp Exp $
#

PORTNAME=	mailparse
PORTVERSION=	2.1.6
CATEGORIES=	mail www
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
EXTRACT_SUFX=	.tgz
DIST_SUBDIR=	PECL

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PECL extension to create and decode MIME messages

USE_PHP=	mbstring
USE_PHPIZE=	yes
USE_PHP_BUILD=	yes
USE_PHPEXT=	yes
PHP_MODNAME=	mailparse

.include <bsd.port.mk>
