.if defined(DPORTS_BUILDER)
.undef FORBIDDEN
.endif

# zrj: too noisy on gcc80
CXXFLAGS+=	-Wno-expansion-to-defined -Wno-class-memaccess

dfly-patch:
	(cd ${WRKSRC} && ${TOUCH} \
		aclocal.m4 configure configure.ac autotoolsconfig.h.in)
	${FIND} ${WRKSRC} -name "GNUmakefile.*" | ${XARGS} ${TOUCH}
