DPMSG=		${WRKDIR}/dports-message

.if !defined(DPORTS_BUILDER) && defined(PACKAGE_BUILDING)
RUN_DEPENDS:=	${RUN_DEPENDS:N*warsow-data}
PKGMESSAGE=	${DPMSG}

dfly-patch:
	@${ECHO} "####################################################" >> ${DPMSG}
	@${ECHO} "# Build games/warsow-data from source to play this #" >> ${DPMSG}
	@${ECHO} "####################################################" >> ${DPMSG}

.endif
