# Created by: Sébastien Santoro <dereckson@gmail.com>
# $FreeBSD: devel/p5-ReadLine-TTYtter/Makefile 326865 2013-09-10 05:48:19Z az $

PORTNAME=	ReadLine-TTYtter
PORTVERSION=	1.4
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Term
PKGNAMEPREFIX=	p5-
DISTNAME=	Term-${PORTNAME}-${PORTVERSION}

MAINTAINER=	dereckson@gmail.com
COMMENT=	Perl5 module for Term::ReadLine allowing rich editing

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
