# New ports collection makefile for:	xfsinfo
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/xfsinfo/Makefile,v 1.4 2012/11/17 06:03:30 svnexp Exp $
#

PORTNAME=	xfsinfo
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X font server information utility

XORG_CAT=	app
USE_XORG=	x11 libfs

PLIST_FILES=	bin/xfsinfo

MAN1=		xfsinfo.1

.include <bsd.port.mk>
