# New ports collection makefile for:	Class-Gomor
# Date created:			3 Jan 2007
# Whom:				Christopher Boumenot <boumenot@gmail.com>
#
# $FreeBSD: finance/p5-Finance-Amortization/Makefile 324171 2013-08-02 18:21:05Z az $
#

PORTNAME=	Finance-Amortization
PORTVERSION=	0.5
CATEGORIES=	finance perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Simple amortization schedules

USES=		perl5
USE_PERL5=	configure

MAN3=	Finance::Amortization.3

.include <bsd.port.mk>
