# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: devel/rubygem-holidays/Makefile 340901 2014-01-24 14:46:50Z miwi $

PORTNAME=	holidays
PORTVERSION=	1.0.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	freebsdports@chillibear.com
COMMENT=	A collection of Ruby methods to deal with statutory and other holidays

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
