# $FreeBSD: devel/R-cran-Hmisc/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	Hmisc
DISTVERSION=	3.10-1
PORTREVISION=	5
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Harrell Miscellaneous functions useful for data analysis

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
