# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-Class-Inner/Makefile 331856 2013-10-28 13:46:25Z vanilla $

PORTNAME=	Class-Inner
PORTVERSION=	0.200001
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perlish implementation of Java like inner classes

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
