#!/bin/sh
#
# $FreeBSD: games/pachi/pkg-install 300896 2012-07-14 13:54:48Z beat $

SCOREDIR="/var/games/pachi"
SCOREFILE="/var/games/pachi/scores.dat"

[ "$2" != "POST-INSTALL" -o -f "$SCOREFILE" ] && exit 0 

echo "Creating hiscore file..."
mkdir -p "$SCOREDIR"

# Empty scorefile seem to contain 170 zero bytes
truncate -s 170 "$SCOREFILE"
chgrp -R games "$SCOREDIR"
chmod g+w "$SCOREFILE"
