# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: textproc/p5-XML-Tiny/Makefile 333056 2013-11-07 03:52:41Z vanilla $

PORTNAME=	XML-Tiny
PORTVERSION=	2.06
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple lightweight parser for a subset of XML

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
