# $FreeBSD: www/py-plone.app.i18n/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	plone.app.i18n
PORTVERSION=	2.0.2
CATEGORIES=	www python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Plone specific i18n extensions

LICENSE=	GPLv2

DIST_SUBDIR=	zope
USE_PYTHON=	yes
USE_PYDISTUTILS=easy_install
USE_ZIP=	yes

NO_STAGE=	yes

.include <bsd.port.mk>
