# Created by: Toni Viemerö <toni.viemero@iki.fi>
# $FreeBSD: devel/p5-PatchReader/Makefile 326636 2013-09-07 14:07:59Z az $

PORTNAME=	PatchReader
PORTVERSION=	0.9.6
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:TMANNERM
PKGNAMEPREFIX=	p5-

MAINTAINER=	toni.viemero@iki.fi
COMMENT=	Perl module with utilities to read and manipulate patches and CVS

USES=		perl5
USE_PERL5=	configure

MAN3=		PatchReader.3

.include <bsd.port.mk>
