# New ports collection makefile for:	p5-IO-Stty
# Date created:		1 Oct 2011
# Whom:			Stephon Chen <stephon@gmail.com>
#
# $FreeBSD: ports/devel/p5-IO-Stty/Makefile,v 1.14 2012/11/17 05:56:19 svnexp Exp $
#

PORTNAME=	IO-Stty
PORTVERSION=	0.03
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Change and print terminal line settings

PERL_MODBUILD=	yes

MAN3=		IO::Stty.3

.include <bsd.port.mk>
