# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: textproc/rubygem-redcarpet/Makefile 326230 2013-09-03 22:47:41Z zi $

PORTNAME=	redcarpet
PORTVERSION=	3.0.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A fast, safe and extensible Markdown to (X)HTML parser

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_RAKE=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES+=	bin/redcarpet

.include <bsd.port.mk>
