# Created by: ijliao
# $FreeBSD: devel/p5-Date-Leapyear/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	Date-Leapyear
PORTVERSION=	1.72
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl module to determine if a particular year a leap year

USES=		perl5
USE_PERL5=	configure

MAN3=	Date::Leapyear.3

.include <bsd.port.mk>
