# Created by: Dennis Herrmann <adox@mcx2.org>
# $FreeBSD: audio/p5-Audio-Mixer/Makefile 327706 2013-09-20 14:36:35Z bapt $

PORTNAME=	Audio-Mixer
PORTVERSION=	0.7
CATEGORIES=	audio perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	dhn@FreeBSD.org
COMMENT=	Perl extension for Sound Mixer control

USES=		perl5
NO_STAGE=	yes
USE_PERL5=	configure

MAN3=		Audio::Mixer.3

.include <bsd.port.mk>
