# New ports collection makefile for:	p5-Audio-Mixer
# Date created:			05 Oct 2008
# Whom:				Dennis Herrmann <adox@mcx2.org>
#
# $FreeBSD: ports/audio/p5-Audio-Mixer/Makefile,v 1.3 2012/11/17 05:54:40 svnexp Exp $
#

PORTNAME=	Audio-Mixer
PORTVERSION=	0.7
CATEGORIES=	audio perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	dhn@FreeBSD.org
COMMENT=	Perl extension for Sound Mixer control

PERL_CONFIGURE=	YES

MAN3=		Audio::Mixer.3

.include <bsd.port.mk>
