# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: graphics/rubygem-geokit/Makefile 321633 2013-06-23 12:42:52Z swills $

PORTNAME=	geokit
PORTVERSION=	1.6.5
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A Ruby gem for maps-based apps

RUN_DEPENDS=	rubygem-multi_json>=0:${PORTSDIR}/devel/rubygem-multi_json

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
