# New ports collection makefile for:   p5-Sys-Load
# Date created:                19 January 2010
# Whom:                        Konstantin Menshikov <kostjnspb@yandex.ru>
#
# $FreeBSD: ports/sysutils/p5-Sys-Load/Makefile,v 1.2 2012/11/17 06:01:40 svnexp Exp $
#

PORTNAME=	Sys-Load
PORTVERSION=	0.2
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN \
		http://kostjn.spb.ru/freebsd/
PKGNAMEPREFIX=	p5-

MAINTAINER=	kostjnspb@yandex.ru
COMMENT=	Getting the current system load and uptime

PERL_CONFIGURE=	YES

MAN3=	Sys::Load.3

.include <bsd.port.mk>
