# Created by: Toby Allsopp <toby@mi6.gen.nz>
# $FreeBSD: ports/textproc/p5-Text-Tabs+Wrap/Makefile,v 1.9 2012/12/27 16:09:08 svnexp Exp $

PORTNAME=	Text-Tabs+Wrap
PORTVERSION=	2012.0818
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Line wrapping to form simple paragraphs

PERL_CONFIGURE=	YES

MAN3=		modern::Text::Wrap.3 modern::Text::Tabs.3

.include <bsd.port.mk>
