# Created by: Toby Allsopp <toby@mi6.gen.nz>
# $FreeBSD: textproc/p5-Text-Tabs+Wrap/Makefile 323444 2013-07-22 13:13:20Z culot $

PORTNAME=	Text-Tabs+Wrap
PORTVERSION=	2013.0523
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Line wrapping to form simple paragraphs

PERL_CONFIGURE=	YES

MAN3=		modern::Text::Wrap.3 modern::Text::Tabs.3

.include <bsd.port.mk>
