# Created by: Toby Allsopp <toby@mi6.gen.nz>
# $FreeBSD: textproc/p5-Text-Tabs+Wrap/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Text-Tabs+Wrap
PORTVERSION=	2013.0523
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Line wrapping to form simple paragraphs

USES=		perl5
USE_PERL5=	configure

MAN3=		modern::Text::Wrap.3 modern::Text::Tabs.3

.include <bsd.port.mk>
