# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: devel/pear-PHP_ArrayOf/Makefile 333263 2013-11-08 21:41:53Z antoine $

PORTNAME=	PHP_ArrayOf
PORTVERSION=	0.2.1
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Abstract class package to create arrays of specific element types

BUILD_DEPENDS=	${PEARDIR}/PEAR.php:${PORTSDIR}/devel/pear
RUN_DEPENDS=	${PEARDIR}/PEAR.php:${PORTSDIR}/devel/pear

PEAR_AUTOINSTALL=	yes

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.mk"
.include <bsd.port.post.mk>
