# $FreeBSD: devel/hs-ranges/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	ranges
PORTVERSION=	0.2.4
PORTREVISION=	7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Ranges and various functions on them

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
