# $FreeBSD: x11/xlogo/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xlogo
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Displays the X Window System logo

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	xrender xft xext xt xaw xp xprintutil

.include <bsd.port.mk>
