# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: ports/devel/p5-Date-EzDate/Makefile,v 1.6 2012/11/25 13:13:57 svnexp Exp $

PORTNAME=	Date-EzDate
PORTVERSION=	1.12
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Date and time manipulation made easy

PERL_CONFIGURE=	yes

MAN3=	Date::EzDate.3

.include <bsd.port.mk>
