# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-Date-EzDate/Makefile 331933 2013-10-29 07:56:01Z vanilla $

PORTNAME=	Date-EzDate
PORTVERSION=	1.12
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Date and time manipulation made easy

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
