# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: devel/pear-channel-pirum/Makefile 333263 2013-11-08 21:41:53Z antoine $

PORTNAME=	pirum
PORTVERSION=	20110921
PORTREVISION=	1
CATEGORIES=	devel www pear

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.pirum-project.org

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
