# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: devel/rubygem-jquery-ui-themes/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	jquery-ui-themes
PORTVERSION=	0.0.11
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Allows inclusion of pre-built jquery themes without editing

RUN_DEPENDS=	rubygem-httparty>=0:${PORTSDIR}/www/rubygem-httparty

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
