# Created by: Brad Walker <tha_walka@hotmail.com>
# $FreeBSD: audio/rubygem-ruby-mp3info/Makefile 327706 2013-09-20 14:36:35Z bapt $

PORTNAME=	ruby-mp3info
PORTVERSION=	0.8
CATEGORIES=	audio rubygems
MASTER_SITES=	RG

MAINTAINER=	tha_walka@hotmail.com
COMMENT=	A Ruby library to access information on mp3 files

USE_RUBY=	yes
NO_STAGE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
