# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: devel/hs-hslogger/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	hslogger
PORTVERSION=	1.2.1
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Versatile logging framework

LICENSE=	BSD

USE_CABAL=	mtl network

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
