# $FreeBSD: textproc/rubygem-gemoji/Makefile 332051 2013-10-30 02:58:22Z swills $

PORTNAME=	gemoji
PORTVERSION=	1.4.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Emoji assets

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes


.include <bsd.port.mk>
