# $FreeBSD: hebrew/libreoffice/Makefile 327734 2013-09-20 18:41:52Z bapt $

LO_I18N=	he
LO_HAS_HELPPACK=	yes
CATEGORIES=	hebrew editors

NO_STAGE=	yes
.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
