# New ports collection makefile for:	xman
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xman/Makefile,v 1.6 2012/11/17 06:03:22 svnexp Exp $
#

PORTNAME=	xman
PORTVERSION=	1.1.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Manual page display program for X

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	xt xaw xp xprintutil

MAN1=		xman.1

.include <bsd.port.mk>
