# $FreeBSD: devel/rubygem-multi_test/Makefile 338483 2014-01-02 20:06:01Z sunpoet $

PORTNAME=	multi_test
PORTVERSION=	0.0.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Help control rogue test, unit, autorun requirments

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
