# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: textproc/p5-Text-SimpleTemplate/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	Text-SimpleTemplate
PORTVERSION=	0.36
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Yet another Perl module for template processing

USES=		perl5
USE_PERL5=	configure

MAN3=		Text::SimpleTemplate.3

NO_STAGE=	yes
.include <bsd.port.mk>
