# Created by: db
# $FreeBSD: astro/pyephem/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	pyephem
PORTVERSION=	3.7.5.1
PORTEPOCH=	1
CATEGORIES=	astro math hamradio
MASTER_SITES=	CHEESESHOP

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Scientific-grade astronomical computations for Python

NO_STAGE=	yes
USE_PYTHON=	2
USE_PYDISTUTILS=yes

.include <bsd.port.mk>
