# Created by: Pav Lucistnik <pav@FreeBSD.org>
# $FreeBSD: ports/lang/tcl84-thread/Makefile,v 1.8 2012/11/26 18:25:55 svnexp Exp $

PORTNAME=	tcl

MAINTAINER=	tcltk@FreeBSD.org
COMMENT=	Tool command language (threads support)

BUILDING_TCL_THREADS=	yes

MASTERDIR=	${.CURDIR}/../tcl84

.include "${MASTERDIR}/Makefile"
