# New ports collection makefile for:	Module::Versions
# Date created:		03 Apr 2010
# Whom:			Jun Kuriyama <kuriyama@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Module-Versions/Makefile,v 1.2 2012/11/17 05:56:22 svnexp Exp $
#

PORTNAME=	Module-Versions
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to handle versions of loaded modules

USE_ZIP=	yes
PERL_CONFIGURE=	yes

MAN3=	Module::Versions.3

.include <bsd.port.mk>
