# $FreeBSD: databases/postgresql92-pgtcl/Makefile 327717 2013-09-20 16:13:47Z bapt $

WANT_PGSQL_VER=	92
PKGNAMESUFFIX=	-postgresql${WANT_PGSQL_VER}

CONFLICTS=	pgtcl-[0-9]* pgtcl-postgresql9[01]-[0-9]*

MASTERDIR=	${.CURDIR}/../pgtcl

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
