# $FreeBSD: ports/databases/postgresql92-pgtcl/Makefile,v 1.3 2012/11/17 05:55:21 svnexp Exp $

WANT_PGSQL_VER=	92
PKGNAMESUFFIX=	-postgresql${WANT_PGSQL_VER}

CONFLICTS=	pgtcl-[0-9]* pgtcl-postgresql9[01]-[0-9]*

MASTERDIR=	${.CURDIR}/../pgtcl

.include "${MASTERDIR}/Makefile"
