# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-Class-Accessor/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Class-Accessor
PORTVERSION=	0.34
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Automated accessor generation

USES=		perl5
USE_PERL5=	configure

MAN3=		Class::Accessor.3 Class::Accessor::Fast.3 \
		Class::Accessor::Faster.3

.include <bsd.port.mk>
