# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: www/rubygem-addressable/Makefile 319744 2013-06-03 01:41:49Z swills $

PORTNAME=	addressable
PORTVERSION=	2.3.4
CATEGORIES=	www devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A replacement for the URI implementation

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
