# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/www/rubygem-addressable/Makefile 332053 2013-10-30 03:00:33Z swills $

PORTNAME=	addressable
PORTVERSION=	2.3.5
CATEGORIES=	www devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A replacement for the URI implementation

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
