# $FreeBSD: devel/hs-time-compat/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	time-compat
PORTVERSION=	0.1.0.3
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Compatibility with old-time for the time package

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
