# $FreeBSD: devel/hs-time-compat/Makefile 327723 2013-09-20 17:04:43Z bapt $

PORTNAME=	time-compat
PORTVERSION=	0.1.0.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Compatibility with old-time for the time package

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
