# New ports collection makefile for:	tel
# Date created:		7 March 2007
# Whom:			Andrew Pantyukhin <infofarmer@FreeBSD.org>
#
# $FreeBSD: deskutils/tel/Makefile 316464 2013-04-24 18:10:30Z ak $
#

PORTNAME=	tel
PORTVERSION=	0.1.7.1
PORTREVISION=	2
CATEGORIES=	deskutils
MASTER_SITES=	CENKES BERLIOS

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Little console-based phone book manager

USE_BZIP2=	yes
USES=		gettext
USE_PYTHON=	yes
USE_PYDISTUTILS=yes

.include <bsd.port.mk>
