# $FreeBSD: devel/py-zope.cachedescriptors/Makefile 327992 2013-09-23 12:52:16Z rm $

PORTNAME=	zope.cachedescriptors
PORTVERSION=	3.5.1
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Method and property caching decorators

LICENSE=	ZPL21

DIST_SUBDIR=	zope
USE_PYTHON=	yes
USE_PYDISTUTILS=easy_install
USE_ZIP=	yes

NO_STAGE=	yes

.include <bsd.port.mk>
