# Created by: Gabor Kovesdan
# $FreeBSD: security/p5-Crypt-License/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	Crypt-License
PORTVERSION=	2.04
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension to examine a license

USES=		perl5
USE_PERL5=	configure

MAN3=		Crypt::License.3 Crypt::License::Util.3 Crypt::License::Notice.3

NO_STAGE=	yes
.include <bsd.port.mk>
