# New ports collection makefile for:	Screen
# Date created:				Dec 17, 2000
# Whom:					Ying-Chieh Liao <ijliao@csie.nctu.edu.tw>
#
# $FreeBSD: ports/devel/p5-Term-Screen/Makefile,v 1.16 2012/11/17 05:56:31 svnexp Exp $
#

PORTNAME=	Term-Screen
PORTVERSION=	1.03
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Basic screen + input class

PERL_CONFIGURE=	yes

MAN3=		Term::Screen.3

.include <bsd.port.mk>
