# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: textproc/yi-aspell/Makefile 332672 2013-11-04 08:30:37Z bapt $

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-yi-0.01.1-1
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Yiddish dictionary

DICT=	 	yi

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
