# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: misc/teseq/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	teseq
PORTVERSION=	1.1
CATEGORIES=	misc
MASTER_SITES=	GNU

MAINTAINER=	danilo@FreeBSD.org
COMMENT=	Terminal control sequence analyzer

GNU_CONFIGURE=	yes
USES=	gmake

INFO=	teseq

PLIST_FILES=	bin/reseq bin/teseq \
				man/man1/reseq.1.gz \
				man/man1/teseq.1.gz

.include <bsd.port.mk>
