# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: biology/python-nexus/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	python-nexus
PORTVERSION=	0.87
CATEGORIES=	biology python
MASTER_SITES=	CHEESESHOP

MAINTAINER=	wen@FreeBSD.org
COMMENT=	A generic nexus file format reader for python

USE_PYTHON=		yes
USE_PYDISTUTILS=	easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
