# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: net-im/p5-Net-AOLIM/Makefile 327756 2013-09-20 22:13:34Z bapt $

PORTNAME=	Net-AOLIM
PORTVERSION=	1.61
CATEGORIES=	net-im perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl OO interface to the AOL Instant Messenger TOC client protocol

USES=		perl5
USE_PERL5=	configure
WRKSRC=		${WRKDIR}/${PORTNAME}

MAN3=		Net::AOLIM.3

NO_STAGE=	yes
.include <bsd.port.mk>
