# New ports collection makefile for:	p5-File-MMagic
# Date created:		25 February 2000
# Whom:	      		Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/devel/p5-File-MMagic/Makefile,v 1.26 2012/11/17 05:56:16 svnexp Exp $
#

PORTNAME=	File-MMagic
PORTVERSION=	1.29
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to guess file type like file(1)

PERL_CONFIGURE=	yes

MAN3=		File::MMagic.3

.include <bsd.port.mk>
