# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-File-NFSLock/Makefile 338880 2014-01-06 13:53:21Z az $

PORTNAME=	File-NFSLock
PORTVERSION=	1.21
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	File::NFSLock - perl module to do NFS (or not) locking

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
