# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: textproc/p5-String-ShellQuote/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	String-ShellQuote
PORTVERSION=	1.04
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl module for quote strings for passing through the shell

USES=		perl5
USE_PERL5=	configure

MAN1=	shell-quote.1
MAN3=	String::ShellQuote.3

.include <bsd.port.mk>
