# $FreeBSD: head/textproc/py-alabaster/Makefile 455210 2017-11-30 15:50:30Z mat $

PORTNAME=	alabaster
PORTVERSION=	0.7.6
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kmoore@FreeBSD.org
COMMENT=	Modified Kr Sphinx theme

LICENSE=	MIT

NO_ARCH=	yes
USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
