# Created by: Martin Jackson (mhjacks@swbell.net)
# $FreeBSD: devel/p5-Shell-EnvImporter/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Shell-EnvImporter
PORTVERSION=	1.07
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mhjacks@swbell.net
COMMENT=	Inherit different shell environments and restore previous

RUN_DEPENDS=	p5-Class-MethodMaker>=0:${PORTSDIR}/devel/p5-Class-MethodMaker

USES=		perl5
USE_PERL5=	configure

MAN3=		Shell::EnvImporter.3 Shell::EnvImporter::Result.3 Shell::EnvImporter::Shell.3

NO_STAGE=	yes
.include <bsd.port.mk>
