# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-Term-Encoding/Makefile 326592 2013-09-07 10:16:46Z az $

PORTNAME=	Term-Encoding
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Detect encoding of the current terminal

USES=		perl5
USE_PERL5=	configure

MAN3=		Term::Encoding.3

.include <bsd.port.mk>
