# New ports collection makefile for:	p5-Term-Encoding
# Date created:		2006-07-13
# Whom:			Gea-Suan Lin <gslin@gslin.org>
#
# $FreeBSD: ports/devel/p5-Term-Encoding/Makefile,v 1.6 2012/11/17 05:56:31 svnexp Exp $
#

PORTNAME=	Term-Encoding
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Detect encoding of the current terminal

PERL_CONFIGURE=	yes

MAN3=		Term::Encoding.3

.include <bsd.port.mk>
