# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: textproc/R-cran-XML/Makefile 321791 2013-06-26 10:11:29Z tota $

PORTNAME=	XML
DISTVERSION=	3.98-1.1
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for parsing and generating XML

LICENSE=	BSD

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes
USE_GNOME=	libxml2

.include <bsd.port.mk>
