# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: textproc/R-cran-XML/Makefile 319316 2013-05-28 15:15:05Z bf $

PORTNAME=	XML
DISTVERSION=	3.96-1.1
PORTREVISION=	1
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for parsing and generating XML

LICENSE=	BSD

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes
USE_GNOME=	libxml2

.include <bsd.port.mk>
