# Created by: Martin Dieringer <martin.dieringer@gmx.de>
# $FreeBSD: print/rtf2latex2e/Makefile 327765 2013-09-20 22:43:59Z bapt $

PORTNAME=	rtf2latex2e
PORTVERSION=	2.0.1
CATEGORIES=	print
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}-unix/2-0
DISTNAME=	${PORTNAME}-${PORTVERSION:C|\.|-|g}

MAINTAINER=	martin.dieringer@gmx.de
COMMENT=	A newer filter that converts RTF (MS Rich Text Format) into LaTeX

LICENSE=	GPLv2

USE_ZIP=	yes
USE_GMAKE=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
