# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: devel/p5-Tree-Node/Makefile 324175 2013-08-02 21:38:09Z mat $

PORTNAME=	Tree-Node
PORTVERSION=	0.08
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Memory-efficient tree nodes in Perl

USES=		perl5
USE_PERL5=	modbuild

MAN3=		Tree::Node.3

.include <bsd.port.mk>
