# $FreeBSD: databases/rubygem-bdb1/Makefile 336187 2013-12-11 18:08:52Z bapt $

PORTNAME=	bdb1
PORTVERSION=	0.2.5
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby interface to Berkeley DB revision 1.8x with full feature support

LIB_DEPENDS=	libexecinfo.so:${PORTSDIR}/devel/libexecinfo

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
