# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: ports/graphics/R-cran-dichromat/Makefile,v 1.7 2013/01/25 14:46:06 svnexp Exp $

PORTNAME=	dichromat
DISTVERSION=	2.0-0
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Color schemes for dichromats

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
