# Created by: Lars Eggert <lars.eggert@gmx.net>
# $FreeBSD: devel/p5-Sub-Override/Makefile 332205 2013-10-31 07:36:25Z vanilla $

PORTNAME=	Sub-Override
PORTVERSION=	0.09
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for easily overriding subroutines

TEST_DEPENDS=	p5-Test-Fatal>=0.0:${PORTSDIR}/devel/p5-Test-Fatal

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
