# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: net/rubygem-iproto/Makefile 327755 2013-09-20 22:10:23Z bapt $

PORTNAME=	iproto
PORTVERSION=	0.3.10
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	vg@FreeBSD.org
COMMENT=	Ruby implementation of Mail.Ru iproto protocol

RUN_DEPENDS=	rubygem-bin_utils>=0.0.3:${PORTSDIR}/devel/rubygem-bin_utils

RUBY_VER=	1.9
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
