# $FreeBSD: converters/php53-recode/Makefile 327715 2013-09-20 16:05:24Z bapt $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php53

PKGNAMESUFFIX=	-recode

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
