# Created by: Pawel Pekala <c0rn@o2.pl>
# $FreeBSD: mail/claws-mail-vcalendar/Makefile 336489 2013-12-14 22:02:10Z pawel $

PORTNAME=	vcalendar
PORTREVISION=	0

COMMENT=	vCalendar plugin for Claws Mail

CLAWS_PLUGINS_BUILD=	vcalendar

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
