# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: devel/hs-datetime/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	datetime
PORTVERSION=	0.2.1
PORTREVISION=	7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities to make Data.Time.* easier to use in Haskell

LICENSE=	GPLv3

USE_CABAL=	QuickCheck>=2

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
