# Created by: Alex Kapranoff <kapr@crosswinds.net>
# $FreeBSD: russian/p5-Lingua-RU-Charset/Makefile 341813 2014-01-30 08:45:50Z az $

PORTNAME=	Lingua-RU-Charset
PORTVERSION=	0.02
CATEGORIES=	russian perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl extension for detecting and converting Russian character sets

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
