# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-Class-Prototyped/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Class-Prototyped
PORTVERSION=	1.13
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Fast prototype-based OO programming in Perl

USES=		perl5
USE_PERL5=	configure

MAN3=	Class::Prototyped.3 \
	Class::Prototyped::why.3

NO_STAGE=	yes
.include <bsd.port.mk>
