# Created by: Andrej Zverev <az@FreeBSD.org>
# $FreeBSD: devel/p5-File-ShareDir-Install/Makefile 326224 2013-09-03 20:02:04Z tobez $

PORTNAME=	File-ShareDir-Install
PORTVERSION=	0.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Install read-only data files from a distribution

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=	File::ShareDir::Install.3

.include <bsd.port.mk>
