# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: databases/p5-DBIx-HA/Makefile 326896 2013-09-10 12:14:21Z az $

PORTNAME=	DBIx-HA
PORTVERSION=	1.1
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	DBIx
PKGNAMEPREFIX=	p5-

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	High Availability package for DBI

USES=		perl5
USE_PERL5=	configure

MAN3=		DBIx::HA.3

.include <bsd.port.mk>
