# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: math/R-cran-outliers/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	outliers
PORTVERSION=	0.14
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Collection of some tests commonly used for identifying outliers

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
