# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: math/R-cran-outliers/Makefile 314659 2013-03-19 15:45:03Z danfe $

PORTNAME=	outliers
PORTVERSION=	0.14
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	danfe@FreeBSD.org
COMMENT=	Collection of some tests commonly used for identifying outliers

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
