# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: head/devel/p5-Sub-Identify/Makefile 332205 2013-10-31 07:36:25Z vanilla $

PORTNAME=	Sub-Identify
PORTVERSION=	0.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Retrieve names of code references

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
