# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-Lingua-EN-Inflect/Makefile 333056 2013-11-07 03:52:41Z vanilla $

PORTNAME=	Lingua-EN-Inflect
PORTVERSION=	1.89.3
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Convert singular words to their plural form

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
