# New ports collection makefile for:	p5-Template-Multilingual
# Date created:		19 June 2005
# Whom:			TAKAHASHI Kaoru <kaoru@kaisei.org>
#
# $FreeBSD: www/p5-Template-Multilingual/Makefile 326053 2013-09-02 18:23:34Z az $
#

PORTNAME=	Template-Multilingual
PORTVERSION=	1.00
CATEGORIES=	www textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kaoru@kaisei.org
COMMENT=	Multilingual templates for Template Toolkit

RUN_DEPENDS=	p5-Template-Toolkit>=0:${PORTSDIR}/www/p5-Template-Toolkit

USES=		perl5
USE_PERL5=	configure

MAN3=		Template::Multilingual.3 \
		Template::Multilingual::Parser.3

.include <bsd.port.mk>
