# Created by: Mike Heffner <mikeh@FreeBSD.org>
# $FreeBSD: net-p2p/napshare/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	napshare
PORTVERSION=	1.3
PORTREVISION=	1
CATEGORIES=	net-p2p
MASTER_SITES=	SF/${PORTNAME}/NapShare%20V${PORTVERSION}/Linux

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A GTK based Gnutella client

USE_GMAKE=	yes
USE_GNOME=	gtk12
GNU_CONFIGURE=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
