# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: multimedia/gstreamer-plugins-xvid/Makefile 332416 2013-11-01 22:14:07Z kwm $
#    $MCom: ports/multimedia/gstreamer-plugins-xvid/Makefile,v 1.5 2008/03/19 14:05:37 ahze Exp $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer xvid plugin

GST_PLUGIN=	xvid

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
