# Created by: MIHIRA Yoshiro <sanpei@FreeBSD.org>
# $FreeBSD: net/rubygem-domain_name/Makefile 327755 2013-09-20 22:10:23Z bapt $

PORTNAME=	domain_name
PORTVERSION=	0.5.12
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Domain Name manipulation library for ruby

RUN_DEPENDS=	rubygem-unf>=0.0.5:${PORTSDIR}/textproc/rubygem-unf

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
