# $FreeBSD: devel/hs-PSQueue/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	PSQueue
PORTVERSION=	1.1
PORTREVISION=	7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Priority Search Queue

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
