# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: textproc/hs-xml/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	xml
PORTVERSION=	1.3.13
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple XML library for Haskell

LICENSE=	BSD

USE_CABAL=	text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
