# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: textproc/hs-xml/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	xml
PORTVERSION=	1.3.13
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple XML library for Haskell

LICENSE=	BSD

USE_CABAL=	text

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
