# New ports collection makefile for:   puff
# Date created:        10 April 2003
# Whom:                Leif Pedersen <bilbo@devpit.org>
#
# $FreeBSD: ports/editors/puff/Makefile,v 1.15 2012/11/17 05:57:18 svnexp Exp $
#

PORTNAME=	puff
PORTVERSION=	1.0.1
CATEGORIES=	editors
MASTER_SITES=	http://devpit.org/puff/ \
		http://www.freebsdbrasil.com.br/~jmelo/

MAINTAINER=	bilbo@hobbiton.org
COMMENT=	Simple and efficient text editor

PLIST_FILES=	bin/puff etc/puff.conf.sample

.include <bsd.port.mk>
