# $FreeBSD: editors/libreoffice-ug/Makefile 306473 2012-10-26 20:24:07Z jkim $

LO_I18N=	ug
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
