# Created by: Gabor Kovesdan
# $FreeBSD: security/p5-Digest-JHash/Makefile 341821 2014-01-30 09:08:26Z az $

PORTNAME=	Digest-JHash
PORTVERSION=	0.07
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension for JHash hash algorithm

LICENSE=	ART20

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
