# Created by: arved
# $FreeBSD: net-mgmt/p5-SNMP-Info/Makefile 332221 2013-10-31 11:04:50Z jadawin $

PORTNAME=	SNMP-Info
PORTVERSION=	3.08
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Perl5 module for gathering information from network devices

LICENSE=	BSD

LIB_DEPENDS=	libnetsnmp.so.30:${PORTSDIR}/net-mgmt/net-snmp

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
