# ex:ts=8
# Ports collection makefile for:	hebcal
# Date created:				Aug 26, 2010
# Whom:	      				Edwin Groothuis
#
# $FreeBSD: ports/deskutils/hebcal/Makefile,v 1.2 2012/11/17 05:55:28 svnexp Exp $
#

PORTNAME=	hebcal
PORTVERSION=	3.7
CATEGORIES=	deskutils
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}-c/${PORTVERSION}/

MAINTAINER=	edwin@mavetju.org
COMMENT=	Hebrew Calendar calculator

HAS_CONFIGURE=	yes

PLIST_FILES=	bin/hebcal
MAN1=		hebcal.1
INFO=		hebcal

.include <bsd.port.mk>
