# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: graphics/py-opencv/Makefile 335601 2013-12-04 02:51:00Z jhale $

PORTREVISION=	0
CATEGORIES=	graphics python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

COMMENT=	OpenCV Python library

OCV_SLAVE=	python
OCV_PYTHON=	yes
MASTERDIR=	${.CURDIR:H}/opencv
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
