# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: graphics/py-opencv/Makefile 327733 2013-09-20 18:35:44Z bapt $

_BUILDING_OPENCV_PYTHON=	yes
MASTERDIR=	${.CURDIR}/../opencv

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
