# New ports collection makefile for:	php5-pspell
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/textproc/php5-pspell/Makefile,v 1.6 2012/11/17 06:02:16 svnexp Exp $
#

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-pspell

.include "${MASTERDIR}/Makefile"
