# Created by: Mathieu Arnold <m@absolight.net>
# $FreeBSD: textproc/p5-YAPE-HTML/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	YAPE-HTML
PORTVERSION=	1.11
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PINYAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Yet Another Parser/Extractor for HTML

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
