# Created by: Cheng-Lung Sung <clsung@dragon2.net>
# $FreeBSD: textproc/p5-Regex-PreSuf/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	Regex-PreSuf
PORTVERSION=	1.17
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JHI
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Regex::PreSuf - Given word lists, create regular expressions

USES=		perl5
USE_PERL5=	configure

MAN3=		Regex::PreSuf.3

NO_STAGE=	yes
.include <bsd.port.mk>
