# New ports collection makefile for:	textproc/p5-Regex-PreSuf
# Date created:				11 Octobor 2003
# Whom:					Cheng-Lung Sung <clsung@dragon2.net>
#
# $FreeBSD: ports/textproc/p5-Regex-PreSuf/Makefile,v 1.7 2012/11/17 06:02:07 svnexp Exp $

PORTNAME=	Regex-PreSuf
PORTVERSION=	1.17
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JHI
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Regex::PreSuf - Given word lists, create regular expressions

PERL_CONFIGURE=	yes

MAN3=		Regex::PreSuf.3

.include <bsd.port.mk>
