# New ports collection makefile for:	gstreamer-plugins-sndfile
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD: ports/audio/gstreamer-plugins-sndfile/Makefile,v 1.12 2012/11/17 05:54:34 svnexp Exp $
#

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer sndfile plugin

GST_PLUGIN=	sndfile

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
