# New ports collection makefile for:    am-aspell
# Date created:                         28 December 2004
# Whom:                                 Thierry Thomas <thierry@pompo.net>
#
# $FreeBSD: ports/textproc/am-aspell/Makefile,v 1.7 2012/11/17 06:01:51 svnexp Exp $
#

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-am-0.03-1
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Amharic dictionary

DICT=	 	am

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
