# $FreeBSD: x11-fonts/encodings/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	encodings
PORTVERSION=	1.0.4
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Encoding fonts

XORG_CAT=	font
USE_XORG=	fontutil
FONTDIR=	encodings/large encodings

.include <bsd.port.mk>
