# New ports collection makefile for:    encodings
# Date created:				Oct 29 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/encodings/Makefile,v 1.4 2012/11/17 06:03:27 svnexp Exp $
#

PORTNAME=	encodings
PORTVERSION=	1.0.4
PORTEPOCH=	1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Encoding fonts

XORG_CAT=	font
USE_XORG=	fontutil
FONTDIR=	encodings/large encodings

.include <bsd.port.mk>
