# $FreeBSD: x11-fonts/encodings/Makefile 327781 2013-09-20 23:51:14Z bapt $

PORTNAME=	encodings
PORTVERSION=	1.0.4
PORTEPOCH=	1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Encoding fonts

XORG_CAT=	font
USE_XORG=	fontutil
FONTDIR=	encodings/large encodings

NO_STAGE=	yes
.include <bsd.port.mk>
