# $FreeBSD: hungarian/calligra-l10n/Makefile 336675 2013-12-16 22:59:42Z avilla $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
CATEGORIES=	hungarian editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Hungarian messages and documentation for Calligra

CALLIGRA_L10N=	hu

.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
