# Created by: Kelly Yancey <kbyanc@posi.net>
# $FreeBSD: misc/p5-LEGO-RCX/Makefile 327745 2013-09-20 20:50:57Z bapt $

PORTNAME=	LEGO-RCX
PORTVERSION=	1.01
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module for communicating with the Lego RCX brick via the IR tower

USES=		perl5
USE_PERL5=	configure

MAN3=		LEGO::RCX.3

NO_STAGE=	yes
.include <bsd.port.mk>
