# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: databases/php5-dba/Makefile 327717 2013-09-20 16:13:47Z bapt $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-dba

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
