# $FreeBSD: security/hs-crypto-random-api/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	crypto-random-api
PORTVERSION=	0.2.0
PORTREVISION=	1
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple random generators API for cryptography related code

LICENSE=	BSD

USE_CABAL=	entropy

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
