# Created by: Pawel Worach
# $FreeBSD: x11-fonts/font-adobe-100dpi/Makefile 327781 2013-09-20 23:51:14Z bapt $

PORTNAME=	font-adobe-100dpi
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Adobe 100dpi font

XORG_CAT=	font
USE_XORG=	fontutil

NO_STAGE=	yes
.include <bsd.port.mk>
