# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: mail/rubygem-rmail/Makefile 323794 2013-07-27 16:06:01Z swills $

PORTNAME=	rmail
PORTVERSION=	1.0.0
CATEGORIES=	mail rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Lightweight mail library

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
