# $FreeBSD: x11-drivers/xf86-video-i128/Makefile 336621 2013-12-16 11:11:09Z zeising $

PORTNAME=	xf86-video-i128
PORTVERSION=	1.3.6
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org i128 display driver

XORG_CAT=	driver

.include <bsd.port.mk>
