# Created by: chinsan
# $FreeBSD: textproc/p5-Text-CharWidth/Makefile 333056 2013-11-07 03:52:41Z vanilla $

PORTNAME=	Text-CharWidth
DISTVERSION=	0.04
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Get number of occupied columns of a string on terminal

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
