# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: net/pear-Horde_Socket_Client/Makefile 334186 2013-11-18 13:12:01Z mm $

PORTNAME=	Horde_Socket_Client
PORTVERSION=	1.1.0
CATEGORIES=	net www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Socket Client

USE_HORDE_RUN=	Horde_Exception

NO_STAGE=	yes
.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
