# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: math/R-cran-fracdiff/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	fracdiff
DISTVERSION=	1.4-2
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Fractionally differenced ARIMA aka ARFIMA(p,d,q) models

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
