# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: www/hs-HTTP/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	HTTP
PORTVERSION=	4000.2.8
PORTREVISION=	1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library for client-side HTTP

LICENSE=	BSD

USE_CABAL=	mtl network parsec

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
