# $FreeBSD: devel/p5-Algorithm-Binpack/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Algorithm-BinPack
PORTVERSION=	0.5
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	wblock@FreeBSD.org
COMMENT=	Efficiently pack items into bins

USES=		perl5
USE_PERL5=	configure

MAN3=		Algorithm::BinPack.3

PORTSCOUT=	limit:^\d+\.\d+

NO_STAGE=	yes
.include <bsd.port.mk>
