# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: converters/p5-Number-RecordLocator/Makefile 341761 2014-01-29 17:00:41Z az $

PORTNAME=	Number-RecordLocator
PORTVERSION=	0.005
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Encodes integers into a short locator string

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
