# $FreeBSD: sysutils/gstreamer1-plugins-cdio/Makefile 327772 2013-09-20 23:05:58Z bapt $

PORTREVISION=	0
CATEGORIES=	sysutils

COMMENT=	Gstreamer compact disc input and control library

GST_PLUGIN=	cdio
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
