# Ports collection makefile for:	rubygem-chunky_png
# Date created:				7 October 2011
# Whom:					Phil Phillips <pphillips@experts-exchange.com>
#
# $FreeBSD: ports/graphics/rubygem-chunky_png/Makefile,v 1.3 2012/11/17 05:58:22 svnexp Exp $
#

PORTNAME=	chunky_png
PORTVERSION=	1.2.5
PORTREVISION=	1
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	pphillips@experts-exchange.com
COMMENT=	Ruby library to read and write PNG images

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
