# Created by: Anatoly Borodin <anatoly.borodin@gmail.com>
# $FreeBSD: www/xpi-permatabs/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	permatabs
PORTVERSION=	1.7.0
DISTVERSIONSUFFIX=	-fx
CATEGORIES=	www

MAINTAINER=	anatoly.borodin@gmail.com
COMMENT=	Turn tabs of your choice into permanent tabs

XPI_ID=		{20291fcc-1471-46c8-8213-0911f5ce6d65}
XPI_NUM=	2558

NO_STAGE=	yes
.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
