# Created by: Emanuel Haupt <ehaupt@FreeBSD.org>
# $FreeBSD: ports/dns/py-ldns/Makefile,v 1.2 2012/11/22 12:55:54 svnexp Exp $

MASTERDIR=	${.CURDIR}/../../dns/ldns

OPTIONS_SET=	PYLDNS

.include "${MASTERDIR}/Makefile"
