# Created by: Jean-Yves Lefort <jylefort@FreeBSD.org>
# $FreeBSD: devel/libbonobo-reference/Makefile 336013 2013-12-09 18:41:16Z antoine $

PORTREVISION=	0

REFERENCE_SRC=	${WRKSRC}/doc
BOOKS=		activation-api api

.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
