--- plugins/enc-amf/cmake/cppcheck.cmake.orig	2022-10-11 17:53:45 UTC
+++ plugins/enc-amf/cmake/cppcheck.cmake
@@ -61,7 +61,7 @@ function(cppcheck)
 		else()
 			set(CPPCHECK_PLATFORM "win64")
 		endif()
-	elseif(("${CMAKE_SYSTEM_NAME}" MATCHES "Linux") OR ("${CMAKE_SYSTEM_NAME}" MATCHES "FreeBSD") OR APPLE)
+	elseif(("${CMAKE_SYSTEM_NAME}" MATCHES "Linux") OR ("${CMAKE_SYSTEM_NAME}" MATCHES "FreeBSD|DragonFly") OR APPLE)
 		if(BITS EQUAL "32")		
 			set(CPPCHECK_PLATFORM "unix32")
 		else()
@@ -72,7 +72,7 @@ function(cppcheck)
 	endif()
 	if(WIN32)
 		list(APPEND CPPCHECK_LIBRARIES "windows")
-	elseif("${CMAKE_SYSTEM_NAME}" MATCHES "FreeBSD")
+	elseif("${CMAKE_SYSTEM_NAME}" MATCHES "FreeBSD|DragonFly")
 		list(APPEND CPPCHECK_LIBRARIES "bsd")
 	elseif("${CMAKE_SYSTEM_NAME}" MATCHES "Linux")
 		list(APPEND CPPCHECK_LIBRARIES "gnu")
