# $FreeBSD: audio/gstreamer1-plugins-twolame/Makefile 316693 2013-04-27 20:56:38Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer High-quality free MP2 encoder plugin

GST_PLUGIN=	twolame
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
