# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: devel/hs-readline/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	readline
PORTVERSION=	1.0.3.0
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Interface to the GNU readline library

LICENSE=	GPLv2

USES+=		readline

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
