# New ports collection makefile for:    blas
# Date created:         27 October 1994
# Whom:                 ljo
#
# $FreeBSD: ports/math/blas/Makefile,v 1.52 2012/11/17 05:59:19 svnexp Exp $
#

PORTNAME=	blas
PORTREVISION=	0

MAINTAINER=	maho@FreeBSD.org
COMMENT=	Basic Linear Algebra Subroutines

DESCR=	${.CURDIR}/pkg-descr
BLAS_SLAVEPORT	=	yes

MASTERDIR=	${.CURDIR}/../lapack

.include "${MASTERDIR}/Makefile"
