# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: astro/p5-Astro-WaveBand/Makefile 325163 2013-08-21 17:42:57Z sunpoet $

PORTNAME=	Astro-WaveBand
PORTVERSION=	0.08
CATEGORIES=	astro perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Transparently work in waveband, wavelength, or filter

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USE_PERL5=	modbuild
USES=		perl5

MAN3=		Astro::WaveBand.3

.include <bsd.port.mk>
