# Created by: Simun Mikecin < numisemis at yahoo dot com >
# $FreeBSD: net/p5-Cisco-IPPhone/Makefile 327755 2013-09-20 22:10:23Z bapt $

PORTNAME=	Cisco-IPPhone
PORTVERSION=	0.05
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	numisemis@yahoo.com
COMMENT=	Package for creating Cisco IPPhone XML objects

USES=		perl5
USE_PERL5=	configure

MAN3=	Cisco::IPPhone.3

NO_STAGE=	yes
.include <bsd.port.mk>
