# New ports collection makefile for:	rubygem-runt
# Date created:		7 April 2009
# Whom:			Philip M. Gollucci <pgollucci@p6m7g8.com>
#
# $FreeBSD: devel/rubygem-runt/Makefile 322053 2013-06-29 21:08:44Z swills $
#

PORTNAME=	runt
PORTVERSION=	0.9.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby implementation of select Martin Fowler patterns

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
