# Created by: Vasiliy Ch <blttll@gmail.com>
# $FreeBSD: sysutils/ciso/Makefile 326879 2013-09-10 09:08:24Z marino $

PORTNAME=	ciso
PORTVERSION=	1.0.0
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	SF

MAINTAINER=	blttll@gmail.com
COMMENT=	A tool to compress ISO images to CSO format


USE_DOS2UNIX=	yes
PLIST_FILES=	bin/ciso

.include <bsd.port.mk>
