# New ports collection makefile for:	ciso
# Date created:		4 November 2007
# Whom:			Vasiliy Ch <blttll@gmail.com>
#
# $FreeBSD: ports/sysutils/ciso/Makefile,v 1.3 2012/11/17 06:01:26 svnexp Exp $
#

PORTNAME=	ciso
PORTVERSION=	1.0.0
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	http://ciso.tenshu.fr/

MAINTAINER=	blttll@gmail.com
COMMENT=	A tool to compress ISO images to CSO format

USE_DOS2UNIX=	yes
PLIST_FILES=	bin/ciso

.include <bsd.port.mk>
