# Created by: ijliao
# $FreeBSD: net/rfbproxy/Makefile 341981 2014-01-31 12:14:30Z miwi $

PORTNAME=	rfbproxy
PORTVERSION=	1.1.1
CATEGORIES=	net
MASTER_SITES=	SF

MAINTAINER=	pphillips@experts-exchange.com
COMMENT=	A simple tool for recording VNC sessions

GNU_CONFIGURE=	yes

USE_BZIP2=	yes

PLIST_FILES=	bin/rfbproxy \
		man/man1/rfbproxy.1.gz


.include <bsd.port.mk>
