# Created by: wosch
# $FreeBSD: net/rshell/Makefile 327755 2013-09-20 22:10:23Z bapt $

PORTNAME=	rshell
PORTVERSION=	1.0
CATEGORIES=	net
MASTER_SITES=	http://wolfram.schneider.org/src/

MAINTAINER=	wosch@FreeBSD.org
COMMENT=	A front end for rsh(1) and rcp(1)

MAN1=		rshell.1
MLINKS=		rshell.1 rcopy.1
MANCOMPRESSED=	maybe

NO_STAGE=	yes
.include <bsd.port.mk>
