# New ports collection makefile for:	Digital Harmony (metacity theme)
# Date created:				08 Sep 2006
# Whom:					Alexey Dokuchaev <danfe@FreeBSD.org>
#
# $FreeBSD: ports/x11-themes/metacity-digital-harmony-theme/Makefile,v 1.2 2012/11/17 06:03:33 svnexp Exp $
#

TYPE=		metacity
MASTERDIR=	${.CURDIR}/../gtk-digital-harmony-theme

.include "${MASTERDIR}/Makefile"
