# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: x11-themes/metacity-digital-harmony-theme/Makefile 327783 2013-09-20 23:54:03Z bapt $

TYPE=		metacity
MASTERDIR=	${.CURDIR}/../gtk-digital-harmony-theme

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
