# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-test/Makefile 332043 2013-10-30 02:47:06Z swills $

PORTNAME=	test
PORTVERSION=	0.4.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
DISTNAME=	${GEM_NAME}

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Run automated tests

USE_RUBY=		yes
USE_RAKE=		yes
USE_RUBYGEMS=		yes
GEM_NAME=		rubygems-test-${PORTVERSION}
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
