# $FreeBSD: x11/xwininfo/Makefile 328644 2013-09-29 03:14:14Z eadler $

PORTNAME=	xwininfo
PORTVERSION=	1.1.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Window information utility for X

XORG_CAT=	app
USES=		iconv
USE_XORG=	x11 xcb xproto xorg-macros

PLIST_FILES=	bin/xwininfo man/man1/xwininfo.1.gz

.include <bsd.port.mk>
