# Created by: trasz <trasz@pin.if.uz.zgora.pl>
# $FreeBSD: audio/liblscp/Makefile 337911 2013-12-28 20:54:43Z antoine $

PORTNAME=	liblscp
PORTVERSION=	0.5.6
CATEGORIES=	audio
MASTER_SITES=	SF/qsampler/${PORTNAME}/${PORTVERSION} \
		http://download.linuxsampler.org/packages/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Wrapper around the LSCP network protocol

LICENSE=	LGPL21

USES=		gmake pathfix
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
