# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: ports/www/rubygem-net-http-persistent/Makefile,v 1.12 2012/12/04 07:04:23 svnexp Exp $

PORTNAME=	net-http-persistent
PORTVERSION=	2.8
CATEGORIES=	www net rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Manages persistent connections using Net::HTTP

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
