# New ports collection makefile for:   ctemplate
# Date created:        02 April 2007
# Whom:                Alex Pesternikov <ap@page2rss.com>
#
# $FreeBSD: ports/www/ctemplate/Makefile,v 1.4 2012/11/17 06:02:30 svnexp Exp $
#

PORTNAME=	ctemplate
PORTVERSION=	0.5
CATEGORIES=	www textproc
MASTER_SITES=	SF

MAINTAINER=	ap@page2rss.com
COMMENT=	Template system for C

USE_GMAKE=	yes
GNU_CONFIGURE=	yes

PLIST_FILES+=	bin/h2ap

.include <bsd.port.mk>
