# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: ports/www/xpi-adblock_plus/Makefile,v 1.34 2013/02/19 12:18:36 svnexp Exp $

PORTNAME=	adblock_plus
PORTVERSION=	2.2.3
DISTVERSIONSUFFIX=	-tb+an+sm+fx
CATEGORIES=	www

MAINTAINER=	ale@FreeBSD.org
COMMENT=	A content filtering extension

XPI_NUM=	1865
XPI_ID=		{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}

.include "../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
