# Created by: ijliao
# $FreeBSD: devel/p5-Inline-Files/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Inline-Files
PORTVERSION=	0.68
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Multiple virtual files at the end of your code

USES=		perl5
USE_PERL5=	configure

MAN3=		Inline::Files.3 \
		Inline::Files::Virtual.3

NO_STAGE=	yes
.include <bsd.port.mk>
