# ex:ts=8
# Ports collection makefile for:	Inline::Files
# Created by: ijliao
# $FreeBSD: devel/p5-Inline-Files/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Inline-Files
PORTVERSION=	0.68
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Multiple virtual files at the end of your code

USES=		perl5
USE_PERL5=	configure

MAN3=		Inline::Files.3 \
		Inline::Files::Virtual.3

.include <bsd.port.mk>
