# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: textproc/p5-PDF-API3/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	PDF-API3
PORTVERSION=	3.001
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	The Next Generation of Text::PDF::API2

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
