# Created by: stas
# $FreeBSD: graphics/rubygem-exifr/Makefile 327733 2013-09-20 18:35:44Z bapt $

PORTNAME=	exifr
PORTVERSION=	1.1.3
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A pure-ruby EXIF reader

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/exifr

NO_STAGE=	yes
.include <bsd.port.mk>
