# Created by: Maxim Sobolev <sobomax@FreeBSD.org>
# $FreeBSD: devel/p5-String-Parity/Makefile 332205 2013-10-31 07:36:25Z vanilla $

PORTNAME=	String-Parity
PORTVERSION=	1.31
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A perl5 module to generate and test even, odd, mark, and space parity

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
