# New ports collection makefile for:   p5-Geo-Point
# Date created:        27 December 2005
# Whom:                estith
#
# $FreeBSD: ports/devel/p5-Geo-ShapeFile/Makefile,v 1.7 2012/11/17 05:56:17 svnexp Exp $
#

PORTNAME=	Geo-ShapeFile
PORTVERSION=	2.52
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lippe@FreeBSD.org
COMMENT=	Perl extension for handling ESRI GIS Shapefiles

PERL_CONFIGURE=	yes

MAN3=		Geo::ShapeFile.3 Geo::ShapeFile::Point.3 Geo::ShapeFile::Shape.3

.include <bsd.port.mk>
