# $FreeBSD: devel/p5-Log-Any/Makefile 318693 2013-05-21 13:30:27Z kuriyama $

PORTNAME=	Log-Any
PORTVERSION=	0.15
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JSWARTZ
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to bring loggers and listeners together

PERL_CONFIGURE=	yes

MAN3=	Log::Any.3 \
	Log::Any::Adapter::Core.3 \
	Log::Any::Adapter::Null.3 \
	Log::Any::Test.3

.include <bsd.port.mk>
