# Created by: alex
# $FreeBSD: textproc/nl-ispell/Makefile 340722 2014-01-22 17:00:46Z mat $

MAINTAINER=	office@FreeBSD.org

ISPELL_NL=	yes
PORTNAME=	nl-ispell
PORTVERSION=	1.0.0
PORTREVISION=	2
MASTERDIR=	${.CURDIR}/../ispell

NO_STAGE=	yes
.include        "${MASTERDIR}/Makefile"
