# New ports collection makefile for:    nl-ispell
# Date created:                         13 January 2001
# Whom:                                 alex
#
# $FreeBSD: ports/textproc/nl-ispell/Makefile,v 1.9 2012/11/17 06:02:03 svnexp Exp $
#

MAINTAINER=	office@FreeBSD.org

ISPELL_NL=	yes
PORTNAME=	nl-ispell
PORTVERSION=	1.0.0
PORTREVISION=	2
MASTERDIR=	${.CURDIR}/../ispell

.include        "${MASTERDIR}/Makefile"
