# $FreeBSD: textproc/p5-XML-Code/Makefile 333056 2013-11-07 03:52:41Z vanilla $

PORTNAME=	XML-Code
PORTVERSION=	0.4
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Module for converting XML hash structures into plain text

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
