# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: textproc/ebook-tools/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	ebook-tools
PORTVERSION=	0.2.2
CATEGORIES=	textproc kde
MASTER_SITES=	SF

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Accesses and converts various ebook file formats

LIB_DEPENDS=	zip:${PORTSDIR}/archivers/libzip

USES=		cmake
USE_LDCONFIG=	yes
USE_GNOME=	libxml2

NO_STAGE=	yes
.include <bsd.port.mk>
