# Created by: TERAMOTO Masahiro <markun@onohara.to>
# $FreeBSD: www/rubygem-simple-rss/Makefile 322897 2013-07-13 06:50:08Z swills $

PORTNAME=	simple-rss
PORTVERSION=	1.2.3
CATEGORIES=	www textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	markun@onohara.to
COMMENT=	A simple, flexible, extensible, and liberal RSS and Atom reader for Ruby.

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
