# New ports collection makefile for:	rubygem-simple-rss
# Date created:		2009-07-13
# Whom:			TERAMOTO Masahiro <markun@onohara.to>
#
# $FreeBSD: ports/www/rubygem-simple-rss/Makefile,v 1.3 2012/11/17 06:03:05 svnexp Exp $
#

PORTNAME=	simple-rss
PORTVERSION=	1.2
CATEGORIES=	www textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	markun@onohara.to
COMMENT=	A simple, flexible, extensible, and liberal RSS and Atom reader for Ruby.

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
