# Created by: Mario S F Ferreira <lioux@FreeBSD.org>
# $FreeBSD: math/p5-Math-FFT/Makefile 332813 2013-11-05 06:56:18Z vanilla $

PORTNAME=	Math-FFT
PORTVERSION=	1.28
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module providing an interface to Fast Fourier Transform routines

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
