# New ports collection makefile for:	p5-Math-FFT
# Date created:				12 Mar 2001
# Whom:			Mario S F Ferreira <lioux@FreeBSD.org>
#
# $FreeBSD: ports/math/p5-Math-FFT/Makefile,v 1.10 2012/11/17 05:59:26 svnexp Exp $
#

PORTNAME=	Math-FFT
PORTVERSION=	1.28
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module providing an interface to Fast Fourier Transform routines

PERL_CONFIGURE=	yes

MAN3=		Math::FFT.3

.include <bsd.port.mk>
