# $FreeBSD: comms/gstreamer1-plugins-spandsp/Makefile 332416 2013-11-01 22:14:07Z kwm $

PORTREVISION=	0
CATEGORIES=	comms

COMMENT=	Gstreamer DSP library and software FAX machine plugin

GST_PLUGIN=	spandsp
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
