# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11/libXvMC/Makefile 336621 2013-12-16 11:11:09Z zeising $

PORTNAME=	libXvMC
PORTVERSION=	1.0.8
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Video Extension Motion Compensation library

XORG_CAT=	lib
USE_XORG=	x11 xext xv xextproto videoproto:both xproto:both

.include <bsd.port.mk>
