# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: devel/rubygem-hashie/Makefile 340901 2014-01-24 14:46:50Z miwi $

PORTNAME=	hashie
PORTVERSION=	2.0.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	Hashie is a simple collection of useful Hash extensions

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=yes

.include <bsd.port.mk>
