# New ports collection makefile for:	xtoolwait
# Date created:		31 May 1997
# Whom:			jonny
#
# $FreeBSD: ports/x11/xtoolwait/Makefile,v 1.12 2012/11/17 06:03:23 svnexp Exp $
#

PORTNAME=	xtoolwait
PORTVERSION=	1.3
PORTREVISION=	2
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	utilities

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tool startup utility for X11

USE_IMAKE=	yes
USE_XORG=	x11 xext
MAN1=		xtoolwait.1
PLIST_FILES=	bin/xtoolwait

.include <bsd.port.mk>
