# Created by: jonny
# $FreeBSD: x11/xtoolwait/Makefile 327777 2013-09-20 23:43:19Z bapt $

PORTNAME=	xtoolwait
PORTVERSION=	1.3
PORTREVISION=	2
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	utilities

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tool startup utility for X11

USES=		imake
USE_XORG=	x11 xext
MAN1=		xtoolwait.1
PLIST_FILES=	bin/xtoolwait

NO_STAGE=	yes
.include <bsd.port.mk>
