# Created by: jonny
# $FreeBSD: x11/xtoolwait/Makefile 322008 2013-06-28 22:51:40Z bapt $

PORTNAME=	xtoolwait
PORTVERSION=	1.3
PORTREVISION=	2
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	utilities

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tool startup utility for X11

USES=		imake
USE_XORG=	x11 xext
MAN1=		xtoolwait.1
PLIST_FILES=	bin/xtoolwait

.include <bsd.port.mk>
