# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-minitest/Makefile 332039 2013-10-30 02:39:14Z swills $

PORTNAME=	minitest
PORTVERSION=	5.0.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Minitest provides a complete suite of testing facilities

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
