# New ports collection makefile for:	rubygem-minitest
# Date created:		2011-06-19
# Whom:			Steve Wills <swills@FreeBSD.org>
#
# $FreeBSD: ports/devel/rubygem-minitest/Makefile,v 1.14 2012/11/17 05:57:00 svnexp Exp $
#

PORTNAME=	minitest
PORTVERSION=	3.3.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Minitest provides a complete suite of testing facilities

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
