# $FreeBSD: ports/databases/postgresql90-pgtcl/Makefile,v 1.3 2012/11/17 05:55:20 svnexp Exp $

WANT_PGSQL_VER=	90
PKGNAMESUFFIX=	-postgresql${WANT_PGSQL_VER}

CONFLICTS=	pgtcl-[0-9]* pgtcl-postgresql9[12]-[0-9]*

MASTERDIR=	${.CURDIR}/../pgtcl

.include "${MASTERDIR}/Makefile"
