# New ports collection makefile for:	lookup for Mule 2.3
# Date created:		98/11/19
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/lookup-emacs21/Makefile,v 1.31 2012/11/17 05:58:36 svnexp Exp $
#

MASTERDIR=	${.CURDIR}/../lookup

USE_EMACS=	yes
EMACS_PORT_NAME=	emacs21

.include "${MASTERDIR}/Makefile"
