# Created by: vl
# $FreeBSD: www/mod_lisp2/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	mod_lisp2
PORTVERSION=	1.3.1
PORTREVISION=	2
CATEGORIES=	www
MASTER_SITES=	http://freebsd.minira.nl/

MAINTAINER=	viktor.leis@googlemail.com
COMMENT=	Apache2 module for use with Common Lisp

DEPRECATED=	distfile unfetchable
EXPIRATION_DATE=2014-01-01

USE_APACHE=	22
AP_FAST_BUILD=	yes
AP_GENPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
