# New ports collection makefile for:	AI-NeuralNet-BackProp
# Date created:				15 Nov 2000
# Whom:					will
#
# $FreeBSD: ports/math/p5-AI-NeuralNet-BackProp/Makefile,v 1.10 2012/11/17 05:59:25 svnexp Exp $
#

PORTNAME=	AI-NeuralNet-BackProp
PORTVERSION=	0.89
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module implementing a back-propagation feed-forward neural network

USE_ZIP=	yes
NO_WRKSUBDIR=	yes
PERL_CONFIGURE=	yes

MAN3=		AI::NeuralNet::BackProp.3

.include <bsd.port.mk>
