# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: net/p5-BBS-UserInfo-Maple3/Makefile 338799 2014-01-05 16:55:04Z az $

PORTNAME=	BBS-UserInfo-Maple3
PORTVERSION=	0.01
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:GSLIN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Get user information of Maple3-style BBS

RUN_DEPENDS=	p5-Expect>=0:${PORTSDIR}/lang/p5-Expect

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
