# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: textproc/p5-Text-FixedLength-Extra/Makefile 340907 2014-01-24 14:56:48Z mat $

PORTNAME=	Text-FixedLength-Extra
PORTVERSION=	1.1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Various niceties for p5-Text-FixedLength lovers

BUILD_DEPENDS=	p5-Text-FixedLength>=0:${PORTSDIR}/textproc/p5-Text-FixedLength
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
