# Created by: Pawel Worach
# $FreeBSD: x11-fonts/font-jis-misc/Makefile 336621 2013-12-16 11:11:09Z zeising $

PORTNAME=	font-jis-misc
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org miscellaneous JIS fonts

XORG_CAT=	font

.include <bsd.port.mk>
