# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-Time-Piece/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Time-Piece
PORTVERSION=	1.23
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Time::Piece - Object Oriented time objects

USES=		perl5
USE_PERL5=	configure

MAN3=		Time::Piece.3 Time::Seconds.3

NO_STAGE=	yes
.include <bsd.port.mk>
