# Created by: Jyun-Yan You <jyyou@cs.nctu.edu.tw>
# $FreeBSD: devel/ats-contrib-testing/Makefile 327722 2013-09-20 17:03:26Z bapt $

PORTNAME=	testing
PORTVERSION=	${ATS_VER}
CATEGORIES=	devel
MASTER_SITES=	# empty
DISTFILES=	# empty

MAINTAINER=	jyyou@cs.nctu.edu.tw
COMMENT=	Facilitating construction of testing code for ATS language

NO_BUILD=	yes
ATS_CTRB=	testing

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ats/bsd.ats.mk"
.include <bsd.port.mk>
