# $FreeBSD: devel/p5-Test-Requires/Makefile 341623 2014-01-28 16:45:35Z miwi $

PORTNAME=	Test-Requires
PORTVERSION=	0.07
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for checking to see if the module can be loaded

USES=	perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
