# Created by: Stephen Roznowski (sjr@home.com)
# $FreeBSD: textproc/p5-Parse-Syslog/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	Parse-Syslog
PORTVERSION=	1.10
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 routines that present a simple interface to parse syslog files

BUILD_DEPENDS=	p5-IO-stringy>=0:${PORTSDIR}/devel/p5-IO-stringy

USES=		perl5
USE_PERL5=	configure

MAN3=		Parse::Syslog.3

NO_STAGE=	yes
.include <bsd.port.mk>
