# $FreeBSD: x11/xmh/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	xmh
PORTVERSION=	1.0.2
CATEGORIES=	x11 mail

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Send and read mail with an X interface to MH

RUN_DEPENDS+=	repl:${PORTSDIR}/mail/nmh

XORG_CAT=	app
USE_XORG=	xaw xmu xt xbitmaps

MAN1=		xmh.1

.include <bsd.port.mk>
