# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: devel/p5-Test-File/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Test-File
PORTVERSION=	1.34
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Test file attributes

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Manifest>=1.14:${PORTSDIR}/devel/p5-Test-Manifest

USES=		perl5
USE_PERL5=	configure

MAN3=		Test::File.3

.include <bsd.port.mk>
