# Created by: Douglas Thrift <douglas@douglasthrift.net>
# $FreeBSD: devel/py-pycerberus/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	pycerberus
PORTVERSION=	0.5
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	douglas@douglasthrift.net
COMMENT=	Highly flexible, no magic input validation library

LICENSE=	MIT

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
