# $FreeBSD: devel/hs-data-default-instances-dlist/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	data-default-instances-dlist
PORTVERSION=	0.0.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Default instances for types in dlist

LICENSE=	BSD

USE_CABAL=	data-default-class dlist

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
