# Created by: Alexey V. Antipovsky <kemm@in-line.ru>
# $FreeBSD: head/devel/p5-Date-Simple/Makefile 341630 2014-01-28 16:47:06Z miwi $

PORTNAME=		Date-Simple
PORTVERSION=		3.03
CATEGORIES=		devel perl5
MASTER_SITES=		CPAN
PKGNAMEPREFIX=		p5-

MAINTAINER=		dhn@FreeBSD.org
COMMENT=		A simple date object

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
