# $FreeBSD: ports/finance/expense/Makefile,v 1.9 2012/11/17 05:57:25 svnexp Exp $

PORTNAME=	expense
PORTVERSION=	0.1
PORTREVISION=	2
CATEGORIES=	finance gnustep
MASTER_SITES=	http://www.eskimo.com/~pburns/Expense/files/
DISTNAME=	Expense-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Application to track your expense under GNUstep

LICENSE=	GPLv2

USE_GNUSTEP=	yes
USE_GNUSTEP_BACK=	yes
USE_GNUSTEP_BUILD=	yes
USE_GNUSTEP_INSTALL=	yes

WRKSRC=		${WRKDIR}/Expense

.include <bsd.port.mk>
