# $FreeBSD: security/hs-cipher-aes/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	cipher-aes
PORTVERSION=	0.1.8
PORTREVISION=	1
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast AES cipher implementation with advanced mode of operations

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
