# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: archivers/p5-Compress-Bzip2/Makefile 338685 2014-01-04 23:32:43Z bapt $

PORTNAME=	Compress-Bzip2
PORTVERSION=	2.17
CATEGORIES=	archivers perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Perl5 interface to bzip2 compression library

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
