# $FreeBSD: textproc/rubygem-jsmin/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	jsmin
PORTVERSION=	1.0.1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby implementation of Douglas Crockford's JSMin JavaScript minifier

USE_RUBY=	yes
USE_PYTHON=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
