# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: audio/opencore-amr/Makefile 325727 2013-08-30 23:01:05Z bapt $

PORTNAME=	opencore-amr
PORTVERSION=	0.1.3
CATEGORIES=	audio
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}

MAINTAINER=	gslin@gslin.org
COMMENT=	OpenCORE implementation of AMR Narrowband & Wideband speech codec

LICENSE=	AL2

GNU_CONFIGURE=	yes
USES=		gmake pathfix
USE_LDCONFIG=	yes

.include <bsd.port.mk>
