# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: archivers/quazip/Makefile 334586 2013-11-22 12:55:00Z makc $

PORTNAME=	quazip
PORTVERSION=	0.5.1
#PORTREVISION=	0
CATEGORIES=	archivers
MASTER_SITES=	SF

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Qt/C++ wrapper for ZIP/UNZIP package

LICENSE=	LGPL21

USES=		qmake
USE_LDCONFIG=	yes
USE_QT4=	corelib moc_build qtestlib

.include <bsd.port.mk>
