PORTNAME=	fortunate
PORTVERSION=	3.1
PORTREVISION=	11
CATEGORIES=	games gnustep
MASTER_SITES=	https://broken_for_developer_mode.z/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Graphical front-end to the command-line BSD fortune
WWW=		https://www.orange-carb.org/~csaldanh/software.html

USES=		gnustep
USE_GNUSTEP=	back build

.include <bsd.port.mk>
