# New ports collection makefile for:	devel/p5-IO-CaptureOutput
# Date created:				27 December 2004
# Whom:					Lars Thegler <lth@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-IO-CaptureOutput/Makefile,v 1.13 2012/11/17 05:56:18 svnexp Exp $
#

PORTNAME=	IO-CaptureOutput
PORTVERSION=	1.11.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Capture STDOUT/STDERR from subprocesses and XS/C modules

PERL_CONFIGURE=	yes

MAN3=	IO::CaptureOutput.3

.include <bsd.port.mk>
