# Created by: Kimo <kimor79@yahoo.com>
# $FreeBSD: www/rubygem-eventmachine_httpserver/Makefile 332054 2013-10-30 03:01:19Z swills $

PORTNAME=	eventmachine_httpserver
PORTVERSION=	0.2.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	EventMachine HTTP Server

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
