# $FreeBSD: ftp/gstreamer1-plugins-curl/Makefile 316693 2013-04-27 20:56:38Z kwm $

PORTREVISION=	0
CATEGORIES=	ftp

COMMENT=	Gstreamer curl plugin

GST_PLUGIN=	curl
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
