# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: textproc/hs-Diff/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	Diff
PORTVERSION=	0.2.0
PORTREVISION=	1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	O(ND) diff algorithm in haskell

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
