# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD: math/R-cran-RSvgDevice/Makefile 335044 2013-11-27 18:56:43Z dbn $

PORTNAME=	RSvgDevice
PORTVERSION=	0.6.4.3
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	A R SVG graphics device

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
