# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD: math/R-cran-RSvgDevice/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	RSvgDevice
PORTVERSION=	0.6.4.3
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	A R SVG graphics device

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=	cran:auto-plist

.include <bsd.port.mk>
