# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD: math/R-cran-RSvgDevice/Makefile 322997 2013-07-14 18:41:01Z dbn $

PORTNAME=	RSvgDevice
PORTVERSION=	0.6.4.3
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	A R SVG graphics device

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
