# $FreeBSD: devel/hs-silently/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	silently
PORTVERSION=	1.2.4.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Prevent or capture writing to stdout and other handles

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
