# $FreeBSD: ports/devel/hs-silently/Makefile,v 1.5 2013/02/05 22:47:09 svnexp Exp $

PORTNAME=	silently
PORTVERSION=	1.2.4.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Prevent or capture writing to stdout and other handles

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
