# Created by: Konstantin Chuguev <Konstantin.Chuguev@dante.org.uk>
# $FreeBSD: converters/iconv-rfc1345/Makefile 326872 2013-09-10 07:55:33Z az $

PORTNAME=	iconv-rfc1345
PORTVERSION=	2.0
CATEGORIES=	converters
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	bland

MAINTAINER=	bland@FreeBSD.org
COMMENT=	Additional charset modules for the iconv library (from RFC1345)

LIB_DEPENDS=	biconv.2:${PORTSDIR}/converters/iconv

USES=		perl5

.include <bsd.port.mk>
