# Created by: Alex Kapranoff <kappa@FreeBSD.org.ua>
# $FreeBSD: devel/p5-Devel-ptkdb/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Devel-ptkdb
PORTVERSION=	1.1091
PORTREVISION=	4
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tk debugger for Perl

RUN_DEPENDS=	p5-Tk>=0:${PORTSDIR}/x11-toolkits/p5-Tk

USES=		perl5
USE_PERL5=	configure

MAN3=		Devel::ptkdb.3

NO_STAGE=	yes
.include <bsd.port.mk>
