@@ -54,10 +54,11 @@
 RRTYPETA_CONFIGURE_ENABLE=		rrtype-ta
 RRTYPEAVC_CONFIGURE_ENABLE=		rrtype-avc
 RRTYPEAMTRELAY_CONFIGURE_ENABLE=	rrtype-amtrelay
-EXAMPLES_CONFIGURE_WITH=		examples
+#EXAMPLES_CONFIGURE_WITH=		examples
 DRILL_CONFIGURE_WITH=			drill
 DRILL_INSTALL_TARGET=			install-drill
-EXAMPLES_INSTALL_TARGET=		install-examples
+#EXAMPLES_INSTALL_TARGET=		install-examples
+PLIST_SUB+=                    EXAMPLES="@comment "
 
 .if defined(BUILD_PYLDNS)
 USES+=		python
