# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: graphics/hs-HGL/Makefile 317973 2013-05-12 19:30:28Z pgj $

PORTNAME=	HGL
PORTVERSION=	3.2.0.2
PORTREVISION=	9
CATEGORIES=	graphics haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A simple Haskell graphics library based on X11 or Win32

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	X11

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
