# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: graphics/hs-HGL/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	HGL
PORTVERSION=	3.2.0.2
PORTREVISION=	11
CATEGORIES=	graphics haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple Haskell graphics library based on X11 or Win32

LICENSE=	BSD

USE_CABAL=	X11

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
