# Created by: brg@dgate.org
# $FreeBSD: emulators/vmips/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	vmips
PORTVERSION=	1.4.1
CATEGORIES=	emulators
MASTER_SITES=	SF \
		http://www.dgate.org/vmips/releases/${DISTNAME}/

MAINTAINER=	brg@dgate.org
COMMENT=	MIPS R3000 simulator

USE_GMAKE=	yes
GNU_CONFIGURE=	yes

MAN1=		vmips.1 vmipstool.1
INFO=		vmips

NO_STAGE=	yes
.include <bsd.port.mk>
