# Created by: renchap@cocoa-x.com
# $FreeBSD: net/rubygem-bunny/Makefile 322879 2013-07-13 05:10:37Z swills $

PORTNAME=	bunny
PORTVERSION=	0.8.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Another synchronous Ruby AMQP client

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
