# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD: www/py-django-mezzanine-grappelli/Makefile 317398 2013-05-05 06:41:29Z koobs $

PORTNAME=	django-mezzanine-grappelli
PORTVERSION=	0.2.21
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	grappelli_safe-${PORTVERSION}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Fork of django-grappelli for Mezzanine CMS

USE_PYTHON=	yes
USES=		gettext
USE_PYDISTUTILS=	easy_install
PYDISTUTILS_PKGNAME=	grappelli_safe

.include <bsd.port.mk>
