# New ports collection makefile for:	p5-Data-IPV4-Range-Parse
# Date created:		2010-11-10
# Whom:			Gea-Suan Lin <gslin@gslin.org>
#
# $FreeBSD: ports/net/p5-Data-IPV4-Range-Parse/Makefile,v 1.3 2012/11/17 06:00:09 svnexp Exp $
#

PORTNAME=	Data-IPV4-Range-Parse
PORTVERSION=	1.05
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Perl extension parsing IPv4 ranges

PERL_CONFIGURE=	yes

MAN3=		Data::IPV4::Range::Parse.3

.include <bsd.port.mk>
