# New ports collection makefile for: squid_radius_auth
# Date created: 18 October 2005
# Whom: Michael Capp <myntric@exeonline.com>
#
# $FreeBSD: ports/www/squid_radius_auth/Makefile,v 1.4 2012/11/17 06:03:06 svnexp Exp $
#

PORTNAME=	squid_radius_auth
PORTVERSION=	1.10
CATEGORIES=	www
MASTER_SITES=	http://www.squid-cache.org/contrib/squid_radius_auth/

MAINTAINER=	freebsd@falz.net
COMMENT=	RADIUS authenticator for squid proxy 2.5 and later

MAN8=		squid_radius_auth.8

.include <bsd.port.mk>
