# $FreeBSD: devel/hs-simple-reflect/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	simple-reflect
PORTVERSION=	0.3.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple reflection of expressions containing variables

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
