# Created by: George Reid <greid@ukug.uk.freebsd.org>
# $FreeBSD: ports/archivers/sectar/Makefile,v 1.14 2012/12/18 08:04:12 svnexp Exp $

PORTNAME=	sectar
PORTVERSION=	1.02
CATEGORIES=	archivers
MASTER_SITES=	SF/star/${PORTNAME}/${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Program to create encrypted tar archives

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/sectar

.include <bsd.port.mk>
