
CFLAGS+=	-Wno-format-truncation

dfly-patch:
	${REINPLACE_CMD} -e 's@\(defined(__FreeBSD__)\)@(\1 || defined(__DragonFly__))@g' \
		${WRKSRC}/anongitssh.c
	${REINPLACE_CMD} -e 's@-Wmissing-variable-declarations@@g' \
			 -e 's@-Wthread-safety@@g' -e 's@-Qunused-arguments@@g' \
		${WRKSRC}/Makefile
