# $FreeBSD: textproc/rubygem-compass-rails/Makefile 335757 2013-12-06 15:23:38Z sunpoet $

PORTNAME=	compass-rails
PORTVERSION=	1.1.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Integrate Compass into Rails 2.3 and up

LICENSE=	MIT

RUN_DEPENDS=	rubygem-compass>=0.12.2:${PORTSDIR}/textproc/rubygem-compass

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
