# $FreeBSD: devel/hs-MonadCatchIO-transformers/Makefile 327723 2013-09-20 17:04:43Z bapt $

PORTNAME=	MonadCatchIO-transformers
PORTVERSION=	0.3.0.0
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad-transformer-compatible version of Control.Exception

LICENSE=	BSD

USE_CABAL=	extensible-exceptions>=0.1 transformers>=0.2

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
