# Created by: Tony Maher <tonym@biolateral.com.au>
# $FreeBSD: devel/p5-Class-ObjectTemplate/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Class-ObjectTemplate
PORTVERSION=	0.7
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Optimized template builder base class

USES=		perl5
USE_PERL5=	configure

MAN3=		Class::ObjectTemplate.3

NO_STAGE=	yes
.include <bsd.port.mk>
