# $FreeBSD: multimedia/p5-Net-UPnP/Makefile 332815 2013-11-05 07:28:38Z vanilla $

PORTNAME=	Net-UPnP
PORTVERSION=	1.4.2
CATEGORIES=	multimedia devel
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:SKONNO
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for UPnP

USES=		perl5
USE_PERL5=	configure

LICENSE=	BSD
LICENSE_FILE=	${WRKSRC}/README

.include <bsd.port.mk>
