# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: net-mgmt/p5-Xymon/Makefile 327757 2013-09-20 22:24:43Z bapt $

PORTNAME=	Xymon
PORTVERSION=	0.01
CATEGORIES=	net-mgmt
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Xymon Base Module

USES=		perl5
USE_PERL5=	configure

MAN3=		Xymon.3

NO_STAGE=	yes
.include <bsd.port.mk>
