# Created by: Rong-En Fan <rafan@FreeBSD.org>
# $FreeBSD: security/p5-Crypt-OICQ/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	Crypt-OICQ
PORTVERSION=	1.1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
EXTRACT_SUFX=	.tgz

MAINTAINER=	rafan@FreeBSD.org
COMMENT=	Cryptographic algorithm used by OICQ protocol

USES=		perl5
USE_PERL5=	configure

MAN3=		Crypt::OICQ.3

NO_STAGE=	yes
.include <bsd.port.mk>
