# Created by: TAKAHASHI Kaoru <kaoru@kaisei.org>
# $FreeBSD: www/p5-Acme-Monta/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	Acme-Monta
PORTVERSION=	0.01
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kaoru@kaisei.org
COMMENT=	Monta Method reproduced in web

USES=		perl5
USE_PERL5=	configure

MAN3=		Acme::Monta.3

NO_STAGE=	yes
.include <bsd.port.mk>
