# Created by: Jim Riggs <ports@christianserving.org>
# $FreeBSD: devel/libestr/Makefile 328096 2013-09-24 06:24:17Z bapt $

PORTNAME=	libestr
PORTVERSION=	0.1.5
CATEGORIES=	devel
MASTER_SITES=	http://libestr.adiscon.com/files/download/

MAINTAINER=	brd@FreeBSD.org
COMMENT=	Library for some string essentials

USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--prefix="${PREFIX}" \
			--disable-testbench

.include <bsd.port.mk>
