# Created by: Jean-Yves Lefort <jylefort@FreeBSD.org>
# $FreeBSD: net/linc-reference/Makefile 327755 2013-09-20 22:10:23Z bapt $

PORTREVISION=	0

REFERENCE_SRC=	${WRKSRC}/docs

NO_STAGE=	yes
.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
