# Created by: ijliao
# $FreeBSD: databases/py-oops/Makefile 339634 2014-01-13 21:00:02Z rene $

PORTNAME=	oops
PORTVERSION=	0.9.1
CATEGORIES=	databases python
MASTER_SITES=	SF/pyobjfs/OOPS-Python%20Datastore/${PORTNAME}-${PORTVERSION}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Object Oriented Database Library For Persistent Storage in Python

USE_PYTHON=		2
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
