# Created by: Simon Barner <barner@gmx.de>
# $FreeBSD: audio/p5-Audio-WMA/Makefile 332336 2013-11-01 02:28:24Z vanilla $

PORTNAME=	Audio-WMA
PORTVERSION=	1.3
CATEGORIES=	audio perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Fetch info from WMA audio files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
