# Created by: Jean-Yves Lefort <jylefort@FreeBSD.org>
# $FreeBSD: devel/ORBit2-reference/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTREVISION=	0

REFERENCE_SRC=	${WRKSRC}/docs/api

NO_STAGE=	yes
.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
