# Created by: J.R. Oldroyd <fbsd@opal.com>
# $FreeBSD: devel/libisofs/Makefile 331069 2013-10-20 22:55:19Z delphij $

PORTNAME=	libisofs
PORTVERSION=	1.3.2
CATEGORIES=	devel
MASTER_SITES=	http://files.libburnia-project.org/releases/

MAINTAINER=	delphij@FreeBSD.org
COMMENT=	Libburnia ISO9660 filesystem creation library

LICENSE=	GPLv2

LIB_DEPENDS=	burn.4:${PORTSDIR}/devel/libburn

GNU_CONFIGURE=	yes
USES=		iconv
USE_LDCONFIG=	yes

.include <bsd.port.mk>
