# Created by: Wen Heping <wenhping@gmail.com>
# $FreeBSD: lang/cython/Makefile 317011 2013-05-01 11:14:06Z wen $

PORTNAME=	cython
PORTVERSION=	0.19
CATEGORIES=	lang python
MASTER_SITES=	http://www.cython.org/release/ \
		CHEESESHOP
DISTNAME=	Cython-${PORTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Compiler for Writing C Extensions for the Python Language

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_PKGNAME=	Cython

.include <bsd.port.mk>
