Obtained from:	https://github.com/pypa/pip-audit/commit/4bd5b528b91233fd70ce0c085ab16c40ef78bc1f

--- pyproject.toml.orig	2025-02-06 22:57:47 UTC
+++ pyproject.toml
@@ -28,7 +28,7 @@ dependencies = [
 ]
 dependencies = [
     "CacheControl[filecache] >= 0.13.0",
-    "cyclonedx-python-lib >= 5,< 9",
+    "cyclonedx-python-lib >= 5,< 10",
     "packaging>=23.0.0",                 # https://github.com/pypa/pip-audit/issues/464
     "pip-api>=0.0.28",
     "pip-requirements-parser>=32.0.0",
