# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: devel/pear-Horde_Support/Makefile 326198 2013-09-03 18:43:02Z mm $

PORTNAME=	Horde_Support
PORTVERSION=	2.1.1
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde support package

USE_HORDE_RUN=	Horde_Exception \
		Horde_Stream_Wrapper

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
