# Created by: Mario S F Ferreira <lioux@linf.unb.br> et al.
# $FreeBSD: math/p5-Math-Logic/Makefile 327746 2013-09-20 20:55:04Z bapt $

PORTNAME=	Math-Logic
PORTVERSION=	1.19
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module providing pure 2, 3, or multi-value logic

USES=		perl5
USE_PERL5=	configure
MAN3=		Math::Logic.3

NO_STAGE=	yes
.include <bsd.port.mk>
