# $FreeBSD: www/twiki-WysiwygPlugin/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	WysiwygPlugin
SVNREV=		17720
PORTREVISION=	1

COMMENT=	Translator framework for Wysiwyg editors

RUN_DEPENDS=	p5-HTML-Parser>=3.28:${PORTSDIR}/www/p5-HTML-Parser

NO_STAGE=	yes
.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
