# New ports collection makefile for:    xrisk
# Date created:		4 Jan 1995
# Whom:			swallace
#
# $FreeBSD: ports/games/xrisk/Makefile,v 1.29 2012/11/17 05:57:58 svnexp Exp $
#

PORTNAME=	xrisk
PORTVERSION=	2.15
PORTREVISION=	2
CATEGORIES=	games
MASTER_SITES=	http://my.pages.de/pub/comp/unix/games/xrisk/old/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A game for X11, much like the popular board game

USE_IMAKE=	yes
USE_XORG=	x11 xext xt
MAN6=		xrisk.6

RESTRICTED=	"Possible trademark infringement"

.include <bsd.port.mk>
