# Created by: Yukihiro Nakai <Nakai@Mlab.t.u-tokyo.ac.jp>
# $FreeBSD: x11/xzoom/Makefile 322008 2013-06-28 22:51:40Z bapt $

PORTNAME=	xzoom
PORTVERSION=	0.3
PORTREVISION=	2
CATEGORIES=	x11 accessibility
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	libs/X
EXTRACT_SUFX=	.tgz

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Magnify, rotate, mirror the image on the X screen

USES=		imake
USE_XORG=	x11 xext
MAN1=		xzoom.1
PLIST_FILES=	bin/xzoom

.include <bsd.port.mk>
