# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: math/p5-Math-Combinatorics/Makefile 327746 2013-09-20 20:55:04Z bapt $

PORTNAME=	Math-Combinatorics
PORTVERSION=	0.09
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perform combinations and permutations on lists

MAN3=		Math::Combinatorics.3

USES=		perl5
USE_PERL5=	configure

NO_STAGE=	yes
.include <bsd.port.mk>
