# $FreeBSD: ports/devel/gwenhywfar-qt4/Makefile,v 1.4 2012/11/17 05:55:46 svnexp Exp $

PORTREVISION=	0
PKGNAMESUFFIX=	-${SLAVEPORT}

MAINTAINER=	jhale@FreeBSD.org
COMMENT=	Gwenhywfar Qt4 support library

MASTERDIR=	${.CURDIR}/../../devel/gwenhywfar
SLAVEPORT=	qt4
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
