# $FreeBSD: www/pear-Horde_SessionHandler/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	Horde_SessionHandler
PORTVERSION=	2.2.3
CATEGORIES=	www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Session Handler API

USE_HORDE_RUN=	Horde_Exception \
		Horde_Util

NO_STAGE=	yes
.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
