# Ports collection makefile for:  pear-Horde_SessionHandler
# Date created:			  6 July 2011
# Whom:				  Martin Matuska <mm@FreeBSD.org>
#
# $FreeBSD: www/pear-Horde_SessionHandler/Makefile 317889 2013-05-11 15:37:47Z mm $

PORTNAME=	Horde_SessionHandler
PORTVERSION=	2.1.0
CATEGORIES=	www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Session Handler API

USE_HORDE_RUN=	Horde_Exception \
		Horde_Util

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
