# Created by: Will Andrews <andrews@technologist.com>
# $FreeBSD: devel/p5-IO-Tty/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	IO-Tty
PORTVERSION=	1.10
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Flexible I/O Perl5 module that allows manipulation of pseudo-TTYs

USES=		perl5
USE_PERL5=	configure

MAN3=		IO::Pty.3 \
		IO::Tty.3 \
		IO::Tty::Constant.3

.include <bsd.port.mk>
