# Created by: johnpupu <johnpupu@gmail.com>
# $FreeBSD: ports/databases/pecl-mysqlnd_ms/Makefile,v 1.7 2012/11/17 05:55:18 svnexp Exp $

PORTNAME=	mysqlnd_ms
PORTVERSION=	1.4.2
CATEGORIES=	databases
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
EXTRACT_SUFX=	.tgz
DIST_SUBDIR=	PECL

MAINTAINER=	johnpupu@gmail.com
COMMENT=	Replication and load balancing plugin for mysqlnd

USE_PHP=	json
USE_PHP_BUILD=	yes
USE_PHPEXT=	yes
USE_PHPIZE=	yes

.include <bsd.port.mk>
