# $FreeBSD: x11/scripts/Makefile 336621 2013-12-16 11:11:09Z zeising $

PORTNAME=	scripts
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Various X related scripts

XORG_CAT=	app
USE_XORG=	x11

.include <bsd.port.mk>
