# New ports collection makefile for:    pa-aspell
# Date created:                         02 June 2005
# Whom:                                 Thierry Thomas <thierry@pompo.net>
#
# $FreeBSD: ports/textproc/pa-aspell/Makefile,v 1.7 2012/11/17 06:02:14 svnexp Exp $
#

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-pa-0.01-1
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Punjabi dictionary

DICT=	 	pa

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
