# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: textproc/p5-Regexp-Log/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Regexp-Log
PORTVERSION=	0.06
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Regexp::Log - A base class for log files regexp builders

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
