# New ports collection makefile for:	rubygem-deeptest
# Date created:		7 April 2009
# Whom:			Philip M. Gollucci <pgollucci@p6m7g8.com>
#
# $FreeBSD: devel/rubygem-deeptest/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	deep_test
PORTVERSION=	1.2.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Enable tests to run in parallel using multiple processes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/deep_test

.include <bsd.port.mk>
