# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: textproc/lv-aspell/Makefile 332672 2013-11-04 08:30:37Z bapt $

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-lv-0.5.5-1
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Latvian dictionary

DICT=	 	lv

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
