# $FreeBSD: ports/devel/hs-optparse-applicative/Makefile,v 1.2 2013/02/05 22:47:09 svnexp Exp $

PORTNAME=	optparse-applicative
PORTVERSION=	0.5.2.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities and combinators for parsing command line options

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
