# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: russian/aspell/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	aspell
DISTVERSION=	6-ru-0.99f7-1
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	russian textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Russian dictionary

DICT=	 	ru

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
