# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: sysutils/ncdu/Makefile 317888 2013-05-11 15:31:46Z pawel $

PORTNAME=	ncdu
PORTVERSION=	1.10
CATEGORIES=	sysutils
MASTER_SITES=	http://dev.yorhel.nl/download/

MAINTAINER=	pawel@FreeBSD.org
COMMENT=	Ncurses du(1)

LICENSE=	MIT

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/${PORTNAME}
MAN1=		${PORTNAME}.1

.include <bsd.port.mk>
