# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: math/p5-Math-Round-Var/Makefile 324175 2013-08-02 21:38:09Z mat $

PORTNAME=	Math-Round-Var
PORTVERSION=	1.0.0
DISTVERSION=	v${PORTVERSION}
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Variations on rounding

MAN3=	Math::Round::Var.3

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
