# Created by: Edward Tomasz Napierala <trasz@FreeBSD.org>
# $FreeBSD: sysutils/confctl/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	confctl
PORTVERSION=	1.2
CATEGORIES=	sysutils
MASTER_SITES=	http://cloud.github.com/downloads/trasz/confctl/ \
		${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	trasz

MAINTAINER=	trasz@FreeBSD.org
COMMENT=	Utility to parse and modify C-like configuration files

LICENSE=	BSD

GNU_CONFIGURE=	yes
MAN1=		confctl.1
PLIST_FILES=	bin/confctl

NO_STAGE=	yes
.include <bsd.port.mk>
