# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-Test-Taint/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Test-Taint
PORTVERSION=	1.06
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Tools to test taintedness

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		Test::Taint.3

.include <bsd.port.mk>
