# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: ukrainian/kde4-l10n/Makefile 327774 2013-09-20 23:19:33Z bapt $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
CATEGORIES=	ukrainian kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Ukrainian messages and documentation for KDE SC 4

KDE4_L10N=	uk

MANLANG=	${KDE4_L10N}
NO_STAGE=	yes
.include <${.CURDIR}/Makefile.man>

.include "${.CURDIR}/../../misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
