# New ports collection makefile for:    swisswatch
# Date created:         16 December 1995
# Whom:                 Yoshiro MIHIRA <sanpei@yy.cs.keio.ac.jp>
#
# $FreeBSD: ports/x11-clocks/swisswatch/Makefile,v 1.17 2012/11/17 06:03:24 svnexp Exp $
#

PORTNAME=	swisswatch
PORTVERSION=	0.06
PORTREVISION=	2
CATEGORIES=	x11-clocks
MASTER_SITES=	${MASTER_SITE_PORTS_JP}
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	sanpei@FreeBSD.org
COMMENT=	A Swiss railway clock emulation, and a fancy default appearance

USE_IMAKE=	yes
USE_XORG=	ice sm x11 xext xmu xt
MAN1=		swisswatch.1

.include <bsd.port.mk>
