# Ports collection makefile for:	rubygem-mixlib-shellout
# Date created:				23 Aug 2012
# Whom:					ndewing@experts-exchange.com
#
# $FreeBSD: ports/devel/rubygem-mixlib-shellout/Makefile,v 1.3 2012/11/17 05:57:00 svnexp Exp $
#

PORTNAME=	mixlib-shellout
PORTVERSION=	1.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	nickdewing@gmail.com
COMMENT=	Shell interface that also collects stdout and stderr

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
