# Created by: Pav Lucistnik <pav@FreeBSD.org>
# $FreeBSD: archivers/rzip/Makefile 327699 2013-09-20 13:11:20Z bapt $

PORTNAME=	rzip
PORTVERSION=	2.1
CATEGORIES=	archivers
MASTER_SITES=	http://rzip.samba.org/ftp/rzip/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Compression program similar to gzip or bzip2

GNU_CONFIGURE=	yes

NO_STAGE=	yes
MAN1=		rzip.1
PLIST_FILES=	bin/rzip

.include <bsd.port.mk>
