# New ports collection makefile for:	rzip
# Date created:			9 April 2004
# Whom:				Pav Lucistnik <pav@FreeBSD.org>
#
# $FreeBSD: ports/archivers/rzip/Makefile,v 1.3 2012/11/17 05:54:23 svnexp Exp $

PORTNAME=	rzip
PORTVERSION=	2.1
CATEGORIES=	archivers
MASTER_SITES=	http://rzip.samba.org/ftp/rzip/

MAINTAINER=	pav@FreeBSD.org
COMMENT=	Compression program similar to gzip or bzip2

GNU_CONFIGURE=	yes

MAN1=		rzip.1
PLIST_FILES=	bin/rzip

.include <bsd.port.mk>
