# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: textproc/p5-Regexp-DefaultFlags/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	Regexp-DefaultFlags
PORTVERSION=	0.01
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Set default flags on regular expressions

USES=		perl5
USE_PERL5=	configure

MAN3=		Regexp::DefaultFlags.3

NO_STAGE=	yes
.include <bsd.port.mk>
