# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: textproc/p5-Text-Highlight/Makefile 333056 2013-11-07 03:52:41Z vanilla $

PORTNAME=	Text-Highlight
PORTVERSION=	0.04
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ICRF
PKGNAMEPREFIX=	p5-
DISTNAME=	text-highlight-${PORTVERSION}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Syntax highlighting framework

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
