
# zrj: be naughty (include dir search ordering)
dfly-patch:
	${REINPLACE_CMD} -e 's@BITS=32@BITS=64@g'	\
			 -e "s@-fno-rtti@-isystem ${LOCALBASE}/include@g"	\
		${WRKSRC}/../jogl/make/build-oculusvr.xml	\
		${WRKSRC}/../gluegen/Makefile
