# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: devel/p5-Data-Flow/Makefile 338884 2014-01-06 14:40:31Z az $

PORTNAME=	Data-Flow
PORTVERSION=	1.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl extension for simple-minded recipe-controlled build of data

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
