# New ports collection makefile for:	fr-MT
# Date created:			Fri, 2 Oct 2009 07:56:20 GMT
# Whom:				takefu
#
# $FreeBSD: ports/french/MT/Makefile,v 1.6 2012/11/17 05:57:28 svnexp Exp $
#

CATEGORIES=	french www
DISTNAME=	MTOS-${PORTVERSION}-${PKGNAMEPREFIX:S,-,,}
PKGNAMEPREFIX=	fr-

COMMENT=	French localization of the MovableType publishing system

MASTERDIR=	${.CURDIR}/../../www/MT
CONFLICTS=	MT-[2-5].* de-MT-[2-5].* ja-MT-[2-5].* ru-MT-[2-5].*

.include "${MASTERDIR}/Makefile"
