--- pyproject.toml.orig	2023-01-06 23:50:19 UTC
+++ pyproject.toml
@@ -27,26 +27,26 @@ all = [
 
 [project.optional-dependencies]
 all = [
-    "autopep8>=1.6.0,<1.7.0",
-    "flake8>=5.0.0,<7",
-    "mccabe>=0.7.0,<0.8.0",
-    "pycodestyle>=2.9.0,<2.11.0",
-    "pydocstyle>=6.2.0,<6.3.0",
-    "pyflakes>=2.5.0,<3.1.0",
+    "autopep8>=1.6.0",
+    "flake8>=5.0.0",
+    "mccabe>=0.7.0",
+    "pycodestyle>=2.9.0",
+    "pydocstyle>=6.2.0",
+    "pyflakes>=2.5.0",
     "pylint>=2.5.0,<3",
     "rope>1.2.0",
     "yapf",
     "whatthepatch>=1.0.2,<2.0.0"
 ]
-autopep8 = ["autopep8>=1.6.0,<1.7.0"]
-flake8 = ["flake8>=5.0.0,<7"]
-mccabe = ["mccabe>=0.7.0,<0.8.0"]
-pycodestyle = ["pycodestyle>=2.9.0,<2.11.0"]
-pydocstyle = ["pydocstyle>=6.2.0,<6.3.0"]
-pyflakes = ["pyflakes>=2.5.0,<3.1.0"]
+autopep8 = ["autopep8>=1.6.0"]
+flake8 = ["flake8>=5.0.0"]
+mccabe = ["mccabe>=0.7.0"]
+pycodestyle = ["pycodestyle>=2.9.0"]
+pydocstyle = ["pydocstyle>=6.2.0"]
+pyflakes = ["pyflakes>=2.5.0"]
 pylint = ["pylint>=2.5.0,<3"]
 rope = ["rope>1.2.0"]
-yapf = ["yapf", "whatthepatch>=1.0.2,<2.0.0"]
+yapf = ["yapf", "whatthepatch>=1.0.2"]
 websockets = ["websockets>=10.3"]
 test = [
     "pylint>=2.5.0,<3",
