# $FreeBSD: ports/devel/geany-plugin-doc/Makefile,v 1.2 2012/11/17 05:55:44 svnexp Exp $

PORTNAME=	geany-plugin
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	makc@FreeBSD.org
COMMENT=	Geany plugin: ${${GEANY_PLUGIN}_DESC}

GEANY_PLUGIN=	doc
GEANY_PLUGIN_DIR=	geanydoc

.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
