# Created by: Alexander Logvinov <ports@logvinov,com>
# $FreeBSD: databases/rubygem-activerecord-jdbc-adapter/Makefile 321611 2013-06-23 04:44:35Z swills $

PORTNAME=	activerecord-jdbc-adapter
PORTVERSION=	1.2.9
CATEGORIES=	databases rubygems java
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	JDBC adapter for ActiveRecord, for use within JRuby on Rails

RUN_DEPENDS=	jruby:${PORTSDIR}/lang/jruby

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
