# New ports collection makefile for:	p5-XML-RSSLite
# Date created:		2008-07-31
# Whom:			Tomoyuki Sakurai <cherry@trombik.org>
#
# $FreeBSD: ports/textproc/p5-XML-RSSLite/Makefile,v 1.5 2012/11/17 06:02:13 svnexp Exp $
#

PORTNAME=	XML-RSSLite
PORTVERSION=	0.15
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
EXTRACT_SUFX=	.tgz

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lightweight, relaxed RSS (and XML-ish) parser

PERL_CONFIGURE=	Yes
MAN3=	XML::RSSLite.3

.include <bsd.port.mk>
