# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: textproc/it-aspell/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-it-2.2_20050523-0
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Italian dictionary

DICT=	 	it

NO_STAGE=	yes
.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
