# $FreeBSD: x11-fonts/fslsfonts/Makefile 313933 2013-03-11 19:49:36Z zeising $

PORTNAME=	fslsfonts
PORTVERSION=	1.0.4
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	List fonts served by the X font server

XORG_CAT=	app
USE_XORG=	x11 libfs xorg-macros

PLIST_FILES=	bin/fslsfonts

MAN1=		fslsfonts.1

.include <bsd.port.mk>
