# Created by: Stanislav Sedov <ssedov@mbsd.msk.ru>
# $FreeBSD: graphics/edje_viewer/Makefile 318567 2013-05-20 03:05:29Z gblach $

PORTNAME=	edje_viewer
PORTVERSION=	20130520
CATEGORIES=	graphics enlightenment
MASTER_SITES=	LOCAL/gblach/e17/extra/

MAINTAINER=	gblach@FreeBSD.org
COMMENT=	A simple viewer for .edj files

DIST_SUBDIR=	e17
USE_BZIP2=	yes
GNU_CONFIGURE=	yes
USE_EFL=	evas ecore edje elementary
USE_EFL_ECORE=	file

.include <bsd.port.mk>
