# New ports collection makefile for:	gstreamer-plugins-amrwbdec
# Date created:			6 Sep 2010
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD: ports/audio/gstreamer-plugins-amrwbdec/Makefile,v 1.2 2012/11/17 05:54:33 svnexp Exp $
#

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer OpenCore based Adaptive Multi-Rate Wide-Band Decoder plugin

GST_PLUGIN=	amrwbdec

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
