# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: ports/devel/p5-Import-Into/Makefile,v 1.2 2012/11/17 05:56:19 svnexp Exp $

PORTNAME=	Import-Into
PORTVERSION=	1.001000
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MSTROUT
PKGNAMEPREFIX=	p5-

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Import packages into other packages

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		Import::Into.3

.include <bsd.port.mk>
