# $FreeBSD: math/hs-categories/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	categories
PORTVERSION=	1.0.5
PORTREVISION=	3
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Categories

LICENSE=	BSD

USE_CABAL=	void>=0.5.4.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
