# Created by: Douglas Thrift <douglas@douglasthrift.net>
# $FreeBSD: devel/py-fs/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	fs
PORTVERSION=	0.4.0
CATEGORIES=	devel python
MASTER_SITES=	GOOGLE_CODE
PROJECTHOST=	pyfilesystem
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	douglas@douglasthrift.net
COMMENT=	Python filesystem abstraction

LICENSE=	BSD

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
