# needs <filesystem>
BUILD_DEPENDS+= cxxfs_gcc8>0:misc/cxxfs_gcc8
CXXFLAGS+=      -isystem ${LOCALBASE}/cxxfs_gcc8
LDFLAGS+=       -L${LOCALBASE}/cxxfs_gcc8

# fails, just hardcode
dfly-patch:
	 ${REINPLACE_CMD} -e 's@\(defined(__FreeBSD__)\)@(\1 || defined(__DragonFly__))@g' \
		${WRKSRC}/libraries/libedit-20140620-3.1/src/chartype.h \
		${WRKSRC}/libraries/libffi/src/dlmalloc.c \
		${WRKSRC}/csl/fox/src/FXDir.cpp \
		${WRKSRC}/csl/fox/src/FXDate.cpp \
		${WRKSRC}/csl/fox/src/FXSystem.cpp
