# Created by: TAKAHASHI Kaoru <kaoru@kaisei.org>
# $FreeBSD: devel/p5-Test-Mock-LWP/Makefile 338880 2014-01-06 13:53:21Z az $

PORTNAME=	Test-Mock-LWP
PORTVERSION=	0.06
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kaoru@kaisei.org
COMMENT=	Easy mocking of LWP packages

RUN_DEPENDS=	p5-Test-MockObject>=1.08:${PORTSDIR}/devel/p5-Test-MockObject

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
