# Created by: chinsan <chinsan.tw@gmail.com>
# $FreeBSD: sysutils/p5-File-Next/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	File-Next
PORTVERSION=	1.12
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	File-finding iterator

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
