# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: textproc/p5-HTML-Entities-Numbered/Makefile 340610 2014-01-21 14:03:59Z mat $

PORTNAME=	HTML-Entities-Numbered
PORTVERSION=	0.04
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	HTML::Entities::Numbered - Conversion of numbered HTML entities

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
