# $FreeBSD: ports/devel/py-Jinja2-doc/Makefile,v 1.2 2012/11/17 05:56:44 svnexp Exp $

PKGNAMESUFFIX=	-doc

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Documentation of Jinja2 template engine

LICENSE=	BSD

DESCR=	${.CURDIR}/pkg-descr

MASTERDIR=	${.CURDIR}/../py-Jinja2

OPTIONS_DEFINE=
OPTIONS_DEFAULT=

PLIST=	${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
