# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: x11-themes/kde-icons-vista-inspirate/Makefile 327783 2013-09-20 23:54:03Z bapt $

PORTNAME=	vista-inspirate
PORTVERSION=	1.0
MASTER_SITES=	http://nuovext.pwsp.net/vista-inspirate/files/
DISTNAME=	Vista-Inspirate_${PORTVERSION}-kde

COMMENT=	KDE Vista Inspirate iconset

WRKSRC=		"${WRKDIR}/Vista-Inspirate_${PORTVERSION}"

NO_STAGE=	yes
.include "${.CURDIR}/../kde-icons-noia/Makefile.icons"
