# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: math/p5-Statistics-OLS/Makefile 341829 2014-01-30 10:27:43Z az $

PORTNAME=	Statistics-OLS
PORTVERSION=	0.07
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl module to perform ordinary least squares and other bivariate statistics

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
