# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: ports/devel/p5-BSD-stat/Makefile,v 1.11 2012/11/18 06:03:42 svnexp Exp $

PORTNAME=	BSD-stat
PORTVERSION=	1.34
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	A stat() with BSD 4.4 extensions

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		BSD::stat.3

.include <bsd.port.mk>
