
# zrj: add missing link against -lm in libvarnishapi.so
# NOTYPE  GLOBAL DEFAULT  UND {round, pow}  vs  FUNC    GLOBAL DEFAULT  UND round@DF306.0 (10)
# fixes www/varnish4 (binutils 2.27 ld.gold is unhappy)
dfly-patch:
	${REINPLACE_CMD} -e "/libvarnishapi_la_LIBADD/s/\(@PCRE_LIBS@ @RT_LIBS@\)/\1 @LIBM@/g"	\
		${WRKSRC}/lib/libvarnishapi/Makefile.am
