# Created by: Ashish SHUKLA <wahjava@gmail.com>
# $FreeBSD: devel/p5-MooseX-Object-Pluggable/Makefile 339893 2014-01-16 05:16:43Z ashish $

PORTNAME=	MooseX-Object-Pluggable
PORTVERSION=	0.0012
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Make your classes pluggable

BUILD_DEPENDS=	p5-Moose>=0.35:${PORTSDIR}/devel/p5-Moose
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
