# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: misc/pantry/Makefile 327745 2013-09-20 20:50:57Z bapt $

PORTNAME=	pantry
PORTVERSION=	32
CATEGORIES=	misc
MASTER_SITES=	http://www.smileystation.com/pantry/downloads/

MAINTAINER=	earl@eeg3.net
COMMENT=	Command-line nutrition analysis program

USE_BZIP2=	yes
GNU_CONFIGURE=	yes

MAN1=		pantry.1 pantryd.1

NO_STAGE=	yes
.include <bsd.port.mk>
