# New ports collection makefile for:	exim-postgresql
# Date created:				11 Jun 2001
# Whom:					Sheldon Hearn <sheldonh@FreeBSD.org>
#
# $FreeBSD: ports/mail/exim-postgresql/Makefile,v 1.4 2012/11/17 05:59:02 svnexp Exp $
#

PKGNAMESUFFIX=	-postgresql
MASTERDIR=	${.CURDIR}/../exim

WITH_PGSQL=	yes

.include "${MASTERDIR}/Makefile"
