# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: www/twiki-BugzillaLinkPlugin/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	BugzillaLinkPlugin
SVNREV=		15560
MASTER_SITES=	http://protey.ru/freebsd/distfiles/ \
		${MASTER_SITE_LOCAL:S!$!skv/!}

COMMENT=	Link to Bugzilla bugs using shorthand references

NO_STAGE=	yes
.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
