# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: www/twiki-BugzillaLinkPlugin/Makefile 316241 2013-04-22 15:37:34Z bdrewery $

PORTNAME=	BugzillaLinkPlugin
SVNREV=		15560
MASTER_SITES=	http://protey.ru/freebsd/distfiles/ \
		${MASTER_SITE_LOCAL:S!$!skv/!}

COMMENT=	Link to Bugzilla bugs using shorthand references

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
