# $FreeBSD: x11/xrdb/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xrdb
PORTVERSION=	1.1.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X server resource database utility

XORG_CAT=	app
USE_XORG=	xmuu x11

PLIST_FILES=	bin/xrdb man/man1/xrdb.1.gz

.include <bsd.port.mk>
