# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: audio/rubygem-librmpd/Makefile 329245 2013-10-03 22:35:12Z vg $

PORTNAME=	librmpd
PORTVERSION=	0.1.1
CATEGORIES=	audio rubygems
MASTER_SITES=	RG

MAINTAINER=	vg@FreeBSD.org
COMMENT=	Is a simple yet powerful Music Player Daemon library

USE_RUBY=	yes
NO_STAGE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
