# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: devel/php5-tokenizer/Makefile 332107 2013-10-30 13:32:02Z ale $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-tokenizer

.include "${MASTERDIR}/Makefile"
