# New ports collection makefile for:	p5-Kwalify
# Date created:				2008/10/23
# Whom:					Martin Wilke <miwi@FreeBSD.org>
#
# $FreeBSD: ports/textproc/p5-Kwalify/Makefile,v 1.5 2012/11/17 06:02:05 svnexp Exp $
#

PORTNAME=	Kwalify
PORTVERSION=	1.21
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:SREZIC
PKGNAMEPREFIX=	p5-

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Implementation of Kwalify parser, validator and data binding tool

MAN1=		pkwalify.1
MAN3=		Kwalify.3 Schema::Kwalify.3

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
