# New ports collection makefile for:	exim-ldap2
# Date created:				3 Jul 2001
# Whom:					Sheldon Hearn <sheldonh@FreeBSD.org>
#
# $FreeBSD: ports/mail/exim-ldap2/Makefile,v 1.4 2012/11/17 05:59:02 svnexp Exp $
#

PKGNAMESUFFIX=	-ldap2
MASTERDIR=	${.CURDIR}/../exim

WITH_OPENLDAP=		yes

.include "${MASTERDIR}/Makefile"
