# Created by: Sheldon Hearn <sheldonh@FreeBSD.org>
# $FreeBSD: mail/exim-ldap2/Makefile 340722 2014-01-22 17:00:46Z mat $

PKGNAMESUFFIX=	-ldap2
MASTERDIR=	${.CURDIR}/../exim

WITH_OPENLDAP=		yes

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
