# Created by: Shigeyuki FUKUSHIMA <shige@FreeBSD.org>
# $FreeBSD: graphics/xv-m17n/Makefile 340722 2014-01-22 17:00:46Z mat $

MAINTAINER=	dinoex@FreeBSD.org
COMMENT=	An X11 program that displays images of various formats with multilingualization

MASTERDIR=	${.CURDIR}/../xv

WITH_M17N=	yes

.include "${MASTERDIR}/Makefile"
