# New ports collection makefile for:	cursor-chameleon-skyblue
# Date created:		2009-11-14
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD: ports/x11-themes/cursor-chameleon-skyblue/Makefile,v 1.2 2012/11/17 06:03:30 svnexp Exp $
#

PORTNAME=	chameleon
PORTVERSION=	0.5
CATEGORIES=	x11-themes
MASTER_SITES=	http://www.egregorion.net/works/
PKGNAMEPREFIX=	cursor-
PKGNAMESUFFIX=	-skyblue
DISTNAME=	Chameleon-SkyBlue-${PORTVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	Chameleon Xcursors theme

THEME=		SkyBlue

.include "${.CURDIR}/../cursor-chameleon-white/files/Makefile.common"
.include <bsd.port.mk>
