# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11/libXdamage/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	libXdamage
PORTVERSION=	1.1.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Damage extension library

XORG_CAT=	lib
USE_XORG=	x11 damageproto:both xfixes fixesproto xextproto xproto:both

.include <bsd.port.mk>
