# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11/xf86driproto/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	xf86driproto
PORTVERSION=	2.1.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XFree86-DRI extension headers

LICENSE=	MIT

XORG_CAT=	proto

.include <bsd.port.mk>
