# Created by: Mathieu Arnold <m@absolight.net>
# $FreeBSD: misc/p5-Net-vCard/Makefile 332594 2013-11-03 08:05:18Z az $

PORTNAME=		Net-vCard
PORTVERSION=		0.5
CATEGORIES=		misc perl5
MASTER_SITES=		CPAN
PKGNAMEPREFIX=		p5-

MAINTAINER=		perl@FreeBSD.org
COMMENT=		Read and write vCard files (RFC 2426)

USES=			perl5
USE_PERL5=		configure

.include <bsd.port.mk>
