# $FreeBSD: ports/editors/libreoffice-sk/Makefile,v 1.3 2012/11/17 05:57:16 svnexp Exp $

LO_I18N=	sk	
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
