# Created by: Joao Carlos Mendes Luis <jonny@jonny.eng.br>
# $FreeBSD: portuguese/ispell-pt_BR/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	ispell
PORTVERSION=	2.4
CATEGORIES=	portuguese textproc
MASTER_SITES=	http://www.ime.usp.br/~ueda/br.ispell/
PKGNAMEPREFIX=	pt_BR-
DISTNAME=	br.ispell-2.4

MAINTAINER=	jonny@jonny.eng.br
COMMENT=	Ispell dictionary for Brazilian Portuguese

BUILD_DEPENDS=	buildhash:${PORTSDIR}/textproc/ispell

MAN1=		conjugue.1

NO_STAGE=	yes
.include <bsd.port.mk>
