# Created by: Khairil Yusof <kaeru@inigo-tech.com>
# $FreeBSD: devel/py-pytz/Makefile 314804 2013-03-21 05:01:03Z lwhsu $

PORTNAME=	pytz
PORTVERSION=	2013b
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	World Timezone Definitions for Python

USE_BZIP2=	yes
USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

PLIST_FILES=	%%PYTHON_SITELIBDIR%%/%%PYEASYINSTALL_EGG%%

.include <bsd.port.mk>
