# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-Class-Constant/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Class-Constant
PORTVERSION=	0.06
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ROBN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Build constant classes

USES=		perl5
USE_PERL5=	modbuild

MAN3=		Class::Constant.3

NO_STAGE=	yes
.include <bsd.port.mk>
