# $FreeBSD: ports/editors/calligra-l10n-en_GB/Makefile,v 1.40 2013/02/05 12:23:33 svnexp Exp $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
CATEGORIES=	editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	British messages and documentation for Calligra

CALLIGRA_L10N=	en_GB

.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
