# $FreeBSD: devel/hs-primitive/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	primitive
PORTVERSION=	0.5.0.1
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Primitive memory-related operations

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
