# New ports collection makefile for:    kde4-l10n-de
# Date created:                         29 July 2008
# Whom:                                 Martin Wilke <miwi@FreeBSD.org>
#
# $FreeBSD: ports/german/kde4-l10n/Makefile,v 1.58 2012/11/17 05:57:59 svnexp Exp $
#

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
CATEGORIES?=	german kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	German messages and documentation for KDE4

KDE4_L10N=	de

MANLANG=	${KDE4_L10N}
.include <${.CURDIR}/Makefile.man>

.include "${.CURDIR}/../../misc/kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
