# Created by: mat
# $FreeBSD: devel/p5-NEXT/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	NEXT
PORTVERSION=	0.65
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Provide a pseudo-class NEXT (et al) that allows method redispatch

USES=		perl5
USE_PERL5=	configure

MAN3=		NEXT.3

.include <bsd.port.mk>
