# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: graphics/R-cran-RColorBrewer/Makefile 333659 2013-11-13 08:19:34Z bf $

PORTNAME=	RColorBrewer
DISTVERSION=	1.0-5
PORTREVISION=	11
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	ColorBrewer palettes

LICENSE=	AL2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
