# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: ports/graphics/R-cran-RColorBrewer/Makefile,v 1.11 2013/01/04 18:45:34 svnexp Exp $

PORTNAME=	RColorBrewer
DISTVERSION=	1.0-5
PORTREVISION=	7
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	ColorBrewer palettes

LICENSE=	AL2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
