# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: security/p5-Text-Password-Pronounceable/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Text-Password-Pronounceable
PORTVERSION=	0.30
CATEGORIES=	security textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for generating pronounceable passwords

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
