# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: security/p5-Text-Password-Pronounceable/Makefile 332949 2013-11-06 07:39:31Z vanilla $

PORTNAME=	Text-Password-Pronounceable
PORTVERSION=	0.30
CATEGORIES=	security textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for generating pronounceable passwords

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
