# Created by: kris@FreeBSD.org
# $FreeBSD: security/fragrouter/Makefile 328578 2013-09-28 15:17:01Z ohauer $

PORTNAME=	fragrouter
PORTVERSION=	1.6
CATEGORIES=	security
MASTER_SITES=	http://monkey.org/~dugsong/ \
		LOCAL/ohauer

MAINTAINER=	ohauer@FreeBSD.org
COMMENT=	Tool for testing network IDS implementations

GNU_CONFIGURE=	yes

PLIST_FILES=	sbin/fragrouter \
		man/man8/fragrouter.8.gz

.include <bsd.port.mk>
