# Created by: Zach Thompson <hideo@lastamericanempire.com>
# $FreeBSD: finance/p5-Locale-Currency-Format/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Locale-Currency-Format
PORTVERSION=	1.30
CATEGORIES=	finance perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl functions for formatting monetary values

USES=		perl5
USE_PERL5=	configure

LICENSE_COMB=	dual
LICENSE=	ART20 GPLv1

MAN3=		Locale::Currency::Format.3

.include <bsd.port.mk>
