# New ports collection makefile for:	PostgreSQL PL/Tcl
# Date created:		January 14, 2002
# Whom:			Palle Girgensohn <girgen@partitur.se>
#
# $FreeBSD: ports/databases/postgresql83-pltcl/Makefile,v 1.2 2012/11/17 05:55:20 svnexp Exp $
#

WANT_PGSQL_VER?=83

.include "${.CURDIR}/../postgresql91-pltcl/Makefile"
