# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: net/p5-Net-Interface/Makefile 327755 2013-09-20 22:10:23Z bapt $

PORTNAME=	Net-Interface
PORTVERSION=	1.012
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension to access network interfaces

USES=		perl5
USE_PERL5=	configure

MAN3=		Net::Interface.3 Net::Interface::Developer.3 \
  			Net::Interface::NetSymbols.3

NO_STAGE=	yes
.include <bsd.port.mk>
