# Created by: joerg
# $FreeBSD: editors/uzap/Makefile 327720 2013-09-20 16:36:23Z bapt $

PORTNAME=	uzap
PORTVERSION=	1.0
CATEGORIES=	editors
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	joerg
DISTNAME=	${PORTNAME}

MAINTAINER=	joerg@FreeBSD.org
COMMENT=	Visual binary file editor

# Has been posted to alt.sources in 1989
# http://www.megalextoria.com/usenet-archive/news097f1/b120/alt/sources/00000521.html
NO_CDROM=	This software may not be used to make a profit in any way.
NO_WRKSUBDIR=	yes
MAN1=		uzap.1
PLIST_FILES=	bin/uzap

NO_STAGE=	yes
.include <bsd.port.mk>
