# Created by: chinsan
# $FreeBSD: devel/p5-Getopt-Euclid/Makefile 323454 2013-07-22 14:30:05Z culot $

PORTNAME=	Getopt-Euclid
PORTVERSION=	0.4.3
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Executable Uniform Command-Line Interface Descriptions

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_MODBUILD=	yes

MAN3=		Getopt::Euclid.3

.include <bsd.port.mk>
