# Created by: Tim Bishop <tdb@FreeBSD.org>
# $FreeBSD: devel/rubygem-piston/Makefile 340902 2014-01-24 14:47:11Z miwi $

PORTNAME=	piston
PORTVERSION=	1.4.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	tdb@FreeBSD.org
COMMENT=	Utility to manage local copies of Subversion repositories

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/piston

.include <bsd.port.mk>
