# Created by: Philippe Audeoud <jadawin@tuxaco.net>
# $FreeBSD: net/p5-Net-Proxy/Makefile 337794 2013-12-27 19:47:35Z jadawin $

PORTNAME=	Net-Proxy
PORTVERSION=	0.12
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Net
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Framework for proxying network connections in many ways

USES=		perl5
USE_PERL5=	configure

MAN1=	connect-tunnel.1 \
	sslh.1

.include <bsd.port.mk>
