# New ports collection makefile for:	php53-gettext
# Date created:			12 Apr 2012
# Whom:				Florian Smeets <flo@FreeBSD.org>
#
# $FreeBSD: ports/devel/php53-gettext/Makefile,v 1.4 2012/11/17 05:56:41 svnexp Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php53

PKGNAMESUFFIX=	-gettext

.include "${MASTERDIR}/Makefile"
