# Created by: Joe Horn <joehorn@gmail.com>
# $FreeBSD: net/p5-Geo-IP-PurePerl/Makefile 332868 2013-11-05 16:42:55Z vanilla $

PORTNAME=	Geo-IP-PurePerl
PORTVERSION=	1.25
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Look up country by IP Address

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
