# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: graphics/R-cran-shape/Makefile 339220 2014-01-09 12:58:46Z tota $

PORTNAME=	shape
PORTVERSION=	1.4.1
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Functions for plotting graphical shapes, colors

LICENSE=	GPLv3

USES=	cran:auto-plist

.include <bsd.port.mk>
