# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: devel/p5-Test-LeakTrace/Makefile 325163 2013-08-21 17:42:57Z sunpoet $

PORTNAME=	Test-LeakTrace
PORTVERSION=	0.14
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Traces memory leaks

USE_PERL5=	configure
USES=		perl5

MAN3=		Test::LeakTrace.3 \
		Test::LeakTrace::JA.3 \
		Test::LeakTrace::Script.3

.include <bsd.port.mk>
