# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: devel/p5-Heap-Simple/Makefile 331958 2013-10-29 15:08:11Z vanilla $

PORTNAME=	Heap-Simple
PORTVERSION=	0.13
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Fast and easy to use classic heaps

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
