# Created by: Jeremy Shaffner <jeremy@external.org>
# $FreeBSD: textproc/p5-dTemplate/Makefile 315509 2013-03-29 00:44:53Z eadler $

PORTNAME=	dTemplate
PORTVERSION=	2.5
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Powerful template handling logic with advanced features

PERL_CONFIGURE=	yes

MAN3=		dTemplate.3

.include <bsd.port.mk>
