# Created by: ijliao
# $FreeBSD: devel/p5-Exporter-Tidy/Makefile 315509 2013-03-29 00:44:53Z eadler $

PORTNAME=	Exporter-Tidy
PORTVERSION=	0.07
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Another way of exporting symbols

PERL_CONFIGURE=	yes

MAN3=	Exporter::Tidy.3

.include <bsd.port.mk>
