# Created by: Rong-En Fan <rafan@infor.org>
# $FreeBSD: devel/p5-PerlIO-eol/Makefile 326784 2013-09-09 08:21:32Z az $

PORTNAME=	PerlIO-eol
PORTVERSION=	0.14
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	rafan@FreeBSD.org
COMMENT=	PerlIO layer for normalizing line endings

USES=		perl5
USE_PERL5=	configure

MAN3=		PerlIO::eol.3

.include <bsd.port.mk>
