# Created by: Rong-En Fan <rafan@infor.org>
# $FreeBSD: devel/p5-PerlIO-eol/Makefile 338916 2014-01-06 18:07:56Z az $

PORTNAME=	PerlIO-eol
PORTVERSION=	0.14
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	rafan@FreeBSD.org
COMMENT=	PerlIO layer for normalizing line endings

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
