# Created by: clutton mbsd@isgroup.com.ua
# $FreeBSD: www/xpi-pentadactyl/Makefile 324387 2013-08-08 11:05:02Z bdrewery $

PORTNAME=	pentadactyl
PORTVERSION=	20130808
CATEGORIES=	www
MASTER_SITES=	GOOGLE_CODE
PROJECTHOST=	dactyl

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Firefox for Vim and Links addicts

XPI_NUM=	235854
XPI_ID=		pentadactyl@dactyl.googlecode.com

.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
