# $FreeBSD: devel/rubygem-stomp/Makefile 322057 2013-06-29 21:28:12Z swills $

PORTNAME=	stomp
PORTVERSION=	1.2.9
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Streaming Text Orientated Messaging Protocol gem

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=		bin/catstomp bin/stompcat

.include <bsd.port.mk>
