# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: misc/rubygem-vpim/Makefile 321509 2013-06-21 23:51:42Z swills $

PORTNAME=	vpim
PORTVERSION=	0.695
CATEGORIES=	misc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	pure-ruby library for decoding and encoding vCard and iCalendar data

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES+=	bin/reminder bin/rrule

.include <bsd.port.mk>
