# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: misc/rubygem-vpim/Makefile 340638 2014-01-21 19:13:02Z swills $

PORTNAME=	vpim
PORTVERSION=	13.11.11
CATEGORIES=	misc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	pure-ruby library for decoding and encoding vCard and iCalendar data

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES+=	bin/reminder bin/rrule

.include <bsd.port.mk>
