# Created by: Frederic Culot <culot@FreeBSD.org>
# $FreeBSD: devel/p5-Test-Weaken/Makefile 326728 2013-09-08 13:59:48Z az $

PORTNAME=	Test-Weaken
PORTVERSION=	3.022000
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Test that freed memory objects were, indeed, freed

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		Test::Weaken.3

.include <bsd.port.mk>
