# Created by: dliakh
# $FreeBSD: mail/p5-Email-AddressParser/Makefile 327742 2013-09-20 19:59:12Z bapt $

PORTNAME=	Email-AddressParser
PORTVERSION=	0.04
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	dliakh@ukr.net
COMMENT=	RFC 2822 Address Parsing and Creation

USES=		perl5
USE_PERL5=	configure

MAN3=	Email::AddressParser.3

NO_STAGE=	yes
.include <bsd.port.mk>
