# Ports collection Makefile for:	p5-Digest-Elf
# Date created:				17 Dec 2005
# Whom:					Gabor Kovesdan
# $FreeBSD: ports/security/p5-Digest-Elf/Makefile,v 1.9 2012/11/17 06:01:12 svnexp Exp $

PORTNAME=	Digest-Elf
PORTVERSION=	1.4
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension for ElfHash hash algorithm

PERL_CONFIGURE=	yes

MAN3=	Digest::Elf.3

.include <bsd.port.mk>
