# Created by: Gabor Kovesdan
# $FreeBSD: security/p5-Digest-Elf/Makefile 341825 2014-01-30 09:42:48Z az $

PORTNAME=	Digest-Elf
PORTVERSION=	1.4
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension for ElfHash hash algorithm

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
