# $FreeBSD: devel/hs-vector/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	vector
PORTVERSION=	0.10.0.1
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient Arrays

LICENSE=	BSD

USE_CABAL=	primitive>=0.5

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
