# $FreeBSD: devel/pear-Horde_Cli/Makefile 323135 2013-07-16 23:00:57Z mm $

PORTNAME=	Horde_Cli
PORTVERSION=	2.0.4
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Command Line Interface API

USE_HORDE_RUN=	Horde_Support Horde_Translation

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
