# Ports collection makefile for:  pear-Horde_Cli
# Date created:			  6 July 2011
# Whom:				  Martin Matuska <mm@FreeBSD.org>
#
# $FreeBSD: ports/devel/pear-Horde_Cli/Makefile,v 1.8 2013/02/12 17:38:59 svnexp Exp $

PORTNAME=	Horde_Cli
PORTVERSION=	2.0.3
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Command Line Interface API

USE_HORDE_RUN=	Horde_Support Horde_Translation

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
