# Created by: mat
# $FreeBSD: www/p5-Template-Alloy/Makefile 329224 2013-10-03 18:38:13Z sunpoet $

PORTNAME=	Template-Alloy
PORTVERSION=	1.020
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:RHANDOM
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Mixing of all of the major template systems

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
