# Created by: David Sze <dsze@alumni.uwaterloo.ca>
# $FreeBSD: textproc/rl/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	rl
PORTVERSION=	0.2.7
CATEGORIES=	textproc
MASTER_SITES=	http://arthurdejong.org/rl/

MAINTAINER=	jharris@widomaker.com
COMMENT=	Randomizes lines from a specified input file

GNU_CONFIGURE=	yes

MAN1=		rl.1
PLIST_FILES=	bin/rl

NO_STAGE=	yes
.include <bsd.port.mk>
