# Created by: Tsung-Han Yeh <snowfly@yuntech.edu.tw>
# $FreeBSD: security/p5-Cisco-Hash/Makefile 341821 2014-01-30 09:08:26Z az $

PORTNAME=	Cisco-Hash
PORTVERSION=	0.02
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	snowfly@yuntech.edu.tw
COMMENT=	De- and encrypts Cisco type 7 hashes

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
