# New ports collection makefile for:	xf86-video-i740
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-i740/Makefile,v 1.14 2012/11/17 06:03:25 svnexp Exp $
#

PORTNAME=	xf86-video-i740
PORTVERSION=	1.3.2
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org i740 display driver

XORG_CAT=	driver
USE_XORG=	videoproto xextproto
MAN4=		i740.4x

.include <bsd.port.mk>
