# $FreeBSD: x11-drivers/xf86-video-i740/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xf86-video-i740
PORTVERSION=	1.3.4
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org i740 display driver

XORG_CAT=	driver

.include <bsd.port.mk>
