# Created by: christian
# $FreeBSD: devel/p5-Text-LevenshteinXS/Makefile 341710 2014-01-29 10:33:57Z az $

PORTNAME=      Text-LevenshteinXS
PORTVERSION=   0.03
CATEGORIES=    devel perl5
MASTER_SITES=  CPAN
PKGNAMEPREFIX=  p5-

MAINTAINER=    christian@karg.org
COMMENT=       Text::LevenshteinXS - CPAN Levenshtein edit distance

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
