# $FreeBSD: devel/hs-vector-algorithms/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	vector-algorithms
PORTVERSION=	0.5.4.2
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient algorithms for vector arrays

LICENSE=	BSD

USE_CABAL=	primitive>=0.3 vector>=0.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
