# $FreeBSD: german/calligra-l10n/Makefile 327732 2013-09-20 18:30:00Z bapt $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
CATEGORIES=	german editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	German messages and documentation for Calligra

CALLIGRA_L10N=	de

NO_STAGE=	yes
.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
