# $FreeBSD: devel/R-cran-glmnet/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	glmnet
DISTVERSION=	1.8-5
PORTREVISION=	2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Lasso and elastic-net regularized generalized linear models

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
