# New ports collection makefile for:	textproc/p5- Text-Reflow
# Date created:				2 August 2002
# Whom:					Mathieu Arnold <m@absolight.net>
#
# $FreeBSD: ports/textproc/p5-Text-Reflow/Makefile,v 1.14 2012/11/17 06:02:10 svnexp Exp $
#

PORTNAME=	Text-Reflow
PORTVERSION=	1.09
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for reflowing text files

PERL_CONFIGURE=	yes

MAN3=		Text::Reflow.3

EXTRA_PATCHES=	${PATCHDIR}/5.8-Reflow.pm

.include <bsd.port.mk>
