# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: devel/p5-Term-UI/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Term-UI
PORTVERSION=	0.36
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Term::ReadLine UI made easy

USES=		perl5
USE_PERL5=	configure

MAN3=		Term::UI.3 Term::UI::History.3

.include <bsd.port.mk>
