# Created by: Lapo Luchini <lapo@lapo.it>
# $FreeBSD: www/xpi-firebug/Makefile 326845 2013-09-09 22:10:47Z bar $

PORTNAME=	firebug
PORTVERSION=	1.12.1
DISTVERSIONSUFFIX=	-fx
PORTEPOCH=	3
CATEGORIES=	www

MAINTAINER=	bar@FreeBSD.org
COMMENT=	Lets you edit, debug, and monitor CSS, HTML, and JS

LICENSE=	BSD

XPI_NUM=	1843
XPI_ID=		firebug@software.joehewitt.com

.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
