# $FreeBSD: net/tftpgrab/Makefile 328226 2013-09-25 00:54:08Z bdrewery $

PORTNAME=	tftpgrab
PORTVERSION=	0.2
CATEGORIES=	net
MASTER_SITES=	http://pseudo-flaw.net/tftpgrab/ \
		http://www.atarininja.org/~wxs/distfiles/

MAINTAINER=	wxs@FreeBSD.org
COMMENT=	TFTP stream extractor

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/tftpgrab

.include <bsd.port.mk>
