# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: textproc/py-texttable/Makefile 340987 2014-01-25 05:39:09Z miwi $

PORTNAME=	texttable
PORTVERSION=	0.8.1
CATEGORIES=	textproc python
MASTER_SITES=	http://foutaise.org/code/texttable/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Module for creating simple ASCII tables

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

PLIST_FILES=	%%PYTHON_SITELIBDIR%%/texttable.py \
		%%PYTHON_SITELIBDIR%%/texttable.pyc \
		%%PYTHON_SITELIBDIR%%/texttable.pyo

.include <bsd.port.mk>
