# Created by: Pawel Worach
# $FreeBSD: x11-fonts/font-misc-cyrillic/Makefile 327781 2013-09-20 23:51:14Z bapt $

PORTNAME=	font-misc-cyrillic
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org miscellaneous Cyrillic font

XORG_CAT=	font

NO_STAGE=	yes
.include <bsd.port.mk>
