# New ports collection makefile for:	String-RexxParse
# Date created:				Mon Jan  1 11:16:32 2001
# Whom:					will
#
# $FreeBSD: ports/devel/p5-String-RexxParse/Makefile,v 1.8 2012/11/17 05:56:30 svnexp Exp $
#

PORTNAME=	String-RexxParse
PORTVERSION=	1.08
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module that provides an interface to REXX parsing routines

PERL_CONFIGURE=	yes

MAN3=		String::RexxParse.3

.include <bsd.port.mk>
