# Created by: Alexander <alexander.4mail@gmail.com>
# $FreeBSD: ports/misc/fbless/Makefile,v 1.2 2013/02/19 19:10:30 svnexp Exp $

PORTNAME=	fbless
PORTVERSION=	0.2.2
PORTREVISION=	1
CATEGORIES=	misc textproc python

MAINTAINER=	alexander.4mail@gmail.com
COMMENT=	Text-mode fb2 books reader

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
USE_GITHUB=	yes
GH_ACCOUNT=	matimatik
GH_COMMIT=	b6259ab

.include <bsd.port.mk>
