# New ports collection makefile for:	Math-Bezier
# Date created:				Wed Jan  3 10:40:02 2001
# Whom:					will
#
# $FreeBSD: ports/math/p5-Math-Bezier/Makefile,v 1.8 2012/11/17 05:59:25 svnexp Exp $
#

PORTNAME=	Math-Bezier
PORTVERSION=	0.01
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module to solve Bezier curves

PERL_CONFIGURE=	yes

MAN3=		Math::Bezier.3

.include <bsd.port.mk>
