# $FreeBSD: devel/hs-blaze-builder/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	blaze-builder
PORTVERSION=	0.3.1.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient buffered output

LICENSE=	BSD

USE_CABAL=	text>=0.10

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
