# Created by: will
# $FreeBSD: devel/p5-Alias/Makefile 331766 2013-10-27 12:17:59Z vanilla $

PORTNAME=	Alias
PORTVERSION=	2.32
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A perl module that performs aliasing services

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
