# Created by: Gvozdikov Veniamin <g.veniamin@googlemail.com>
# $FreeBSD: devel/rubygem-sumbur/Makefile 319336 2013-05-29 00:44:15Z miwi $

PORTNAME=	sumbur
PORTVERSION=	0.1.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	Consistent spreading for server balancing

RUBY_VER=	1.9
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
