# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: devel/rubygem-sumbur/Makefile 340903 2014-01-24 14:49:29Z miwi $

PORTNAME=	sumbur
PORTVERSION=	0.1.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	vg@FreeBSD.org
COMMENT=	Consistent spreading for server balancing

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
