# $FreeBSD: editors/se/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	se
PORTVERSION=	3.0.1
CATEGORIES=	editors
MASTER_SITES=	http://se-editor.org/dist/

MAINTAINER=	danilo@FreeBSD.org
COMMENT=	Screen oriented version of the classic UNIX text editor ed

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
