# $FreeBSD: editors/se/Makefile 328690 2013-09-29 13:44:12Z danilo $

PORTNAME=	se
PORTVERSION=	3.0.1
CATEGORIES=	editors
MASTER_SITES=	http://se-editor.org/dist/

MAINTAINER=	danilo@FreeBSD.org
COMMENT=	Screen oriented version of the classic UNIX text editor ed

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
