# New ports collection makefile for:	exim-mysql
# Date created:				11 Jun 2001
# Whom:					Sheldon Hearn <sheldonh@FreeBSD.org>
#
# $FreeBSD: ports/mail/exim-mysql/Makefile,v 1.4 2012/11/17 05:59:02 svnexp Exp $
#

PKGNAMESUFFIX=	-mysql
MASTERDIR=	${.CURDIR}/../exim

WITH_MYSQL=	yes

.include "${MASTERDIR}/Makefile"
