# New ports collection makefile for:	bsdcrashtar
# Date created:				18 October 2009
# Whom:					Mikolaj Golub <to.my.trociny@gmail.com>
#
# $FreeBSD: sysutils/bsdcrashtar/Makefile 327341 2013-09-15 13:42:07Z trociny $
#

PORTNAME=	bsdcrashtar
PORTVERSION=	0.1.3
CATEGORIES=	sysutils
MASTER_SITES=	GOOGLE_CODE

MAINTAINER=	trociny@FreeBSD.org
COMMENT=	Archive FreeBSD kernel crash files

PLIST_FILES=	sbin/bsdcrashtar
MAN8=		bsdcrashtar.8
MANCOMPRESSED=	yes

MAKE_ENV+=	NO_OBJ=yes

.include <bsd.port.mk>
