# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: security/php55-hash/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-hash

.include "${MASTERDIR}/Makefile"
