# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: security/php55-hash/Makefile 332107 2013-10-30 13:32:02Z ale $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-hash

.include "${MASTERDIR}/Makefile"
