# Created by: Oleg Ukraincev <oleg@ht-systems.ru>
# $FreeBSD: textproc/py-stripogram/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	stripogram
PORTVERSION=	1.4
CATEGORIES=	textproc python
MASTER_SITES=	SF/squishdot/strip-o-gram/${PORTVERSION}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	stripogram-1-4
EXTRACT_SUFX=	.tgz

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Converting HTML to Plain Text and stripping specified tags from HTML

WRKSRC=		${WRKDIR}/stripogram

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
