# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: devel/p5-Getargs-Long/Makefile 331953 2013-10-29 14:32:08Z vanilla $

PORTNAME=	Getargs-Long
PORTVERSION=	1.1003
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Parse routine arguments

BUILD_DEPENDS=	p5-Log-Agent>=0.105:${PORTSDIR}/devel/p5-Log-Agent \
		p5-Module-Install>=0:${PORTSDIR}/devel/p5-Module-Install
RUN_DEPENDS=	p5-Log-Agent>=0.105:${PORTSDIR}/devel/p5-Log-Agent

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
