# Created by: ijliao
# $FreeBSD: devel/p5-Hash-AsObject/Makefile 331958 2013-10-29 15:08:11Z vanilla $

PORTNAME=	Hash-AsObject
PORTVERSION=	0.13
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Hashes with accessors/mutators

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
