# Created by: ijliao
# $FreeBSD: devel/p5-Hash-AsObject/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Hash-AsObject
PORTVERSION=	0.13
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Hashes with accessors/mutators

USES=		perl5
USE_PERL5=	configure

MAN3=		Hash::AsObject.3

NO_STAGE=	yes
.include <bsd.port.mk>
