# $FreeBSD: security/php53-openssl/Makefile 332429 2013-11-01 23:49:56Z flo $

PORTREVISION=	1

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php53

PKGNAMESUFFIX=	-openssl

.include "${MASTERDIR}/Makefile"
