# New ports collection makefile for:	php53-openssl
# Date created:			12 Apr 2012
# Whom:				Florian Smeets <flo@FreeBSD.org>
#
# $FreeBSD: security/php53-openssl/Makefile 325434 2013-08-27 10:33:45Z garga $
#

PORTREVISION=	1

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php53

PKGNAMESUFFIX=	-openssl

.include "${MASTERDIR}/Makefile"
