# Created by: Lars Thegler <lars@thegler.dk>
# $FreeBSD: devel/p5-Date-Easter/Makefile 338856 2014-01-06 11:00:15Z az $

PORTNAME=	Date-Easter
PORTVERSION=	1.14
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Calculates Easter for any given year

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
