# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: graphics/p5-Image-Size/Makefile 326958 2013-09-11 09:54:08Z az $

PORTNAME=	Image-Size
PORTVERSION=	3.232
CATEGORIES=	graphics www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tolid@tolid.eu.org
COMMENT=	Perl5 module to determine the size of images in several common formats

USES=		perl5
USE_PERL5=	configure

MAN1=		imgsize.1
MAN3=		Image::Size.3

.include <bsd.port.mk>
