# Created by: Yoshisato YANAGISAWA
# $FreeBSD: security/p5-Crypt-Camellia_PP/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	Crypt-Camellia_PP
PORTVERSION=	0.02
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	yanagisawa@csg.is.titech.ac.jp
COMMENT=	Perl extension for Camellia Encryption Algorithm in pure Perl

USES=		perl5
USE_PERL5=	configure

MAN3=		Crypt::Camellia_PP.3

NO_STAGE=	yes
.include <bsd.port.mk>
