# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: ports/devel/hs-ghc-mtl/Makefile,v 1.12 2013/02/05 22:47:09 svnexp Exp $

PORTNAME=	ghc-mtl
PORTVERSION=	1.0.1.2
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	An mtl compatible version of the Ghc-Api monads and\
		monad-transformers

LICENSE=	BSD

USE_CABAL=	MonadCatchIO-mtl>=0.2.0.0 mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
