# New ports collection Makefile for:	p5-Crypt-Chimera
# Date created:				20 Dec 2006
# Whom:	      				Gabor Kovesdan
# $FreeBSD: ports/security/p5-Crypt-Chimera/Makefile,v 1.7 2012/11/17 06:01:10 svnexp Exp $

PORTNAME=	Crypt-Chimera
PORTVERSION=	1.01
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl extension for Chimera key exchange protocol

PERL_CONFIGURE=	yes

MAN3=		Crypt::Chimera.3

.include <bsd.port.mk>
