# Created by: Andrew Stevenson <andrew@ugh.net.au>
# $FreeBSD: mail/poppwd/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	poppwd
PORTVERSION=	2.0
CATEGORIES=	mail
MASTER_SITES=	ftp://ftp.ugh.net.au/pub/unix/poppwd/	\
		http://www.ugh.eclipse.co.uk/mirror/ftp.ugh.net.au/pub/unix/poppwd/

MAINTAINER=	andrew@ugh.net.au
COMMENT=	Implementation of the Eudora password changing protocol

WRKSRC=		${WRKDIR}/poppwd

MAN8=		poppwd.8
MANCOMPRESSED=	maybe
PLIST_FILES=	libexec/poppwd

NO_STAGE=	yes
.include <bsd.port.mk>
