# $FreeBSD: devel/pear-channel-phing/Makefile 333263 2013-11-08 21:41:53Z antoine $

PORTNAME=	phing
PORTVERSION=	20120813
CATEGORIES=	devel www pear

MAINTAINER=	mm@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.phing.info

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
