# Created by: Shen Chuan-Hsing <statue@freebsd.sinica.edu.tw>
# $FreeBSD: chinese/unzip/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	chinese

MAINTAINER=	ports@FreeBSD.org

CONFLICTS=	unzip-[0-9]* unzip-iconv-[0-9]* ko-unzip-[0-9]* ru-unzip-[0-9]*

MASTERDIR=	${.CURDIR}/../../archivers/unzip

EXTRA_PATCHES=	${.CURDIR}/files/patch-fileio.c

.include "${MASTERDIR}/Makefile"
