# Created by: Dennis Herrmann <adox@mcx2.org>
# $FreeBSD: www/multisort/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	multisort
PORTVERSION=	1.1
CATEGORIES=	www
MASTER_SITES=	http://www.xach.com/multisort/ \
		http://mirror.mcx2.org/

MAINTAINER=	dhn@FreeBSD.org
COMMENT=	A small program to take multiple httpd logfiles into one

PLIST_FILES=	bin/multisort

NO_STAGE=	yes
.include <bsd.port.mk>
