# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: net/p5-Net-NIS/Makefile 327755 2013-09-20 22:10:23Z bapt $

PORTNAME=	Net-NIS
PORTVERSION=	0.43
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Interface to Sun's Network Information Service

USES=		perl5
USE_PERL5=	configure

MAN3=		Net::NIS.3 Net::NISTable.3

NO_STAGE=	yes
.include <bsd.port.mk>
