# Created by: rpsfa@rit.edu
# $FreeBSD: devel/rubygem-yui-compressor/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	yui-compressor
PORTVERSION=	0.10.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A YUI Compressor for minifying JavaScript and CSS assets

RUN_DEPENDS=	rubygem-popen4>=0.1.4:${PORTSDIR}/devel/rubygem-popen4

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
