# Ports collection makefile for:	rubygem-yui-compressor
# Date created:				2011-06-16
# Whom:					rpsfa@rit.edu
#
# $FreeBSD: ports/devel/rubygem-yui-compressor/Makefile,v 1.4 2012/11/17 05:57:01 svnexp Exp $

PORTNAME=	yui-compressor
PORTVERSION=	0.9.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A YUI Compressor for minifying JavaScript and CSS assets

RUN_DEPENDS=	rubygem-popen4>=0.1.4:${PORTSDIR}/devel/rubygem-popen4

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
