# Created by: Kaspars Bankovskis <kaspars@bankovskis.lv>
# $FreeBSD: textproc/hs-csv/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	csv
PORTVERSION=	0.1.2
PORTREVISION=	7
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	CSV library for Haskell

LICENSE=	MIT

USE_CABAL=	parsec

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
