# Created by: Kaspars Bankovskis <kaspars@bankovskis.lv>
# $FreeBSD: textproc/hs-csv/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	csv
PORTVERSION=	0.1.2
PORTREVISION=	8
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	CSV library for Haskell

LICENSE=	MIT

USE_CABAL=	parsec

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
