# Created by: Kaspars Bankovskis <kaspars@bankovskis.lv>
# $FreeBSD: textproc/hs-csv/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	csv
PORTVERSION=	0.1.2
PORTREVISION=	9
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	CSV library for Haskell

LICENSE=	MIT

USE_CABAL=	parsec

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
