# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: multimedia/gstreamer-plugins-x264/Makefile 332416 2013-11-01 22:14:07Z kwm $
#   $MCom: ports/multimedia/gstreamer-plugins-x264/Makefile,v 1.3 2008/03/19 14:05:37 ahze Exp $

PORTREVISION=	2
CATEGORIES=	multimedia

COMMENT=	Gstreamer x264 plugin

GST_PLUGIN=	x264

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
