# $FreeBSD: head/devel/p5-Term-ReadPassword/Makefile 341710 2014-01-29 10:33:57Z az $

PORTNAME=	Term-ReadPassword
PORTVERSION=	0.11
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl module for asking the user for a password

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
