# Created by: andrew@scoop.co.nz
# $FreeBSD: ports/devel/p5-Algorithm-Numerical-Shuffle/Makefile,v 1.4 2012/11/17 05:56:04 svnexp Exp $

PORTNAME=	Algorithm-Numerical-Shuffle
PORTVERSION=	1.4
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=       Shuffle-${PORTVERSION}
EXTRACT_SUFX=   .tgz

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Shuffle a list

PERL_CONFIGURE=	yes

MAN3=		Algorithm::Numerical::Shuffle.3

.include <bsd.port.mk>
