# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: devel/pear-Validate_US/Makefile 314361 2013-03-16 15:21:58Z wen $

PORTNAME=	Validate_US
PORTVERSION=	0.5.5
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR data validation class for US

BUILD_DEPENDS=	pear-Validate>=0.5.0:${PORTSDIR}/devel/pear-Validate
RUN_DEPENDS=	pear-Validate>=0.5.0:${PORTSDIR}/devel/pear-Validate

PEAR_AUTOINSTALL=	yes

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.mk"
.include <bsd.port.post.mk>
