# Created by: Stanislav Sedov <stas@FreeBSD.org>
# $FreeBSD: x11/emprint/Makefile 329516 2013-10-05 22:07:06Z gblach $

PORTNAME=	emprint
PORTVERSION=	20130520
CATEGORIES=	x11 enlightenment
MASTER_SITES=	LOCAL/gblach/e17/extra/

MAINTAINER=	gblach@FreeBSD.org
COMMENT=	Utility for taking screenshots for E17

DIST_SUBDIR=	e17
USE_BZIP2=	yes
GNU_CONFIGURE=	yes
USES=		pkgconfig
USE_EFL=	eina evas ecore
USE_EFL_ECORE=	evas file input x11

.include <bsd.port.mk>
