
# zrj: we allow to fully override almost all base compiler headers
dfly-patch:
	${MV} ${WRKSRC}/limits.h ${WRKSRC}/msort_limits.h
	${REINPLACE_CMD} -e 's@limits.h@msort_limits.h@g'	\
		${WRKSRC}/Makefile.am	\
		${WRKSRC}/Makefile.in
	${REINPLACE_CMD} -e 's@"limits.h"@"msort_limits.h"@g'	\
		${WRKSRC}/info.c	\
		${WRKSRC}/input.c	\
		${WRKSRC}/msort.c	# prevent shadowing in gmp.h
