# Ports collection makefile for:	rubygem-unicode
# Date created:				Sat 31 Jul 2010
# Whom:					Alexey V. Degtyarev <alexey@renatasystems.org>
#
# $FreeBSD: ports/devel/rubygem-unicode/Makefile,v 1.6 2012/11/17 05:57:01 svnexp Exp $

PORTNAME=	unicode
PORTVERSION=	0.4.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	alexey@renatasystems.org
COMMENT=	Unicode string manipulation library for Ruby

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
