# Created by: Gabor Kovesdan
# $FreeBSD: security/p5-Digest-MD5-File/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	Digest-MD5-File
PORTVERSION=	0.08
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension for getting MD5 sums for files and urls

RUN_DEPENDS=	p5-libwww>=0:${PORTSDIR}/www/p5-libwww

USES=		perl5
USE_PERL5=	configure

MAN3=	Digest::MD5::File.3

NO_STAGE=	yes
.include <bsd.port.mk>
