# $FreeBSD: ports/devel/hs-stm/Makefile,v 1.8 2013/02/05 22:47:09 svnexp Exp $

PORTNAME=	stm
PORTVERSION=	2.4
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Software Transactional Memory

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
