# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: math/hs-erf/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	erf
PORTVERSION=	2.0.0.0
PORTREVISION=	8
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	The error function, erf, and friends for Haskell

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
