# $FreeBSD: archivers/hs-tar/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	tar
PORTVERSION=	0.4.0.1
PORTREVISION=	4
CATEGORIES=	archivers haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Reading, writing, and manipulating ".tar" archive files

LICENSE=	BSD


.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
