# New ports collection makefile for:	p5-Set-Partition
# Date created:				05 Jun 2006
# Whom:					Aaron Dalton <aaron@FreeBSD.org>
#
# $FreeBSD: ports/math/p5-Set-Partition/Makefile,v 1.6 2012/11/17 05:59:27 svnexp Exp $
#

PORTNAME=	Set-Partition
PORTVERSION=	0.03
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Enumerate all arrangements of a set in fixed subsets

MAN3=	Set::Partition.3

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
