# $FreeBSD: textproc/stardict-BritannicaConcise/Makefile 333307 2013-11-09 16:00:36Z makc $

PORTNAME=	stardict-BritannicaConcise
PORTVERSION=	2.4.2
CATEGORIES=	textproc
MASTER_SITES=	http://abloz.com/huzheng/stardict-dic/dict.org/

MAINTAINER=	makc@FreeBSD.org
COMMENT=	The Britannica Concise Encyclopedia

USE_BZIP2=	yes

.include "${.CURDIR}/../../russian/stardict-mueller7/files/Makefile.common"
.include <bsd.port.mk>
