# Created by: Oliver Eikemeier <eik@FreeBSD.org>
# $FreeBSD: mail/exim-sa-exim/Makefile 327742 2013-09-20 19:59:12Z bapt $

PKGNAMESUFFIX=	-sa-exim
MASTERDIR=	${.CURDIR}/../exim

PORTVERSION?=	${EXIM_VERSION}+${SA_EXIM_VERSION}

WITH_SA_EXIM=	yes

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
