# Created by: Tim Bishop <tdb@FreeBSD.org>
# $FreeBSD: sysutils/puppet-lint/Makefile 327772 2013-09-20 23:05:58Z bapt $

PORTNAME=	puppet-lint
PORTVERSION=	0.3.2
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	tdb@FreeBSD.org
COMMENT=	Checks Puppet manifests against the style guide

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/puppet-lint

NO_STAGE=	yes
.include <bsd.port.mk>
