# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: science/R-cran-som/Makefile 333659 2013-11-13 08:19:34Z bf $

PORTNAME=	som
DISTVERSION=	0.3-5
PORTREVISION=	7
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Self-Organizing Map

LICENSE=	GPLv3

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
