# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: science/R-cran-som/Makefile 313562 2013-03-07 04:21:34Z bf $

PORTNAME=	som
DISTVERSION=	0.3-5
PORTREVISION=	4
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Self-Organizing Map

LICENSE=	GPLv3

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
