# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: science/R-cran-som/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	som
DISTVERSION=	0.3-5
PORTREVISION=	7
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Self-Organizing Map

LICENSE=	GPLv3

USES=	cran:auto-plist

.include <bsd.port.mk>
