# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: audio/gstreamer-plugins-amrnb/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer OpenCore based Adaptive Multi-Rate Narrow-Band plugin

GST_PLUGIN=	amrnb

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
