# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: ports/devel/rubygem-listen/Makefile,v 1.5 2012/12/04 07:22:48 svnexp Exp $

PORTNAME=	listen
PORTVERSION=	0.6.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Listen to file modifications and notify about the changes

RUN_DEPENDS=	rubygem-rb-inotify>=0.8.8:${PORTSDIR}/devel/rubygem-rb-inotify

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
