# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: devel/py-grizzled/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	grizzled
PORTVERSION=	0.9.4
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	The Grizzled Python Utility Library

USE_PYTHON=		yes
USE_PYDISTUTILS=	easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
