# Created by: Ju Pengfei <jupengfei@gmail.com>
# $FreeBSD: ftp/py-tftpy/Makefile 325163 2013-08-21 17:42:57Z sunpoet $

PORTNAME=	tftpy
PORTVERSION=	0.6.0
CATEGORIES=	ftp python
MASTER_SITES=	SF \
		CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Pure Python TFTP Implementation

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
