# Created by: Ju Pengfei <jupengfei@gmail.com>
# $FreeBSD: ftp/py-tftpy/Makefile 326670 2013-09-07 17:53:23Z sunpoet $

PORTNAME=	tftpy
PORTVERSION=	0.6.0
CATEGORIES=	ftp python
MASTER_SITES=	SF \
		CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Pure Python TFTP Implementation

USE_PYTHON=	yes
USE_PYDISTUTILS=yes

.include <bsd.port.mk>
