# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-pkg-config/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	pkg-config
PORTVERSION=	1.1.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A pkg-config implementation for Ruby

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_RAKE=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
