# New ports collection Makefile for:	p5-Exception-Handler
# Date created:				25th April 2007
# Whom: 				jeffhung
#
# $FreeBSD: ports/devel/p5-Exception-Handler/Makefile,v 1.5 2012/11/17 05:56:15 svnexp Exp $
#

PORTNAME=	Exception-Handler
PORTVERSION=	1.004
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jeffhung@mail2000.com.tw
COMMENT=	Perl module that report exceptions with formatted text call-stack

PERL_CONFIGURE=	YES

MAN3=		Exception::Handler.3

.include <bsd.port.mk>
