# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: print/rubygem-prawn-core/Makefile 327765 2013-09-20 22:43:59Z bapt $

PORTNAME=	prawn-core
PORTVERSION=	0.8.4
CATEGORIES=	print rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Core of Rubygem-prawn

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
