# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: devel/rubygem-elif/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	elif
PORTVERSION=	0.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Read file in reverse order

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
