# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11/libXfixes/Makefile 319899 2013-06-04 19:31:29Z zeising $

PORTNAME=	libXfixes
PORTVERSION=	5.0.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Fixes extension library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 fixesproto:both xproto:both xextproto

MAN3=		Xfixes.3

.include <bsd.port.mk>
