# Whom:	Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-hike/Makefile 319592 2013-06-01 21:22:07Z swills $

PORTNAME=	hike
PORTVERSION=	1.2.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A Ruby library for finding files in a set of paths

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
