# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-hike/Makefile 332038 2013-10-30 02:36:45Z swills $

PORTNAME=	hike
PORTVERSION=	1.2.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A Ruby library for finding files in a set of paths

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
