# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: devel/hs-mmap/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	mmap
PORTVERSION=	0.5.8
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Memory-mapped files for POSIX and Windows

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
