# Created by: Matt Mills <matt_mills@btopenworld.com>
# $FreeBSD: textproc/p5-String-Format/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	String-Format
PORTVERSION=	1.17
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	matt_mills@btopenworld.com
COMMENT=	Perl module for sprintf-like string formatting capability

LICENSE=	GPLv2

USES=		perl5
USE_PERL5=	configure

MAN3=		String::Format.3

NO_STAGE=	yes
.include <bsd.port.mk>
