# $FreeBSD: archivers/php53-bz2/Makefile 327699 2013-09-20 13:11:20Z bapt $

CATEGORIES=	archivers

NO_STAGE=	yes
MASTERDIR=	${.CURDIR}/../../lang/php53

PKGNAMESUFFIX=	-bz2

.include "${MASTERDIR}/Makefile"
