# $FreeBSD: x11/xorg-docs/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xorg-docs
PORTVERSION=	1.7
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.org documentation files

CONFIGURE_ARGS+=	--without-xmlto --without-fop --disable-specs

XORG_CAT=	doc

.include <bsd.port.mk>
