# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: x11/xtrans/Makefile 325381 2013-08-26 10:07:01Z zeising $

PORTNAME=	xtrans
PORTVERSION=	1.2.7
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Abstract network code for X

CONFLICTS=	libXtrans

LICENSE=	MIT

XORG_CAT=	lib

CONFIGURE_ARGS+=--disable-docs --without-xmlto

.include <bsd.port.mk>
