# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: x11/xtrans/Makefile 328711 2013-09-29 17:01:41Z zeising $

PORTNAME=	xtrans
PORTVERSION=	1.2.7
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Abstract network code for X

LICENSE=	MIT

XORG_CAT=	lib

CONFIGURE_ARGS+=--disable-docs --without-xmlto

.include <bsd.port.mk>
