# $FreeBSD: devel/cx_Freeze/Makefile 335997 2013-12-09 15:12:08Z wg $

PORTNAME=	cx_Freeze
PORTVERSION=	4.3.2
CATEGORIES=	devel python
MASTER_SITES=	SF/cx-freeze/${PORTVERSION}

MAINTAINER=	araujo@FreeBSD.org
COMMENT=	The cx_Freeze is a set of utilities for freezing Python scripts

USE_GCC=	yes
USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
