# Created by: Martin Dieringer <martin.dieringer@gmx.de>
# $FreeBSD: math/clipper/Makefile 313157 2013-03-01 16:26:37Z pawel $

PORTNAME=	clipperlib
PORTVERSION=	5.1.2
CATEGORIES=	math
MASTER_SITES=	SF
MASTER_SITE_SUBDIR=	polyclipping
DISTNAME=	clipper_ver${PORTVERSION}

MAINTAINER=	martin.dieringer@gmx.de
COMMENT=	Polygon clipping library

WRKSRC=		${WRKDIR}/cpp

USE_LDCONFIG=	yes
USE_ZIP=	yes
USE_CMAKE=	yes

.include <bsd.port.mk>
