# Created by: Lars Balker Rasmussen <lbr@FreeBSD.org>
# $FreeBSD: devel/p5-Sub-Install/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Sub-Install
PORTVERSION=	0.926
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Install subroutines into packages easily

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=	Sub::Install.3

.include <bsd.port.mk>
