# $FreeBSD: portuguese/php_doc-br/Makefile 327763 2013-09-20 22:38:31Z bapt $

CATEGORIES=	portuguese lang
PKGNAMEPREFIX=

PHP_LANG=	br
MASTERDIR=	${.CURDIR}/../../lang/php_doc

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
