# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: audio/gstreamer-plugins-mad/Makefile 327706 2013-09-20 14:36:35Z bapt $
#   $MCom: ports/audio/gstreamer-plugins-mad/Makefile,v 1.5 2008/03/19 14:05:30 ahze Exp $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer mp3 decoder plugin

GST_PLUGIN=	mad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins
NO_STAGE=	yes

.include "${MASTERDIR}/Makefile"
