# Created by: nork@FreeBSD.org
# $FreeBSD: security/p5-Crypt-Serpent/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Crypt-Serpent
PORTVERSION=	1.01
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl implementation of the Serpent encryption algorithm

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
