# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: math/hs-vector-space/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	vector-space
PORTVERSION=	0.8.6
PORTREVISION=	5
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Vector & affine spaces, linear maps, and derivatives

LICENSE=	BSD

USE_CABAL=	Boolean>=0.1.0 MemoTrie>=0.5 NumInstances>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
