# Created by: Olivier Duchateau <duchateau.olivier@gmail.com>
# $FreeBSD: graphics/pysvg/Makefile 327733 2013-09-20 18:35:44Z bapt $

PORTNAME=	pysvg
PORTVERSION=	0.2.1
PORTREVISION=	1
CATEGORIES=	graphics python
MASTER_SITES=	GOOGLE_CODE

MAINTAINER=	duchateau.olivier@gmail.com
COMMENT=	pySVG - creating svg with python

USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

USE_PYTHON=	-2.7
USE_ZIP=	yes

.include <bsd.port.mk>
