# New ports collection makefile for:	pysvg
# Date created:				2009-08-26
# Whom:					Olivier Duchateau <duchateau.olivier@gmail.com>
#
# $FreeBSD: ports/graphics/pysvg/Makefile,v 1.3 2012/11/17 05:58:21 svnexp Exp $
#

PORTNAME=	pysvg
PORTVERSION=	0.2.1
CATEGORIES=	graphics python
MASTER_SITES=	GOOGLE_CODE

MAINTAINER=	duchateau.olivier@gmail.com
COMMENT=	pySVG - creating svg with python

USE_PYDISTUTILS=yes
USE_PYTHON=	-2.7
USE_ZIP=	yes

PLIST_SUB=	PYDISTUTILS_EGGINFO=${PYDISTUTILS_EGGINFO}

.include <bsd.port.mk>
