# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: textproc/la-aspell/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-la-20020503-0
PORTREVISION=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Latin dictionary

DICT=	 	la

NO_STAGE=	yes
.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
