# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: textproc/la-aspell/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-la-20020503-0
PORTREVISION=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Latin dictionary

DICT=	 	la

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
