# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: databases/freetds-msdblib/Makefile 327717 2013-09-20 16:13:47Z bapt $

PKGNAMESUFFIX=	-msdblib

MAINTAINER=	cowbert@gmail.com

WITH_MSDBLIB=	yes

MASTERDIR=	${.CURDIR}/../freetds

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
