# Created by: Alex Keda <admin@lissyara.su>
# $FreeBSD: net-mgmt/php52-snmp/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	net-mgmt

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-snmp

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
