# New ports collection makefile for:	php52-snmp
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/net-mgmt/php52-snmp/Makefile,v 1.2 2012/11/17 06:00:36 svnexp Exp $
#

CATEGORIES=	net-mgmt

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-snmp

.include "${MASTERDIR}/Makefile"
