# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: textproc/p5-XML-Atom-SimpleFeed/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	XML-Atom-SimpleFeed
PORTVERSION=	0.86
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	XML::Atom::SimpleFeed - Generate simple Atom syndication feeds

USES=		perl5
USE_PERL5=	configure

MAN3=	XML::Atom::SimpleFeed.3

.include <bsd.port.mk>
