# New ports collection makefile for:	textproc/p5-XML-Atom-SimpleFeed
# Date created:				16 October 2005
# Whom:					Anton Berezin <tobez@FreeBSD.org>
#
# $FreeBSD: ports/textproc/p5-XML-Atom-SimpleFeed/Makefile,v 1.9 2012/11/17 06:02:11 svnexp Exp $
#

PORTNAME=	XML-Atom-SimpleFeed
PORTVERSION=	0.86
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	XML::Atom::SimpleFeed - Generate simple Atom syndication feeds

PERL_CONFIGURE=	yes

MAN3=	XML::Atom::SimpleFeed.3

.include <bsd.port.mk>
