# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: textproc/p5-XML-Atom-SimpleFeed/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	XML-Atom-SimpleFeed
PORTVERSION=	0.86
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	XML::Atom::SimpleFeed - Generate simple Atom syndication feeds

USES=		perl5
USE_PERL5=	configure

MAN3=	XML::Atom::SimpleFeed.3

NO_STAGE=	yes
.include <bsd.port.mk>
