# $FreeBSD: www/twiki-SlideShowPlugin/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	SlideShowPlugin
SVNREV=		17261

COMMENT=	Convert a topic with headings into a slideshow

NO_STAGE=	yes
.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
