# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: mail/rubygem-pony/Makefile 322807 2013-07-12 03:35:10Z swills $

PORTNAME=	pony
PORTVERSION=	1.5
CATEGORIES=	mail rubygems
MASTER_SITES=	RG

MAINTAINER=	freebsdports@chillibear.com
COMMENT=	The express way to send mail from Ruby

RUN_DEPENDS=	rubygem-mail>=2.0:${PORTSDIR}/mail/rubygem-mail

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
