# Created by: Erwin Lansing <erwin@FreeBSD.org>
# $FreeBSD: devel/p5-Cache-Mmap/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Cache-Mmap
PORTVERSION=	0.11
PORTEPOCH=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Cache::Mmap - Shared data cache using memory mapped files

USES=		perl5
USE_PERL5=	configure

MAN3=		Cache::Mmap.3

NO_STAGE=	yes
.include <bsd.port.mk>
