# New ports collection makefile for:	gstreamer-plugins-dv
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD: ports/multimedia/gstreamer-plugins-dv/Makefile,v 1.15 2012/11/17 05:59:49 svnexp Exp $
#   $MCom: ports/multimedia/gstreamer-plugins-dv/Makefile,v 1.5 2008/03/19 14:05:36 ahze Exp $
#

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer dv plugin

GST_PLUGIN=	dv

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
