# Created by: ricci@cs.utah.edu
# $FreeBSD: x11-wm/ion/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	ion
PORTVERSION=	20020207
PORTREVISION=	2
CATEGORIES=	x11-wm
MASTER_SITES=	http://modeemi.fi/~tuomov/dl/archives/

MAINTAINER=	ricci@cs.utah.edu
COMMENT=	A window manager with a text-editorish, keyboard friendly interface

CONFLICTS=	ion-2-*

MAN1=		ion.1x

USE_XORG=	x11
USE_GMAKE=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
