# Created by: Ilia Chipitsine <ilia@jane.cgu.chel.su>
# $FreeBSD: converters/p5-Unicode-String/Makefile 327715 2013-09-20 16:05:24Z bapt $

PORTNAME=	Unicode-String
PORTVERSION=	2.09
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	These are experimental Perl5 modules to handle various Unicode issues

USES=		perl5
USE_PERL5=	configure

MAN3=		Unicode::CharName.3 Unicode::String.3

NO_STAGE=	yes
.include <bsd.port.mk>
