# New ports collection makefile for:	p5-Unicode-String
# Date created:				10th September 2000
# Whom:					Ilia Chipitsine <ilia@jane.cgu.chel.su>
#
# $FreeBSD: ports/converters/p5-Unicode-String/Makefile,v 1.18 2012/12/17 08:35:00 svnexp Exp $
#

PORTNAME=	Unicode-String
PORTVERSION=	2.09
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	These are experimental Perl5 modules to handle various Unicode issues

PERL_CONFIGURE=	yes

MAN3=		Unicode::CharName.3 Unicode::String.3

.include <bsd.port.mk>
