# Created by: Robert Gogolok <gogo@cs.uni-sb.de>
# $FreeBSD: www/rubygem-haml/Makefile 340677 2014-01-22 01:24:09Z swills $

PORTNAME=	haml
PORTVERSION=	4.0.4
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	gogolok+freebsd@gmail.com
COMMENT=	Markup language to describe HTML

LICENSE=	MIT

RUN_DEPENDS=	rubygem-tilt>=0:${PORTSDIR}/devel/rubygem-tilt

USE_RAKE=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/haml

.include <bsd.port.mk>
