# Created by: Robert Gogolok <gogo@cs.uni-sb.de>
# $FreeBSD: www/rubygem-haml/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	haml
PORTVERSION=	3.1.7
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	gogolok+freebsd@gmail.com
COMMENT=	Markup language to describe XHTML

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/haml bin/html2haml

NO_STAGE=	yes
.include <bsd.port.mk>
