# New ports collection makefile for:	p5-IO-MultiPipe
# Date created:		2009-01-14
# Whom:			Zane C, Bowers <vvelox@vvelox.net>
#
# $FreeBSD: ports/devel/p5-IO-MultiPipe/Makefile,v 1.4 2012/11/17 05:56:18 svnexp Exp $
#

PORTNAME=	IO-MultiPipe
PORTVERSION=	0.0.0
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:VVELOX
PKGNAMEPREFIX=	p5-

MAINTAINER=	vvelox@vvelox.net
COMMENT=	Check for errors when running a command through multiple pipes

PERL_CONFIGURE=	yes

MAN3=		IO::MultiPipe.3

.include <bsd.port.mk>
