# Created by: Kurt Lidl <kurt.lidl@cello.com>
# $FreeBSD: devel/p5-Data-Inspect/Makefile 338884 2014-01-06 14:40:31Z az $

PORTNAME=	Data-Inspect
PORTVERSION=	0.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:OWL
PKGNAMEPREFIX=	p5-

MAINTAINER=	kurt.lidl@cello.com
COMMENT=	Another pretty-printer for perl objects

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
