# Created by: Kurt Lidl <kurt.lidl@cello.com>
# $FreeBSD: devel/p5-Data-Inspect/Makefile 326706 2013-09-08 08:16:43Z az $

PORTNAME=	Data-Inspect
PORTVERSION=	0.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:OWL
PKGNAMEPREFIX=	p5-

MAINTAINER=	kurt.lidl@cello.com
COMMENT=	Another pretty-printer for perl objects

USES=		perl5
USE_PERL5=	configure

MAN3=	Data::Inspect.3

.include <bsd.port.mk>
