# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: www/twiki-GluePlugin/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	GluePlugin
SVNREV=		15708
MASTER_SITES=	http://protey.ru/freebsd/distfiles/ \
		${MASTER_SITE_LOCAL:S!$!skv/!}

COMMENT=	Allow to format tags and arguments on multiple lines

NO_STAGE=	yes
.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
