# Created by: Murilo Opsfelder <mopsfelder@gmail.com>
# $FreeBSD: sysutils/p5-Sys-HostIP/Makefile 327772 2013-09-20 23:05:58Z bapt $

PORTNAME=	Sys-HostIP
PORTVERSION=	1.9.3
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	mopsfelder@gmail.com
COMMENT=	A Perl module to get IP address related info

USES=		perl5
USE_PERL5=	configure

MAN3=		Sys::HostIP.3

NO_STAGE=	yes
.include <bsd.port.mk>
