# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/archivers/php70-zlib/Makefile 422569 2016-09-21 15:43:47Z tz $

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-zlib

.include "${MASTERDIR}/Makefile"
