# Created by: Gabor Kovesdan
# $FreeBSD: security/p5-Digest-Tiger/Makefile 326980 2013-09-11 13:54:50Z az $

PORTNAME=	Digest-Tiger
PORTVERSION=	0.03
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl extension for Tiger hash algorithm

USES=		perl5
USE_PERL5=	configure

MAN3=	Digest::Tiger.3

.include <bsd.port.mk>
