# Created by: Gabor Kovesdan
# $FreeBSD: security/p5-Digest-Tiger/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	Digest-Tiger
PORTVERSION=	0.03
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl extension for Tiger hash algorithm

USES=		perl5
USE_PERL5=	configure

MAN3=	Digest::Tiger.3

NO_STAGE=	yes
.include <bsd.port.mk>
