# Created by: Gabor Kovesdan
# $FreeBSD: security/p5-Digest-Tiger/Makefile 341821 2014-01-30 09:08:26Z az $

PORTNAME=	Digest-Tiger
PORTVERSION=	0.03
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl extension for Tiger hash algorithm

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
