# New ports collection makefile for:	p5-Convert-NLS_DATE_FORMAT
# Date created:		2011-10-19
# Whom:			Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
#
# $FreeBSD: ports/converters/p5-Convert-NLS_DATE_FORMAT/Makefile,v 1.3 2012/11/17 05:55:03 svnexp Exp $
#

PORTNAME=	Convert-NLS_DATE_FORMAT
PORTVERSION=	0.05
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:KOLIBRIE
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Convert Oracle NLS_DATE_FORMAT <-> strftime format strings

PERL_CONFIGURE=	yes

MAN3=		Convert::NLS_DATE_FORMAT.3

.include <bsd.port.mk>
