# $FreeBSD: ports/net/hs-hostname/Makefile,v 1.9 2013/02/05 22:47:12 svnexp Exp $

PORTNAME=	hostname
PORTVERSION=	1.0
PORTREVISION=	7
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cross-platform means of determining the hostname

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
