# Created by: Max Khon <fjoe@FreeBSD.org>
# $FreeBSD: archivers/libmspack/Makefile 330365 2013-10-15 05:12:03Z fjoe $

PORTNAME=	libmspack
PORTVERSION=	0.4
CATEGORIES=	archivers
MASTER_SITES=	http://www.cabextract.org.uk/libmspack/
DISTNAME=	${PORTNAME}-${PORTVERSION}alpha

MAINTAINER=	fjoe@FreeBSD.org
COMMENT=	Library for Microsoft compression formats

LICENSE=	LGPL21

USE_AUTOTOOLS=	libtool
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes
USES=		pathfix

.include <bsd.port.mk>
