# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: textproc/p5-HTML-Fraction/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	HTML-Fraction
PORTVERSION=	0.50
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	HTML::Fraction - Encode fractions as HTML entities

USES=		perl5
USE_PERL5=	configure

MAN3=	HTML::Fraction.3

NO_STAGE=	yes
.include <bsd.port.mk>
