# Created by: chinsan
# $FreeBSD: sysutils/p5-Iterator-File/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Iterator-File
PORTVERSION=	1.01
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	File iterator, optionally stateful and verbose

USES=		perl5
USE_PERL5=	configure
MAN3=		Iterator::File::Status.3 \
		Iterator::File::Source::FlatFile.3 \
		Iterator::File::Utility.3 \
		Iterator::File::State::Interface.3 \
		Iterator::File::Source::Interface.3 \
		Iterator::File::State::TempFile.3 \
		Iterator::File.3 \
		Iterator::File::State::IPCShareable.3

.include <bsd.port.mk>
