# Created by: ijliao
# $FreeBSD: misc/py-pexpect/Makefile 315240 2013-03-25 18:44:20Z eadler $

PORTNAME=	pexpect
PORTVERSION=	2.4
PORTREVISION=	1
CATEGORIES=	misc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Pure Python Expect-like module

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
