# Created by: ijliao
# $FreeBSD: misc/py-pexpect/Makefile 340833 2014-01-23 15:44:14Z wg $

PORTNAME=	pexpect
PORTVERSION=	3.1
CATEGORIES=	misc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Pure Python Expect-like module

LICENSE=	ISCL

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
