# ex:ts=8
# Ports collection makefile for:	pexpect
# Date created:			Jan 11, 2003
# Whom:				ijliao
#
# $FreeBSD: ports/misc/py-pexpect/Makefile,v 1.14 2012/11/17 05:59:44 svnexp Exp $
#

PORTNAME=	pexpect
PORTVERSION=	2.4
PORTREVISION=	1
CATEGORIES=	misc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A Pure Python Expect-like module

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
