# New ports collection makefile for:   enygma
# Date created:                14 September 2008
# Whom:                        Wouter Reckman <gennerate@zonnet.nl>
#
# $FreeBSD: games/enygma/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=		enygma
PORTVERSION=	1.04
CATEGORIES=		games
MASTER_SITES=	http://www.chiark.greenend.org.uk/~sgtatham/enigma/
DISTNAME=		enigma-${DISTVERSION}
DIST_SUBDIR=	${PORTNAME}

MAINTAINER=		gennerate@zonnet.nl
COMMENT=		A text-based puzzle game

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
