# Created by: Jeremy Shaffner <jeremy@external.org>
# $FreeBSD: devel/p5-File-Tail/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	File-Tail
PORTVERSION=	0.99.3
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl Module to read the end of a file as it\'s appended to

USES=		perl5
USE_PERL5=	configure

MAN3=		File::Tail.3

NO_STAGE=	yes
.include <bsd.port.mk>
