# $FreeBSD: www/hs-shakespeare-i18n/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	shakespeare-i18n
PORTVERSION=	1.0.0.2
PORTREVISION=	7
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type-based approach to internationalization

LICENSE=	MIT

USE_CABAL=	parsec shakespeare>=1.0 text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
