# Created by: Erwin Lansing <erwin@FreeBSD.org>
# $FreeBSD: www/p5-Apache-ConfigFile/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Apache-ConfigFile
PORTVERSION=	1.23
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:NWIGER
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Apache::ConfigFile - Parse Apache style httpd.conf configuration files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
