# Created by: Alex Keda <admin@lissyara.su>
# $FreeBSD: mail/php52-imap/Makefile 327742 2013-09-20 19:59:12Z bapt $

CATEGORIES=	mail

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-imap

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
