# New ports collection makefile for:	webalizer2
# Date created:		11.Sep 2003
# Whom:			wtp@bsdguru.org
#
# $FreeBSD: ports/polish/webalizer2/Makefile,v 1.3 2012/11/17 06:00:45 svnexp Exp $

CATEGORIES=	polish

MAINTAINER=	wtp@bsdguru.org

MASTERDIR?=	${.CURDIR}/../../www/webalizer
WEBALIZER_LANG=	polish

.if exists(${.CURDIR}/Makefile.local)
.include "${.CURDIR}/Makefile.local"
.endif

.include "${MASTERDIR}/Makefile"
