# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-Class-ArrayObjects/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Class-ArrayObjects
PORTVERSION=	1.03
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Utility class for array based objects

USES=		perl5
USE_PERL5=	configure

MAN3=		Class::ArrayObjects.3

.include <bsd.port.mk>
