# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: textproc/p5-String-BufferStack/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	String-BufferStack
PORTVERSION=	1.16
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	String
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Nested buffers for templating systems

USES=		perl5
USE_PERL5=	configure

MAN3=	String::BufferStack.3

NO_STAGE=	yes
.include <bsd.port.mk>
