# New ports collection makefile for:	AluminumAlloy-Cryogenic (metacity theme)
# Date Created:				27 August 2004
# Whom:					Alexey Dokuchaev <danfe@FreeBSD.org>
#
# $FreeBSD: ports/x11-themes/metacity-aluminumalloy-cryogenic-theme/Makefile,v 1.2 2012/11/17 06:03:33 svnexp Exp $
#

TYPE=		metacity
MASTERDIR=	${.CURDIR}/../gtk-aluminumalloy-cryogenic-theme

.include "${MASTERDIR}/Makefile"
