# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: textproc/rubygem-colored/Makefile 332050 2013-10-30 02:57:17Z swills $

PORTNAME=	colored
PORTVERSION=	1.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Colorize text on the console

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_RAKE=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
