# Created by: Ryan Steinmetz <rpsfa@rit.edu>
# $FreeBSD: devel/rubygem-warden/Makefile 334437 2013-11-20 18:32:17Z sunpoet $

PORTNAME=	warden
PORTVERSION=	1.2.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Rack middleware that provides authentication for rack applications

LICENSE=	MIT

RUN_DEPENDS=	rubygem-rack>=1.0:${PORTSDIR}/www/rubygem-rack

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
