# Created by: Ryan Steinmetz <rpsfa@rit.edu>
# $FreeBSD: devel/rubygem-warden/Makefile 332043 2013-10-30 02:47:06Z swills $

PORTNAME=	warden
PORTVERSION=	1.2.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Rack middleware that provides authentication for rack applications

RUN_DEPENDS=	rubygem-rack>=1.0:${PORTSDIR}/www/rubygem-rack

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
