# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-Sub-Name/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	Sub-Name
PORTVERSION=	0.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Sub::Name - (re)name a sub

USES=		perl5
USE_PERL5=	configure

MAN3=	Sub::Name.3

.include <bsd.port.mk>
