# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: devel/pear-channel-openpear/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	openpear
PORTVERSION=	20111203
CATEGORIES=	devel www pear
MASTER_SITES=	#

MAINTAINER=	tota@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	openpear.org

NO_STAGE=	yes
.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
