# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: devel/pear-channel-openpear/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	openpear
PORTVERSION=	20111203
CATEGORIES=	devel www pear
MASTER_SITES=	#

MAINTAINER=	tota@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	openpear.org

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
