# $FreeBSD: ports/net/p5-Net-Divert/Makefile,v 1.7 2012/12/12 21:45:13 svnexp Exp $

PORTNAME=	Net-Divert
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
EXTRACT_SUFX=	.tgz

MAINTAINER=	ecu@200ok.org
COMMENT=	A module to deal with divert(4) sockets

PERL_CONFIGURE=	yes

MAN3=		Net::Divert.3

.include <bsd.port.mk>
