# $FreeBSD: devel/p5-Module-Pluggable/Makefile 320532 2013-06-11 06:38:21Z lth $

PORTNAME=	Module-Pluggable
PORTVERSION=	4.8
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Automatically give your module the ability to have plugins

PERL_CONFIGURE=	yes

MAN3=		Devel::InnerPackage.3 \
		Module::Pluggable.3 \
		Module::Pluggable::Object.3

.include <bsd.port.mk>
