# $FreeBSD: x11/xdriinfo/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xdriinfo
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Query configuration information of DRI drivers

USE_GL=		gl

XORG_CAT=	app
USE_XORG=	x11 glproto
PLIST_FILES=	bin/xdriinfo man/man1/xdriinfo.1.gz

.include <bsd.port.mk>
