#
# $FreeBSD: sysutils/sb16config/files/Makefile 340722 2014-01-22 17:00:46Z mat $
#

PROG=		sb16config
MAN=		sb16config.8

BINDIR=		${PREFIX}/bin
SHAREDIR=	${PREFIX}
NOOBJ=		yes

.include <bsd.prog.mk>
