#
# $FreeBSD: ports/sysutils/sb16config/files/Makefile,v 1.3 2012/11/17 06:01:45 svnexp Exp $
#

PROG=		sb16config
MAN=		sb16config.8

BINDIR=		${PREFIX}/bin
SHAREDIR=	${PREFIX}
NOOBJ=		yes

.include <bsd.prog.mk>
