# $FreeBSD: x11-drivers/xf86-video-ark/Makefile 336621 2013-12-16 11:11:09Z zeising $

PORTNAME=	xf86-video-ark
PORTVERSION=	0.7.5
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org ark display driver

XORG_CAT=	driver

.include <bsd.port.mk>
