# $FreeBSD: x11-drivers/xf86-video-ark/Makefile 327779 2013-09-20 23:48:39Z bapt $

PORTNAME=	xf86-video-ark
PORTVERSION=	0.7.5
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org ark display driver

XORG_CAT=	driver

NO_STAGE=	yes
.include <bsd.port.mk>
