# New ports collection makefile for:	pystemmer
# Date created:		2009-03-17
# Whom:			Wen Heping <wenheping@gmail.com>
#
# $FreeBSD: ports/textproc/pystemmer/Makefile,v 1.4 2012/11/17 06:02:18 svnexp Exp $
#

PORTNAME=	pystemmer
PORTVERSION=	1.2.0
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP \
		http://snowball.tartarus.org/wrappers/
DISTNAME=	PyStemmer-${PORTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Snowball Stemming Algorithms for Information Retrieval

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_PKGNAME=	PyStemmer

.include <bsd.port.mk>
