# New ports collection makefile for:	typetrainer
# Date created:				29 January 2011
# Whom:					Ruslan Mahmatkhanov <cvs-src@yandex.ru>
#
# $FreeBSD: ports/misc/typetrainer/Makefile,v 1.9 2012/11/17 05:59:45 svnexp Exp $
#

PORTNAME=	typetrainer
PORTVERSION=	0.5.2
PORTREVISION=	1
CATEGORIES=	misc python
MASTER_SITES=	CHEESESHOP

MAINTAINER=	rm@FreeBSD.org
COMMENT=	Typing tutor trainer

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GNOME=	pygtk2
USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

.include <bsd.port.mk>
