# New ports collection makefile for:	Elib for GNU Emacs 21
# Date created:		4 August 2007
# Whom:			MANTANI Nobutaka <nobutaka@FreeBSD.org>
#
# $FreeBSD: ports/devel/elib-emacs21/Makefile,v 1.2 2012/11/17 05:55:42 svnexp Exp $
#

MAINTAINER=	ports@FreeBSD.org

# This is a slave port.
PORTCLASS=	slave

MASTERDIR=	${.CURDIR}/../../devel/elib

# emacs port setup
USE_EMACS=	yes
EMACS_PORT_NAME=	emacs21

.include "${MASTERDIR}/Makefile"
