# Created by: MANTANI Nobutaka <nobutaka@FreeBSD.org>
# $FreeBSD: devel/elib-emacs21/Makefile 327722 2013-09-20 17:03:26Z bapt $

MAINTAINER=	ports@FreeBSD.org

# This is a slave port.
PORTCLASS=	slave

MASTERDIR=	${.CURDIR}/../../devel/elib

# emacs port setup
USE_EMACS=	yes
EMACS_PORT_NAME=	emacs21

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
