# $FreeBSD: textproc/stardict-MerrianWebster/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	stardict-merrianwebster
PORTVERSION=	2.4.2
CATEGORIES=	textproc
MASTER_SITES=	http://yeelou.com/huzheng/stardict-dic/dict.org/

MAINTAINER=	makc@FreeBSD.org
COMMENT=	Merrian Webster 10th dictionary

NO_STAGE=	yes
.include "${.CURDIR}/../../russian/stardict-mueller7/files/Makefile.common"
.include <bsd.port.mk>
