# New ports collection makefile for:   lua50-posix
# Date created:        27 March 2006
# Whom:                Andrew Turner <andrew+ports@fubar.geek.nz>
#
# $FreeBSD: ports/devel/lua50-posix/Makefile,v 1.6 2012/11/17 05:55:59 svnexp Exp $
#

USE_LUA=	5.0

MASTERDIR=	${.CURDIR}/../lua-posix

.include "${MASTERDIR}/Makefile"
