# Created by: Philip Paeps <philip@paeps.cx>
# $FreeBSD: math/p5-Roman/Makefile 341829 2014-01-30 10:27:43Z az $

PORTNAME=	Roman
PORTVERSION=	1.22
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	philip@FreeBSD.org
COMMENT=	Perl module to convert between Arabic and Roman numerals

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
