# $FreeBSD: ports/editors/libreoffice-bg/Makefile,v 1.3 2012/11/17 05:57:15 svnexp Exp $

LO_I18N=	bg	
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
