# New ports collection makefile for:	libspiro
# Date created:				10 Janurary 2008
# Whom:					Naram Qashat <cyberbotx@cyberbotx.com>
#
# $FreeBSD: ports/graphics/libspiro/Makefile,v 1.5 2012/11/17 05:58:13 svnexp Exp $
#

PORTNAME=	libspiro
DISTVERSION=	20071029
CATEGORIES=	graphics
MASTER_SITES=	SF
DISTNAME=	${PORTNAME}_src-${PORTVERSION}

MAINTAINER=	cyberbotx@cyberbotx.com
COMMENT=	Library to convert clothoid splines into Bezier splines

USE_BZIP2=	yes
USE_GMAKE=	yes
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

WRKSRC=		${WRKDIR}/${PORTNAME}-${DISTVERSION}

.include <bsd.port.mk>
