# New ports collection makefile for:	I18N::AcceptLanguage
# Date created:		14 Feb 2011
# Whom:			Jun Kuriyama <kuriyama@FreeBSD.org>
#
# $FreeBSD: www/p5-I18N-AcceptLanguage/Makefile 326156 2013-09-03 15:07:52Z az $
#

PORTNAME=	I18N-AcceptLanguage
PORTVERSION=	1.04
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to matches language preference (HTTP Accept-Language)

USES=		perl5
USE_PERL5=	configure

MAN3=	I18N::AcceptLanguage.3

.include <bsd.port.mk>
