# $FreeBSD: www/p5-I18N-AcceptLanguage/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	I18N-AcceptLanguage
PORTVERSION=	1.04
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to matches language preference (HTTP Accept-Language)

USES=		perl5
USE_PERL5=	configure

MAN3=	I18N::AcceptLanguage.3

NO_STAGE=	yes
.include <bsd.port.mk>
