# Created by: mat
# $FreeBSD: devel/p5-Devel-Trace/Makefile 331933 2013-10-29 07:56:01Z vanilla $

PORTNAME=	Devel-Trace
PORTVERSION=	0.12
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Print out each line before it is executed (like sh -x)

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
