# $FreeBSD: www/twiki-RenderListPlugin/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	RenderListPlugin
SVNREV=		16417

COMMENT=	Render bullet lists in a variety of formats

NO_STAGE=	yes
.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
