# Created by: jsellens
# $FreeBSD: x11/xmsg/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xmsg
PORTVERSION=	1.1
PORTREVISION=	2
CATEGORIES=	x11
MASTER_SITES=	http://www.generalconcepts.com/resources/software/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Shows a message on the screen

PLIST_FILES=	bin/xmsg man/man1/xmsg.1.gz
USES=		imake
USE_XORG=	x11 xext xaw xmu xt sm ice

.include <bsd.port.mk>
