# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/glproto/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	glproto
PORTVERSION=	1.4.17
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	GLX extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
