# $FreeBSD: x11-fonts/showfont/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	showfont
PORTVERSION=	1.0.4
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Font dumper for the X font server

XORG_CAT=	app
USE_XORG=	libfs

PLIST_FILES=	bin/showfont

MAN1=		showfont.1

.include <bsd.port.mk>
