
# zrj: these to work around missing -I option in base soelim for building DOCS
BUILD_DEPENDS+= ${LOCALBASE}/bin/groff:${PORTSDIR}/textproc/groff
CONFIGURE_ARGS+= SOELIM=${LOCALBASE}/bin/soelim GROFF=${LOCALBASE}/bin/groff
