# New ports collection makefile for:	php5-zip
# Date created:			10 Dec 2008
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/archivers/php5-zip/Makefile,v 1.2 2012/11/17 05:54:22 svnexp Exp $
#

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-zip

.include "${MASTERDIR}/Makefile"
