# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: ports/devel/p5-Test-Fixme/Makefile,v 1.1 2013/01/30 20:05:59 svnexp Exp $

PORTNAME=	Test-Fixme
PORTVERSION=	0.08
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
#MASTER_SITE_SUBDIR=
PKGNAMEPREFIX=	p5-
#PKGNAMESUFFIX=
#DISTNAME=
#EXTRACT_SUFX=
#DISTFILES=
#DIST_SUBDIR=	${PORTNAME}
#EXTRACT_ONLY=

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Check code for FIXMEs

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		Test::Fixme.3

.include <bsd.port.mk>
