# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: dns/rubygem-public_suffix/Makefile 327719 2013-09-20 16:31:57Z bapt $

PORTNAME=	public_suffix
PORTVERSION=	1.3.0
CATEGORIES=	dns rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Parse and decompose a domain name into top level domain, domain and subdomains

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
