# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: dns/rubygem-public_suffix/Makefile 335752 2013-12-06 15:23:08Z sunpoet $

PORTNAME=	public_suffix
PORTVERSION=	1.3.3
CATEGORIES=	dns rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Parse and decompose a domain name into top level domain, domain and subdomains

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
