# New ports collection makefile for:	twiki-CommentPlugin
# Date created:		17 April 2008
#
# $FreeBSD: ports/www/twiki-CommentPlugin/Makefile,v 1.3 2012/11/17 06:03:09 svnexp Exp $
#

PORTNAME=	CommentPlugin
SVNREV=		17567

COMMENT=	Post comments easily

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
