# New ports collection makefile for:    mi-aspell
# Date created:                         19 March 2004
# Whom:                                 Thierry Thomas <thierry@pompo.net>
#
# $FreeBSD: ports/textproc/mi-aspell/Makefile,v 1.5 2012/11/17 06:02:03 svnexp Exp $
#

PORTNAME=	${DICT}-aspell
DISTVERSION=	-mi-0.50-0
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Maori dictionary

DICT=	 	mi

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
