# New ports collection makefile for:    price
# Date created:         28 Aug 2006
# Whom:                 gurkan@phys.ethz.ch
#
# $FreeBSD: ports/graphics/price/Makefile,v 1.20 2012/11/17 05:58:19 svnexp Exp $
#

PORTNAME=	price
PORTVERSION=	1.1.0
CATEGORIES=	graphics gnustep
MASTER_SITES=	SF/${PORTNAME}/PRICE%20source/${PORTVERSION}
DISTNAME=	PRICE-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Image filtering and manipulation using GNUstep

LICENSE=	GPLv2

USE_GNUSTEP=	yes
USE_GNUSTEP_BACK=	yes
USE_GNUSTEP_BUILD=	yes
USE_GNUSTEP_INSTALL=	yes

WRKSRC=		${WRKDIR}/PRICE-${PORTVERSION}

.include <bsd.port.mk>
