# Created by: gurkan@phys.ethz.ch
# $FreeBSD: graphics/price/Makefile 327733 2013-09-20 18:35:44Z bapt $

PORTNAME=	price
PORTVERSION=	1.1.0
CATEGORIES=	graphics gnustep
MASTER_SITES=	SF/${PORTNAME}/PRICE%20source/${PORTVERSION}
DISTNAME=	PRICE-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Image filtering and manipulation using GNUstep

LICENSE=	GPLv2

USE_GNUSTEP=	yes
USE_GNUSTEP_BACK=	yes
USE_GNUSTEP_BUILD=	yes
USE_GNUSTEP_INSTALL=	yes

WRKSRC=		${WRKDIR}/PRICE-${PORTVERSION}

NO_STAGE=	yes
.include <bsd.port.mk>
