# Created by: TERAMOTO Masahiro <markun@onohara.to>
# $FreeBSD: textproc/rubygem-htmlentities/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	htmlentities
PORTVERSION=	4.3.1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	markun@onohara.to
COMMENT=	HTML entity encoding and decoding for Ruby

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
