# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-Lingua-EN-Numbers-Ordinate/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=		Lingua-EN-Numbers-Ordinate
PORTVERSION=		1.02
CATEGORIES=		textproc perl5
MASTER_SITES=		CPAN
PKGNAMEPREFIX=		p5-

MAINTAINER=		perl@FreeBSD.org
COMMENT=	Go from cardinal number (3) to ordinal ("3rd")

USES=		perl5
USE_PERL5=	configure

MAN3=			Lingua::EN::Numbers::Ordinate.3

NO_STAGE=	yes
.include <bsd.port.mk>
