# Created by: Jean-Yves Lefort <jylefort@FreeBSD.org>
# $FreeBSD: graphics/cairo-reference/Makefile 327733 2013-09-20 18:35:44Z bapt $

PORTREVISION=	0

REFERENCE_SRC=	${WRKSRC}/doc/public

NO_STAGE=	yes
.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
