# New ports collection makefile for:	xpi-stylish
# Date created:		26 June 2007
# Whom:			Andrew Pantyukhin <infofarmer@FreeBSD.org>
#
# $FreeBSD: ports/www/xpi-stylish/Makefile,v 1.14 2012/11/17 06:03:13 svnexp Exp $
#

PORTNAME=	stylish
PORTVERSION=	1.2.5
DISTVERSIONSUFFIX=	-fx+tb+sm
CATEGORIES=	www

MAINTAINER=	gecko@FreeBSD.org
COMMENT=	User styles manager

XPI_NUM=	2108
XPI_ID=		{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}

.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
