# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: devel/rubygem-r18n-core/Makefile 332040 2013-10-30 02:40:36Z swills $

PORTNAME=	r18n-core
PORTVERSION=	1.1.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	i18n tool to translate your Ruby application

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes


.include <bsd.port.mk>
