# New ports collection makefile for:	gd2
# Date created:				19 Aug 1998
# Whom:					ichiro@ichiro.org
#
# $FreeBSD: ports/japanese/gd/Makefile,v 1.18 2012/11/17 05:58:34 svnexp Exp $
#

CATEGORIES=	japanese

MAINTAINER=	ichiro@ichiro.org
COMMENT=	A graphics library for fast image creation with Japanese support

MASTERDIR=	${.CURDIR}/../../graphics/gd

CPPFLAGS+=	-DJISX0208

PKGNAMEPREFIX=	ja-

.include "${MASTERDIR}/Makefile"
