# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: devel/pear-Horde_Autoloader_Cache/Makefile 333263 2013-11-08 21:41:53Z antoine $

PORTNAME=	Horde_Autoloader_Cache
PORTVERSION=	2.0.1
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Autoloader Cache

USE_HORDE_RUN=	Horde_Autoloader
USE_PHP=	json

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
