# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: ports/lang/tcl-modules/Makefile,v 1.5 2012/11/26 18:25:55 svnexp Exp $

PORTNAME=	tcl-modules
PORTREVISION=

MAINTAINER=	tcltk@FreeBSD.org
COMMENT=	Tcl common modules

BUILDING_TCL_TM=	yes

MASTERDIR=	${.CURDIR}/../tcl85

.include	"${MASTERDIR}/Makefile"
