# New ports collection makefile for:    p5-Convert-ASCII-Armour
# Date created:				2001/08/26
# Whom:					nork@cityfujisawa.ne.jp
#
# $FreeBSD: ports/converters/p5-Convert-ASCII-Armour/Makefile,v 1.14 2012/12/17 08:35:00 svnexp Exp $
#

PORTNAME=	Convert-ASCII-Armour
PORTVERSION=	1.4
PORTREVISION=	2
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Convert binary octets into ASCII armoured messages

PERL_CONFIGURE=	yes

MAN3=		Convert::ASCII::Armour.3 Convert::ASCII::Armor.3

.include <bsd.port.mk>
