# Created by: nork@cityfujisawa.ne.jp
# $FreeBSD: converters/p5-Convert-ASCII-Armour/Makefile 327715 2013-09-20 16:05:24Z bapt $

PORTNAME=	Convert-ASCII-Armour
PORTVERSION=	1.4
PORTREVISION=	2
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Convert binary octets into ASCII armoured messages

USES=		perl5
USE_PERL5=	configure

MAN3=		Convert::ASCII::Armour.3 Convert::ASCII::Armor.3

NO_STAGE=	yes
.include <bsd.port.mk>
