# Created by: Mathieu Arnold <m@absolight.net>
# $FreeBSD: devel/p5-B-Keywords/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	B-Keywords
PORTVERSION=	1.13
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lists of reserved barewords and symbol names

LICENSE=	ART10 GPLv2
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		B::Keywords.3

NO_STAGE=	yes
.include <bsd.port.mk>
