# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: mail/p5-Mail-POP3Client/Makefile 329554 2013-10-06 12:31:21Z demon $

PORTNAME=	Mail-POP3Client
PORTVERSION=	2.19
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Perl5 module to talk to a POP3 (RFC1939) server

USES=		perl5
USE_PERL5=	configure

MAN3=		Mail::POP3Client.3

NO_STAGE=	yes
.include <bsd.port.mk>
