# $FreeBSD: devel/hs-profunctors/Makefile 315580 2013-03-29 22:43:58Z pgj $

PORTNAME=	profunctors
PORTVERSION=	3.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 Profunctors

LICENSE=	BSD

USE_CABAL=	comonad>=3 tagged>=0.4.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
