# $FreeBSD: devel/hs-profunctors/Makefile 327723 2013-09-20 17:04:43Z bapt $

PORTNAME=	profunctors
PORTVERSION=	3.3.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 Profunctors

LICENSE=	BSD

USE_CABAL=	comonad>=3 tagged>=0.4.4

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
