# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: textproc/pear-File_MARC/Makefile 314735 2013-03-20 14:24:13Z wen $

PORTNAME=	File_MARC
PORTVERSION=	0.7.1
CATEGORIES=	textproc pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Parse, modify, and create MARC records

PEAR_AUTOINSTALL=	yes

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.mk"
.include <bsd.port.post.mk>
