# $FreeBSD: x11/xfwp/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xfwp
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X firewall proxy

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	x11 ice xproxymngproto

PLIST_FILES=	bin/xfwp man/man1/xfwp.1.gz

.include <bsd.port.mk>
