# Created by: Pawel Pekala <c0rn@o2.pl>
# $FreeBSD: mail/claws-mail-address_keeper/Makefile 317877 2013-05-11 14:10:28Z pawel $

PORTNAME=	address_keeper
PORTREVISION=	0

COMMENT=	Recipient addresses keeper plugin for Claws Mail

CLAWS_PLUGINS_BUILD=	address_keeper

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
