# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD: math/R-cran-gss/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	gss
DISTVERSION=	2.0-14
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	General Smoothing Splines

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
