# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11/libXres/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	libXres
PORTVERSION=	1.0.7
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Resource usage library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 xext xextproto resourceproto xproto:both

.include <bsd.port.mk>
