# New ports collection makefile for:	gnome-icons-dropline-neu
# Date created:		2010-08-03
# Whom:			Jimmy Olgeni <olgeni@FreeBSD.org>
#
# $FreeBSD: ports/x11-themes/gnome-icons-dropline-neu/Makefile,v 1.2 2012/11/17 06:03:31 svnexp Exp $
#

PORTNAME=	dropline-neu
PORTVERSION=	0.6
CATEGORIES=	x11-themes gnome
MASTER_SITES=	http://www.silvestre.com.ar/icons/
DISTNAME=	Neu-${PORTVERSION}-PR3

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Dropline Neu Icons for Gnome

USE_BZIP2=	yes
WRKSRC=		"${WRKDIR}/Neu"

.include "${.CURDIR}/../gnome-icons/bsd.gnome-icons.mk"
.include <bsd.port.mk>
