# Created by: Li-Wen Hsu <lwhsu@FreeBSD.org>
# $FreeBSD: devel/py-sysv_ipc/Makefile 338545 2014-01-03 15:16:56Z lwhsu $

PORTNAME=	sysv_ipc
PORTVERSION=	0.6.6
CATEGORIES=	devel python
MASTER_SITES=	http://semanchuk.com/philip/sysv_ipc/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	System V IPC for Python

LICENSE=	BSD

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

PLIST_FILES=	%%PYTHON_SITELIBDIR%%/sysv_ipc.so

NO_STAGE=	yes

.include <bsd.port.mk>
