# Created by: Alex Keda <admin@lissyara.su>
# $FreeBSD: graphics/php52-exif/Makefile 327733 2013-09-20 18:35:44Z bapt $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-exif

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
