# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: textproc/ca-aspell/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-ca-2.1.5-1
PORTEPOCH=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Catalan dictionary

DICT=	 	ca

NO_STAGE=	yes
.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
