# New ports collection makefile for:    ca-aspell
# Date created:                         1 September 2002
# Whom:                                 Thierry Thomas <thierry@pompo.net>
#
# $FreeBSD: ports/textproc/ca-aspell/Makefile,v 1.9 2012/11/17 06:01:52 svnexp Exp $
#

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-ca-2.1.5-1
PORTEPOCH=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Catalan dictionary

DICT=	 	ca

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
