# $FreeBSD: multimedia/gstreamer1-plugins-dts/Makefile 327747 2013-09-20 20:57:48Z bapt $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer dts plugin

GST_PLUGIN=	dts
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
