# Created by: William Grzybowski <william88@gmail.com>
# $FreeBSD: multimedia/py-guessit/Makefile 333198 2013-11-08 10:53:05Z wg $

PORTNAME=	guessit
PORTVERSION=	0.6.2
CATEGORIES=	multimedia python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Extract as much information as possible from a video file

LICENSE=	LGPL3

USE_PYTHON=	-2.7
USE_PYDISTUTILS=	easy_install
PYDISTUTILS_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
