# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: www/rubygem-rack-cache/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	rack-cache
PORTVERSION=	1.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Rack middleware to enable HTTP caching

RUN_DEPENDS=	rubygem-rack>=0.4:${PORTSDIR}/www/rubygem-rack

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
