# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-Term-CallEditor/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Term-CallEditor
PORTVERSION=	0.62
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Solicit for data from an external editor

LICENSE=	ART10

USES=		perl5
USE_PERL5=	configure

MAN3=	Term::CallEditor.3

NO_STAGE=	yes
.include <bsd.port.mk>
