# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: www/p5-HTTPD-User-Manage/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	HTTPD-User-Manage
PORTVERSION=	1.66
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl modules for managing access control with the web server

USES=		perl5
USE_PERL5=	configure

MAN3=		HTTPD::Authen.3 HTTPD::GroupAdmin.3 HTTPD::Realm.3 \
		HTTPD::RealmManager.3 HTTPD::UserAdmin.3

.include <bsd.port.mk>
