# Created by: peter.schuller@infidyne.com
# $FreeBSD: textproc/rubygem-liquid/Makefile 332052 2013-10-30 02:59:10Z swills $

PORTNAME=	liquid
PORTVERSION=	2.5.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for rendering safe templates

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
