# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-PadWalker/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	PadWalker
PORTVERSION=	1.96
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ROBIN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	PadWalker - play with Perl lexical variables

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		PadWalker.3

NO_STAGE=	yes
.include <bsd.port.mk>
