# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-PadWalker/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	PadWalker
PORTVERSION=	1.96
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ROBIN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	PadWalker - play with Perl lexical variables

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		PadWalker.3

.include <bsd.port.mk>
