# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-mspec/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	mspec
PORTVERSION=	1.5.20
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A specialized Ruby testing framework

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/mspec bin/mkspec bin/mspec-ci bin/mspec-run bin/mspec-tag

NO_STAGE=	yes
.include <bsd.port.mk>
