# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: ukrainian/aspell/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	aspell
DISTVERSION=	6-uk-1.4.0-0
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	ukrainian textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Ukrainian dictionaries

DICT=	 	uk

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
