# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/p5-Class-Null/Makefile 331856 2013-10-28 13:46:25Z vanilla $

PORTNAME=	Class-Null
PORTVERSION=	2.110730
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module which implements the Null Class design pattern

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
