# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/p5-Class-Null/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Class-Null
PORTVERSION=	2.110730
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module which implements the Null Class design pattern

USES=		perl5
USE_PERL5=	configure

MAN3=		Class::Null.3

NO_STAGE=	yes
.include <bsd.port.mk>
