# Created by: Emanuel Haupt <ehaupt@critical.ch>
# $FreeBSD: devel/p5-Sort-Array/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Sort-Array
DISTVERSION=	0.26
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Powerful array sorting Perl interface

USES=		perl5
USE_PERL5=	configure

MAN3=		Sort::Array.3

NO_STAGE=	yes
.include <bsd.port.mk>
