# Created by: Alexander Wittig <alexander@wittig.name>
# $FreeBSD: mail/squirrelmail-compatibility-plugin/Makefile 336240 2013-12-12 01:32:34Z adamw $

PORTNAME=	compatibility
PORTVERSION=2.0.16
CATEGORIES=	mail www
DISTNAME=	${PORTNAME}-${PORTVERSION}-1.0

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Required by many plugins for compatibility with SquirrelMail

NO_STAGE=	yes

.include <bsd.port.pre.mk>
.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.post.mk>
