# Created by: Pawel Worach
# $FreeBSD: x11-fonts/font-screen-cyrillic/Makefile 336621 2013-12-16 11:11:09Z zeising $

PORTNAME=	font-screen-cyrillic
PORTVERSION=	1.0.4
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Screen Cyrillic font

XORG_CAT=	font

.include <bsd.port.mk>
