# $FreeBSD: www/twiki-SpreadSheetPlugin/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	SpreadSheetPlugin
SVNREV=		16417

COMMENT=	Spreadsheet capabilities in topics

NO_STAGE=	yes
.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
