# Created by: Oleg A. Mamontov <oleg@mamontov.net>
# $FreeBSD: devel/p5-Module-List/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Module-List
PORTVERSION=	0.003
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	oleg@mamontov.net
COMMENT=	Module 'directory' listing

RUN_DEPENDS=	p5-parent>=0:${PORTSDIR}/devel/p5-parent

USES=		perl5
USE_PERL5=	modbuild

MAN3=		Module::List.3

NO_STAGE=	yes
.include <bsd.port.mk>
