# Created by: HONDA Yasuhiro <honda@kashio.info.mie-u.ac.jp>
# $FreeBSD: japanese/ng-canna/Makefile 330460 2013-10-15 21:17:55Z eadler $

PKGNAMESUFFIX=	-canna

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Lightweight Emacs-clone with Japanese and Canna support

MASTERDIR=	${.CURDIR}/../ng

DESCR=		${.CURDIR}/pkg-descr

WITH_CANNA=	yes

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
