# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-Data-HexDump/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Data-HexDump
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple hexadecimal dumper

USES=		perl5
USE_PERL5=	configure

MAN3=		Data::HexDump.3

NO_STAGE=	yes
.include <bsd.port.mk>
