
PORTNAME=	dfly-nrelease-ports
PORTVERSION=	0.1a
CATEGORIES=	misc

MAINTAINER=	zrj@ef.irc
COMMENT=	nrelease complete distribution metaport

USES=		metaport

RUN_DEPENDS+=	git>0:devel/git \
		bind-tools>0:dns/bind-tools \
		isc-dhcp44-server>0:net/isc-dhcp44-server \
		cdrtools>0:sysutils/cdrtools

.include <bsd.port.mk>
