# $FreeBSD: devel/hs-List/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	List
PORTVERSION=	0.5.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	List monad transformer and class

LICENSE=	BSD

USE_CABAL=	transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
