# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-Commands-Guarded/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Commands-Guarded
PORTVERSION=	1.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Deterministic guarded commands for Perl

USES=		perl5
USE_PERL5=	configure

MAN3=	Commands::Guarded.3

.include <bsd.port.mk>
