# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: devel/p5-Commands-Guarded/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Commands-Guarded
PORTVERSION=	1.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Deterministic guarded commands for Perl

USES=		perl5
USE_PERL5=	configure

MAN3=	Commands::Guarded.3

NO_STAGE=	yes
.include <bsd.port.mk>
