# New ports collection makefile for:	devel/p5-Commands-Guarded
# Date created:				19 November 2004
# Whom:					Anton Berezin <tobez@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Commands-Guarded/Makefile,v 1.5 2012/11/17 05:56:08 svnexp Exp $
#

PORTNAME=	Commands-Guarded
PORTVERSION=	1.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Deterministic guarded commands for Perl

PERL_CONFIGURE=	yes

MAN3=	Commands::Guarded.3

.include <bsd.port.mk>
