# Created by: Charlie & <root@meatwad.mouf.net>
# $FreeBSD: devel/rubygem-bacon/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	bacon
PORTVERSION=	1.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Bacon is a small RSpec clone

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/bacon

NO_STAGE=	yes
.include <bsd.port.mk>
