# New ports collection makefile for:	rubygem-bacon
# Date created:		2012-06-04
# Whom:			Charlie & <root@meatwad.mouf.net>
#
# $FreeBSD: devel/rubygem-bacon/Makefile 310891 2013-01-23 20:05:26Z swills $
#

PORTNAME=	bacon
PORTVERSION=	1.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Bacon is a small RSpec clone

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/bacon

.include <bsd.port.mk>
