# New ports collection makefile for:	syck
# Date created:			2 December 2004
# Whom:				dd
#
# $FreeBSD: ports/textproc/syck/Makefile,v 1.11 2012/11/17 06:02:22 svnexp Exp $
#

PORTNAME=	syck
PORTVERSION=	0.70
CATEGORIES=	textproc devel
MASTER_SITES=	http://cloud.github.com/downloads/indeyets/syck/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A library for reading and writing YAML 1.0

GNU_CONFIGURE=	yes
USE_BISON=	build
CFLAGS+=	-fPIC
MAKE_JOBS_UNSAFE=	yes

.include <bsd.port.mk>
