# $FreeBSD: textproc/hs-regex-base/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	regex-base
PORTVERSION=	0.93.2
PORTREVISION=	9
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Interface API for regex-posix,pcre,parsec,tdfa,dfa

LICENSE=	BSD

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
