# $FreeBSD: www/twiki-TWikiUserMappingContrib/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	TWikiUserMappingContrib
SVNREV=		17569

COMMENT=	Traditional topic-based user mapping and management

NO_STAGE=	yes
.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
