#!/bin/sh
#
# $FreeBSD: security/pear-Crypt_CBC/pkg-deinstall 300897 2012-07-14 14:29:18Z beat $
#
# Remove package declaration from PEAR's registry.

if [ x$2 != xDEINSTALL ]; then
    exit
fi
PKG_NAME=${1%%-[0-9._]*}
PACKAGE=$(echo $PKG_NAME | sed 's/pear-//')

${PKG_PREFIX}/bin/pear uninstall -r ${PACKAGE} || true
