# Ports collection makefile for:	rubygem-file-tail
# Date created:				06 October 2009
# Whom:					Eric Freeman <freebsdports@chillibear.com>
#
# $FreeBSD: ports/devel/rubygem-file-tail/Makefile,v 1.8 2012/11/17 05:56:59 svnexp Exp $
#

PORTNAME=	file-tail
PORTVERSION=	1.0.11
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	freebsdports@chillibear.com
COMMENT=	This is a small Ruby library that allows Ruby to 'tail' files

RUN_DEPENDS=	rubygem-tins>=0.5.0:${PORTSDIR}/devel/rubygem-tins

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
