# $FreeBSD: textproc/hs-regex-tdfa/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	regex-tdfa
PORTVERSION=	1.1.8
PORTREVISION=	1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Replaces/Enhances Text.Regex

USE_CABAL=	mtl parsec regex-base>=0.93.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
