# $FreeBSD: textproc/hs-regex-tdfa/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	regex-tdfa
PORTVERSION=	1.1.8
PORTREVISION=	3
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Replaces/Enhances Text.Regex

USE_CABAL=	mtl parsec regex-base>=0.93.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
