# Created by: clsung@dragon2.net
# $FreeBSD: devel/p5-Object-MultiType/Makefile 332127 2013-10-30 15:19:23Z vanilla $

PORTNAME=	Object-MultiType
PORTVERSION=	0.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl Objects as Hash, Array, and Scalar at the same time

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
