# Created by: William Grzybowski <william88@gmail.com>
# $FreeBSD: devel/py-billiard/Makefile 322501 2013-07-08 12:30:27Z wg $

PORTNAME=	billiard
PORTVERSION=	2.7.3.31
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Python multiprocessing fork with improvements and bugfixes

LICENSE=	BSD

USE_PYTHON=	-2.7
USE_PYDISTUTILS=	easy_install
PYEASYINSTALL_ARCHDEP=	yes

.include <bsd.port.mk>
