# Created by: roam@orbitel.bg
# $FreeBSD: net/tcpcat/Makefile 328226 2013-09-25 00:54:08Z bdrewery $

PORTNAME=	tcpcat
PORTVERSION=	1.2.0
CATEGORIES=	net
MASTER_SITES=	http://ess4.engr.uvic.ca/proj/tcpcat/ \
		${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	roam/net

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A simple utility for sending/receiving data over a TCP or a Unix-domain socket

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/tcpcat

.include <bsd.port.mk>
