# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: devel/p5-Tree-R/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Tree-R
PORTVERSION=	0.06
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	amdmi3@FreeBSD.org
COMMENT=	Perl extension for the Rtree data structure and algorithms

USES=		perl5
USE_PERL5=	configure

MAN3=		Tree::R.3

NO_STAGE=	yes
.include <bsd.port.mk>
