# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: ports/math/R-cran-LearnBayes/Makefile,v 1.1 2012/11/23 02:46:05 svnexp Exp $

PORTNAME=	LearnBayes
PORTVERSION=	2.12
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Functions for Learning Bayesian Inference

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
