# $FreeBSD: archivers/hs-zlib-enum/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	zlib-enum
PORTVERSION=	0.2.3
PORTREVISION=	2
CATEGORIES=	archivers haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Enumerator interface for zlib compression

LICENSE=	MIT

USE_CABAL=	enumerator transformers>=0.2 zlib-bindings

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
