# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: hebrew/aspell/Makefile 332672 2013-11-04 08:30:37Z bapt $

PORTNAME=	aspell
DISTVERSION=	6-he-1.0-0
PORTREVISION=	1
PORTEPOCH=	2
CATEGORIES=	hebrew textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Hebrew dictionaries

DICT=	 	he

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
