# $FreeBSD: audio/gstreamer1-plugins-sidplay/Makefile 332416 2013-11-01 22:14:07Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer Commodore SID decoder plugin

GST_PLUGIN=	sidplay
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
