# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: science/R-cran-epicalc/Makefile 333659 2013-11-13 08:19:34Z bf $

PORTNAME=	epicalc
PORTVERSION=	2.15.1.0
PORTREVISION=	5
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Epidemiological calculator

USE_R_MOD=		yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
