# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: ports/science/R-cran-epicalc/Makefile,v 1.11 2012/11/17 06:00:56 svnexp Exp $

PORTNAME=	epicalc
PORTVERSION=	2.15.1.0
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Epidemiological calculator

USE_R_MOD=		yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
