# New ports collection makefile for:	i386-rtems-gdb
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/i386-rtems-gdb/Makefile,v 1.32 2012/11/17 05:55:50 svnexp Exp $
#

MAINTAINER=	ports@FreeBSD.org

TGTARCH=	i386
TGTABI=		rtems

WITH_RTEMS_PATCHES=	yes

MASTERDIR=	${.CURDIR}/../cross-gdb
.include "${MASTERDIR}/Makefile"
