# New ports collection makefile for:	php52-pdo_firebird
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: databases/php52-pdo_firebird/Makefile 315592 2013-03-30 04:37:26Z acm $
#

PORTREVISION=	1
CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-pdo_firebird

.include "${MASTERDIR}/Makefile"
