# New ports collection makefile for:	php52-pdo_firebird
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: databases/php52-pdo_firebird/Makefile 323158 2013-07-17 10:21:39Z erwin $
#

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-pdo_firebird

.include "${MASTERDIR}/Makefile"
