# $FreeBSD: x11-drivers/xf86-video-tdfx/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xf86-video-tdfx
PORTVERSION=	1.4.5
PORTREVISION=	3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org tdfx display driver

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto glproto

.include <bsd.port.mk>
