# $FreeBSD: x11-drivers/xf86-video-tdfx/Makefile 327779 2013-09-20 23:48:39Z bapt $

PORTNAME=	xf86-video-tdfx
PORTVERSION=	1.4.5
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org tdfx display driver

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto glproto
MAN4=		tdfx.4x

NO_STAGE=	yes
.include <bsd.port.mk>
