# Created by: Jean-Yves Lefort <jylefort@FreeBSD.org>
# $FreeBSD: databases/libgda3-reference/Makefile 327717 2013-09-20 16:13:47Z bapt $

PORTREVISION=	1

REFERENCE_SRC=	${WRKSRC}/doc/C

NO_STAGE=	yes
.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
