# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: net/gstreamer-plugins-libmms/Makefile 332416 2013-11-01 22:14:07Z kwm $
#   $MCom: ports/net/gstreamer-plugins-libmms/Makefile,v 1.3 2008/03/19 14:05:38 ahze Exp $

PORTREVISION=	0
CATEGORIES=	net

COMMENT=	Gstreamer mms:// and mmsh:// plugin

GST_PLUGIN=	libmms

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
