# Created by: Jaap Boender <jaapb@kerguelen.org>
# $FreeBSD: devel/ocaml-deriving-ocsigen/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	deriving-ocsigen
PORTVERSION=	0.3c
CATEGORIES=	devel www
MASTER_SITES=	http://ocsigen.org/download/
PKGNAMEPREFIX=	ocaml-

MAINTAINER=	jaapb@kerguelen.org
COMMENT=	Function derivation library

USE_OCAML=		yes
USE_OCAML_FINDLIB=	yes
USE_OCAMLFIND_PLIST=	yes
USE_OCAML_LDCONFIG=	yes

USE_GMAKE=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
