# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: devel/p5-Test-Object/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Test-Object
PORTVERSION=	0.07
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ADAMK
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Thoroughly testing objects via registered handlers

USES=		perl5
USE_PERL5=	configure

MAN3=		Test::Object.3

NO_STAGE=	yes
.include <bsd.port.mk>
