# $FreeBSD: x11-toolkits/gstreamer1-plugins-pango/Makefile 327785 2013-09-20 23:57:47Z bapt $

PORTREVISION=	0
CATEGORIES=	x11-toolkits

COMMENT=	Gstreamer pango textoverlay plugin

GST_PLUGIN=	pango
DIST=		base

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
