# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: textproc/p5-Pod-Stripper/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	Pod-Stripper
PORTVERSION=	0.22
PORTREVISION=	4
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Strip all pod, and output what's left

USES=		perl5
USE_PERL5=	configure
USE_DOS2UNIX=	yes

MAN1=		podstrip.1
MAN3=		Pod::Stripper.3

NO_STAGE=	yes
.include <bsd.port.mk>
