# Created by: Yoshihiko Sarumaru <mistral@imasy.or.jp>
# $FreeBSD: net/p5-Net-Wake/Makefile 338810 2014-01-05 17:53:15Z az $

PORTNAME=	Net-Wake
PORTVERSION=	0.02
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sarumaru@jp.FreeBSD.org
COMMENT=	Send Wake On Lan (WOL) packets to power on computers

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
