# Created by: Rui Lopes (<rgl ruilopes com>)
# $FreeBSD: devel/rubygem-gem_plugin/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	gem_plugin
PORTVERSION=	0.2.3
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Gem Based Plugin System

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/gpgen

NO_STAGE=	yes
.include <bsd.port.mk>
