# $FreeBSD: ports/japanese/calligra-l10n/Makefile,v 1.4 2013/02/05 12:23:34 svnexp Exp $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
CATEGORIES=	japanese editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Japanese messages and documentation for Calligra

CALLIGRA_L10N=	ja

.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
