# Created by: Alex Keda <admin@lissyara.su>
# $FreeBSD: devel/php52-sysvmsg/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-sysvmsg

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
