# $FreeBSD: devel/p5-File-LibMagic/Makefile 338909 2014-01-06 17:28:12Z az $

PORTNAME=	File-LibMagic
PORTVERSION=	0.96
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
EXTRACT_SUFX=	.tgz

MAINTAINER=	tj@FreeBSD.org
COMMENT=	Nice wrapper for libmagic

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
