# Created by: imp
# $FreeBSD: games/seahaven/Makefile 327730 2013-09-20 17:36:33Z bapt $

PORTNAME=	seahaven
PORTVERSION=	1.60
CATEGORIES=	games
MASTER_SITES=	http://seahaven.sourceforge.net/
EXTRACT_SUFX=	.tgz

MAINTAINER=	imp@FreeBSD.org
COMMENT=	The classic, lightweight version of Seahaven Towers

GNU_CONFIGURE=	yes
USE_XORG=	x11 xext xft
MAN6?=		seahaven.6
PLIST_FILES=	bin/seahaven

NO_STAGE=	yes
.include <bsd.port.mk>
