--- ntp.toml.orig	2023-07-28 10:31:31 UTC
+++ ntp.toml
@@ -18,7 +18,7 @@ max-peers = 4
 #max-peers = 4
 
 [observe]
-path = "/run/ntpd-rs/observe"
+path = "/var/run/ntpd-rs/observe"
 
 # Below are configured various thresholds beyond which ntpd-rs will not
 # change the system clock. CHANGE THESE TO MATCH YOUR SECURITY NEEDS!
