--- test-keys/unsafe.nts.server.toml.orig	2023-07-28 10:31:19 UTC
+++ test-keys/unsafe.nts.server.toml
@@ -20,7 +20,7 @@ startup-panic-threshold = { forward = 0, backward = 18
 startup-panic-threshold = { forward = 0, backward = 1800 }
 
 [observe]
-path = "/run/ntpd-rs/observe"
+path = "/var/run/ntpd-rs/observe"
 
 # to function as an NTS server, we must also provide key exchange
 # uses an unsecure certificate chain!
