--- ntp.server.toml.orig	2023-07-28 10:30:50 UTC
+++ ntp.server.toml
@@ -18,7 +18,7 @@ max-peers = 4
 #max-peers = 4
 
 [observe]
-path = "/run/ntpd-rs/observe"
+path = "/var/run/ntpd-rs/observe"
 
 # Serve NTP on any interface (requires permissions to use udp port 123)
 [[server]]
