# Created by: KIMURA Yasuhiro <yasu@utahime.org>
# $FreeBSD: mail/c-sig-emacs21/Makefile 340722 2014-01-22 17:00:46Z mat $

MASTERDIR=	${.CURDIR}/../c-sig

USE_EMACS=	yes
EMACS_PORT_NAME=	emacs21

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
