# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: devel/py-mox/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	mox
PORTVERSION=	0.5.3
CATEGORIES=	devel python
MASTER_SITES=	GOOGLE_CODE
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	Mock object framework for Python

PROJECTHOST=	pymox
USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
