# $FreeBSD: net/rubygem-packetfu/Makefile 327755 2013-09-20 22:10:23Z bapt $

PORTNAME=	packetfu
PORTVERSION=	1.1.9
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Mid-level packet manipulation library for Ruby

LICENSE=	BSD

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=yes

NO_STAGE=	yes
.include <bsd.port.mk>
