# Created by:			Yuri Pankov <yuri.pankov@gmail.com>
# $FreeBSD: textproc/libunibreak/Makefile 327227 2013-09-14 06:56:19Z fluffy $
#

PORTNAME=	libunibreak
PORTVERSION=	1.0
PORTEPOCH=	1
CATEGORIES=	textproc
MASTER_SITES=	SF/vimgadgets/${PORTNAME}/${PORTVERSION}

MAINTAINER=	fluffy@FreeBSD.org
COMMENT=	Implementation of the line and word breaking algorithm for Unicode

GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes
USES=		pathfix
.include <bsd.port.mk>
