# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: audio/gstreamer-plugins-jack/Makefile 340722 2014-01-22 17:00:46Z mat $
#   $MCom: ports/audio/gstreamer-plugins-jack/Makefile,v 1.5 2008/03/19 14:05:29 ahze Exp $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer low-latency audio server plugin

GST_PLUGIN=	jack

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
