# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: audio/gstreamer-plugins-jack/Makefile 332416 2013-11-01 22:14:07Z kwm $
#   $MCom: ports/audio/gstreamer-plugins-jack/Makefile,v 1.5 2008/03/19 14:05:29 ahze Exp $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer low-latency audio server plugin

GST_PLUGIN=	jack

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
