# New ports collection makefile for:	p5-Set-IntSpan
# Date created:		February 7, 1998
# Whom:			Don Croyle <croyle@gelemna.org>
#
# $FreeBSD: ports/math/p5-Set-IntSpan/Makefile,v 1.20 2012/11/17 05:59:27 svnexp Exp $
#

PORTNAME=	Set-IntSpan
PORTVERSION=	1.16
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Manages sets of integers

PERL_CONFIGURE=	yes

MAN3=		Set::IntSpan.3

.include <bsd.port.mk>
