# $FreeBSD: math/hs-ieee754/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	ieee754
PORTVERSION=	0.7.3
PORTREVISION=	6
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities for dealing with IEEE floating point numbers

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
