# Created by: Jim Pirzyk <pirzyk@FreeBSD.org>
# $FreeBSD: security/pam_per_user/Makefile 342161 2014-02-01 14:54:06Z miwi $

PORTNAME=	pam_per_user
PORTVERSION=	0.4
PORTREVISION=	1
CATEGORIES=	security
MASTER_SITES=	ftp://ftp.feep.net/pub/software/PAM/pam_per_user/

MAINTAINER=	pirzyk@FreeBSD.org
COMMENT=	PAM module for per-user authentication

USE_AUTOTOOLS=	libtool

.include <bsd.port.mk>
