# $FreeBSD: devel/rubygem-highline/Makefile 335244 2013-11-29 23:00:02Z sunpoet $

PORTNAME=	highline
PORTVERSION=	1.6.20
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	High-level IO library for command-line interfaces

LICENSE=	GPLv2

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
