# Created by: Timur I. Bakeyev <bat@cpan.org>
# $FreeBSD: ports/databases/p5-Relations/Makefile,v 1.5 2012/11/17 05:55:16 svnexp Exp $

PORTNAME=	Relations
PORTVERSION=	0.95
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	5u623l20@gmail.com
COMMENT=	Functions to Use with Databases and Queries

PERL_CONFIGURE=	yes

MAN3=		Relations.3

.include <bsd.port.mk>
