# Created by: Timur I. Bakeyev <bat@cpan.org>
# $FreeBSD: databases/p5-Relations/Makefile 341764 2014-01-29 17:31:52Z az $

PORTNAME=	Relations
PORTVERSION=	0.95
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	5u623l20@gmail.com
COMMENT=	Functions to Use with Databases and Queries

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
