# $FreeBSD: textproc/tinyxml/files/Makefile 300897 2012-07-14 14:29:18Z beat $
# $Id$

LIB = 	tinyxml
SRCS=	tinystr.cpp tinyxmlerror.cpp tinyxml.cpp tinyxmlparser.cpp
INCS=	tinyxml.h tinystr.h

SHLIB_MAJOR=	%%SHLIB_MAJOR%%

LIBDIR=		${PREFIX}/lib
INCLUDEDIR=	${PREFIX}/include

.include <bsd.lib.mk>
