# $FreeBSD: audio/p5-Audio-Ecasound/Makefile 326958 2013-09-11 09:54:08Z az $

PORTNAME=	Audio-Ecasound
PORTVERSION=	1.01
CATEGORIES=	audio perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for ecasound sampler, recorder, fx-processor

BUILD_DEPENDS=	libecasoundc-config:${PORTSDIR}/audio/ecasound

USES=		perl5
USE_PERL5=	configure

MAN3=	Audio::Ecasound.3

.include <bsd.port.mk>
