# $FreeBSD: x11-fonts/xfontsel/Makefile 327781 2013-09-20 23:51:14Z bapt $

PORTNAME=	xfontsel
PORTVERSION=	1.0.5
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Point and click selection of X11 font names

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xfontsel.1

NO_STAGE=	yes
.include <bsd.port.mk>
