# Ports collection makefile for:  pear-Horde_Date
# Date created:			  6 July 2011
# Whom:				  Martin Matuska <mm@FreeBSD.org>
#
# $FreeBSD: devel/pear-Horde_Token/Makefile 317889 2013-05-11 15:37:47Z mm $

PORTNAME=	Horde_Token
PORTVERSION=	2.0.4
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Token API

USE_HORDE_RUN=	Horde_Exception \
		Horde_Translation \
		Horde_Url \
		Horde_Util
USE_PHP=	hash

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
