# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: textproc/p5-YAML-Syck/Makefile 318660 2013-05-21 08:46:11Z tobez $

PORTNAME=	YAML-Syck
PORTVERSION=	1.27
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Fast, lightweight YAML and JSON loader and dumper

PERL_CONFIGURE=	yes
CONFIGURE_ARGS+=	< /dev/null

MAN3=		JSON::Syck.3 YAML::Syck.3

.include <bsd.port.mk>
