# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: textproc/p5-YAML-Syck/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	YAML-Syck
PORTVERSION=	1.27
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Fast, lightweight YAML and JSON loader and dumper

USES=		perl5
USE_PERL5=	configure
CONFIGURE_ARGS+=	< /dev/null

MAN3=		JSON::Syck.3 YAML::Syck.3

.include <bsd.port.mk>
