# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD: math/R-cran-stabledist/Makefile 319316 2013-05-28 15:15:05Z bf $

PORTNAME=	stabledist
DISTVERSION=	0.6-5
PORTREVISION=	3
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	Stable Distribution Functions

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
