# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD: math/R-cran-stabledist/Makefile 327746 2013-09-20 20:55:04Z bapt $

PORTNAME=	stabledist
DISTVERSION=	0.6-6
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	Stable Distribution Functions

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
