# New ports collection makefile for:	devel/p5-Getopt-Long
# Date created:				31 May 2001
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/devel/p5-Getopt-Long/Makefile,v 1.14 2012/11/17 05:56:17 svnexp Exp $
#

PORTNAME=	Getopt-Long
PORTVERSION=	2.38
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl module for extended processing of command line options

PERL_CONFIGURE=	yes

MAN3=		Getopt::Long.3

.include <bsd.port.mk>
