# $FreeBSD: audio/gstreamer1-plugins-speex/Makefile 332416 2013-11-01 22:14:07Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer speex voice plugin

GST_PLUGIN=	speex
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
