# Ports collection makefile for:	p5-Task-Weaken
# Date created:				Apr 5, 2007
# Whom:					lbr@freebsd.org
#
# $FreeBSD: ports/devel/p5-Task-Weaken/Makefile,v 1.10 2012/11/17 05:56:31 svnexp Exp $
#

PORTNAME=	Task-Weaken
PORTVERSION=	1.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Ensure that a platform has weaken support

PERL_CONFIGURE=	yes

MAN3=	Task::Weaken.3

.include <bsd.port.mk>
