# $FreeBSD: x11-drivers/xf86-video-cirrus/Makefile 336621 2013-12-16 11:11:09Z zeising $

PORTNAME=	xf86-video-cirrus
PORTVERSION=	1.5.2
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org cirrus display driver

XORG_CAT=	driver

.include <bsd.port.mk>
