# New ports collection makefile for:	twiki-NewUserPlugin
# Date created:		9 Jan 2009
# Whom:			Sergey Skvortsov <skv@protey.ru>
#
# $FreeBSD: ports/www/twiki-NewUserPlugin/Makefile,v 1.3 2012/11/17 06:03:09 svnexp Exp $
#

PORTNAME=	NewUserPlugin
SVNREV=		17515
MASTER_SITES=	http://protey.ru/freebsd/distfiles/ \
		${MASTER_SITE_LOCAL:S!$!skv/!}

MAINTAINER=	skv@FreeBSD.org
COMMENT=	Create user's topic for externally authenticated users

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
