LIB_DEPENDS+=	libexpat.so:textproc/expat2
LIB_DEPENDS+=	libfreetype.so:print/freetype2
LIB_DEPENDS+=	libfontconfig.so:x11-fonts/fontconfig

# /usr/local/include/poppler/PDFDoc.h:295:153: error: 'nullptr' was not declared
USE_CXXSTD=	c++11
