# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: textproc/ta-aspell/Makefile 332672 2013-11-04 08:30:37Z bapt $

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-ta-20040424-1
PORTREVISION=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Tamil dictionary

DICT=	 	ta

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
