# Created by: Palle Girgensohn <girgen@partitur.se>
# $FreeBSD: databases/postgresql92-pltcl/Makefile 327717 2013-09-20 16:13:47Z bapt $

WANT_PGSQL_VER=	92

NO_STAGE=	yes
.include "${.CURDIR}/../postgresql90-pltcl/Makefile"
