# $FreeBSD: www/py-plone.app.locales/Makefile 327956 2013-09-23 09:18:55Z rm $

PORTNAME=	plone.app.locales
PORTVERSION=	4.3.2
CATEGORIES=	www python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Translation files for Plone

LICENSE=	GPLv2

DIST_SUBDIR=	zope
USE_PYTHON=	-2.7
USE_PYDISTUTILS=easy_install
USE_ZIP=	yes

NO_STAGE=	yes

.include <bsd.port.mk>
