# New ports collection makefile for:	Text::FormatTable
# Date created:				24 Jan 2002
# Whom:					Seamus Venasse <svenasse@polaris.ca>
#
# $FreeBSD: ports/textproc/p5-Text-FormatTable/Makefile,v 1.10 2012/11/17 06:02:10 svnexp Exp $
#

PORTNAME=		Text-FormatTable
PORTVERSION=		1.03
CATEGORIES=		textproc perl5
MASTER_SITES=		CPAN
PKGNAMEPREFIX=		p5-

MAINTAINER=		perl@FreeBSD.org
COMMENT=	Renders simple tables as text

PERL_CONFIGURE=		yes

MAN3=			Text::FormatTable.3

.include <bsd.port.mk>
