# $FreeBSD: sysutils/hs-cpu/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	cpu
PORTVERSION=	0.1.1
PORTREVISION=	3
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cpu information and properties helpers

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
