# $FreeBSD: sysutils/hs-cpu/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	cpu
PORTVERSION=	0.1.1
PORTREVISION=	4
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cpu information and properties helpers

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
