# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: devel/pear-Symfony_Component_Console/Makefile 325537 2013-08-28 14:44:55Z wg $

PORTNAME=	Console
PORTVERSION=	2.3.4
CATEGORIES=	devel pear
PKGNAMEPREFIX=	pear-Symfony_Component_

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Symfony2 Console Component

LICENSE=	MIT

IGNORE_WITH_PHP=52

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-symfony2/bsd.symfony2.mk"
.include <bsd.port.post.mk>
