# Ports collection makefile for:	getopt
# Date created:				Tue 16 Mar 2010
# Whom:					Alexey V. Degtyarev <alexey@renatasystems.org>
#
# $FreeBSD: ports/devel/rubygem-getopt/Makefile,v 1.4 2012/11/17 05:56:59 svnexp Exp $

PORTNAME=	getopt
PORTVERSION=	1.4.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	alexey@renatasystems.org
COMMENT=	Command line parsing with Ruby

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
