--- cmake/Helper.cmake.orig	2020-01-15 15:59:29 UTC
+++ cmake/Helper.cmake
@@ -278,7 +278,7 @@ FUNCTION(GET_ANDROID_TOOLCHAIN_VARS _pre
 ENDFUNCTION()
 
 
-IF("${CMAKE_SYSTEM_NAME}" MATCHES "BSD")
+IF("${CMAKE_SYSTEM_NAME}" MATCHES "BSD" OR "${CMAKE_SYSTEM_NAME}" MATCHES "DragonFly")
 	SET(BSD true)
 ENDIF()
 
