# New ports collection makefile for:	fixesproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: x11/fixesproto/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	fixesproto
PORTVERSION=	5.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Fixes extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
