# New ports collection makefile for:	fixesproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/fixesproto/Makefile,v 1.5 2012/11/17 06:03:15 svnexp Exp $
#

PORTNAME=	fixesproto
PORTVERSION=	5.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Fixes extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
