# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: x11/fixesproto/Makefile 328096 2013-09-24 06:24:17Z bapt $

PORTNAME=	fixesproto
PORTVERSION=	5.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Fixes extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
