# New ports collection makefile for:	enscript (a4)
# Date created:			24 Jul, 1997
# Whom:				kline
#
# $FreeBSD: ports/print/enscript-a4/Makefile,v 1.5 2012/11/17 06:00:49 svnexp Exp $
#

CONFLICTS=	enscript-letter-* enscript-letterdj-*

PAPERSIZE=	a4
PS=		A4

MASTERDIR=	${.CURDIR}/../enscript-letter

.include "${MASTERDIR}/Makefile"
