# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: sysutils/p5-Proc-PidUtil/Makefile 338851 2014-01-06 09:44:19Z az $

PORTNAME=	Proc-PidUtil
PORTVERSION=	0.08
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	PID file management utilities

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
