# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: devel/py-EnthoughtBase/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	EnthoughtBase
PORTVERSION=	3.1.0
CATEGORIES=	devel python
MASTER_SITES=	http://enthought.com/repo/ets/ \
		CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Core Packages for the Enthought Tool Suite

USE_PYTHON=		yes
USE_PYDISTUTILS=	easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
