# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: ports/textproc/p5-Text-Filter/Makefile,v 1.11 2013/01/28 11:07:35 svnexp Exp $

PORTNAME=	Text-Filter
PORTVERSION=	1.10
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Base class for objects that can read and write text lines

PERL_CONFIGURE=	yes

MAN3=		Text::Filter.3 Text::Filter::Cooked.3

.include <bsd.port.mk>
