#until update to 6.2.0
pre-patch:
	${REINPLACE_CMD} -e 's/_HAS_CPP_DEMANGLE=1/_HAS_C--_DEMANGLE=0/g'	\
			 -e 's/execinfo.h/execinfo.h__not/g'			\
		${WRKSRC}/Utilities/KWSys/vtksys/CMakeLists.txt
	${REINPLACE_CMD} -e 's|#define USE_STAT_64|//#define USE_STAT_64|g'	\
		${WRKSRC}/IO/LSDyna/private/LSDynaFamily.cxx
