# Created by: Emanuel Haupt <ehaupt@FreeBSD.org>
# $FreeBSD: sysutils/p5-Dir-Purge/Makefile 326572 2013-09-07 06:13:27Z az $

PORTNAME=	Dir-Purge
PORTVERSION=	1.02
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Purge directories to a given number of files

USES=		perl5
USE_PERL5=	configure

MAN3=		Dir::Purge.3

.include <bsd.port.mk>
