# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: devel/hs-arrows/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	arrows
PORTVERSION=	0.4.4.1
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell arrow classes and transformers

LICENSE=	BSD

USE_CABAL=	Stream

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
