# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: sysutils/rubygem-sys-admin/Makefile 323794 2013-07-27 16:06:01Z swills $

PORTNAME=	sys-admin
PORTVERSION=	1.6.0
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Unified, cross platform replacement for the Etc module

RUN_DEPENDS=	rubygem-ffi>=1.0.0:${PORTSDIR}/devel/rubygem-ffi

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
