# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: sysutils/rubygem-sys-admin/Makefile 327772 2013-09-20 23:05:58Z bapt $

PORTNAME=	sys-admin
PORTVERSION=	1.6.0
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Unified, cross platform replacement for the Etc module

RUN_DEPENDS=	rubygem-ffi>=1.0.0:${PORTSDIR}/devel/rubygem-ffi

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
