# $FreeBSD: security/pear-Horde_Auth/Makefile 326198 2013-09-03 18:43:02Z mm $

PORTNAME=	Horde_Auth
PORTVERSION=	2.1.0
CATEGORIES=	security www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Authentication API

USE_HORDE_RUN=	Horde_Exception Horde_Util
USE_PHP=	hash

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
