# $FreeBSD: ports/polish/calligra-l10n/Makefile,v 1.39 2012/11/17 06:00:44 svnexp Exp $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
CATEGORIES?=	polish editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Polish messages and documentation for Calligra

CALLIGRA_L10N=	pl

.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
