# New ports collection makefile for:   c2ps (a4)
# Date created:        19 March 1997
# Whom:                Matthew Hunt <mph@pobox.com>
#
# $FreeBSD: ports/print/c2ps-a4/Makefile,v 1.4 2012/11/17 06:00:48 svnexp Exp $
#

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../c2ps-letter

.include "${MASTERDIR}/Makefile"
