--- cargo-crates/rug-1.17.0/Cargo.toml.orig	2022-11-10 13:39:30 UTC
+++ cargo-crates/rug-1.17.0/Cargo.toml
@@ -42,6 +42,7 @@ version = "1.1"
 version = "~1.4"
 optional = true
 default-features = false
+features = [ "use-system-libs" ]
 
 [dependencies.libc]
 version = "0.2.44"
