# Created by: will
# $FreeBSD: sysutils/p5-Unix-ConfigFile/Makefile 332957 2013-11-06 08:54:17Z vanilla $

PORTNAME=	Unix-ConfigFile
PORTVERSION=	0.06
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl modules that provides a simple interface to reading /etc files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
