# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: converters/p5-Encode-IMAPUTF7/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Encode-IMAPUTF7
PORTVERSION=	1.05
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Modification of UTF-7 encoding for IMAP

BUILD_DEPENDS=	p5-Test-NoWarnings>=0:${PORTSDIR}/devel/p5-Test-NoWarnings
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

MAN3=		Encode::IMAPUTF7.3

.include <bsd.port.mk>
