# Created by: Kai Wang <kaiw27@gmail.com>
# $FreeBSD: devel/hs-BNFC/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	BNFC
PORTVERSION=	2.6.0.3
PORTREVISION=	4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Compiler front-end generator

LICENSE=	GPLv2

USE_CABAL=	mtl

EXECUTABLE=	bnfc

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
