# Created by: Kai Wang <kaiw27@gmail.com>
# $FreeBSD: devel/hs-BNFC/Makefile 315636 2013-03-31 13:43:10Z pgj $

PORTNAME=	BNFC
PORTVERSION=	2.6.0.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Compiler front-end generator

LICENSE=	GPLv2

USE_CABAL=	mtl

EXECUTABLE=	bnfc

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
