# $FreeBSD: shells/nologinmsg/files/Makefile 340722 2014-01-22 17:00:46Z mat $
PROG=	nologinmsg
SRCS=	nologinmsg.c
BINDIR=	${PREFIX}/bin
MANDIR=	${PREFIX}/man/man
MAN8=	nologinmsg.8

CFLAGS+=	-g

.include <bsd.prog.mk>
