# Created by: Tom Judge <tj@FreeBSD.org>
# $FreeBSD: devel/p5-constant/Makefile 341761 2014-01-29 17:00:41Z az $

PORTNAME=	constant
PORTVERSION=	1.27
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tj@FreeBSD.org
COMMENT=	Perl pragma to declare constants

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
