# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: textproc/rubygem-markaby/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	markaby
PORTVERSION=	0.7.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	HTML Markup as Ruby

RUN_DEPENDS=	rubygem-builder>=2.0.0:${PORTSDIR}/devel/rubygem-builder

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_RAKE=	yes
RUBYGEM_AUTOPLIST=  yes

NO_STAGE=	yes
.include <bsd.port.mk>
