# New ports collection makefile for:	stardict-computer
# Date created:		2010-03-16
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD: russian/stardict-computer/Makefile 323455 2013-07-22 14:34:22Z vg $
#

PORTNAME=	stardict-computer
PORTVERSION=	2.4.2
CATEGORIES=	russian
MASTER_SITES=	http://yeelou.com/huzheng/stardict-dic/ru/
DISTNAME=	${PORTNAME}-ru-${PORTVERSION}

MAINTAINER=	vg@FreeBSD.org
COMMENT=	English-Russian Computer dictionary

.include "${.CURDIR}/../stardict-mueller7/files/Makefile.common"
.include <bsd.port.mk>
