# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: converters/p5-Convert-Binary-C/Makefile 332379 2013-11-01 14:20:56Z vanilla $

PORTNAME=	Convert-Binary-C
PORTVERSION=	0.76
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Binary Data Conversion using C Types

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

MAKE_JOBS_UNSAFE=	yes

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
