# New ports collection makefile for:	Convert-Binary-C
# Date created:	   26 May 2004
# Whom:		   Sergey Skvortsov <skv@protey.ru>
#
# $FreeBSD: ports/converters/p5-Convert-Binary-C/Makefile,v 1.24 2012/11/17 05:55:03 svnexp Exp $
#

PORTNAME=	Convert-Binary-C
PORTVERSION=	0.76
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Binary Data Conversion using C Types

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

MAKE_JOBS_UNSAFE=	yes

PERL_CONFIGURE=	yes

MAN1=		ccconfig.1
MAN3=		Convert::Binary::C.3 Convert::Binary::C::Cached.3

.include <bsd.port.mk>
