# $FreeBSD: devel/hs-profunctor-extras/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	profunctor-extras
PORTVERSION=	3.3
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Profunctor extras

LICENSE=	BSD

USE_CABAL=	comonad>=3 profunctors>=3.2 semigroupoid-extras>=3 \
		semigroupoids>=3 tagged>=0.4.4 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
