# Created by: swallace
# $FreeBSD: games/xchomp/Makefile 324744 2013-08-14 22:35:50Z ak $

PORTNAME=	xchomp
PORTVERSION=	pl1
PORTREVISION=	2
CATEGORIES=	games
MASTER_SITES=	XCONTRIB/../R5contrib

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Pac-man-like game under X11

WRKSRC=		${WRKDIR}/xchomp

USES=		imake
USE_XORG=	x11 xext

PLIST_FILES=	bin/xchomp

.include <bsd.port.mk>
