# Created by: Sergey V. Dyatko <sergey.dyatko@gmail.com>
# $FreeBSD: devel/p5-interface/Makefile 341707 2014-01-29 09:19:35Z az $

PORTNAME=	interface
PORTVERSION=	0.03
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:SWALTERS
PKGNAMEPREFIX=	p5-

MAINTAINER=	sergey.dyatko@gmail.com
COMMENT=	Simple compile time interface checking for OO Perl

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
