# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: devel/rubygem-validatable/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	validatable
PORTVERSION=	1.6.7
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Library for adding database/object validations

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_RAKE=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
