# $FreeBSD: devel/hs-MonadRandom/Makefile 327723 2013-09-20 17:04:43Z bapt $

PORTNAME=	MonadRandom
PORTVERSION=	0.1.9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Random-number generation monad

USE_CABAL=	mtl random

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
