# $FreeBSD: devel/hs-MonadRandom/Makefile 319894 2013-06-04 18:53:40Z pgj $

PORTNAME=	MonadRandom
PORTVERSION=	0.1.9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Random-number generation monad

USE_CABAL=	mtl random

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
