# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-Config-Tiny/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Config-Tiny
PORTVERSION=	2.19
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
EXTRACT_SUFX=	.tgz

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Read/Write .ini style files with as little code as possible

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		Config::Tiny.3

NO_STAGE=	yes
.include <bsd.port.mk>
