# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: sysutils/p5-Unix-Processors/Makefile 327772 2013-09-20 23:05:58Z bapt $

PORTNAME=	Unix-Processors
PORTVERSION=	2.042
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Interface to processor (CPU) information

USES=		perl5
USE_PERL5=	configure

MAN3=		Unix::Processors.3 Unix::Processors::Info.3

NO_STAGE=	yes
.include <bsd.port.mk>
