# New ports collection makefile for:	Unix-Processors
# Date created:		13 Dec 2001
# Whom:			Sergey Skvortsov <skv@protey.ru>
#
# $FreeBSD: ports/sysutils/p5-Unix-Processors/Makefile,v 1.14 2012/11/17 06:01:40 svnexp Exp $
#

PORTNAME=	Unix-Processors
PORTVERSION=	2.042
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Interface to processor (CPU) information

PERL_CONFIGURE=	yes

MAN3=		Unix::Processors.3 Unix::Processors::Info.3

.include <bsd.port.mk>
