# $FreeBSD: www/hs-http-date/Makefile 315580 2013-03-29 22:43:58Z pgj $

PORTNAME=	http-date
PORTVERSION=	0.0.4
PORTREVISION=	1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTTP Date parser/formatter

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	attoparsec

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
