# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: www/py-pywebdav/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	PyWebDAV
PORTVERSION=	0.9.8
CATEGORIES=	www net python
MASTER_SITES=	GOOGLE_CODE \
		CHEESESHOP
MASTER_SITE_SUBDIR=	source/P/PyWebDAV
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	WebDAV Library and Server for Python

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
