--- configure.cmake.orig	Fri Feb 28 15:40:08 2025
+++ configure.cmake	Fri Feb
@@ -68,7 +68,7 @@ if(Python3_EXECUTABLE)
 endif()
 
 #### Tests
-if(LINUX OR FREEBSD)
+if(LINUX OR FREEBSD OR DRAGONFLY)
    check_for_ulimit()
 endif()
 
@@ -428,7 +428,7 @@ qt_feature("webengine-system-libpci" PRIVATE
 
 qt_feature("webengine-ozone-x11" PRIVATE
     LABEL "Support GLX on qpa-xcb"
-    CONDITION LINUX OR FREEBSD
+    CONDITION LINUX OR FREEBSD OR DRAGONFLY
         AND TARGET Qt::Gui
         AND QT_FEATURE_xcb
         AND X11_FOUND
@@ -466,12 +466,12 @@ assertTargets(
 )
 add_check_for_support(
    MODULES QtWebEngine
-   CONDITION LINUX OR (WIN32 AND NOT WIN_ARM_64) OR MACOS OR FREEBSD
+   CONDITION LINUX OR (WIN32 AND NOT WIN_ARM_64) OR MACOS OR FREEBSD OR DRAGONFLY
    MESSAGE "Build can be done only on Linux, Windows or macOS."
 )
 add_check_for_support(
    MODULES QtPdf
-   CONDITION LINUX OR (WIN32 AND NOT WIN_ARM_64) OR MACOS OR IOS OR ANDROID OR FREEBSD
+   CONDITION LINUX OR (WIN32 AND NOT WIN_ARM_64) OR MACOS OR IOS OR ANDROID OR FREEBSD OR DRAGONFLY
    MESSAGE "Build can be done only on Linux, Windows, macO, iOS and Android."
 )
 if(LINUX AND CMAKE_CROSSCOMPILING)
@@ -573,6 +573,8 @@ add_check_for_support(
    CONDITION MSVC OR
        (FREEBSD AND CMAKE_CXX_COMPILER_ID STREQUAL "GNU") OR
        (FREEBSD AND CMAKE_CXX_COMPILER_ID STREQUAL "Clang") OR
+       (DRAGONFLY AND CMAKE_CXX_COMPILER_ID STREQUAL "GNU") OR
+       (DRAGONFLY AND CMAKE_CXX_COMPILER_ID STREQUAL "Clang") OR
        (MACOS AND CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
    MESSAGE
        "${CMAKE_CXX_COMPILER_ID} compiler is not supported."
@@ -583,6 +585,8 @@ add_check_for_support(
    CONDITION MSVC OR
        (FREEBSD AND CMAKE_CXX_COMPILER_ID STREQUAL "GNU") OR
        (FREEBSD AND CMAKE_CXX_COMPILER_ID STREQUAL "Clang") OR
+       (DRAGONFLY AND CMAKE_CXX_COMPILER_ID STREQUAL "GNU") OR
+       (DRAGONFLY AND CMAKE_CXX_COMPILER_ID STREQUAL "Clang") OR
        (APPLE AND CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang") OR
        (ANDROID AND CMAKE_CXX_COMPILER_ID STREQUAL "Clang") OR
        (MINGW AND CMAKE_CXX_COMPILER_ID STREQUAL "GNU") OR
