# Created by: SimaMoto,RyoTa <liangtai.s16@gmail.com>
# $FreeBSD: misc/gimp-help-en_GB/Makefile 342129 2014-02-01 12:49:26Z makc $

CATEGORIES=	misc graphics

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	The GIMP User Manual in British English

LICENSE=	GFDL

MASTERDIR=	${.CURDIR}/../gimp-help-en

DOCLANG=	en_GB

.include "${MASTERDIR}/Makefile"
