# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: audio/gstreamer-plugins-taglib/Makefile 332416 2013-11-01 22:14:07Z kwm $
#   $MCom: ports/audio/gstreamer-plugins-taglib/Makefile,v 1.3 2008/03/19 14:05:32 ahze Exp $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer taglib plugin

GST_PLUGIN=	taglib

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
