# New ports collection makefile for:	p5-String-MkPasswd
# Date created:			Fri Apr 29 10:13:10 CEST 2011
# Whom:				Frank Wall <fw@moov.de>
#
# $FreeBSD: ports/security/p5-String-MkPasswd/Makefile,v 1.3 2012/11/17 06:01:14 svnexp Exp $
#

PORTNAME=	String-MkPasswd
PORTVERSION=	0.04
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:CGRAU
PKGNAMEPREFIX=	p5-

MAINTAINER=	fw@moov.de
COMMENT=	A random password generator

PERL_CONFIGURE=	yes

MAN1=		mkpasswd.pl.1
MAN3=		String::MkPasswd.3

.include <bsd.port.mk>
