# Created by: decept
# $FreeBSD: ports/x11-themes/kde-style-comix/Makefile,v 1.22 2013/02/08 10:55:15 svnexp Exp $

PORTNAME=	comix
PORTVERSION=	1.3.8
PORTREVISION=	8
CATEGORIES=	x11-themes kde
MASTER_SITES=	http://www.kde-look.org/CONTENT/content-files/
PKGNAMEPREFIX=	kde-style-
DISTNAME=	16028-${PORTNAME}-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Flat KDE style and window decoration

USE_BZIP2=	yes
USE_GMAKE=	yes
USE_KDEBASE_VER=3
USE_AUTOTOOLS=	libtool
WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}

.include <bsd.port.mk>
