# $FreeBSD: portuguese/webalizer-pt_BR/Makefile 327763 2013-09-20 22:38:31Z bapt $

CATEGORIES=	portuguese
PKGNAMEPREFIX?=	pt_BR-

MAINTAINER=	ports@FreeBSD.org

MASTERDIR?=	${.CURDIR}/../../www/webalizer
WEBALIZER_LANG=	portuguese_brazil

NO_STAGE=	yes
.if exists(${.CURDIR}/Makefile.local)
.include "${.CURDIR}/Makefile.local"
.endif

.include "${MASTERDIR}/Makefile"
