# $FreeBSD: www/rubygem-modernizr/Makefile 332056 2013-10-30 03:03:35Z swills $

PORTNAME=	modernizr
PORTVERSION=	2.6.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Neatly packaged Modernizr JS assets

RUN_DEPENDS=	rubygem-sprockets>=2.0:${PORTSDIR}/devel/rubygem-sprockets

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes


.include <bsd.port.mk>
