# Created by: Dmitry Sivachenko <dima@Chg.RU>
# $FreeBSD: www/p5-HTML-TableLayout/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	HTML-TableLayout
PORTVERSION=	1.001008
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Layout manager for CGI-based web applications

USES=		perl5
USE_PERL5=	configure

MAN3=		HTML::TableLayout.3

NO_STAGE=	yes
.include <bsd.port.mk>
