# New ports collection makefile for:	Math-Financial
# Date created:				Wed Jan  3 11:00:59 2001
# Whom:					will
#
# $FreeBSD: ports/finance/p5-Math-Financial/Makefile,v 1.10 2012/12/11 19:59:26 svnexp Exp $
#

PORTNAME=	Math-Financial
PORTVERSION=	0.76
CATEGORIES=	finance math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl module containing common functions for loans and annuities

PERL_CONFIGURE=	yes

MAN3=		Math::Financial.3

.include <bsd.port.mk>
