# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: devel/py-qserve/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	qserve
PORTVERSION=	0.2.8
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Job queue server

USE_ZIP=	yes
USE_PYTHON=	yes
USE_PYDISTUTILS=yes

NO_STAGE=	yes
.include <bsd.port.mk>
