# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-App-Trace/Makefile 326639 2013-09-07 14:36:58Z az $

PORTNAME=	App-Trace
PORTVERSION=	0.50
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Embedded debug statements, including call/return tracing

RUN_DEPENDS=	p5-App-Options>=0:${PORTSDIR}/devel/p5-App-Options

USES=		perl5
USE_PERL5=	configure

MAN3=		App::Trace.3

.include <bsd.port.mk>
