# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: devel/pear-channel-horde/Makefile 333263 2013-11-08 21:41:53Z antoine $

PORTNAME=	horde
PORTVERSION=	20120210
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.horde.org

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
