# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: databases/rubygem-mysql/Makefile 314486 2013-03-17 20:22:40Z zi $

PORTNAME=	mysql
PORTVERSION=	2.9.1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	The MySQL API module for Ruby

USE_MYSQL=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
