# New ports collection makefile for:	p5-Mail-IMAPTalk
# Date created:				24 May 2006
# Whom:					Aaron Dalton <aaron@FreeBSD.org>
#
# $FreeBSD: ports/mail/p5-Mail-IMAPTalk/Makefile,v 1.11 2012/11/17 05:59:09 svnexp Exp $
#

PORTNAME=	Mail-IMAPTalk
PORTVERSION=	3.01
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	IMAP client interface with lots of features

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

MAKE_JOBS_SAFE=	yes
PERL_CONFIGURE=	yes

MAN3=		Mail::IMAPTalk.3

.include <bsd.port.mk>
