# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: security/rubygem-rc4/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	rc4
PORTVERSION=	0.1.5
CATEGORIES=	security rubygems
MASTER_SITES=	RG
DISTNAME=	ruby-${PORTNAME}-${PORTVERSION}

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Pure Ruby implementation of the RC4 algorithm

GEM_NAME=	${DISTNAME}
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
