# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-Params-Classify/Makefile 315509 2013-03-29 00:44:53Z eadler $

PORTNAME=	Params-Classify
PORTVERSION=	0.013
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Argument type classification

PERL_MODBUILD=	yes

MAN3=		Params::Classify.3

.include <bsd.port.mk>
