# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: www/p5-HTML-Stream/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	HTML-Stream
PORTVERSION=	1.60
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 HTML output stream class, and some markup utilities

USES=		perl5
USE_PERL5=	configure

MAN3=		HTML::Stream.3

.include <bsd.port.mk>
