# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: www/p5-HTML-TagCloud/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	HTML-TagCloud
PORTVERSION=	0.37
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	HTML::TagCloud - Generate An HTML Tag Cloud

USES=		perl5
USE_PERL5=	configure

MAN3=	HTML::TagCloud.3

.include <bsd.port.mk>
