# New ports collection makefile for:	www/p5-HTML-TagCloud
# Date created:				06 October 2005
# Whom:					Anton Berezin <tobez@FreeBSD.org>
#
# $FreeBSD: ports/www/p5-HTML-TagCloud/Makefile,v 1.8 2012/11/17 06:02:50 svnexp Exp $
#

PORTNAME=	HTML-TagCloud
PORTVERSION=	0.37
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	HTML::TagCloud - Generate An HTML Tag Cloud

PERL_CONFIGURE=	yes

MAN3=	HTML::TagCloud.3

.include <bsd.port.mk>
