# $FreeBSD: net-mgmt/p5-Net-CIDR/Makefile 326245 2013-09-04 03:27:37Z az $

PORTNAME=	Net-CIDR
PORTVERSION=	0.17
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Perl module to manipulate IPv4/IPv6 netblocks in CIDR notation

USES=		perl5
USE_PERL5=	configure

MAN3=		Net::CIDR.3

.include <bsd.port.mk>
