# New ports collection makefile for:	p5-File-MMagic-XS
# Date created:				18 Jun 2006
# Whom:					Aaron Dalton <aaron@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-File-MMagic-XS/Makefile,v 1.12 2012/12/17 15:16:54 svnexp Exp $
#

PORTNAME=	File-MMagic-XS
PORTVERSION=	0.09006
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Guess File Type With XS (a la mod_mime_magic)

MAKE_JOBS_UNSAFE=	yes
PERL_CONFIGURE=	yes

MAN3=		File::MMagic::XS.3

.include <bsd.port.mk>
