# New ports collection makefile for:	rubygem-slop
# Date created:		2012-02-08
# Whom:			Shin-ya MURAKAMI <murashin@gfd-dennou.org>
#
# $FreeBSD: ports/devel/rubygem-slop/Makefile,v 1.3 2012/11/17 05:57:01 svnexp Exp $
#

PORTNAME=	slop
PORTVERSION=	3.3.2
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A simple DSL for gathering options and parsing the command line

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
