# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: textproc/pear-Horde_Text_Filter/Makefile 334527 2013-11-21 21:55:54Z mm $

PORTNAME=	Horde_Text_Filter
PORTVERSION=	2.2.0
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Text Filter API

USE_HORDE_RUN=	Horde_Exception \
		Horde_Util

NO_STAGE=	yes
.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
