# New ports collection makefile for:  p5-SNMP-Trapinfo
# Date created:	       10 december 2009
# Whom:		       joris
#
# $FreeBSD: ports/net-mgmt/p5-SNMP-Trapinfo/Makefile,v 1.3 2012/11/17 06:00:36 svnexp Exp $
#

PORTNAME=	SNMP-Trapinfo
PORTVERSION=	1.02
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	joris.dedieu@gmail.com
COMMENT=	Process an SNMP trap with perl

PERL_CONFIGURE=	yes

MAN3=		SNMP::Trapinfo.3

.include <bsd.port.mk>
