# Created by: Cezary Morga <cm@therek.net>
# $FreeBSD: converters/p5-Format-Human-Bytes/Makefile 332379 2013-11-01 14:20:56Z vanilla $

PORTNAME=	Format-Human-Bytes
PORTVERSION=	0.06
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module to format a bytecount and make it human readable

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
