# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: devel/p5-IPC-MM/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	IPC-MM
PORTVERSION=	0.03
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl interface to Ralf Engelschall's mm library

LIB_DEPENDS=	mm.14:${PORTSDIR}/devel/mm

USES=		perl5
USE_PERL5=	configure

MAN3=		IPC::MM.3

.include <bsd.port.mk>
