# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: textproc/nn-aspell/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	${DICT}-aspell
DISTVERSION=	-nn-0.50.1-1
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Norwegian Nynorsk dictionary

DICT=	 	nn

NO_STAGE=	yes
.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
