# New ports collection makefile for:	ssid
# Date created:		2011-02-15
# Whom:			Martin Wilke <miwi@FreeBSD.org>
#
# $FreeBSD: ports/sysutils/ssid/Makefile,v 1.2 2012/11/17 06:01:46 svnexp Exp $
#

PORTNAME=	ssid
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	http://dl.suckless.org/tools/

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Simple setsid replacement

LICENSE=	MIT

PLIST_FILES=	bin/ssid

.include <bsd.port.mk>
