# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD: science/py-coards/Makefile 341150 2014-01-26 00:52:15Z koobs $

PORTNAME=	coards
PORTVERSION=	1.0.5
CATEGORIES=	science python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	xmj@chaot.net
COMMENT=	COARDS compliant time parser

LICENSE=	MIT

USE_PYTHON=		2
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
