# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD: science/py-coards/Makefile 327767 2013-09-20 22:48:30Z bapt $

PORTNAME=	coards
PORTVERSION=	1.0.5
CATEGORIES=	science python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	xmj@chaot.net
COMMENT=	COARDS compliant time parser

LICENSE=	MIT

USE_PYTHON=		2.7
USE_PYDISTUTILS=	easy_install

NO_STAGE=	yes
.include <bsd.port.mk>
