# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: devel/rubygem-active_scaffold/Makefile 314493 2013-03-17 20:56:19Z zi $

PORTNAME=	active_scaffold
PORTVERSION=	3.2.19
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A gem to handle all CRUD user interface needs

RUN_DEPENDS=	rubygem-rails>=3.1.3:${PORTSDIR}/www/rubygem-rails

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
