# $FreeBSD: textproc/php53-dom/Makefile 327773 2013-09-20 23:17:30Z bapt $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php53

PKGNAMESUFFIX=	-dom

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
