# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: graphics/php5-exif/Makefile 327733 2013-09-20 18:35:44Z bapt $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-exif

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
