# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: math/php55-bcmath/Makefile 332107 2013-10-30 13:32:02Z ale $

CATEGORIES=	math

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-bcmath

.include "${MASTERDIR}/Makefile"
