# New ports collection makefile for:    p5-User
# Date created:                         May 28th, 2002
# Whom:                                 Erwin Lansing <erwin@FreeBSD.org>
#
# $FreeBSD: ports/sysutils/p5-User/Makefile,v 1.10 2012/11/17 06:01:40 svnexp Exp $
#

PORTNAME=	User
PORTVERSION=	1.9
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	User - API for locating user information regardless of OS

PERL_CONFIGURE=	yes

MAN3=		User.3

.include <bsd.port.mk>
