# Created by: Erwin Lansing <erwin@FreeBSD.org>
# $FreeBSD: sysutils/p5-User/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	User
PORTVERSION=	1.9
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	User - API for locating user information regardless of OS

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
