# Created by: Corey Smith
# $FreeBSD: www/py-slimmer/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	slimmer
PORTVERSION=	0.1.30
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	corsmith@gmail.com
COMMENT=	A whitespace optimizer for CSS, HTML and XHTML output

USE_PYTHON=	yes
USE_PYDISTUTILS=easy_install

PLIST_FILES=	%%PYTHON_SITELIBDIR%%/%%PYEASYINSTALL_EGG%%

NO_STAGE=	yes
.include <bsd.port.mk>
