USE_XORG+=	pixman

LIB_DEPENDS+=	libpng15.so:${PORTSDIR}/graphics/png
LIB_DEPENDS+=	libfreetype.so:${PORTSDIR}/print/freetype2
LIB_DEPENDS+=	libfontconfig.so:${PORTSDIR}/x11-fonts/fontconfig
LIB_DEPENDS+=	libcairo.so:${PORTSDIR}/graphics/cairo
LIB_DEPENDS+=	libexpat.so:${PORTSDIR}/textproc/expat2
