# Created by: Edward Tomasz Napierala <trasz@FreeBSD.org>
# $FreeBSD: audio/libsmf/Makefile 338664 2014-01-04 18:22:00Z bapt $

PORTNAME=	libsmf
PORTVERSION=	1.3
CATEGORIES=	audio
MASTER_SITES=	SF

MAINTAINER=	trasz@FreeBSD.org
COMMENT=	Standard MIDI File format library

USES=	pathfix pkgconfig readline:port
USE_GNOME=	glib20
USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
