# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: graphics/p5-Image-MetaData-GQview/Makefile 326975 2013-09-11 12:59:14Z az $

PORTNAME=	Image-MetaData-GQview
PORTVERSION=	1.9
CATEGORIES=	graphics perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Perl extension for GQview image metadata

USES=		perl5
USE_PERL5=	configure

MAN3=		Image::MetaData::GQview.3

.include <bsd.port.mk>
