# Created by: jhay
# $FreeBSD: net/p5-Net-SMPP/Makefile 338810 2014-01-05 17:53:15Z az $

PORTNAME=	Net-SMPP
PORTVERSION=	1.19
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jhay@FreeBSD.org
COMMENT=	Net::SMPP - pure Perl implementation of SMPP 3.4 over TCP

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
