# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11/libxkbui/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	libxkbui
PORTVERSION=	1.0.2
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The xkbui library

XORG_CAT=	lib
USE_XORG=	x11 xt xkbfile kbproto:both
.include <bsd.port.mk>
