# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: x11/libxkbui/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	libxkbui
PORTVERSION=	1.0.2
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The xkbui library

XORG_CAT=	lib
USE_XORG=	x11 xt xkbfile kbproto:both

.include <bsd.port.mk>
