# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD: ports/math/R-cran-car/Makefile,v 1.27 2012/11/17 05:59:18 svnexp Exp $

PORTNAME=	car
DISTVERSION=	2.0-15
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	naylor.b.david@gmail.com
COMMENT=	Companion to Applied Regression for R

LICENSE=	GPLv2

USE_R_MOD=		yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
