# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD: math/R-cran-car/Makefile 329606 2013-10-06 17:32:53Z dbn $

PORTNAME=	car
DISTVERSION=	2.0-19
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	Companion to Applied Regression for R

LICENSE=	GPLv2

USE_R_MOD=		yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
