# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD: math/R-cran-car/Makefile 335044 2013-11-27 18:56:43Z dbn $

PORTNAME=	car
DISTVERSION=	2.0-19
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	Companion to Applied Regression for R

LICENSE=	GPLv2

USE_R_MOD=		yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
