# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: textproc/sk-aspell/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	${DICT}-aspell
DISTVERSION=	6-sk-2.01-2
PORTEPOCH=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Slovak dictionary

DICT=	 	sk

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
