# Created by: will
# $FreeBSD: archivers/p5-Archive-Zip/Makefile 328247 2013-09-25 03:31:19Z vanilla $

PORTNAME=	Archive-Zip
PORTVERSION=	1.30
PORTREVISION=	1
CATEGORIES=	archivers perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to create, manipulate, read, and write Zip archive files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
