# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: databases/php55-sqlite3/Makefile 327717 2013-09-20 16:13:47Z bapt $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-sqlite3

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
