# Created by: Tom Judge <tj@FreeBSD.org>
# $FreeBSD: devel/p5-Proc-BackOff/Makefile 332269 2013-10-31 17:29:55Z tj $

PORTNAME=	Proc-BackOff
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tj@FreeBSD.org
COMMENT=	Perl module that provides methods to backoff on failures

LICENSE=	ART10

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
