# Created by: Vanilla I. Shu <vanilla@FreeBSD.org>
# $FreeBSD: www/p5-CGI-FastTemplate/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	CGI-FastTemplate
PORTVERSION=	1.09
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module for manage templates and parses templates

USES=		perl5
USE_PERL5=	configure

MAN3=		CGI::FastTemplate.3

NO_STAGE=	yes
.include <bsd.port.mk>
