# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: www/rubygem-erubis/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	erubis
PORTVERSION=	2.7.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A fast, secure, and very extensible implementation of eRuby

RUN_DEPENDS=	rubygem-abstract>=1.0.0:${PORTSDIR}/devel/rubygem-abstract

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/erubis

NO_STAGE=	yes
.include <bsd.port.mk>
