# TODO(tuxillo): Yet another part that requires a newer libusb
dfly-patch:
	${RM} -fr ${WRKSRC}/channels/urbdrc

post-configure:
	${REINPLACE_CMD} -e '/MNT_UNION/d' \
		${WRKSRC}/channels/rdpdr/client/mntent_compat.c
