# $FreeBSD: www/rubygem-rack-mount/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	rack-mount
PORTVERSION=	0.8.3
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Stackable dynamic tree based Rack router

RUN_DEPENDS=	rubygem-rack>=1.0.0:${PORTSDIR}/www/rubygem-rack

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
