# $FreeBSD: x11-drivers/xf86-video-r128/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xf86-video-r128
PORTVERSION=	6.9.2
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org r128 display driver

USE_GL=		gl
XORG_CAT=	driver
USE_XORG=	glproto xf86driproto xf86miscproto xineramaproto

.include <bsd.port.mk>
