# $FreeBSD: textproc/rubygem-ri_cal/Makefile 315371 2013-03-27 10:39:24Z miwi $

PORTNAME=	ri_cal
PORTVERSION=	0.8.8
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for parsing, and generating iCalendar data

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=yes
PLIST_FILES=	bin/ri_cal

.include <bsd.port.mk>
