# $FreeBSD: textproc/rubygem-ri_cal/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	ri_cal
PORTVERSION=	0.8.8
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for parsing, and generating iCalendar data

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=yes
PLIST_FILES=	bin/ri_cal

NO_STAGE=	yes
.include <bsd.port.mk>
