# Created by: Lars Balker Rasmussen <lbr@FreeBSD.org>
# $FreeBSD: devel/p5-Class-C3-XS/Makefile 331856 2013-10-28 13:46:25Z vanilla $

PORTNAME=	Class-C3-XS
PORTVERSION=	0.13
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	XS speedups for Class::C3

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
