DragonFly has no sigqueue(2) implementation

--- boost/test/impl/execution_monitor.ipp.intermediate	2016-07-14 13:23:56 UTC
+++ boost/test/impl/execution_monitor.ipp
@@ -335,10 +335,12 @@ system_signal_exception::report() const
                       "signal: generated by kill() (or family); uid=%d; pid=%d",
                       (int)m_sig_info->si_uid, (int)m_sig_info->si_pid );
         break;
+#ifndef __DragonFly__
     case SI_QUEUE:
         report_error( execution_exception::system_error,
                       "signal: sent by sigqueue()" );
         break;
+#endif
     case SI_TIMER:
         report_error( execution_exception::system_error,
                       "signal: the expiration of a timer set by timer_settimer()" );
