# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: math/p5-Math-Matrix/Makefile 329087 2013-10-02 17:50:48Z sunpoet $

PORTNAME=	Math-Matrix
PORTVERSION=	0.8
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Math::Matrix - multiply and invert matrices

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
