# New ports collection makefile for:	math/p5-Statistics-Distributions
# Date created:				01 January 2001
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/math/p5-Statistics-Distributions/Makefile,v 1.10 2012/11/17 05:59:27 svnexp Exp $
#

PORTNAME=	Statistics-Distributions
PORTVERSION=	1.02
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl module that calculates critical values of common statistical distributions

PERL_CONFIGURE=	yes

MAN3=		Statistics::Distributions.3

.include <bsd.port.mk>
