# $FreeBSD: math/calcoo/Makefile 329323 2013-10-04 15:21:09Z naddy $

PORTNAME=	calcoo
PORTVERSION=	1.3.18
PORTREVISION=	6
CATEGORIES=	math
MASTER_SITES=	SF

MAINTAINER=	naddy@FreeBSD.org
COMMENT=	RPN and algebraic scientific calculator

USES=		pkgconfig
USE_GNOME=	gtk20
GNU_CONFIGURE=	yes

PLIST_FILES=	bin/calcoo \
		man/man1/calcoo.1.gz

.include <bsd.port.mk>
