# $FreeBSD: x11/dri2proto/Makefile 328096 2013-09-24 06:24:17Z bapt $

PORTNAME=	dri2proto
PORTVERSION=	2.8
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	DRI2 prototype headers

XORG_CAT=	proto

.include <bsd.port.mk>
