# New ports collection makefile for:	php5-curl
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/ftp/php5-curl/Makefile,v 1.6 2012/11/17 05:57:30 svnexp Exp $
#

CATEGORIES=	ftp

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-curl

.include "${MASTERDIR}/Makefile"
