# New ports collection makefile for:	html2text
# Date created:		23 April 2007
# Whom:			Andrew Pantyukhin <infofarmer@FreeBSD.org>
#
# $FreeBSD: ports/textproc/py-html2text/Makefile,v 1.12 2012/11/17 06:02:17 svnexp Exp $
#

PORTNAME=	html2text
PORTVERSION=	3.200.3
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Convert HTML into clean plain ASCII text

USE_PYTHON=	yes
USE_PYDISTUTILS=easy_install

CONFLICTS=	html2text-[0-9]*

.include <bsd.port.mk>
