# Created by: Lars Balker Rasmussen <lbr@FreeBSD.org>
# $FreeBSD: www/p5-HTML-LinkList/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	HTML-LinkList
PORTVERSION=	0.1503
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Create a 'smart' list of HTML links

USES=		perl5
USE_PERL5=	modbuild

MAN3=	HTML::LinkList.3

.include <bsd.port.mk>
