# Created by: Lars Balker Rasmussen <lbr@FreeBSD.org>
# $FreeBSD: www/p5-HTML-LinkList/Makefile 333099 2013-11-07 13:55:25Z vanilla $

PORTNAME=	HTML-LinkList
PORTVERSION=	0.1503
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Create a 'smart' list of HTML links

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
