# Created by: Michael Lyngbøl <lyngbol@wheel.dk>
# $FreeBSD: devel/p5-Parse-Yapp/Makefile 326784 2013-09-09 08:21:32Z az $

PORTNAME=	Parse-Yapp
PORTVERSION=	1.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lyngbol@wheel.dk
COMMENT=	Perl extension for generating and using LALR parsers

USES=		perl5
USE_PERL5=	configure

MAN1=		yapp.1
MAN3=		Parse::Yapp.3

.include <bsd.port.mk>
