# New ports collection makefile for:	p5-Parse-Yapp
# Date created:			22 September 2001
# Whom:	      			Michael Lyngbøl <lyngbol@wheel.dk>
#
# $FreeBSD: ports/devel/p5-Parse-Yapp/Makefile,v 1.6 2012/11/17 05:56:26 svnexp Exp $
#

PORTNAME=	Parse-Yapp
PORTVERSION=	1.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lyngbol@wheel.dk
COMMENT=	Perl extension for generating and using LALR parsers

PERL_CONFIGURE=	yes

MAN1=		yapp.1
MAN3=		Parse::Yapp.3

.include <bsd.port.mk>
