USES+=	alias

# grass7 has packaging issues
OPTIONS_DEFAULT:= ${OPTIONS_DEFAULT:NGRASS}

# too noisy logs
CXXFLAGS+=	-Wno-deprecated-declarations

dfly-patch:
	${REINPLACE_CMD} -e 's@STREQUAL "FreeBSD"@MATCHES "FreeBSD|DragonFly"@g' \
		${WRKSRC}/cmake/FindGRASS.cmake \
		${WRKSRC}/src/app/CMakeLists.txt
	${REINPLACE_CMD} -e '/-lulog/d' \
		${WRKSRC}/src/plugins/grass/CMakeLists.txt
	${REINPLACE_CMD} -e 's@txt2tags --encoding=utf-8@txt2tags@g' \
		${WRKSRC}/scripts/release.pl
