# Created by: umeno@rr.iij4u.or.jp
# $FreeBSD: japanese/xlockmore/Makefile 338519 2014-01-03 03:33:06Z jgh $

CATEGORIES=	japanese x11

MAINTAINER=	umeno@rr.iij4u.or.jp

MASTERDIR=	${.CURDIR}/../../x11/xlockmore

PORT_OPTIONS+=	MB
XLOCKMORE_LANG=	ja

.include "${MASTERDIR}/Makefile"
