# Created by: umeno@rr.iij4u.or.jp
# $FreeBSD: japanese/xlockmore/Makefile 327737 2013-09-20 18:47:54Z bapt $

CATEGORIES=	japanese x11

MAINTAINER=	umeno@rr.iij4u.or.jp

MASTERDIR=	${.CURDIR}/../../x11/xlockmore

WITH_MB=	yes
XLOCKMORE_LANG=	ja

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
