# Created by: jabley
# $FreeBSD: net-mgmt/aggregate/Makefile 327757 2013-09-20 22:24:43Z bapt $

PORTNAME=	aggregate
PORTVERSION=	1.6
PORTREVISION=	1
CATEGORIES=	net-mgmt
MASTER_SITES=	${MASTER_SITE_ISC}
MASTER_SITE_SUBDIR=	aggregate

MAINTAINER=	jabley@automagic.org
COMMENT=	Optimise a list of route prefixes to help make nice short filters

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/aggregate bin/aggregate-ios
MAN1=		aggregate.1 aggregate-ios.1

NO_STAGE=	yes
.include <bsd.port.mk>
