# New ports collection makefile for: xlwt
# Date created:		2009-08-19
# Whom:			Dikshie
#
# $FreeBSD: ports/textproc/py-xlwt/Makefile,v 1.3 2012/11/17 06:02:18 svnexp Exp $

PORTNAME=	xlwt
PORTVERSION=	0.7.2
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dikshie@sfc.wide.ad.jp
COMMENT=	Writing data and formatting information from Excel files

PLIST_SUB=	PYTHON_VER=${PYTHON_VER}

USE_PYTHON=	yes
USE_PYDISTUTILS=yes

.include <bsd.port.mk>
