# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: multimedia/gstreamer-plugins-schroedinger/Makefile 332416 2013-11-01 22:14:07Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer Dirac high-speed codec plugin

GST_PLUGIN=	schroedinger

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
