# Created by: ijliao
# $FreeBSD: devel/p5-Data-Hexdumper/Makefile 331933 2013-10-29 07:56:01Z vanilla $

PORTNAME=	Data-Hexdumper
PORTVERSION=	3.00.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Module for displaying binary data in a readable format

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
