# ex:ts=8
# New ports collection makefile for:	Data::Hexdumper
# Date created:			Feb 25, 2004
# Whom:				ijliao
#
# $FreeBSD: ports/devel/p5-Data-Hexdumper/Makefile,v 1.8 2012/11/17 05:56:10 svnexp Exp $
#

PORTNAME=	Data-Hexdumper
PORTVERSION=	3.00.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	A module for displaying binary data in a readable format

PERL_CONFIGURE=	yes

MAN3=		Data::Hexdumper.3

.include <bsd.port.mk>
