# Created by: ijliao
# $FreeBSD: devel/p5-Data-Hexdumper/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Data-Hexdumper
PORTVERSION=	3.00.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Module for displaying binary data in a readable format

USES=		perl5
USE_PERL5=	configure

MAN3=		Data::Hexdumper.3

NO_STAGE=	yes
.include <bsd.port.mk>
