# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: games/p5-Games-AlphaBeta/Makefile 332736 2013-11-04 14:49:24Z vanilla $

PORTNAME=	Games-AlphaBeta
PORTVERSION=	0.4.7
CATEGORIES=	games perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-v${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Game-tree search with object oriented interface

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
