# Created by: Nicholas Esborn <nick@netdot.net>
# $FreeBSD: devel/p5-Time-Period/Makefile 318307 2013-05-16 10:31:12Z miwi $

PORTNAME=	Time-Period
PORTVERSION=	1.20
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PRYAN
PKGNAMEPREFIX=	p5-
DISTNAME=	Period-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A perl module that contains code to deal with time periods

PERL_CONFIGURE=	YES

MAN3=		Time::Period.3

.include <bsd.port.mk>
