# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: devel/hs-testpack/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	testpack
PORTVERSION=	2.1.2.1
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Test Utility Pack for HUnit and QuickCheck

LICENSE=	LGPL21

USE_CABAL=	HUnit mtl QuickCheck>=2.1.0.3 random

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
