# New ports collection makefile for:	gpclib
# Date created:		2009-03-27
# Whom:			Wen Heping <wenheping@gmail.com>
#
# $FreeBSD: ports/math/R-cran-gpclib/Makefile,v 1.22 2012/11/17 05:59:18 svnexp Exp $
#

PORTNAME=	gpclib
DISTVERSION=	1.5-3
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	General Polygon Clipping Library for R

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
