# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: math/R-cran-gpclib/Makefile 313562 2013-03-07 04:21:34Z bf $

PORTNAME=	gpclib
DISTVERSION=	1.5-3
PORTREVISION=	2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	General Polygon Clipping Library for R

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
