# Created by: Michael Vasilenko <acid@stu.cn.ua>
# $FreeBSD: www/links1/Makefile 332222 2013-10-31 11:06:16Z bapt $

PORTNAME=	links
PORTVERSION=	1.03
PORTEPOCH=	1
CATEGORIES=	www
MASTER_SITES=	http://www.jikos.cz/~mikulas/links/download/
PKGNAMESUFFIX=	1

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Lynx-like text WWW browser

GNU_CONFIGURE=	yes

USE_OPENSSL=	yes
CONFLICTS=	links-2*

MAN1=		links.1

NO_STAGE=	yes
.include <bsd.port.mk>
