# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: devel/py-timelib/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	timelib
PORTVERSION=	0.2.4
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Parse English textual date descriptions

USE_ZIP=		yes
USE_PYTHON=		yes
USE_PYDISTUTILS=	easy_install
PYEASYINSTALL_ARCHDEP=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
