# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: www/rubygem-net-http-digest_auth/Makefile 327776 2013-09-20 23:36:50Z bapt $

PORTNAME=	net-http-digest_auth
PORTVERSION=	1.4
CATEGORIES=	www net rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Implementation of RFC 2617 - Digest Access Authentication

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
