# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: www/rubygem-net-http-digest_auth/Makefile 320765 2013-06-13 11:49:28Z sunpoet $

PORTNAME=	net-http-digest_auth
PORTVERSION=	1.3
CATEGORIES=	www net rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Implementation of RFC 2617 - Digest Access Authentication

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
