# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-Tree-Nary/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=		Tree-Nary
PORTVERSION=		1.30
PORTEPOCH=		1
CATEGORIES=		textproc perl5
MASTER_SITES=		CPAN
PKGNAMEPREFIX=		p5-
DISTNAME=		${PORTNAME}-1.3

MAINTAINER=		perl@FreeBSD.org
COMMENT=		Perl implementation of N-ary search trees

USES=		perl5
USE_PERL5=	configure

MAN3=			Tree::Nary.3

.include <bsd.port.mk>
