# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: textproc/p5-Tree-Nary/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Tree-Nary
PORTVERSION=	1.30
PORTEPOCH=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-1.3

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl implementation of N-ary search trees

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
