# Created by: Jonathan Weiss (<jw@innerewut.de>)
# $FreeBSD: devel/rubygem-hoe/Makefile 319649 2013-06-02 11:47:54Z swills $

PORTNAME=	hoe
PORTVERSION=	3.6.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A simple rake/rubygems helper for project Rakefiles

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/sow

.include <bsd.port.mk>
