# New ports collection makefile for:	p5-HTML-Macro
# Date created:				January 27th, 2008
# Whom:	      				Groovis <groovis@groovis.net>
#
# $FreeBSD: ports/www/p5-HTML-Macro/Makefile,v 1.2 2012/11/17 06:02:49 svnexp Exp $
#

PORTNAME=	HTML-Macro
PORTVERSION=	1.27
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	groovis@groovis.net
COMMENT=	Process HTML templates with loops, conditionals, macros and more

PERL_CONFIGURE=	YES

MAN3=		HTML::Macro.3 HTML::Macro::Loop.3

.include <bsd.port.mk>
