# Created by: Peter Pentchev <roam@FreeBSD.org>
# $FreeBSD: dns/p5-Stanford-DNSserver/Makefile 332593 2013-11-03 07:46:27Z vanilla $

PORTNAME=	Stanford-DNSserver
PORTVERSION=	1.2.0
CATEGORIES=	dns perl5
MASTER_SITES=	http://www.stanford.edu/~riepel/lbnamed/Stanford-DNSserver/
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A DNS name server framework with a Perl backend

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
