# $FreeBSD: security/hs-digest/Makefile 339286 2014-01-09 21:32:12Z pgj $

PORTNAME=	digest
PORTVERSION=	0.0.1.2
PORTREVISION=	4
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Various cryptographic hashes for Bytestrings

LICENSE=	BSD

USE_CABAL=	zlib

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
