# $FreeBSD: security/hs-digest/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	digest
PORTVERSION=	0.0.1.2
PORTREVISION=	3
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Various cryptographic hashes for Bytestrings

LICENSE=	BSD

USE_CABAL=	zlib

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
