# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: devel/p5-AutoXS-Header/Makefile 331780 2013-10-27 15:12:16Z vanilla $

PORTNAME=	AutoXS-Header
PORTVERSION=	1.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:SMUELLER
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Container for the AutoXS header files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
