# Created by: Jos Backus <jos@catnook.com>
# $FreeBSD: devel/buildtool/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	buildtool
PORTVERSION=	0.16
CATEGORIES=	devel
MASTER_SITES=	SF

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Set of portable software build utilities

HAS_CONFIGURE=	yes
CONFIGURE_ARGS=	-p ${PREFIX} -d ${DOCSDIR}

.include <bsd.port.mk>
