# New ports collection makefile for:    buildtool
# Date created:         Tue Aug 27 22:11:08 PDT 2002
# Whom:                 Jos Backus <jos@catnook.com>
#
# $FreeBSD: ports/devel/buildtool/Makefile,v 1.21 2012/11/17 05:55:35 svnexp Exp $
#

PORTNAME=	buildtool
PORTVERSION=	0.16
CATEGORIES=	devel
MASTER_SITES=	SF

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A set of portable software build utilities

HAS_CONFIGURE=	yes
CONFIGURE_ARGS=	-p ${PREFIX} -d ${DOCSDIR}

MAN1=		buildtool.1

.include <bsd.port.mk>
