--- compiler/systems.inc.orig	2012-04-22 19:47:06.000000000 +0000
+++ compiler/systems.inc
@@ -148,7 +148,8 @@
              system_i386_iphonesim,     { 69 }
              system_powerpc_wii,        { 70 }
              system_x86_64_openbsd,     { 71 }
-             system_x86_64_netbsd       { 72 }
+             system_x86_64_netbsd,      { 72 }
+             system_x86_64_dragonfly    { 73 }
        );
 
      type
