# Created by: ijliao
# $FreeBSD: devel/rubygem-builder32/Makefile 333913 2013-11-15 19:16:29Z sunpoet $

PORTNAME=	builder
PORTVERSION=	3.2.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	32

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Facilitate programmatic generation of XML markup

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
