# Created by: Alexander Churannov <churanov.port.maintainer@gmail.com>
# $FreeBSD: devel/exercisix/Makefile 327722 2013-09-20 17:03:26Z bapt $

PORTNAME=	exercisix
PORTVERSION=	1.2
CATEGORIES=	devel
MASTER_SITES=	http://alexanderchuranov.com/files/

MAINTAINER=	exercisix@alexanderchuranov.com
COMMENT=	Innovative lightweight unit-test framework for C++

USE_BZIP2=	YES
MAN3=		exercisix.3
MANCOMPRESSED=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
