# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: devel/rubygem-coffee-rails/Makefile 332035 2013-10-30 02:31:04Z swills $

PORTNAME=	coffee-rails
PORTVERSION=	3.2.2
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Coffee Script adapter for the Rails asset pipeline

RUN_DEPENDS=	rubygem-coffee-script>=2.2.0:${PORTSDIR}/devel/rubygem-coffee-script \
		rubygem-railties>=3.2.10:${PORTSDIR}/www/rubygem-railties

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
