# Created by: Jeffrey H. Johnson <CPE1704TKS@bellsouth.net>
# $FreeBSD: sysutils/phantom/Makefile 327772 2013-09-20 23:05:58Z bapt $

PORTNAME=	phantom
PORTVERSION=	1.2
CATEGORIES=	sysutils
MASTER_SITES=	http://www.vanheusden.com/Linux/
EXTRACT_SUFX=	.tgz

MAINTAINER=	ota@j.email.ne.jp
COMMENT=	Phantomblock generator (converts existing files to sparse files)

ALL_TARGET=	all

PLIST_FILES=	bin/phantom

NO_STAGE=	yes
.include <bsd.port.mk>
