# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: lang/p5-Try-Tiny/Makefile 324276 2013-08-05 15:05:29Z az $

PORTNAME=	Try-Tiny
PORTVERSION=	0.12
CATEGORIES=	lang perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DOY
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Minimal try/catch with proper localization of $$@

USES=		perl5
USE_PERL5=	configure

MAN3=	Try::Tiny.3

.include <bsd.port.mk>
