# New ports collection makefile for:	php52-recode
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/converters/php52-recode/Makefile,v 1.2 2012/11/17 05:55:04 svnexp Exp $
#

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-recode

.include "${MASTERDIR}/Makefile"
