# Created by: Alex Keda <admin@lissyara.su>
# $FreeBSD: converters/php52-recode/Makefile 327715 2013-09-20 16:05:24Z bapt $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-recode

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
