# Created by: stas
# $FreeBSD: devel/boehm-gc-redirect/Makefile 330672 2013-10-17 20:53:58Z bsam $

PORTREVISION=	0

COMMENT=	Garbage collection and memory leak detection for C and C++ with malloc redirection

LICENSE=	MIT

MASTERDIR=	${.CURDIR}/../boehm-gc                                                                                                                                                        
DESCR=		${.CURDIR}/pkg-descr
GC_VARIANT=	redirect

.include "${MASTERDIR}/Makefile"
