# Created by: stas
# $FreeBSD: devel/boehm-gc-redirect/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTREVISION=	0

COMMENT=	Garbage collection and memory leak detection for C and C++ with malloc redirection

LICENSE=	MIT

MASTERDIR=	${.CURDIR}/../boehm-gc                                                                                                                                                        
DESCR=		${.CURDIR}/pkg-descr
GC_VARIANT=	redirect

.include "${MASTERDIR}/Makefile"
