# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: math/R-cran-memisc/Makefile 313064 2013-02-27 15:49:02Z tota $

PORTNAME=	memisc
DISTVERSION=	0.96-3
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Provides an infrastructure for the management of survey data

LICENSE=	GPLv2

USE_R_MOD=	yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
