# Created by: Andrey Kostenko <andrey@kostenko.name>
# $FreeBSD: devel/p5-Object-Simple/Makefile 313513 2013-03-06 13:27:39Z tobez $

PORTNAME=	Object-Simple
PORTVERSION=	3.0800
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:C/00$//}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple class builder

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

MAN3=		Object::Simple.3 \
		Object::Simple::Accessor.3 \
		Object::Simple::Guide.3

.include <bsd.port.mk>
