# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: x11-toolkits/gstreamer-plugins-pango/Makefile 332416 2013-11-01 22:14:07Z kwm $
#   $MCom: ports/x11-toolkits/gstreamer-plugins-pango/Makefile,v 1.6 2008/03/21 04:01:32 ahze Exp $

PORTREVISION=	1
CATEGORIES=	x11-toolkits

COMMENT=	Gstreamer pango textoverlay plugin

GST_PLUGIN=	pango

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
