# New ports collection makefile for:	String::LRC
# Date created:				24 October 2002
# Whom:					Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-String-LRC/Makefile,v 1.10 2012/11/17 05:56:29 svnexp Exp $
#

PORTNAME=	String-LRC
PORTVERSION=	1.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A perl interface for longitudinal redundancy check generation

PERL_CONFIGURE=	yes

MAN3=		String::LRC.3

.include <bsd.port.mk>
