# $FreeBSD: devel/tradcpp/Makefile 320658 2013-06-12 05:47:43Z bapt $

PORTNAME=	tradcpp
PORTVERSION=	0.2
CATEGORIES=	devel
MASTER_SITES=	http://ftp.NetBSD.org/pub/NetBSD/misc/dholland/

MAINTAINER=	bapt@FreeBSD.org
COMMENT=	Traditional (K&R-style) C preprocessor

LICENSE=	BSD

MANCOMPRESSED=	yes
MAKE_JOBS_SAFE=	yes
MAKE_ARGS=	BINDIR=${PREFIX}/bin MANDIR=${MANPREFIX}/man/man

PLIST_FILES=	bin/tradcpp

MAN1=		tradcpp.1

.include <bsd.port.mk>
