# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: textproc/pear-Horde_SpellChecker/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Horde_SpellChecker
PORTVERSION=	2.1.1
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Spellcheck API

USE_HORDE_RUN=	Horde_Exception \
		Horde_Util

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
