# Ports collection makefile for:  pear-Horde_SpellChecker
# Date created:			  7 July 2011
# Whom:				  Martin Matuska <mm@FreeBSD.org>
#
# $FreeBSD: ports/textproc/pear-Horde_SpellChecker/Makefile,v 1.6 2013/01/10 18:35:40 svnexp Exp $

PORTNAME=	Horde_SpellChecker
PORTVERSION=	2.1.0
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Spellcheck API

USE_HORDE_RUN=	Horde_Exception \
		Horde_Util

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
