# Created by: Steven Kreuzer <skreuzer@exit2shell.com>
# $FreeBSD: devel/p5-Data-Validate/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Data-Validate
PORTVERSION=	0.08
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Common data validation methods

USES=		perl5
USE_PERL5=	configure

MAN3=	Data::Validate.3

NO_STAGE=	yes
.include <bsd.port.mk>
