# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: textproc/p5-XML-Quote/Makefile 327773 2013-09-20 23:17:30Z bapt $

PORTNAME=	XML-Quote
PORTVERSION=	1.02
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	XML quote/dequote functions

USES=		perl5
USE_PERL5=	configure

MAN3=		XML::Quote.3

NO_STAGE=	yes
.include <bsd.port.mk>
