# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: math/R-cran-mvtnorm/Makefile 327746 2013-09-20 20:55:04Z bapt $

PORTNAME=	mvtnorm
PORTVERSION=	0.9.96
PORTREVISION=	11
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION:C/\./-/g:C/-/\./1}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Multivariate Normal and t Distributions

USE_R_MOD=  		yes
R_MOD_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
