# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: math/R-cran-mvtnorm/Makefile 335044 2013-11-27 18:56:43Z dbn $

PORTNAME=	mvtnorm
PORTVERSION=	0.9.96
PORTREVISION=	13
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION:C/\./-/g:C/-/\./1}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Multivariate Normal and t Distributions

USE_R_MOD=  		yes
R_MOD_AUTOPLIST=	yes

.include <bsd.port.mk>
