# $FreeBSD: editors/libreoffice-ro/Makefile 313667 2013-03-08 19:01:45Z jkim $

LO_I18N=	ro
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
