# New ports collection makefile for: kdelibs3-nocups
# Date created:         Tue 25 Jan 2005
# Whom:                 Michael Nottebrock
#
# $FreeBSD: ports/x11/kdelibs3-nocups/Makefile,v 1.15 2012/11/17 06:03:16 svnexp Exp $

PORTNAME?=		kdelibs3
PKGNAMESUFFIX?=		-nocups

MAINTAINER=		ports@FreeBSD.org

PLIST=			${.CURDIR}/pkg-plist
WITHOUT_CUPS=		yes
MASTERDIR=		${.CURDIR}/../../x11/kdelibs3

.include "${MASTERDIR}/Makefile"
