# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-Object-Declare/Makefile 332127 2013-10-30 15:19:23Z vanilla $

PORTNAME=	Object-Declare
PORTVERSION=	0.22
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Declarative object constructor

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
