# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: textproc/hs-bytestring-csv/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	bytestring-csv
PORTVERSION=	0.1.2
PORTREVISION=	12
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parse CSV formatted data efficiently with Haskell

LICENSE=	BSD

USE_CABAL=	dlist

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
