# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: ports/textproc/hs-bytestring-csv/Makefile,v 1.14 2013/02/05 22:47:14 svnexp Exp $

PORTNAME=	bytestring-csv
PORTVERSION=	0.1.2
PORTREVISION=	10
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parse CSV formatted data efficiently with Haskell

LICENSE=	BSD

USE_CABAL=	dlist

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
