# Created by: Chris D. Faulhaber <jedgar@FreeBSD.org>
# $FreeBSD: archivers/parchive/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	parchive
PORTVERSION=	1.1
CATEGORIES=	archivers
MASTER_SITES=	SF/${PORTNAME}/par/${PORTVERSION}
DISTNAME=	par-v${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Parity Archiver - makes multiple parity volumes from a set of files

MAKEFILE=	${FILESDIR}/Makefile
PLIST_FILES=	bin/parchive
WRKSRC=		${WRKDIR}/par-cmdline

.include <bsd.port.mk>
