# New ports collection makefile for:	parchive
# Whom:					Chris D. Faulhaber <jedgar@FreeBSD.org>
# Date created:				26 November 2001
#
# $FreeBSD: ports/archivers/parchive/Makefile,v 1.8 2012/11/17 05:54:22 svnexp Exp $
#

PORTNAME=	parchive
PORTVERSION=	1.1
CATEGORIES=	archivers
MASTER_SITES=	SF/${PORTNAME}/par/${PORTVERSION}
DISTNAME=	par-v${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Parity Archiver - makes multiple parity volumes from a set of files

MAKEFILE=	${FILESDIR}/Makefile
PLIST_FILES=	bin/parchive
WRKSRC=		${WRKDIR}/par-cmdline

.include <bsd.port.mk>
