# Created by: David O'Brien <obrien@cs.ucdavis.edu>
# $FreeBSD: print/mp-a4/Makefile 340722 2014-01-22 17:00:46Z mat $

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../mp-letter

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
