# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: www/xpi-tabmixplus/Makefile 320612 2013-06-11 16:50:49Z miwi $

PORTNAME=	tabmixplus
DISTVERSION=	0.4.1.0
DISTVERSIONSUFFIX=	-fx
CATEGORIES=	www

MAINTAINER=	gecko@FreeBSD.org
COMMENT=	Enhances tab browsing capabilities

XPI_DISTNAME=	tab_mix_plus
XPI_NUM=	1122
XPI_ID=		{dc572301-7619-498c-a57d-39143191b318}

.include "../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
