# $FreeBSD: devel/p5-Test-Time/Makefile 339787 2014-01-15 15:31:02Z kuriyama $

PORTNAME=	Test-Time
PORTVERSION=	0.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to override time()/sleep() core functions for testing

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
