# $FreeBSD: converters/hs-dataenc/Makefile 331644 2013-10-26 00:52:33Z gerald $

PORTNAME=	dataenc
PORTVERSION=	0.14.0.5
PORTREVISION=	2
CATEGORIES=	converters haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Data encoding library

LICENSE=	BSD

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
