# $FreeBSD: converters/hs-dataenc/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	dataenc
PORTVERSION=	0.14.0.5
PORTREVISION=	3
CATEGORIES=	converters haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Data encoding library

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
