# $FreeBSD: net/hs-maccatcher/Makefile 315580 2013-03-29 22:43:58Z pgj $

PORTNAME=	maccatcher
PORTVERSION=	2.1.5
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Obtain the host MAC address on *NIX and Windows

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	parsec

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
