# $FreeBSD: security/rubygem-origami/Makefile 327769 2013-09-20 22:55:24Z bapt $

PORTNAME=	origami
PORTVERSION=	1.2.6
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Ruby framework to parse analyze and forge PDF documents

LICENSE=	LGPL3

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=yes

NO_STAGE=	yes
.include <bsd.port.mk>
