# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: ports/devel/rubygem-thrift/Makefile,v 1.10 2013/02/26 17:18:30 svnexp Exp $
#

PORTNAME=	thrift
PORTVERSION=	${THRIFT_PORTVERSION} # to keep in sync with ../thrift
PORTEPOCH=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	komarov@valerka.net
COMMENT=	Ruby interface to thrift

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include "../thrift/bsd.thrift.mk"
.include <bsd.port.mk>
