# Created by: Cezary Morga <cm@therek.net>
# $FreeBSD: ports/devel/p5-Devel-Refactor/Makefile,v 1.3 2012/11/17 05:56:14 svnexp Exp $

PORTNAME=	Devel-Refactor
PORTVERSION=	0.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl extension for refactoring Perl code

PERL_CONFIGURE=	YES

MAN3=		Devel::Refactor.3

.include <bsd.port.mk>
