# Created by: Cezary Morga <cm@therek.net>
# $FreeBSD: devel/p5-Devel-Refactor/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Devel-Refactor
PORTVERSION=	0.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl extension for refactoring Perl code

USES=		perl5
USE_PERL5=	configure

MAN3=		Devel::Refactor.3

NO_STAGE=	yes
.include <bsd.port.mk>
