# Created by: Kozlov Sergey <kozlov.sergey.404@gmail.com>
# $FreeBSD: www/py-django-registration-defaults/Makefile 327143 2013-09-13 11:27:42Z wg $

PORTNAME=	django-registration-defaults
PORTVERSION=	0.4.3
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kozlov.sergey.404@gmail.com
COMMENT=	Default templates and settings for django-registration

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django-registration>=0:${PORTSDIR}/www/py-django-registration

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
