# New ports collection makefile for:	py-setuptools_darcs
# Date created:		30 June, 2009
# Whom:			Wen Heping <wenheping@gmail.com>
#
# $FreeBSD: ports/devel/py-setuptools_darcs/Makefile,v 1.5 2012/11/17 05:56:50 svnexp Exp $
#

PORTNAME=	setuptools_darcs
PORTVERSION=	1.2.11
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Setuptools plugin for darcs

BUILD_DEPENDS=		darcsver:${PORTSDIR}/devel/py-darcsver

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

.include <bsd.port.mk>
