# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: x11-themes/kde-icons-nuovext/Makefile 327783 2013-09-20 23:54:03Z bapt $

PORTNAME=	nuoveXT
PORTVERSION=	1.6
MASTER_SITES=	http://nuovext.pwsp.net/files/
DISTNAME=	${PORTNAME}-kde-${PORTVERSION}

COMMENT=	KDE nuoveXT iconset
PLIST_FILE_PATTERN_EXTRA=	-v "^\./(CHANGELOG|GPL)"

NO_STAGE=	yes
.include "${.CURDIR}/../kde-icons-noia/Makefile.icons"
