# New ports collection makefile for:	KDE iconset nuoveXT
# Date created:		Qua 12 Dez 2007 01:57:06 UTC
# Whom:			Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
#
# $FreeBSD: ports/x11-themes/kde-icons-nuovext/Makefile,v 1.2 2012/11/17 06:03:32 svnexp Exp $
#

PORTNAME=	nuoveXT
PORTVERSION=	1.6
MASTER_SITES=	http://nuovext.pwsp.net/files/
DISTNAME=	${PORTNAME}-kde-${PORTVERSION}

COMMENT=	KDE nuoveXT iconset
PLIST_FILE_PATTERN_EXTRA=	-v "^\./(CHANGELOG|GPL)"

.include "${.CURDIR}/../kde-icons-noia/Makefile.icons"
