# New ports collection makefile for: redmine-http-auth
# Date created:                      2010-09-12
# Whom:                              Eygene Ryabinkin <rea-fbsd@codelabs.ru>
#
# $FreeBSD: ports/www/redmine-http-auth/Makefile,v 1.3 2012/11/17 06:03:02 svnexp Exp $
#

PORTNAME=	http-auth
PORTVERSION=	20100730
PORTREVISION=	1
CATEGORIES=	www
MASTER_SITES=	http://dist.codelabs.ru/fbsd/
DISTNAME=	AdamLantos-redmine_http_auth-${GITREV}

MAINTAINER=	rea@FreeBSD.org
COMMENT=	HTTP authentication plugin for Redmine

GITREV=		df98baf
REDMINE_PLUGIN_NAME=	redmine_http_auth

.include "${.CURDIR}/../../www/redmine/bsd.redmine.mk"
