# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: devel/p5-Smart-Comments/Makefile 325119 2013-08-21 12:49:19Z mat $

PORTNAME=	Smart-Comments
PORTVERSION=	1.000005
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DCONWAY
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Comments that do more than just sit there

USES=		perl5
USE_PERL5=	modbuild

MAN3=		Smart::Comments.3

.include <bsd.port.mk>
