# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: devel/p5-Smart-Comments/Makefile 332205 2013-10-31 07:36:25Z vanilla $

PORTNAME=	Smart-Comments
PORTVERSION=	1.000005
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DCONWAY
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Comments that do more than just sit there

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
