# Created by: Foxfair Hu <foxfair@FreeBSD.org>
# $FreeBSD: x11/libXrender/Makefile 327777 2013-09-20 23:43:19Z bapt $

PORTNAME=	libXrender
PORTVERSION=	0.9.8
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Render extension library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 renderproto:both xproto:both

NO_STAGE=	yes
.include <bsd.port.mk>
