# Created by: philip@p6m7g8.com
# $FreeBSD: textproc/p5-Filter-Simple/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	Filter-Simple
PORTVERSION=	0.88
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simplified source filtering

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
