# Created by: Cyrille Lefevre <cyrille.lefevre@laposte.net>
# $FreeBSD: textproc/docproj-nojadetex/Makefile 327773 2013-09-20 23:17:30Z bapt $

PKGNAMESUFFIX=	-nojadetex
WITHOUT_JADETEX=yes

MASTERDIR=	${.CURDIR}/../docproj

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
