# contains freebsd/linux binaries (not used)
.if defined(DEVELOPER)
.MAKEFLAGS+=	DFLY_ALLOW_FOREIGN_BINARIES=yes
DFLY_ALLOW_FOREIGN_BINARIES=yes
.endif

SHEBANG_FILES+=	src/internal/x/fiximports.bash
