# Created by: Mathieu Arnold <m@absolight.net>
# $FreeBSD: devel/p5-Devel-Profile/Makefile 331933 2013-10-29 07:56:01Z vanilla $

PORTNAME=	Devel-Profile
PORTVERSION=	1.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Tell me why my perl program runs so slowly

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
