# Created by: Mathieu Arnold <m@absolight.net>
# $FreeBSD: devel/p5-Devel-Profile/Makefile 324174 2013-08-02 18:52:07Z mat $

PORTNAME=	Devel-Profile
PORTVERSION=	1.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Tell me why my perl program runs so slowly

USES=		perl5
USE_PERL5=	configure

MAN3=		Devel::Profile.3

.include <bsd.port.mk>
