# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: devel/hs-haskell-src-exts/Makefile 327723 2013-09-20 17:04:43Z bapt $

PORTNAME=	haskell-src-exts
PORTVERSION=	1.13.5
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Manipulating Haskell source

LICENSE=	BSD

USE_CABAL=	cpphs>=1.3
USE_HAPPY=	yes

NO_STAGE=	yes
.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
