# $FreeBSD: x11/xvidtune/Makefile 319055 2013-05-25 14:37:02Z zeising $

PORTNAME=	xvidtune
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Video mode tuner for X

XORG_CAT=	app
USE_XORG=	xxf86vm xt xaw

MAN1=		xvidtune.1

.include <bsd.port.mk>
