# Created by: Sebastien gioria <gioria@FreeBSD.org>
# $FreeBSD: misc/p5-Locale-Msgcat/Makefile 327745 2013-09-20 20:50:57Z bapt $

PORTNAME=	Msgcat
PORTVERSION=	1.03
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Locale
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module for systems to support the XPG4 message catalog functions

MAN3=		Locale::Msgcat.3

USES=		perl5
USE_PERL5=	configure

NO_STAGE=	yes
.include <bsd.port.mk>
