# $FreeBSD: ukrainian/calligra-l10n/Makefile 327774 2013-09-20 23:19:33Z bapt $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
CATEGORIES=	ukrainian editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Ukrainian messages and documentation for Calligra

CALLIGRA_L10N=	uk

NO_STAGE=	yes
.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
