# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-IPC-Open3-Simple/Makefile 326728 2013-09-08 13:59:48Z az $

PORTNAME=	IPC-Open3-Simple
PORTVERSION=	0.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	A simple alternative to IPC::Open3

USES=		perl5
USE_PERL5=	configure

MAN3=		IPC::Open3::Simple.3

.include <bsd.port.mk>
