# Created by: SimaMoto,RyoTa <liangtai.s4@gmail.com>
# $FreeBSD: misc/gimp-help-nn/Makefile 327745 2013-09-20 20:50:57Z bapt $

CATEGORIES=	misc graphics

MAINTAINER=	liangtai.s4@gmail.com
COMMENT=	The GIMP User Manual in Norwegian:Ninorsk

MASTERDIR=	${.CURDIR}/../gimp-help-en

DOCLANG=	nn
AMPLE=	""

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
