# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: lang/p5-Scalar-List-Utils/Makefile 336872 2013-12-19 07:23:55Z sunpoet $

PORTNAME=	Scalar-List-Utils
PORTVERSION=	1.35
PORTEPOCH=	1
CATEGORIES=	lang perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl subroutines that would be nice to have in the perl core

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
