# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: www/R-cran-Rpad/Makefile 337846 2013-12-28 10:28:40Z dbn $

PORTNAME=	Rpad
PORTVERSION=	1.3.0
PORTREVISION=	11
CATEGORIES=	www
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Workbook-style, web-based interface to R

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
