# New ports collection makefile for:	p5-Digest-HMAC
# Date created:				2001/12/11
# Whom:					nork@cityfujisawa.ne.jp
#
# $FreeBSD: ports/security/p5-Digest-HMAC/Makefile,v 1.11 2012/11/17 06:01:12 svnexp Exp $
#

PORTNAME=	Digest-HMAC
PORTVERSION=	1.03
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 interface to HMAC Message-Digest Algorithms

PERL_CONFIGURE=	yes

MAN3=		Digest::HMAC.3 \
		Digest::HMAC_MD5.3 \
		Digest::HMAC_SHA1.3

.include <bsd.port.mk>
