# Created by: Bryan Drewery <bryan@shatow.net>
# $FreeBSD: devel/rubygem-backports/Makefile 322937 2013-07-13 15:33:23Z swills $

PORTNAME=	backports
PORTVERSION=	3.3.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby 1.9 backports for 1.8

LICENSE=	MIT

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
