# Created by: Bryan Drewery <bryan@shatow.net>
# $FreeBSD: devel/rubygem-backports/Makefile 321614 2013-06-23 04:49:01Z swills $

PORTNAME=	backports
PORTVERSION=	3.3.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby 1.9 backports for 1.8

LICENSE=	MIT

USE_RUBY=		yes
USE_RUBYGEMS=		yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
