# Created by: thierry@pompo.net
# $FreeBSD: science/netcdf-ftn/Makefile 325163 2013-08-21 17:42:57Z sunpoet $

PORTNAME=	netcdf

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	NetCDF (network Common Data Form), with Fortran support

LATEST_LINK=	netcdf-ftn
MASTERDIR=	${.CURDIR}/../netcdf4

WITH_FORTRAN=	yes

.include "${MASTERDIR}/Makefile"
