# Created by: Cheng-Lung Sung
# $FreeBSD: devel/p5-Module-Dependency/Makefile 332120 2013-10-30 14:44:54Z vanilla $

PORTNAME=	Module-Dependency
PORTVERSION=	1.86
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Collection of modules for examining dependencies

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
