# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: textproc/pear-Horde_Text_Flowed/Makefile 334871 2013-11-25 17:59:58Z antoine $

PORTNAME=	Horde_Text_Flowed
PORTVERSION=	2.0.1
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde API for flowed text as per RFC 3676

USE_HORDE_RUN=	Horde_Util

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear-channel-horde/bsd.horde.mk"
.include <bsd.port.post.mk>
