# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: devel/p5-Config-INI-Simple/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Config-INI-Simple
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gslin@gslin.org
COMMENT=	Simple reading and writing from an INI file

USES=		perl5
USE_PERL5=	configure

MAN3=		Config::INI::Simple.3

NO_STAGE=	yes
.include <bsd.port.mk>
