# Created by: Jonathan Weiss (<jw@innerewut.de>)
# $FreeBSD: databases/rubygem-memcache-client/Makefile 327717 2013-09-20 16:13:47Z bapt $

PORTNAME=	memcache-client
PORTVERSION=	1.8.5
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby bindings for MemCached

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/memcached_top

NO_STAGE=	yes
.include <bsd.port.mk>
