# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: devel/rubygem-columnize/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	columnize
PORTVERSION=	0.3.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Sorts an Array in Column Order

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
