# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: devel/rubygem-columnize/Makefile 332035 2013-10-30 02:31:04Z swills $

PORTNAME=	columnize
PORTVERSION=	0.3.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Sorts an Array in Column Order

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
