# Created by: Tsung-Han Yeh <snowfly@yuntech.edu.tw>
# $FreeBSD: devel/p5-Exporter/Makefile 327724 2013-09-20 17:13:42Z bapt $

PORTNAME=	Exporter
PORTVERSION=	5.68
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	snowfly@yuntech.edu.tw
COMMENT=	Implements default import method for modules

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN3=		Exporter.3 Exporter::Heavy.3

NO_STAGE=	yes
.include <bsd.port.mk>
