# Created by: Mikhail T. <m.tsatsenko@gmail.com>
# $FreeBSD: devel/rubygem-structured_warnings/Makefile 327726 2013-09-20 17:17:44Z bapt $

PORTNAME=	structured_warnings
PORTVERSION=	0.1.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Implementation of structured warnings for Ruby

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

NO_STAGE=	yes
.include <bsd.port.mk>
