# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: net-im/py-skype4py/Makefile 334620 2013-11-22 22:10:53Z nivit $

PORTNAME=	Skype4Py
PORTVERSION=	1.0.35
#PORTREVISION=	0
CATEGORIES=	net-im devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Skype (TM) API wrapper for Python

LICENSE=	BSD

PYDISTUTILS_AUTOPLIST=	yes

USE_PYDISTUTILS=	easy_install
USE_PYTHON=	-2.7
USE_ZIP=	yes

.include <bsd.port.mk>
