# $FreeBSD: devel/py-zope.datetime/Makefile 338824 2014-01-05 21:02:29Z rm $

PORTNAME=	zope.datetime
PORTVERSION=	3.4.1
PORTREVISION=	1
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Commonly used date and time related utility functions

LICENSE=	ZPL21

USE_PYTHON=		yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
