# Created by: Mauricio Herrera Cuadra <mauricio@arareko.net>
# $FreeBSD: ports/devel/p5-Devel-TraceUse/Makefile,v 1.7 2012/11/17 05:56:14 svnexp Exp $

PORTNAME=	Devel-TraceUse
PORTVERSION=	2.08
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mauricio@arareko.net
COMMENT=	This module shows the modules your program loads, recursively

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

PERL_MODBUILD=	yes

MAN3=	Devel::TraceUse.3

.include <bsd.port.mk>
